### ISSUE TITLE
Proposal: fix deleting in multiline contexts

### ISSUE THREAD

**Issue by infokiller** [romkatv/zsh4humans#10]
This issue is not about a bug in z4h, but a bug (or at least surprising behavior) in zsh by default.
By default, when you edit a multiline command and you're not in the first line, it seems you can't go to a previous line by deleting characters (or any other way I'm aware of).
For example, try typing `echo 1 \` and then pressing enter. ZLE will move the cursor to a new line, but then how do you go back to the first one?
I would expect that pressing backspace or <kbd>Ctrl-W</kbd> would do it, but that's not the case. The cursor is stuck on the second line.

In my config, I try to fix it with the following:

```zsh
backward-delete-char-or-up-line() {
  emulate -L zsh
  if [[ -n "${LBUFFER}" ]]; then
    zle backward-delete-char
  elif [[ -n "${PREBUFFER}" ]]; then
    local len=$(( ${#PREBUFFER} -1 ))
    # Based on /usr/share/zsh/functions/Zle/edit-command-line
    print -Rz - "${PREBUFFER:0:${len}}"
    zle send-break
  fi
}
zle -N backward-delete-char-or-up-line
bindkey '^?' backward-delete-char-or-up-line

backward-delete-word-multiline() {
  emulate -L zsh
  if [[ -n "${LBUFFER}" ]]; then
    local len=${#LBUFFER}
    if [[ "${LBUFFER:$((len-1)):${len}}" == $'\n' ]]; then
      zle backward-delete-char
    fi
    zle backward-delete-word
  elif [[ -n "${PREBUFFER}" ]]; then
    local len=${#PREBUFFER}
    # Based on /usr/share/zsh/functions/Zle/edit-command-line
    print -Rz - "${PREBUFFER:0:${$((len-1))}}"
    # send-break is required to break from a multiline editing mode.
    zle send-break
  fi
}
zle -N backward-delete-word-multiline
bindkey '^W' backward-delete-word-multiline
```

Does it make sense to have this behavior by default?

I don't know if the improvement justifies the added complexity for z4h, but thought I'd share it for you to decide.

**Comment by romkatv** [comment]
Why not use alt-enter to define multi-line commands?

**Comment by romkatv** [comment]
Sorry, that was probably too curt to be understandable. The standard way to create a multi-line command is to use alt-enter, or esc-enter. Is it this not good enough?

I think it's possible to automatically convert enter to alt-enter when enter would result in PS2. This might be an interesting thing to experiment with.

**Comment by infokiller** [comment]
I wasn't aware of alt-enter (side note: I think Shift-Enter is more consistent with other software, but it doesn't seem like terminals can detect it).
One can indeed use it and then the behavior I described doesn't apply, but it seems that using `\` also works in bash, so people may be more used to it.
Another thing is that if you start writing a natural multiline command like a for loop, it's nicer to just press enter. For example, try typing `for i in 1 2 3; do` and then pressing enter. You will get the same bug I described.

**Comment by infokiller** [comment]
> Sorry, that was probably too curt to be understandable. The standard way to create a multi-line command is to use alt-enter, or esc-enter. Is it this not good enough?
> 
> I think it's possible to automatically convert enter to alt-enter when enter would result in PS2. This might be an interesting thing to experiment with.
Yes, this conversion is a good idea and will fix this issue in the for loop scenario I described above.

**Comment by romkatv** [comment]
> For example, try typing `for i in 1 2 3; do` and then pressing enter. You will get the same bug I described.

(I wouldn't call it a bug.) This is where I suggested automatically converting enter to alt-enter. Do you think it would be useful?

**Comment by romkatv** [comment]
The advantage of converting enter to alt-enter is that you never enter PS2. In your workaround you enter PS2 and then can go back to PS1 by deleting stuff. But being in PS2 is by itself bad. For example, the moment you enter PS2, transient prompt in p10k kicks in and you no longer see context from prompt. In addition, `SHOW_ON_COMMAND` doesn't work in PS2. This is because it's impossible to reset prompt in PS2.

**Comment by infokiller** [comment]
> > For example, try typing `for i in 1 2 3; do` and then pressing enter. You will get the same bug I described.
> 

Yes, not a bug, I was just too lazy to type "unexpected behavior". BTW, I know nothing about `PS2` and nowhere near a ZSH expert, so I'll probably make a lot of bad assumptions.

> (I wouldn't call it a bug.) This is where I suggested automatically converting enter to alt-enter. Do you think it would be useful?

Yes, definitely, though I have no idea if many people care about it. It's plausible that most people just never type multiline commands.

**Comment by romkatv** [comment]
> > > For example, try typing `for i in 1 2 3; do` and then pressing enter. You will get the same bug I described.
> 
> Yes, not a bug, I was just too lazy to type "unexpected behavior". BTW, I know nothing about `PS2` and nowhere near a ZSH expert, so I'll probably make a lot of bad assumptions.

PS2 is the prompt you get when you hit ENTER after typing `if`. You can even define what gets shown on the left with `PS2='...'`. When PS2 is active, you no longer can reset the main prompt (PS1 and RPS1). They are "finished". PS2 doesn't have right prompt by the way.

> Yes, definitely, though I have no idea if many people care about it. It's plausible that most people just never type multiline commands.

Yeah, it's probably fewer than 1% of all users who use multi-line commands other than by accident.

It's something that could be added to z4h as an option in the future but doesn't seem like high priority.

**Comment by infokiller** [comment]
SGTM

**Comment by romkatv** [comment]
I've added an approximation of this. Please run `z4h update` and add the following line to `.zshrc` next to all other `z4h bindkey` calls:

```zsh
z4h bindkey z4h-accept-line Enter
```

Let me know whether this works for your and especially if you find something broken.

**Comment by QuarticCat** [comment]
Test cases:

- `{` / `(` -> passed
- `echo '` / `echo "` / `echo $'` -> passed
- `echo $(` / `echo =(` / `echo <(` -> passed
- `var=(` -> passed
- `case $var {` -> passed
- `for i in {0..255};` -> triggered PS2

I don't actually write multi-line commands in an interactive environment. Most of the time I just accidentally pressed `'` before pressing enter. So it's good enough for me now.

**Comment by romkatv** [comment]
Thanks for testing!

> * `for i in {0..255};` -> triggered PS2

This looks like a zsh bug to me. I've asked for clarification on zsh-users: https://www.zsh.org/mla/users/2023/msg00467.html.

**Comment by QuarticCat** [comment]
One more thing, this widget should be added into `$ZSH_AUTOSUGGEST_CLEAR_WIDGETS` if zsh-autosuggestions is used.

**Comment by romkatv** [comment]
> > * `for i in {0..255};` -> triggered PS2
> 
> This looks like a zsh bug to me. I've asked for clarification on zsh-users: https://www.zsh.org/mla/users/2023/msg00467.html.

The conclusion is that yes, it's a zsh bug, but it's very difficult to fix. As a workaround you can add `unsetopt short_loops` to `~/.zshrc`. It's a good idea to do that if you are never using the short loop syntax in interactive zsh (most people don't).

**Comment by QuarticCat** [comment]
That works for me. Thank you!
