### ISSUE TITLE
Including - in WORDCHARS messes with z4h-backward-kill-word (z4h-move-and-kill)

### ISSUE THREAD

**Issue by Syphdias** [romkatv/zsh4humans#101]
I use `WORDCHARS='-'` which means `-` is no longer a word separator meaning I can delete/move `foo-bar`in one movement instead of two. Sadly this messes with the `z4h-backward-kill-word` widget.

```
❯ sudo docker run -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec '
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v4/install)"'
# do setup which ever way you want; also see PS
❯ WORDCHARS='-'`
❯ -foo<ctrl-w>
-z4h-move-and-kill:zle:16: unknown option: foo
```

I tried to fix it by adding `(q)` and replacing `-` with `\-` in `BUFFER[from,to]` (in `$Z4H/zsh4humans/fn/-z4h-move-and-kill`) but it messes with the resulting yank, i.e. yanking space as `\ ` and `-` as `\-`.

PS: I tried the configuration skip you suggested [here](https://github.com/romkatv/zsh4humans/issues/23#issuecomment-630981667) for v2 but it didn't work

**Comment by Syphdias** [comment]
I just found a fix I think which is way easier: `zle .copy-region-as-kill -- $BUFFER[from,to]`
Testing...

**Comment by romkatv** [comment]
That's the right fix. Want to send a PR or should I commit it?

**Comment by Syphdias** [comment]
If you hadn't answered, I would have opened a PR. But since you already saw it, just add the 3 characters ;) It'll be faster.

**Comment by Syphdias** [comment]
I just searched for other occourances where `BUFFER` was used as argument in a similar fashion but couldn't find any besides `print -r -- ${BUFFER//$'\n'/$'\\\n'}` which already does use `--`.

**Comment by romkatv** [comment]
When I saw your comment, I already had a commit with the fix (you gave all the info in the bug report, including the line number, so no debugging was necessary), so it's just `git push` for me. Thanks for the report! I've pushed the fix to v5 and backported it to v4.

**Comment by Syphdias** [comment]
`z4h update` and fixed! Thanks!
