### ISSUE TITLE
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS pyenv causes cursor to overlap prompt

### ISSUE THREAD

**Issue by theelderbeever** [romkatv/zsh4humans#103]
When the `POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS` for `pyenv` is enabled the cursor overlaps the prompt text. Typing removes the prompt text from visibility. This does not occur when there is no python environment active.

pyenv Enabled
![image](https://user-images.githubusercontent.com/29295582/111698713-88712180-880d-11eb-84ff-7cfb79544bbb.png)

pyenv Disabled
![image](https://user-images.githubusercontent.com/29295582/111698778-a2aaff80-880d-11eb-8f4b-d15ee3d361af.png)

**Comment by romkatv** [comment]
Can you reproduce this with the latest version of powerlevel10k?

**Comment by theelderbeever** [comment]
The issue was found today after a clean install of powerlevel10k. Is there a best way to check version so that I can verify that it is the latest version pulled?

**Comment by romkatv** [comment]
Please run `z4h update` and check whether it fixes the issue.

**Comment by theelderbeever** [comment]
That appears to have done the trick! Love the easy ones.
