### ISSUE TITLE
respect existing $ZDOTDIR

### ISSUE THREAD

**Issue by techvanity** [romkatv/zsh4humans#105]
It looks like the install script is hard-coded to use $HOME for .zshenv and .zshrc.
I did `export $ZDOTDIR="$HOME/.config/zsh"` prior to installing z4h but it always creates the said two files in home. Consequently, zsh launches but since it looks for config files in $ZDOTDIR, it finds nothing there and starts barebones.

I could probably move z4h-generated files to $ZDOTDIR but the same issue will happen on z4h updates. Is it?

**Comment by romkatv** [comment]
> Consequently, zsh launches but since it looks for config files in $ZDOTDIR

When the installer launches zsh, it explicitly sets `ZDOTDIR=$HOME`, so it works fine.

> I could probably move z4h-generated files to $ZDOTDIR but the same issue will happen on z4h updates.

You can move files after the installation. `z4h update` doesn't modify rc files.

**Comment by techvanity** [comment]
Ah, I had the line `export $ZDOTDIR="$HOME/.config/zsh"` defined in `/etc/zsh/zshenv` as well, that was why it was looking for non existent rc files upon startup. Removing that line fixed the issue.

The feature request as stated in the title still stands. Many thanks for your work nevertheless. I have found z4h to be excellent. It needs more marketing :)

**Comment by romkatv** [comment]
Respecting `ZDOTDIR` during the installation means that zsh won't start in many cases. Right now it'll start as long as users don't modify system files such as `/etc/zsh/zshenv`. Closing as Wont' Fix.

**Comment by romkatv** [comment]
To clarify, zsh4humans respects `ZDOTDIR` everywhere except in the installer. The installer doesn't do anything apart from creating `~/.zshenv` and `~/.zshrc` and those files are never modified by zsh4humans afterwards. You can run the installer to create the initial files and then modify and/or move them.

**Comment by techvanity** [comment]
Question: After moving rc files to `~/.config/zsh`, I add them to my dotfiles repo. When setting up a new system, I would install zsh and pull the repo. Is that enough? I suppose .zenv code auto downloads z4h. Is that correct?

**Comment by romkatv** [comment]
Correct.
