### ISSUE TITLE
tab auto completion scans for subfolders' files

### ISSUE THREAD

**Issue by preludium975** [romkatv/zsh4humans#107]
Is it possible to disable the scanning for the subfolders' files when I press tab for filename auto-completion? In some cases, it reduces the performance and makes the whole shell quite laggy.

**Comment by romkatv** [comment]
> tab auto completion scans for subfolders' files

True.

**Comment by Syphdias** [comment]
I wonder if this get better by using `bfs`?

**Comment by romkatv** [comment]
Installing `bfs` is a good idea. It improves ranking of results.

The files and directories will still be scanned even when using `bfs` and the amount of shell lagishness will be the same. That said, I don't think there is any amount of lagishness in either case. Also, regular (non-recursive) completions results appear instantly. The extra results get streamed in but they don't prevent you from picking the completion you want.

**Comment by romkatv** [comment]
I added an option to disable recursive file completions (even though I'm not aware of a good reason to do this other than the force of habit).

```zsh
zstyle ':z4h:fzf-complete' recurse-dirs 'no'
```

**Comment by romkatv** [comment]
Forgot to mention that the new option works only in v5 (the latest release).
