### ISSUE TITLE
enable-fzf-tab:functions:39: no such function: _main_complete

### ISSUE THREAD

**Issue by gHerzmann** [romkatv/zsh4humans#11]
I installed zsh4humans in one of my machines and it worked perfectly out of the box. However when I tried to install it in another machine, I receive the following error whenever I start zsh:

```
enable-fzf-tab:functions:39: no such function: _main_complete
enable-fzf-tab:functions:46: no such function: _approximate
```
So the completions doesn't work.

I'm using zsh 5.8 on Endeavour OS (Arch based) on both machines.

**Comment by romkatv** [comment]
There was a bug in https://github.com/Aloxaf/fzf-tab that has since been fixed. Try running `z4h update`.

**Comment by gHerzmann** [comment]
Thank you, that fixed the issue!

**Comment by romkatv** [comment]
Thanks for the confirmation!
