### ISSUE TITLE
slow response on "command not found"

### ISSUE THREAD

**Issue by atjshop** [romkatv/zsh4humans#110]
see below, "command not found" took 9s to response, sometime even longer. Is there any settings to make it response much faster?

❯ aaa
zsh: command not found: aaa

~ ·················································· 9s 12:01:08 PM

**Comment by romkatv** [comment]
It can take a while because it can tell you how to install `aaa`. In this case it says nothing because there is no package with `aaa` in it.

There is no setting to disable this. Usually this shouldn't be a problem because you can see the program's name is mistyped before you hit enter (it's red). Is this a problem for you?

**Comment by atjshop** [comment]
thanks for the comment. sometime type too fast and pressed return before realize it is invalid command. 
I can use ctrl+c instead of waiting.

**Comment by romkatv** [comment]
What do you get if you type `bfs` and hit <kbd>Enter</kbd>?

**Comment by atjshop** [comment]
❯ bfs
zsh: command not found: bfs

~ ························································································································· 14s 04:13:54 PM

**Comment by romkatv** [comment]
That's odd. How about `uname -a` ?

**Comment by atjshop** [comment]
that returns correctly: 

❯ uname -a
Darwin xxxxx. 19.6.0 Darwin Kernel Version 19.6.0: Mon Apr 12 20:57:45 PDT 2021; root:xnu-6153.141.28.1~1/RELEASE_X86_64 x86_64

**Comment by romkatv** [comment]
Let's try to find a command that you don't have but that can actually be installed on macos. (I initially suggested `bfs` but I didn't know back then that you are on macos.)

How about `docker`? Or `bat`?

**Comment by atjshop** [comment]
I don't have wget install, it outputs how to install it. However it took 18s.

❯ wget
The program 'wget' is currently not installed. You can install it by typing:
  brew install wget

~ ······································································· 18s 05:29:23 PM

**Comment by romkatv** [comment]
18 seconds is over 10 times more than what I get.

I looked a bit closer and you should be able to disable this feature by adding the following line at the bottom of `~/.zshrc`:

```zsh
[[ ! -v functions[command_not_found_handler] ]] || unfunction command_not_found_handler
```

**Comment by atjshop** [comment]
Thanks. This works great!
