### ISSUE TITLE
`z4h install` not working

### ISSUE THREAD

**Issue by deejayem** [romkatv/zsh4humans#113]
Apologies if this is user error, but with a fresh install of zsh4humans v5, `z4h install` does not appear to be working.

For example, if I run `z4h install wfxr/forgit`, it returns immediately, and doesn't appear to have installed anything:
```
❯ ls $Z4H/wfxr    
ls: cannot access '/home/djm/.cache/zsh4humans/v5/wfxr': No such file or directory
❯ ls $Z4H/**/forgit
zsh: no matches found: /home/djm/.cache/zsh4humans/v5/**/forgit
```

I am able to install the same plugin without issue with various plugin managers, and it isn't limited to any specific plugin:
```
❯ z4h install hlissner/zsh-autopair
❯ ls $Z4H/hlissner                 
ls: cannot access '/home/djm/.cache/zsh4humans/v5/hlissner': No such file or directory
❯ z4h install marlonrichert/zsh-edit
❯ z4h install marlonrichert/zsh-edit@main
❯ ls $Z4H/marlonrichert                   
ls: cannot access '/home/djm/.cache/zsh4humans/v5/marlonrichert': No such file or directory
```
All of these are available on github.com, and use a `master` branch, except the last one which uses `main`.

Compare with:
```
❯ ls $Z4H/ohmyzsh/ohmyzsh/oh-my-zsh.sh 
/home/djm/.cache/zsh4humans/v5/ohmyzsh/ohmyzsh/oh-my-zsh.sh
```

Am I doing something wrong, or is this not working as exepcted?

**Comment by romkatv** [comment]
You need to put `z4h install ...` in `~/.zshrc` close to `z4h install ohmyzsh/ohmyzsh` (the latter is there to serve as an example). Once you do that, restart zsh with `exec zsh`.

**Comment by deejayem** [comment]
Thank you for the fast response. That solves it.

What I am trying to do is to have a separate `~/.zshrc.local` file (and using `z4h source ~/.zshrc.local` at the end of the generated `~/.zshrc`), to keep my customisations separate from the generated file. Can that work? Is there a particular statement in the generated `~/.zshrc` that it would need to before?

**Comment by romkatv** [comment]
All `z4h install` calls must be made before `z4h init`.

You *really* should edit the generated file. You'll never re-generate it again. Go over it and do as you please with it. Remove comments you find useless, remove examples, etc.

**Comment by deejayem** [comment]
Thank you.

**Comment by romkatv** [comment]
To add further, you'll need to add `.zshrc`, `.zshenv` and `.p10k.zsh` to your dotfiles repo. These files are all you need to recreate your shell environment on another machine. You don't need to run the install script again even on another machine. Simply running `zsh` will bootstrap everything.

**Comment by deejayem** [comment]
Here's why I was thinking that keeping the customisations separate, and running the install script on each machine would be better:

1) What if one machine runs macOS, one machine runs Linux with a graphical environment, one machine runs Linux but will be connected to from various places where not all icons/fonts will be available? I could figure out what needs to change, and do it manually, but re-running the script seems easier.
2) What if there are new options in the next version of zsh4humans? How would I know about those without regenerating the file?

**Comment by romkatv** [comment]
> 1. What if one machine runs macOS, one machine runs Linux with a graphical environment, one machine runs Linux but will be connected to from various places where not all icons/fonts will be available? I could figure out what needs to change, and do it manually, but re-running the script seems easier.

The script doesn't install anything and its behavior doesn't depend on the OS you are running it on. When it asks about PC vs Mac, it's asking about your keyboard layout (whether you have Alt vs Option), which gets reflected in your `~/.zshrc` with this line:

```zsh
# Keyboard type: 'mac' or 'pc'.
zstyle ':z4h:bindkey' keyboard 'pc'
```

The installer creates `~/.zshrc` and `~/.zshenv` and then runs `zsh`. The rc files are meant to be used everywhere. You can create separate rc files for different operating systems if you want but it's not required (and usually more work).

> 2. What if there are new options in the next version of zsh4humans? How would I know about those without regenerating the file?

That's a good question and I don't have a good answer. Note that running the installer won't let you know about new options. Sometimes it might but that would be rare.

A huge advantage of keeping your `~/.zshrc` is that your shell will actually work. I guarantee backward compatibility forever, so as long as you have your `~/.zshrc`, you'll be able to get the same shell environment.

If you run the installer, there are no guarantees. The new file you get might look completely different and it can have very different defaults. It might even create a different number of files, or files in different places. Running the installer is only appropriate if you are willing to spend a lot of time and effort to start your configuration from scratch (kind of what you are doing now).

**Comment by deejayem** [comment]
Thank you for the response. If that's the only difference in .zshrc between PC and Mac, then changing it on Mac, and having a separate `p10k.zsh` for servers is likely the easiest way to get what I'm after.

**Comment by romkatv** [comment]
The easiest thing would be to have a single config. You can do something conditional in there if you need to.

You also don't need to manually install or copy your rc files to servers. One of the most useful features of zsh4humans is that it can automatically give you the same shell environment on servers over ssh. By default you should have these options:

```zsh
# Enable ('yes') or disable ('no') automatic teleportation of z4h over
# ssh when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1'   enable 'yes'
zstyle ':z4h:ssh:*.example-hostname2' enable 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   enable 'no'

# Send these files over to the remote host when connecting over ssh to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'
```

As you can see, "automatic teleportation" is disable by default for all hosts. You can try enabling it for one host, or even enable for all host and disable for specific hosts when necessary (I do the latter). If your rc files source additional files that aren't in `$Z4H` directory, you'll need to list them among `send-extra-files`.

Then just try to `ssh some-host`. It'll work even if you don't have `sudo` or `zsh` on the server.
