### ISSUE TITLE
Stuck in vi-mode when attached to tmux

### ISSUE THREAD

**Issue by tumd** [romkatv/zsh4humans#121]
Hi,

Since the last couple of few days/weeks I've noticed a problem while attached to a local tmux-session the shell switches to vi key bindings (bindkey -v) all of a sudden. My guess this issue may have been introduced, and be related to https://github.com/romkatv/zsh4humans/commit/90d521d70d06d6778b9ba9e25f1b08aaae65d513.

Steps to reproduce;
On a new zsh-shell running z4h not attached to my own tmux session.
```
❯ tmux -V
tmux 3.2
❯ echo $TERM
tmux-256color
❯ bindkey -Ll main
bindkey -A emacs main
twan@rupert ~
❯
```
Starting an empty tmux;
```
❯ bindkey -Ll main
bindkey -A emacs main
❯ tmux -Ltemp -f /dev/null -c "/usr/local/Cellar/zsh/5.8_1/bin/zsh -f"
rupert% bindkey -Ll main
bindkey -A viins main
```
As you can see the keymap changed to `viins` by some reason.

Starting a clean bash in a new iTerm-tab showing the expected result;
```
rupert:~ twan$ # Not in vi-mode, not sure how to demonstrate it in bash.
rupert:~ twan$ tmux -Ltemp -f /dev/null -c "/usr/local/Cellar/zsh/5.8_1/bin/zsh -f"
rupert% bindkey -Ll main
bindkey -A emacs main
```
Skipping the `-c` argument to tmux in the above example will start my default z4h shell in emacs-mode, as expected.

**Comment by romkatv** [comment]
Do I understand correctly that you are starting `zsh -f` and are surprised to see `viins` as `main` keymap? If so, what's your `EDITOR`? The default keymap in zsh depends on this var. Also, when you run `zsh -f`, nothing from zsh4humans runs, so it cannot affect anything.

**Comment by romkatv** [comment]
I think there is also some confusion. "vi mode" is not a property of a tty. It's a thing inside zsh. It's also a (separate) thing inside bash. Also in some editors.

**Comment by tumd** [comment]
Yes, my EDITOR is indeed set to vim.
The confusion occurs for me when starting a new terminal running z4h the keybind is set to `emacs`, but as soon as I start a new tmux session from this z4h-shell, the keybinding changes to `viins` in the new shell opened in tmux.

**Comment by romkatv** [comment]
`EDITOR=vim zsh -f` will give you `viins` no matter where you run it. On the other hand, `EDITOR=vim zsh` can result in any keymap because it sources rc files. If your rc files happen to run `bindkey -e` (like z4h rc files do), then you have `emacs`.

**Comment by tumd** [comment]
I didn't know zsh was setting `viins` based on `EDITOR`.
But yea, I noticed that z4h runs `bindkey -e` in it's rc files, but some how starting a new zsh from another zsh-shell results in `viins`. I.e tmux may be ruled out from the irregular behavior.

```
❯ echo $EDITOR
vim
❯ bindkey -Ll main
bindkey -A emacs main
❯ zsh
❯ bindkey -Ll main
bindkey -A viins main
```

**Comment by romkatv** [comment]
Oh, I think you are running an older version of z4h. There was a period with the bug you describe. Namely, than running `zsh` or `exec zsh` would result in `viins` keymap if your `EDITOR` is `*vi*`. Try `z4h update`.

**Comment by tumd** [comment]
Oh, that seems to have solved it. Dang, was almost sure an update was triggered recently. :)
Thank you! :D

**Comment by romkatv** [comment]
I think I've introduced the bug less than a month ago and fixed it less than a week ago (might be wrong but should be close to these boundaries).

Glad you have the issue sorted out!
