### ISSUE TITLE
z4h rearranges path on macOS

### ISSUE THREAD

**Issue by kvndrsslr** [romkatv/zsh4humans#125]
`echo $path` without z4h on clean zsh 5.8 at `/bin/zsh` (no config files):
`/usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/MacGPG2/bin /Applications/Little Snitch.app/Contents/Components /Applications/kitty.app/Contents/MacOS`

`echo $path` with clean z4h v5 installation on clean zsh 5.8 at `/bin/zsh` (no config files):
`/bin /Users/kvn/bin /Users/kvn/.local/bin /usr/local/sbin /Library/TeX/texbin /usr/local/MacGPG2/bin /Applications/Little Snitch.app/Contents/Components /Applications/kitty.app/Contents/MacOS /usr/local/bin /usr/bin /usr/sbin /sbin /Users/kvn/.cache/zsh4humans/v5/fzf/bin`

Particularly irritating is that `/bin` is now moved to the front, which renders all my homebrew overrides unusable.

I am 100% sure this has worked correctly before and I think the latest update broke it (I executed `z4h update` yesterday and just noticed this now).

**Comment by romkatv** [comment]
> z4h rearranges path on macOS

It doesn't or at least it's not supposed to. zsh4humans can add additional directories but doesn't delete or change the order of the existing directories in `PATH`.

What is the output of the following command?

```zsh
PATH= MANPATH= /usr/libexec/path_helper -s
```

What is the output of the following command?

```zsh
ZDOTDIR=/not-found zsh -lixc 'typeset -p path'
```

**Comment by Zoddo** [comment]
I have the same issue on linux

Without z4h:
```
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin
```

With z4h:
```
/home/zoddo/bin:/snap/bin:/home/zoddo/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/games:/home/zoddo/.cache/zsh4humans/v4/fzf/bin
```

(notice the `/snap/bin` which move before `/usr/local/bin` -used to override a few system binaries)

Doing a `grep -r /snap/bin .cache/zsh4humans/`, I've identified the following lines: https://github.com/romkatv/zsh4humans/blob/ae67a80f12d87429c12687b6ad5f5aeec8f15405/main.zsh#L99-L101

I don't understand what it does, but I think it's what causes this issue.

**Comment by romkatv** [comment]
@Zoddo You are right, the indicated code does change the order of directories in `path`. My previous statement to the countrary was wrong.

I'm not sure what to do about this yet.

As a workaround I suggest modifying `path` the way you like in `~/.zshrc`. Search for `path` and add something like this next to the hit:

```zsh
path=(/usr/local/bin $path)
```

This ensures that `/usr/local/bin` is in front.

**Comment by romkatv** [comment]
> @Zoddo You are right, the indicated code does change the order of directories in `path`. My previous statement to the countrary was wrong.

I take that back. I don't see any path reordering. For example:

```zsh
% PATH='/usr/local/bin:/bin' zsh -ic 'print -rC1 -- $path'
...
/usr/local/bin
/bin
...

% PATH='/bin:/usr/local/bin' zsh -ic 'print -rC1 -- $path'
...
/bin
/usr/local/bin
...
```

So the order is preserved.

In order to diagnose the issue you are having I'll need instructions how to reproduce.

**Comment by Zoddo** [comment]
Ok, my test was biased as I confirmed the issue on another machine without z4h installed, then installing it.

Historically, I always added a `~/.zprofile` that sourced `/etc/profile` and `~/.profile`. During the install of z4h, these files are moved to `~/zsh-backup`.

On my system, the snapd packages come with a `/etc/profile.d/apps-bin-path.sh` file which adds `/snap/bin` at the end of the PATH:
```sh
# Expand $PATH to include the directory where snappy applications go.
snap_bin_path="/snap/bin"
if [ -n "${PATH##*${snap_bin_path}}" -a -n "${PATH##*${snap_bin_path}:*}" ]; then
    export PATH=$PATH:${snap_bin_path}
fi
```

This is why the path was correct before installing z4h. But after the install of z4h, this file isn't sourced anymore, so `/snap/bin` is missing in the PATH env, and this path is added by z4h, but it adds it at the *beginning*. This is the issue I observed.

This could be fixed in z4h by adding `/snap/bin` at the *end* of the PATH, but I think there is a more complex issue: currently, the ordering issue can happen with any other directory (usually, the PATH should contain user's dot-directories first, then system directories (with "/usr/local/" variants at first), but if one of them is missing, it will always be *prepended*).

Honestly, I don't see how this can be properly fixed (without ugly hacks).

**Comment by kvndrsslr** [comment]
> > z4h rearranges path on macOS
> 
> It doesn't or at least it's not supposed to. zsh4humans can add additional directories but doesn't delete or change the order of the existing directories in `PATH`.
> 
> What is the output of the following command?
> 
> ```shell
> PATH= MANPATH= /usr/libexec/path_helper -s
> ```

```
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components"; export PATH;
MANPATH="/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/usr/local/MacGPG2/share/man"; export MANPATH;
```

> 
> What is the output of the following command?
> 
> ```shell
> ZDOTDIR=/not-found /bin/zsh -lixc 'typeset -p path'
> ```

```
+/etc/zprofile:6> [ -x /usr/libexec/path_helper ']'
+/etc/zprofile:7> /usr/libexec/path_helper -s
+/etc/zprofile:7> eval 'PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Applications/Little' 'Snitch.app/Contents/Components:/Users/kvn/bin:/Users/kvn/.local/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/Users/kvn/.cache/zsh4humans/v5/fzf/bin";' export 'PATH;' 'MANPATH="/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/usr/local/MacGPG2/share/man:/Users/kvn/.cache/zsh4humans/v5/fzf/man";' export 'MANPATH;'
+(eval):1> PATH='/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/bin:/Applications/Little Snitch.app/Contents/Components:/Users/kvn/bin:/Users/kvn/.local/bin:/usr/local/sbin:/Applications/kitty.app/Contents/MacOS:/Users/kvn/.cache/zsh4humans/v5/fzf/bin' 
+(eval):1> export PATH
+(eval):1> MANPATH=/usr/share/man:/usr/local/share/man:/Library/TeX/Distributions/.DefaultTeX/Contents/Man:/usr/local/MacGPG2/share/man:/Users/kvn/.cache/zsh4humans/v5/fzf/man 
+(eval):1> export MANPATH
+/etc/zshrc:7> [[+/etc/zshrc:7> locale LC_CTYPE
+/etc/zshrc:7> [[ UTF-8 == UTF-8 ]]
+/etc/zshrc:8> setopt COMBINING_CHARS
+/etc/zshrc:12> disable log
+/etc/zshrc:15> HISTFILE=/not-found/.zsh_history 
+/etc/zshrc:16> HISTSIZE=2000 
+/etc/zshrc:17> SAVEHIST=1000 
+/etc/zshrc:20> setopt BEEP
+/etc/zshrc:24> [[ -r /not-found/.zkbd/tmux-256color-apple ]]
+/etc/zshrc:27> typeset -g -A key
+/etc/zshrc:29> [[ -n $'\C-[OP' ]]
+/etc/zshrc:29> key[F1]=$'\C-[OP' 
+/etc/zshrc:30> [[ -n $'\C-[OQ' ]]
+/etc/zshrc:30> key[F2]=$'\C-[OQ' 
+/etc/zshrc:31> [[ -n $'\C-[OR' ]]
+/etc/zshrc:31> key[F3]=$'\C-[OR' 
+/etc/zshrc:32> [[ -n $'\C-[OS' ]]
+/etc/zshrc:32> key[F4]=$'\C-[OS' 
+/etc/zshrc:33> [[ -n $'\C-[[15~' ]]
+/etc/zshrc:33> key[F5]=$'\C-[[15~' 
+/etc/zshrc:34> [[ -n $'\C-[[17~' ]]
+/etc/zshrc:34> key[F6]=$'\C-[[17~' 
+/etc/zshrc:35> [[ -n $'\C-[[18~' ]]
+/etc/zshrc:35> key[F7]=$'\C-[[18~' 
+/etc/zshrc:36> [[ -n $'\C-[[19~' ]]
+/etc/zshrc:36> key[F8]=$'\C-[[19~' 
+/etc/zshrc:37> [[ -n $'\C-[[20~' ]]
+/etc/zshrc:37> key[F9]=$'\C-[[20~' 
+/etc/zshrc:38> [[ -n $'\C-[[21~' ]]
+/etc/zshrc:38> key[F10]=$'\C-[[21~' 
+/etc/zshrc:39> [[ -n $'\C-[[23~' ]]
+/etc/zshrc:39> key[F11]=$'\C-[[23~' 
+/etc/zshrc:40> [[ -n $'\C-[[24~' ]]
+/etc/zshrc:40> key[F12]=$'\C-[[24~' 
+/etc/zshrc:41> [[ -n $'\C-[[1;2P' ]]
+/etc/zshrc:41> key[F13]=$'\C-[[1;2P' 
+/etc/zshrc:42> [[ -n $'\C-[[1;2Q' ]]
+/etc/zshrc:42> key[F14]=$'\C-[[1;2Q' 
+/etc/zshrc:43> [[ -n $'\C-[[1;2R' ]]
+/etc/zshrc:43> key[F15]=$'\C-[[1;2R' 
+/etc/zshrc:44> [[ -n $'\C-[[1;2S' ]]
+/etc/zshrc:44> key[F16]=$'\C-[[1;2S' 
+/etc/zshrc:45> [[ -n $'\C-[[15;2~' ]]
+/etc/zshrc:45> key[F17]=$'\C-[[15;2~' 
+/etc/zshrc:46> [[ -n $'\C-[[17;2~' ]]
+/etc/zshrc:46> key[F18]=$'\C-[[17;2~' 
+/etc/zshrc:47> [[ -n $'\C-[[18;2~' ]]
+/etc/zshrc:47> key[F19]=$'\C-[[18;2~' 
+/etc/zshrc:48> [[ -n $'\C-[[19;2~' ]]
+/etc/zshrc:48> key[F20]=$'\C-[[19;2~' 
+/etc/zshrc:49> [[ -n $'\C-H' ]]
+/etc/zshrc:49> key[Backspace]=$'\C-H' 
+/etc/zshrc:50> [[ -n $'\C-[[2~' ]]
+/etc/zshrc:50> key[Insert]=$'\C-[[2~' 
+/etc/zshrc:51> [[ -n $'\C-[[3~' ]]
+/etc/zshrc:51> key[Delete]=$'\C-[[3~' 
+/etc/zshrc:52> [[ -n $'\C-[[1~' ]]
+/etc/zshrc:52> key[Home]=$'\C-[[1~' 
+/etc/zshrc:53> [[ -n $'\C-[[4~' ]]
+/etc/zshrc:53> key[End]=$'\C-[[4~' 
+/etc/zshrc:54> [[ -n $'\C-[[5~' ]]
+/etc/zshrc:54> key[PageUp]=$'\C-[[5~' 
+/etc/zshrc:55> [[ -n $'\C-[[6~' ]]
+/etc/zshrc:55> key[PageDown]=$'\C-[[6~' 
+/etc/zshrc:56> [[ -n $'\C-[OA' ]]
+/etc/zshrc:56> key[Up]=$'\C-[OA' 
+/etc/zshrc:57> [[ -n $'\C-[OD' ]]
+/etc/zshrc:57> key[Left]=$'\C-[OD' 
+/etc/zshrc:58> [[ -n $'\C-[OB' ]]
+/etc/zshrc:58> key[Down]=$'\C-[OB' 
+/etc/zshrc:59> [[ -n $'\C-[OC' ]]
+/etc/zshrc:59> key[Right]=$'\C-[OC' 
+/etc/zshrc:63> [[ -n $'\C-[[3~' ]]
+/etc/zshrc:63> bindkey $'\C-[[3~' delete-char
+/etc/zshrc:64> [[ -n $'\C-[[1~' ]]
+/etc/zshrc:64> bindkey $'\C-[[1~' beginning-of-line
+/etc/zshrc:65> [[ -n $'\C-[[4~' ]]
+/etc/zshrc:65> bindkey $'\C-[[4~' end-of-line
+/etc/zshrc:66> [[ -n $'\C-[OA' ]]
+/etc/zshrc:66> bindkey $'\C-[OA' up-line-or-search
+/etc/zshrc:67> [[ -n $'\C-[OB' ]]
+/etc/zshrc:67> bindkey $'\C-[OB' down-line-or-search
+/etc/zshrc:70> PS1='%n@%m %1~ %# ' 
+/etc/zshrc:73> [ -r /etc/zshrc_ ']'
+zsh:1> typeset -p path
typeset -aT PATH path=( /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Library/TeX/texbin /usr/local/MacGPG2/bin '/Applications/Little Snitch.app/Contents/Components' /Users/kvn/bin /Users/kvn/.local/bin /usr/local/sbin /Applications/kitty.app/Contents/MacOS /Users/kvn/.cache/zsh4humans/v5/fzf/bin )
```

I did some more tests yesterday and it seems that z4h prepends `dirname $(which zsh)` to the `$path`. I come to this conlusion because my login shell is `/bin/zsh` but I also have an installation at `/usr/local/bin/zsh` (which is an alias for `/usr/local/Cellar/zsh/5.8_1/bin/zsh`) and when I start a zsh instance from `/usr/local/bin/zsh` my path looks like this:

```
/Users/kvn/bin /usr/local/Cellar/zsh/5.8_1/bin /bin /Users/kvn/.local/bin /usr/local/sbin /Library/TeX/texbin /usr/local/MacGPG2/bin /Applications/Little Snitch.app/Contents/Components /Applications/kitty.app/Contents/MacOS /usr/local/bin /usr/bin /usr/sbin /sbin /Users/kvn/.cache/zsh4humans/v5/fzf/bin
```

As for the remaining reordering I have no idea where that stems from.

**Comment by romkatv** [comment]
> I did some more tests yesterday and it seems that z4h prepends the `dirname` of the current zsh executable to the `$path`.

Aha! That's great detective work.

Yes, zsh4humans indeed does that. This is meant to guarantee that running `zsh` or `exec zsh` will give you the same shell. I didn't realize that this could have the side effect of rearranging directories in `PATH`. I'll need to think how to solve this problem better.

The fix/workaround is to use `zsh` that comes first in `PATH` as your login shell. You can achieve this either by changing your login shell or deleting `zsh` that you aren't using and that's shadowing your login shell in `PATH`.

**Comment by kvndrsslr** [comment]
I also figured out the remaining reordering: it is caused by kitty terminal emulator (will file an issue there).
I do not prefer to have `/usr/local/bin/zsh` as my login shell because its sourced from homebrew and might break (its a low percentage chance but it is there).
For the time being, I will just re-insert `/bin` at the end of my path in `.zshrc`.
Maybe we can leave this issue open until you figure out a way to spawn the right zsh instance without reordering path (e.g. by aliasing the current executable to some temporary file in a directory within `~/.cache/zsh4humans` and prepending that directory to the path).

By the way, thanks for all you are doing here, z4h is indeed very helpful for being productive in the shell and the best solution I have found yet.

**Comment by romkatv** [comment]
> I do not prefer to have `/usr/local/bin/zsh` as my login shell

Then the easy fix is to remove it. Would that work for you?

> For the time being, I will just re-insert `/bin` at the end of my path in `.zshrc`.

Just in case, here's how you can do it in `~/.zshrc`:

```zsh
path=(${path:#/bin} /bin)
```

> Maybe we can leave this issue open until you figure out a way to spawn the right zsh instance without reordering path (e.g. by aliasing the current executable to some temporary file in a directory within `~/.cache/zsh4humans` and prepending that directory to the path).

Yeah, that's what I'm considering. It's a bit tricky because you can have multiple instances of zsh running from different binaries at the same time.

> By the way, thanks for all you are doing here, z4h is indeed very helpful for being productive in the shell and the best solution I have found yet.

Thanks for the kind words 🤗

**Comment by romkatv** [comment]
> This could be fixed in z4h by adding `/snap/bin` at the _end_ of the PATH

Good point. I should've done it this way from the start. Fixed.

> I think there is a more complex issue: currently, the ordering issue can happen with any other directory (usually, the PATH should contain user's dot-directories first, then system directories (with "/usr/local/*" variants at first), but if one of them is missing, it will always be _prepended_).

I think this only becomes an issue if `PATH` has directories from `$HOME` and is lacking some system directories *at the point when zsh is started*. While this is possible, it's unlikely. Users would need to do something unusual and explicit to arrange for this to happen.

> Honestly, I don't see how this can be properly fixed without ugly hacks.

I don't see how the "proper fix" can even be formulated. Suppose that before zsh starts `PATH` is `$HOME/bin:/bin:$HOME/sbin:/sbin`. Where should `/usr/local/bin` and `$HOME/.local/bin` be inserted?

zsh4humans tries to set `PATH` so that it's almost always what you would want. If you want something else, you can munge it in `~/.zshrc`.

**Comment by romkatv** [comment]
> > Maybe we can leave this issue open until you figure out a way to spawn the right zsh instance without reordering path (e.g. by aliasing the current executable to some temporary file in a directory within `~/.cache/zsh4humans` and prepending that directory to the path).
> 
> Yeah, that's what I'm considering. It's a bit tricky because you can have multiple instances of zsh running from different binaries at the same time.

This is done. There are now no known cases where zsh4humans change the order of directories in `PATH` that was set prior to starting `zsh`.

**Comment by romkatv** [comment]
I believe this issue is fixed. Please shout if not.

**Comment by kvndrsslr** [comment]
Can confirm it is fixed, tyvm!

**Comment by romkatv** [comment]
Thanks for the confirmation.
