### ISSUE TITLE
How to deactivate SSH function?

### ISSUE THREAD

**Issue by mliradelc** [romkatv/zsh4humans#127]
Hi @romkatv ! Thanks for your amazing work on Z4H,

I love the feature that you can send your profile to an SSH machine, helps me a lot to have the same color scheme and shortcuts like in my local environment. Unfortunately, my coworkers and boss hate this because I disrupt the ZSH configuration in our servers every time I have to log in with the admin user to those machines.

Is there a way that if I use `ssh` z4h won't send my profile (Like before installing z4h)?

**Comment by romkatv** [comment]
What you are asking for is the default.

**Comment by romkatv** [comment]
The default was different before v5. Perhaps you are on the older version? If so, try running the current installer.

**Comment by mliradelc** [comment]
Thanks, how I can see what installer I have?

**Comment by romkatv** [comment]
You don’t have an installer. You can check the version of zsh4humans that you’ve installed with `echo $Z4H`.

**Comment by mliradelc** [comment]
Thanks, I have version 4, I will update ASAP

**Comment by mliradelc** [comment]
Update, unfotunately, after I stripped z4h and any config, and then installed again z4h I have the same issue:
```bash
 me@computer ~  which ssh
ssh () {
        z4h ssh "$@"
}
```

**Comment by romkatv** [comment]
Try `ssh hostname` instead of `which ssh`.

**Comment by mliradelc** [comment]
Thanks @romkatv ! Works as it should!
