### ISSUE TITLE
[question] how to use `z4h-fzf-complete` from a widget 

### ISSUE THREAD

**Issue by romrot** [romkatv/zsh4humans#129]
Hey I

I'm trying to use the 'z4h-fzf-complete' widget from another widget but when several additions are possible the `fzf` menu is empty while using the `expand-or-complete` zsh widget everything works fine (the menu shows all possible completions).

Here are the two versions I tried, with `expand-or-complete`:

```
function .zle-git-add-1() {
    emulate -LR zsh

    zle push-input
    LBUFFER="git add -- "
    zle expand-or-complete
}

zle -N .zle-git-add-1
bindkey '\eg\ea' .zle-git-add-1
```
with `z4h-fzf-complete`:

```
function .zle-git-add-2() {
    emulate -LR zsh

    zle push-input
    LBUFFER="git add -- "
    zle z4h-fzf-complete
}

zle -N .zle-git-add-2
bindkey '\eg\eb' .zle-git-add-2
```

I also noticed that when I leave `.zle-git-add-2` then re-launch the completion menu by pressing the <kbd>Tab</kbd> key all the completions are then correctly displayed!

My question is what the correct way to use `z4h-fzf-complete` inside a ZLE Widget?

Z4H version: v5
ZSH version: zsh 5.8 (x86_64-pc-linux-gnu)
OS: Ubuntu 20.04 (tested in Docker container and native)
Terminal: Alacritty

**Comment by romkatv** [comment]
I don’t know the answer from the top of my head. If I get the time, I’ll try to find it for you but it may take months or even never happen.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.
