### ISSUE TITLE
Attempts to install homebrew-command-not-found on linux - and fails...

### ISSUE THREAD

**Issue by winterhalder** [romkatv/zsh4humans#132]
Seeing this error when attempting to install on Mint Linux:

...
z4h: installing homebrew-command-not-found
Error: /home/linuxbrew/.linuxbrew/Cellar is not writable. You should change the
ownership and permissions of /home/linuxbrew/.linuxbrew/Cellar back to your
user account:
  sudo chown -R $(whoami) /home/linuxbrew/.linuxbrew/Cellar
fatal: could not create work tree dir '/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-command-not-found': Permission denied
Error: Failure while executing; `git clone https://github.com/Homebrew/homebrew-command-not-found /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-command-not-found --origin=origin -q` exited with 128.
z4h: installing tmux
z4h: installing ohmyzsh/ohmyzsh
z4h: installing powerlevel10k
z4h: fetching gitstatus binary

z4h: init failed

**Comment by winterhalder** [comment]
So it looks like the issue there is that I had zsh4humans installed in two user accounts on the box...  one was root, and the other a regular user account.

It looks like to share the ownership of that /home/linuxbrew account directory?

I had to change the ownership over to the user account...  (which I use most often - not sure if I'll have further problems with the root account - maybe only the next time I try to upgrade maybe?)

**Comment by romkatv** [comment]
Thanks for the report. Should be fixed now.
