### ISSUE TITLE
Change ZDOTDIR to `~/.config/zsh/`

### ISSUE THREAD

**Issue by laraib07** [romkatv/zsh4humans#133]
Loved your work.

Consider changing ZDOTDIR from ~ to ~/config/zsh/ and move .zshrc .zsh_history and .p10k.zsh* to it. This way home directory will be less cluttered.

**Comment by romkatv** [comment]
Feel tree to do this in your own config. zsh4humans respects `ZDOTDIR` if you set it. I won't do this by default because I think the advantages outweigh the disadvantages.

**Comment by laraib07** [comment]
I did, but .zsh_history doesnt seems to follow it. 
And please guide me how can I move `.p10k.*` to `~/.config/zsh/`.

**Comment by laraib07** [comment]
Thanks a bunch 🙂
