### ISSUE TITLE
Issues installing z4h on remote Synology NAS (DSM 7)

### ISSUE THREAD

**Issue by MisterWS** [romkatv/zsh4humans#136]
I have recently upgraded my Synology NAS to DSM 7.0 (it's based on Debian, and the latest upgrade switched to using systemd to manage services). Unfortunately, when I ssh into this machine from a computer with z4h installed, the initial remote install of z4h fails with the following message:

````sh
z4h: installing systemd completions
-z4h-postinstall-systemd:7: command not found: systemd-path

z4h: init failed
````

After a little troubleshooting, it looks like there is no executable called `systemd-path` on the machine (presumably because it's not included in the custom Synology distro used by the NAS). Other than bypassing z4h entirely when connecting to this specific machine (by using the ssh passthrough capability), I can't figure out how to amend my .zshrc to successfully account for this.

Any ideas?

**Comment by romkatv** [comment]
Thanks for the report. Fixed. Please run `z4h update` on your local machine and then try to ssh again.

**Comment by MisterWS** [comment]
NP. I've tried running `z4h update`, but I'm using v4 at the moment, so I'm guessing I'll have to upgrade to v5. Do I just re-run the install script in the README?

**Comment by romkatv** [comment]
I've backported the fix to v4 and v3.

**Comment by MisterWS** [comment]
Awesome 😎. Thanks so much.
