### ISSUE TITLE
fzf hangs when pressing enter after choosing directory

### ISSUE THREAD

**Issue by tomyummmm** [romkatv/zsh4humans#137]
Hi,

I am using this on WSL Ubuntu 20.04 and 18.04 on 2 separate PCs, and both show the same issue. For example "cd EE" + Tab key brings up files and folders instantaneously, but when I select one and hit Enter key, it hangs for upwards of 10 seconds, sometimes not seeming to respond until i hit enter or ctrl C a few times.

I am using the installation of zsh4humans as is, no modifications thus far. Using ctrl + R and selecting enter is instantaneous, it only hangs when i press enter after choosing a directory for cd

![image](https://user-images.githubusercontent.com/65211592/132473928-6e23dade-e34f-4ac5-8033-fb26cea8e147.png)

**Comment by romkatv** [comment]
What happens if you press ESC instead of ENTER? Is it fast or slow?

What happens if you manually type the whole `cd` command with exactly the same argument and press ENTER? Is it fast or slow?

**Comment by tomyummmm** [comment]
> What happens if you press ESC instead of ENTER? Is it fast or slow?
It also hangs, sometimes it instantaneously exits, but generally hangs.


> What happens if you manually type the whole `cd` command with exactly the same argument and press ENTER? Is it fast or slow?

When typing whole 'cd' command is instantaneous.

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
() {
  emulate -L zsh
  if [[ -v commands[bfs] ]]; then
    print -r -- $commands[bfs]
    command bfs --version
  fi
  print -r -- $commands[find]
  command find --version
}
```

**Comment by romkatv** [comment]
Also, what happens if you type `cd /usr/`, press TAB and then accept any directory with ENTER? Is it fast or slow?

**Comment by tomyummmm** [comment]
> ```shell
> () {
>   emulate -L zsh
>   if [[ -v commands[bfs] ]]; then
>     print -r -- $commands[bfs]
>     command bfs --version
>   fi
>   print -r -- $commands[find]
>   command find --version
> }
> ```

/usr/bin/find
find (GNU findutils) 4.7.0-git
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Eric B. Decker, James Youngman, and Kevin Dalley.
Features enabled: D_TYPE O_NOFOLLOW(enabled) LEAF_OPTIMISATION FTS(FTS_CWDFD) CBO(level=2)

**Comment by tomyummmm** [comment]
> 
> 
> Also, what happens if you type `cd /usr/`, press TAB and then accept any directory with ENTER? Is it fast or slow?

Is fast, no hangs when i try different folders

**Comment by romkatv** [comment]
Try `find . -type d` in the problematic directory. Does it hang?

You can try installing `bsf` (`sudo apt-get install -y bsf`). This is a good idea in any case because it improves ranking of file completions. It also might just fix the issue for you. If it doesn't, add the following line to `~/.zshrc` and run `exec zsh`:

```zsh
zstyle ':z4h:fzf-complete' recurse-dirs 'no'
```

**Comment by tomyummmm** [comment]
> 
> 
> Try `find . -type d` in the problematic directory. Does it hang?
> 

No hang, is fast

> You can try installing `bsf` (`sudo apt-get install -y bsf`). This is a good idea in any case because it improves ranking of file completions. It also might just fix the issue for you.

```
❯ sudo apt-get install -y bsf
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package bsf
❯ bsf
Command 'bsf' not found, but can be installed with:

sudo apt install code-aster-gui
```
So am i supposed to install this? Your suggestion below to turn off recursive seems to have solved the problem with the cd fzf autocomplete. Although i am also training myself to use the zsh style of changing directories without the cd command, seems quicker too even with the recurse-dirs 'yes'.

>  If it doesn't, add the following line to `~/.zshrc` and run `exec zsh`:
> ```shell
> zstyle ':z4h:fzf-complete' recurse-dirs 'no'
> ```

Seems to have resolved the issue if there is some lag when using fzf TAB autocomplete together with "cd" command.

**Comment by romkatv** [comment]
Sorry, it’s `bfs`, not `bsf`.

**Comment by tomyummmm** [comment]
> 
> 
> Sorry, it’s `bfs`, not `bsf`.

Installed, exec zsh and tried again with 'cd' command TAB autocomplete, does not hang anymore with recurse-dirs 'yes'. The delay is very slight delay, just a little bit slower compared to the ZSH style of changing directories without 'cd' command.

I guess you can mark this as closed and perhaps put up the workaround in an FAQ / Issues. Thanks!

**Comment by romkatv** [comment]
What kind of special directory was that? If I wanted to reproduce this on my machine, what would I need to do?

**Comment by tomyummmm** [comment]
> 
> 
> What kind of special directory was that? If I wanted to reproduce this on my machine, what would I need to do?

Not really a special directory, i am using WSL, and i think its just an issue with using folders that is accessible with windows like /mnt/c/Users/whatever which might have caused issues with the recursive directory listings i think, as there are many files in the folders I have in addition to whatever Windows has.

**Comment by romkatv** [comment]
I use WSL and don’t have this issue. Can you try to narrow it down to a more specific folder?

**Comment by tomyummmm** [comment]
> 
> 
> I use WSL and don’t have this issue. Can you try to narrow it down to a more specific folder?

Quite literally when i am in ~w, /mnt/c/Users/me, it hangs when i 'cd' TAB without bfs. In ~ or / its fine though, but i assume that is because it is able to recurse finish very quickly in root and home.

**Comment by romkatv** [comment]
Thanks! I was able to reproduce a delay of about 0.5 seconds under the conditions similar to what you've described. It's probably just a matter of degree between our setups. I'll keep the issue open to figure out where the delay is coming from. There should be none.

In your previous comment you've mentioned buffering several times. What do you mean by that? What kind buffering are you seeing and where?

**Comment by tomyummmm** [comment]
Buffering as in letting the fzf "load" finish, where the spiral thing doesnt show anymore. So just pressing TAB, moving to/ selecting the directory, waiting for the spiral load animation to disappear, then pressing ENTER.

**Comment by romkatv** [comment]
This should be fixed now. Please give it a try.

1. Run `z4h update`.
2. Remove `bfs` with `sudo apt-get remove -y bfs`
3. Verify that completions for `cd` are fast.
4. Optional but recommended: install `bfs` with `sudo apt-get install -y bfs`. This improves ranking of files, so it's a good idea to install `bfs`.

By the way, you might want to use specialized widgets for changing the current directory. There is <kbd>Alt+Left</kbd> and <kbd>Alt+Right</kbd> to go back/forward (similar to how back/forward buttons work in a web browser), <kbd>Alt+Up</kbd> to go to the parent directory, and <kbd>Alt+Down</kbd> to go to a subdiretory. There is also <kbd>Alt+R</kbd> for fzf-based directory history.

In my own config I rebind things a little bit:

```zsh
z4h bindkey z4h-fzf-dir-history Alt+Down

zstyle ':z4h:fzf-dir-history' fzf-bindings tab:repeat
zstyle ':z4h:fzf-complete'    fzf-bindings tab:repeat
zstyle ':z4h:cd-down'         fzf-bindings tab:repeat
```

The first line rebinds <kbd>Alt+Down</kbd> to fzf-based directory history. The other lines allow you to use <kbd>Tab</kbd> in fzf to accept the selection and repopulate the fzf UI. To go into a subdirectory you can press <kbd>Alt+Down</kbd> followed by <kbd>Tab</kbd>. This works because the first directory offered by <kbd>Alt+Down</kbd> is always the current directory.

> Buffering as in letting the fzf "load" finish

I see. This isn't really buffering. That indicator is saying that zsh4humans is still producing completions for the command. They get streamed into the fzf UI as they are found.

**Comment by tomyummmm** [comment]
> 
> 
> This should be fixed now. Please give it a try.
> 
>     1. Run `z4h update`.
> 
>     2. Remove `bfs` with `sudo apt-get remove -y bfs`
> 
>     3. Verify that completions for `cd` are fast.
> 
>     4. Optional but recommended: install `bfs` with `sudo apt-get install -y bfs`. This improves ranking of files, so it's a good idea to install `bfs`.

Yes, tested in all of the same directories, no hanging when exiting, no delay in pressing ENTER after using TAB autocomplete with cd command even while the completions are being streamed into the fzf UI.


> 
> By the way, you might want to use specialized widgets for changing the current directory. There is Alt+Left and Alt+Right to go back/forward (similar to how back/forward buttons work in a web browser), Alt+Up to go to the parent directory, and Alt+Down to go to a subdiretory. There is also Alt+R for fzf-based directory history.
> 
> In my own config I rebind things a little bit:
> 
> ```shell
> z4h bindkey z4h-fzf-dir-history Alt+Down
> 
> zstyle ':z4h:fzf-dir-history' fzf-bindings tab:repeat
> zstyle ':z4h:fzf-complete'    fzf-bindings tab:repeat
> zstyle ':z4h:cd-down'         fzf-bindings tab:repeat
> ```
> 
> The first line rebinds Alt+Down to fzf-based directory history. The other lines allow you to use Tab in fzf to accept the selection and repopulate the fzf UI. To go into a subdirectory you can press Alt+Down followed by Tab. This works because the first directory offered by Alt+Down is always the current directory.

Interesting, i have my own alias to cd to the large folders directly, never really used the key bindings before. Will look into it.

Thank you so much, will be closing this issue now.

**Comment by romkatv** [comment]
> Yes, tested in all of the same directories, no hanging when exiting, no delay in pressing ENTER after using TAB autocomplete with cd command even while the completions are being streamed into the fzf UI.

Thanks for verifying!
