### ISSUE TITLE
Please do not rebind `alt-f` for fzf completion

### ISSUE THREAD

**Issue by pkazmier** [romkatv/zsh4humans#14]
As an avid command line junkie, I rely on `alt-b` and `alt-f` to quickly navigate back and forth on the command line. Can the same be done with `ctrl-left` and `ctrl-right`? Sure, but your hands have to move off the keyboard. Keyboard enthusiasts will be unhappy you have changed an immutable law of physics 😄 

In meantime, I'll manually rebind it, but I think this binding violates the principle of least surprise when one is accustomed to emacs keybindings.

Thanks!
Pete

**Comment by romkatv** [comment]
Rebound to `alt-i`.

**Comment by pkazmier** [comment]
Thanks!

BTW, thank you for this project. It has proven to greatly simplify zsh for a new user. Before you pointed me to it, I had spent hours and hours on Saturday reading about zsh, which package manager to user, delays with completion, finding just the right packages, etc ... This has simplified all of that. I only ended up making a few changes to my zshrc:

```diff
--- -	2020-04-27 08:54:30.000000000 -0500
+++ /Users/kaz/.zshrc	2020-04-27 08:54:18.000000000 -0500
@@ -1,3 +1,8 @@
+# Proxy settings
+export http_proxy=XXXXX
+export https_proxy=XXXXX
+export no_proxy=XXXXX
+
 # Export XDG environment variables. Other environment variables are
 # exported later (see below).
 export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
@@ -53,6 +58,8 @@
 # apart from cloning the repository and keeping it up-to-date. Cloned
 # files can be used after `z4h init`.
 z4h clone ohmyzsh/ohmyzsh  # just an example; delete it if you don't need it
+z4h clone zsh-users/zsh-history-substring-search
+z4h clone rupa/z
 
 # Z4H_SSH is 1 when zshrc is being sourced on the remove host by `z4h ssh`.
 if (( ! Z4H_SSH )); then
@@ -70,25 +77,45 @@
 bindkey -e
 
 # Export environment variables.
-export EDITOR=nano
+export EDITOR=emacsclient
+export VISUAL=emacsclient
 export GPG_TTY=$TTY
+export LESS_TERMCAP_mb='[1;34m'    # begin bold
+export LESS_TERMCAP_md='[1;34m'    # begin blink
+export LESS_TERMCAP_me='[0m'       # reset bold/blink
+export LESS_TERMCAP_so='[1;43;30m' # begin reverse video
+export LESS_TERMCAP_se='[0m'       # reset reverse video
+export LESS_TERMCAP_us='[1;35m'    # begin underline
+export LESS_TERMCAP_ue='[0m'       # reset underline
 
 # Extend PATH.
-path=(~/bin $path)
+path=(~/bin /usr/local/bin $path)
 
 # Use additional Git repositories pulled in with `z4h clone`.
+z4h source $Z4H/rupa/z/z.sh
 z4h source $Z4H/ohmyzsh/ohmyzsh/lib/diagnostics.zsh
 z4h source $Z4H/ohmyzsh/ohmyzsh/plugins/emoji-clock/emoji-clock.plugin.zsh
+z4h source $Z4H/zsh-users/zsh-history-substring-search/zsh-history-substring-search.zsh
 fpath+=($Z4H/ohmyzsh/ohmyzsh/plugins/supervisor)
 
-# Source additional local files.
-if [[ $LC_TERMINAL == iTerm2 ]]; then
-  # Enable iTerm2 shell integration (if installed).
-  z4h source ~/.iterm2_shell_integration.zsh
-fi
+# Syntax highlighting rules
+ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
+
+typeset -A ZSH_HIGHLIGHT_STYLES
+ZSH_HIGHLIGHT_STYLES[path]='fg=5'
+ZSH_HIGHLIGHT_STYLES[comment]='fg=8'
+ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=9'
+ZSH_HIGHLIGHT_STYLES[named-fd]='fg=9'
+ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=6'
+ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=6'
+
+typeset -A ZSH_HIGHLIGHT_PATTERNS
+ZSH_HIGHLIGHT_PATTERNS+=('rm -rf *' 'fg=white,bold,bg=red')
 
 # Define key bindings.
-bindkey '^H' backward-kill-word # ctrl-h and ctrl-backspace: delete previous word
+bindkey -M emacs '^H' backward-kill-word # ctrl-h and ctrl-backspace: delete previous word
+bindkey -M emacs '^P' history-substring-search-up
+bindkey -M emacs '^N' history-substring-search-down
 
 # Configure command completion: http://zsh.sourceforge.net/Doc/Release/Completion-System.html.
 zstyle ':completion:*' sort false # don't sort completion candidates
@@ -101,7 +128,15 @@
 compdef _directories md
 
 # Define aliases.
+alias l='ls -lAh'
+alias e='emacsclient'
+alias grep="grep --color=auto"
+alias duf="du -sh * | sort -hr"
+alias less="less -R"
+alias cdr='cd "$(git rev-parse --show-toplevel)"'
 alias tree='tree -aC -I .git'
+alias reload!='exec "$SHELL" -l'
+alias awsrun!="AWSRUN_CONFIG=$HOME/.awsrun.s${USER}.yaml awsrun"
 
 # Add flags to existing aliases.
 alias ls="${aliases[ls]:-ls} -A"
```

**Comment by romkatv** [comment]
Glad you found zsh4humans useful. It gets the basics right.

Almost everything in zshrc is meant to be an example to show where you can add your stuff. I think this is easier than wading through docs. When you see `alias`, you know you can put your own aliases there. The same goes for options, bindings, etc. (The order of things is important, so it's a good idea to keep it unchanged.)

I see that you've deleted iTerm2 integration. Great! I encourage you to delete other example stuff. Do you really need that alias for `tree`? If not sure, nuke it. oh-my-zsh is there just to show how to clone and use git repos. You already know how to do that, so you can delete all references to oh-my-zsh.

Try `z4h ssh some-server`. It's pretty cool. You'll get the same shell on the remote machine that you have on local. It'll work even if the remote machine doesn't have zsh. The first login will take some time but after that it's as fast as normal ssh.

Even though zsh4humans is already useful, it should be really good when I finish v2. I've put it on hold currently as I'm super busy with other stuff, but I've design and implementation notes figured out. Hopefully will get to it later.

**Comment by pkazmier** [comment]
Yes, this project is awesome. I really like what you've done. I ditched iterm because kitty is so much better imho. And, I did try out `z4h ssh` yesterday and all I can say is "wow". It is so awesome. I did get some minor error messages from tar incompatibilities from mac to linux maybe? But it did not impact use, so I didn't look much further.

```
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
tar: Ignoring unknown extended header keyword `LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword `SCHILY.dev'
tar: Ignoring unknown extended header keyword `SCHILY.ino'
tar: Ignoring unknown extended header keyword `SCHILY.nlink'
```

**Comment by romkatv** [comment]
Thanks for posting that error message. You ran `ssh` on macOS and the server is Linux, right? Do you have BSD `tar` on macOS? Is it GNU or busybox `tar` on Linux?

**Comment by romkatv** [comment]
OK, I've reproduced the tar issue and committed a fix. Once you update (`z4h update`), the warnings will be gone.

**Comment by pkazmier** [comment]
Sorry, missed your question, but I can confirm it's fixed on my side now too. Thanks again.
