### ISSUE TITLE
Integrated tmux and xplr opening editor

### ISSUE THREAD

**Issue by maximbaz** [romkatv/zsh4humans#140]
Hello,

I'm seeing a very weird integration bug, not sure if it's on z4h side or [xplr](https://github.com/sayanarijit/xplr/) side, I hope you could give me some initial pointers to get more information.

To reproduce:

```sh
$ cat .zshrc # having only one line in .zshrc
z4h init || return

$ kitty --config NONE # to make sure it's not caused by kitty config

$ EDITOR='kak -n' # to make sure it's not caused by kakoune config

$ cd "$(mktemp -d)" # generate some test content
$ echo bla > bla

$ xplr # launch xplr, also without any custom config
```

Once inside `xplr`, press `:e` to open `bla` file in kakoune. Now press `<Space>:q<Enter>` to exit the editor.

Expected: `bla` file is not highlighted, the "Selection" section on the right side of xplr is empty
Actual: somehow, `Space` keypress leaked from kakoune and got captured by xplr, marking the file as selected.

There is in fact this bug already reported to xplr: https://github.com/sayanarijit/xplr/issues/301

However what made me want to ask you first is the fact that if I add `zstyle ':z4h:' start-tmux no` to `.zshrc`, the bug will no longer reproduce.

I'm on latest stable versions of everything, made sure to run `z4h update` before testing.

**Comment by romkatv** [comment]
Do you experience the same issue if you set `start-tmux` to `system`? If yes, try removing all zsh rc files, create an empty .zshrc (just to disable new-user-install) and manually start `tmux`. Same issue in there?

**Comment by maximbaz** [comment]
If I add `zstyle ':z4h:' start-tmux system`, then I get p10k configuration wizard (is that expected?) but once I press `q` and try to repro, the bug does not reproduce.

**Comment by romkatv** [comment]
The configuration wizard is expected because you don’t have a config for an 8-color terminal (by default tmux gives you only 8 colors). If you go through it, it’ll create a new config in addition to the one you already have.

It’s quite likely that the bug is related to the issue you’ve linked to earlier. I suggest waiting for that issue to be fixed. If it doesn’t resolve *this* issue, I’ll take a look.

**Comment by maximbaz** [comment]
It turned out to be bug in xplr, which is now fixed, thanks for your support, it helped to reproduce and fix the issue 🙂

**Comment by romkatv** [comment]
I'm glad.

Can you post a link to the bug in xplr if you have it?

**Comment by maximbaz** [comment]
Sure, the issue is https://github.com/sayanarijit/xplr/issues/301 and the fixing PR is https://github.com/sayanarijit/xplr/pull/339
