### ISSUE TITLE
[feature request] Add option to use system fzf instead of downloading binary

### ISSUE THREAD

**Issue by bermudi** [romkatv/zsh4humans#142]
It would be nice to have a way to instruct z4h to use system installed fzf binary instead of making it download its own binary in the same way that tmux can be chosen.

This would allow z4h to run unmodified on x86 systems.

**Comment by romkatv** [comment]
What benefit would it give you if you could instruct zsh4humans to use the system installed fzf binary?

> This would allow z4h to run unmodified on x86 systems.

What do you mean by "unmodified"?
