### ISSUE TITLE
Autojump recommendations?

### ISSUE THREAD

**Issue by matschaffer** [romkatv/zsh4humans#149]
I noticed some comments like https://github.com/romkatv/zsh4humans/issues/35#issuecomment-848940481 that seem to point to something like https://github.com/rupa/z or https://github.com/wting/autojump built into z4h but it's not quite clear what that is.

I'm accustomed to using `j <first few chars>` to navigate to common locations.

I noticed `z4h bindkey z4h-cd-down    Shift+Down` in my config so tried shift+down but it seems to just complete based on an directory below the current cwd.

For now I just brew installed autojump and added `z4h source "${HOMEBREW_PREFIX}/etc/profile.d/autojump.sh"` to my `~/.zshrc`.

Thanks in advance for the recommendations and really nice work on the setup!

**Comment by romkatv** [comment]
Closing because I believe I've answered all questions here.
