### ISSUE TITLE
Binding of ^J causing issues in libvterm in emacs

### ISSUE THREAD

**Issue by pkazmier** [romkatv/zsh4humans#15]
I just spent all morning reinstalling emacs, libvterm, p10k, and z4h to try and isolate a problem in my embedded terminal (libvterm) within emacs. The problem is that after typing a command to execute, the moment I press `RET` on my Mac, the line of text I typed would disappear as if I had typed a `^U`.

Because I've changed so much of my personal setup this past week, I had no idea where to start so I just started ruling one component at a time. Fast forward several hours later, after having ruled everything else out, I turned my attention to z4h. I basically commented blocks of `z4h.zsh` to narrow down the issue, which turned out to be this line:

```zsh
bindkey '^J'      backward-kill-line             # ctrl+j     delete line before cursor
```

The funny thing is that I actually went looking for any rebinding of `^M`, which is the carriage return, but I did not think about looking at `^J`, which is line feed. Apparently, my embedded vterm in emacs sends `^J` characters. Here are the relevant parts of the emacs vterm module source code:

```elisp
(defun vterm-send-return ()
  "Send `C-m' to the libvterm."
  (interactive)
  (when vterm--term
    (if (vterm--get-icrnl vterm--term)
        (process-send-string vterm--process "\C-j")
      (process-send-string vterm--process "\C-m"))))
```

```c
emacs_value Fvterm_get_icrnl(emacs_env *env, ptrdiff_t nargs,
                             emacs_value args[], void *data) {
  Term *term = env->get_user_ptr(env, args[0]);

  if (term->pty_fd > 0) {
    struct termios keys;
    tcgetattr(term->pty_fd, &keys);

    if (keys.c_iflag & ICRNL)
      return Qt;
    else
      return Qnil;
  }
  return Qnil;
}
```

I guess the point is that we probably shouldn't bind `^J` as there are terminals out there that send it when a user enters a command.

Thoughts?

**Comment by pkazmier** [comment]
In the meantime, if anyone else is having this issue, just add this to your `.zshrc`:

```zsh
bindkey '^J' accept-line
```

**Comment by romkatv** [comment]
Thanks for the report! Fixed.
