### ISSUE TITLE
More detailed SSH docs

### ISSUE THREAD

**Issue by matschaffer** [romkatv/zsh4humans#150]
https://github.com/romkatv/zsh4humans#SSH mentions that the environment can be sent with you over SSH but I can't seem to find details on how to make that happen.

After grepping my way through ` ~/.cache/zsh4humans` I found `z4h help ssh`, so I gave it a try on a random GCP host with

```
z4h ssh -i ~/.ssh/id_rsa -- matschaffer@(IP)
```

But on the remote host I'm still just getting a typical ubuntu bash prompt.

Sorry if I'm missing something and thanks in advance for the advice!

**Comment by matschaffer** [comment]
> . This way you'll get a simpler and more powerful setup and I'll get feedback that I need to ensure that the feature is useful and understandable. This will take some time. I'll ping you here when it's ready. How does that sound?

Sounds great! I'll keep an eye out for the notification.

> It does not. Try sudo -Es instead.

Gotcha. I might even think of this as a "feature". :)

**Comment by romkatv** [comment]
> Instead of my explaining how you can configure distributed command history on top of the existing low-level API, I'll add a new higher-level API that you can test drive.

This will take a lot longer than I've originally expected due to life intervening and all that. I'll keep the issue open.

**Comment by matschaffer** [comment]
Thanks for the update @romkatv , no worries.

I was chatting with @aaronfeng about this yesterday and he was curious if it'd be possible to have shared history for a collection of ssh targets. 

For example when working with EC2, hosts come and go all the time, but it'd be great to preserve the history.

I suspect if you had a ProxyCommand and accessed all hosts via a ssh config Host, this would work. But it might be a nice option to just have one common history file for a glob of SSH targets.

Looking forward to hearing more whenever your schedule allows. Take care of yourself first! 🧡

**Comment by romkatv** [comment]
> I was chatting with @aaronfeng about this yesterday and he was curious if it'd be possible to have shared history for a collection of ssh targets.
> 
> For example when working with EC2, hosts come and go all the time, but it'd be great to preserve the history.

Yep, that's exactly the use case that shared history in z4h was implemented for.

To not keep you waiting until I implemented a new API, here's something to get you started that works with the current (rather complex I'm afraid) API.

```zsh
# This function is invoked by zsh4humans on every ssh command after
# the instructions from ssh-related zstyles have been applied. It allows
# us to configure ssh teleportation in ways that cannot be done with
# zstyles.
#
# Within this function we have readonly access to the following parameters:
#
# - z4h_ssh_client  local hostname
# - z4h_ssh_host    remote hostname is it was specified on the command line
#
# We also have read & write access to these:
#
# - z4h_ssh_enable          1 to use ssh teleportation, 0 for plain ssh
# - z4h_ssh_send_files      list of files to send to the remote; keys are local
#                           file names, values are remote file names
# - z4h_ssh_retrieve_files  the same as z4h_ssh_send_files but for pulling
#                           files from remote to local
# - z4h_retrieve_history    list of local files into which remote $HISTFILE
#                           should be merged at the end of the connection
# - z4h_ssh_command         command to use instead of `ssh`
function z4h-ssh-configure() {
  emulate -L zsh

  # Bail out if ssh teleportation is disabled. We could also
  # override this parameter here if we wanted to.
  (( z4h_ssh_enable )) || return 0

  # Figure out what kind of machine we are about to connect to.
  local machine_tag
  case $z4h_ssh_host in
    ec2-*) machine_tag=ec2;;
    *)     machine_tag=$z4h_ssh_host;;
  esac

  # This is where we are locally keeping command history
  # retrieved from machines of this kind.
  local local_hist=$ZDOTDIR/.zsh/history/retrieved_from_$machine_tag

  # This is where our $local_hist ends up on the remote machine when
  # we connect to it. Command history from files with names like this
  # is explicitly loaded by our zshrc (see below). All new commands
  # on the remote machine will still be written to the regular $HISTFILE.
  local remote_hist='"$ZDOTDIR"/.zsh/history/received_from_'${(q)z4h_ssh_client}

  # At the start of the SSH connection, send $local_hist over and
  # store it as $remote_hist.
  z4h_ssh_send_files[$local_hist]=$remote_hist

  # At the end of the SSH connection, retrieve $HISTFILE from the
  # remote machine and merge it with $local_hist.
  z4h_retrieve_history+=($local_hist)
}

# Load command history that was sent to this machine over ssh.
() {
  emulate -L zsh -o extended_glob
  local hist
  for hist in $ZDOTDIR/.zsh/history/received_from_*(NOm); do
    fc -RI $hist
  done
}
```

You'll need to add this block to `~/.zshrc` below `z4h init`. Before trying it out you'll probably want to modify the logic that computes `machine_tag` based on `$z4h_ssh_host`, although you can also use it as is -- there is a reasonable fallback. Oh, and make sure to run `z4h update` beforehand -- this code relies on https://github.com/romkatv/zsh4humans/commit/5fea79d79748bbc8e222690ca44272213843611c that I have just pushed.

If you are defining `z4h-ssh-configure`, you don't actually need to use ssh-specific zstyles but you still can if you want to. The function is invoked after zstyles are applied, so you can observe and/or override their effect within `z4h-ssh-configure`. For example, `z4h_ssh_enable` within the function is set to 0 or 1 according to the value of `zstyle :z4h:ssh:$hostname enable`. The implementation of `z4h-ssh-configure` that I've posted above bails out if `z4h_ssh_enable` is zero, so it doesn't do anything unless you enable ssh teleportation via `zstyle` for the target host. You could instead set `z4h_ssh_enable` in the function itself based on `$z4h_ssh_host` or anything else.

You can add the following line at the top of `z4h-ssh-configure` to see the initial values of all ssh parameters that z4h lets you read/write.

```zsh
typeset -pm 'z4h_ssh_*'
```

You'll notice that there are a few more parameters than what I've documented in the comments above `z4h-ssh-configure`. Those are low-level blocks of code that get executed on the remote host. You probably shouldn't touch them.

**Comment by matschaffer** [comment]
thanks @romkatv - I'll take it for a test drive and let you know if it works as expected. These past couple weeks aren't as SSH heavy for me so maybe I can rope in @aaronfeng too :)

**Comment by romkatv** [comment]
Did you have a chance to try it out?

**Comment by matschaffer** [comment]
Not yet @romkatv - I've been doing a lot of selenium work lately which doesn't like to run on anything other than my laptop. Will send an update when I get a chance to use it.

**Comment by romkatv** [comment]
There are barebone docs for SSH teleportation here: https://github.com/romkatv/zsh4humans/blob/master/tips.md#ssh
