### ISSUE TITLE
why is there no support for vi keybindings?

### ISSUE THREAD

**Issue by luxus** [romkatv/zsh4humans#152]
I wonder why, what's the reason why it cancels the install? .. and yes as a nvim user I would like to have vi bindings

I have to say zsh4humans is very awesome... its really a wonderful turnkey configuration.. I recommended already a lot. thank you so much for it..

**Comment by romkatv** [comment]
I have limited amount of time, so I have to prioritize. I don't use vi bindings, so it'll take more of my time to implement them well.

If you don't mind a bit of manual setup, you can answer that you want emacs bindings and then do your customizations in zshrc.

**Comment by luxus** [comment]
okay thanks.. I was wondering if there was a technical reason not to use vi bindings. 
I understand the time problem.. you have to do more wonderful benchmarks! thanks for your awesome work!
