### ISSUE TITLE
Init errors out when selecting 'no' for always using tmux for zsh

### ISSUE THREAD

**Issue by dylanjm** [romkatv/zsh4humans#154]
For some reason when I select no on the using tmux init question, I get errors that prevent the rest of the init from completing. When I select 'yes' everything loads up fine, but I don't really like using tmux unless I have to. Here is the output given my z4h:

```
Settings up Zsh For Humans...

z4h: fetching z4h.zsh from github.com/romkatv/zsh4humans
z4h: generating ~/.zshenv
z4h: generating ~/.zshrc
z4h: bootstrapping zsh environment
z4h: installing zsh4humans
z4h: installing zsh-history-substring-search
z4h: installing zsh-autosuggestions
z4h: installing zsh-completions
z4h: installing zsh-syntax-highlighting
z4h: installing terminfo
z4h: installing fzf
z4h: fetching fzf binary
z4h: installing tmux
"$errmsg" is not exported by the Digest::SHA module
Can't continue after import errors at /usr/local/bin/shasum line 24.
BEGIN failed--compilation aborted at /usr/local/bin/shasum line 24.
z4h: installing ohmyzsh/ohmyzsh
z4h: installing powerlevel10k
z4h: fetching gitstatus binary

z4h: init failed
```

It looks like my `shasum` program is symlinked to `/usr/local/Cellar/perl/5.34.0/bin/shasum` if that's of any use. Please advise on any more information or a workaround you might have. 

I'm currently using:

OS: macOS Catalina 10.15.7
Emulator: iTerm2 3.5.0beta2
Package Manager: Homebrew

**Comment by romkatv** [comment]
Does this work?

```zsh
shasum </dev/null
```

If not, try to make it work. Maybe reinstalling some package will help. You can also try removing brew's bin directory from `PATH` or adding `/usr/bin` in front of it (I think the working `shasum` is in there but you need to verify first).

**Comment by dylanjm** [comment]
Okay, I was able to prevent this error from happening by running `brew unlink perl` and then retrying z4h install.  I don't believe I actually rely on anything to do with perl for my day to day use. So it should not effect anything. Thank you.

**Comment by romkatv** [comment]
Glad you solve it.

Just to clarify, it's totally normal for `shasum` in `PATH` to be from perl. It was just broken for some reason in your brew package.

**Comment by romkatv** [comment]
I've committed https://github.com/romkatv/zsh4humans/commit/ecc31f860cd400b1fc2a0d7ea5c48e8b7a2c7ca9. Now zsh4humans will work if `shasum` is broken (it has enough fallbacks for hashing).
