### ISSUE TITLE
z4h ssh tab completion broken

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#157]
With plain ssh I can tab complete entries (both host name and aliases that map to different host names) from `~/.ssh/config`. For `z4h ssh` this does not work for some reason. In addition, tab completing flags to `z4h ssh` doesn't work.

**Comment by romkatv** [comment]
Don't use `z4h ssh`. Use plain `ssh` instead.

**Comment by VorpalBlade** [comment]
Oh, I thought ssh teleportation only happened if you used z4h ssh? I must have misunderstood.

**Comment by romkatv** [comment]
It happens via plain `ssh`. You need to enable it though. Search for "ssh" in zshrc.
