### ISSUE TITLE
zsh4humans overwrite alias definition

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#158]
I want `alias ls='ls --color=auto'` (that is, no `-A`). So I tried putting this in various parts of .zshrc. Both before and after z4h init. Unfortunately it seems like z4h somehow overwrites this alias no matter where I put my definition. What is the correct way to ensure my alias definition wins?

**Comment by VorpalBlade** [comment]
Actually, nevermind, found it. I was blind.

**Comment by romkatv** [comment]
Put it after `z4h init` as the examples suggest.

**Comment by romkatv** [comment]
The only required thing in zshrc is `z4h init`. Everything else is examples. Read them and delete/modify at will.
