### ISSUE TITLE
Clearing screen on ssh, sudo and exit from ssh and sudo

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#159]
When performing su, sudo or ssh and the target environment is zsh4humans the screen is cleared every time. The terminal is also cleared on exit.

I assume this is a result of integrated tmux. However it seems unneeded if the parent environment is already running inside integrated tmux. Is there some way to avoid this behavioiur when both the parent and child environment use zsh4humans?

**Comment by romkatv** [comment]
If you use ssh teleportation, screen won't get cleared. Other than that you are right. This is avoidable in theory but not trivial.

**Comment by VorpalBlade** [comment]
In that case, consider this a feature request I guess. For ssh the teleportation would help (except when sshing between dev machines). For sudo and su I don't see a good alternative though,

**Comment by romkatv** [comment]
I understand the inconvenience but it's not huge, right? Scroll up if you want to see scrollback. It's still there.

**Comment by romkatv** [comment]
Not related to this issue but you might want to check out https://github.com/romkatv/zsh4humans/issues/149 since you are configuring your shell.

**Comment by VorpalBlade** [comment]
Actually it seems to be overwritten, at least when using su on Ubuntu under konsole. So everything above the visible "screen" is still there, but the last screen is lost.

**Comment by romkatv** [comment]
Ah, you are right. Some content from the screen is lost -- some of the visible part. This might be easy to fix.

**Comment by romkatv** [comment]
> Ah, you are right. Some content from the screen is lost -- some of the visible part. This might be easy to fix.

This is done. Run `z4h update` to pick up the fix.

**Comment by romkatv** [comment]
> For sudo and su I don't see a good alternative though,

If you are using these to become root, you can use `sudo -Es` instead.

**Comment by VorpalBlade** [comment]
Ah interesting. What specific environment variables need to be preserved? For security reasons I would prefer the minimal set, and I believe you can add that to the sudoers file (though the syntax is horrible and I don't look forward to messing with that file).

**Comment by romkatv** [comment]
> Also interestingly using `sudo -Es` makes z4h update refuse to run as root

Yep. Because otherwise you would create files and directories owned by root in your home directory. That would be quite bad.

FWIW, I never change anything about my root's shell because if shit hits the fan I want to be able to fix it by logging as root. The advantage of `sudo -Es` over `su -` is that it allows you to use your user's shell (zsh with zsh4humans, for example) as a privileged user. It doesn't depend on root's login shell.

> while a `sudo su -` allows it to update z4h for root.

I this case the home directory is `/root`, so it's fine.

**Comment by romkatv** [comment]
> What specific environment variables need to be preserved?

`_Z4H_*`. This is undocumented and subject to change without notice.

**Comment by romkatv** [comment]
This is partially fixed (no screen content gets lost) and partially added to the TODO (don't spawn another integrated tmux when switching users). No ETA on the second part (although I don't think it's difficult to implement).
