### ISSUE TITLE
Keybindings with putty on windows

### ISSUE THREAD

**Issue by bjoe2k4** [romkatv/zsh4humans#16]
Hi, just discovered this little gem.

I have set `cd-key` to `ctrl` in `.zshrc`

I am using this on a box via putty on Windows 10 and there seems to be an issue with keybindings for me. For example the `ctrl+up` combination (and probably others) do not work.

Via cat, i get the following bindings for `ctrl+up`: `^[OA`

So what actually happens is `z4h-up-local-history`

from z4h.zsh:
```
  bindkey -s '^[OA' '^[[A'  # up
  bindkey '^[[A'    z4h-up-local-history           # up         prev command in local history
```

Is there an easy way to make this work?

**Comment by romkatv** [comment]
Does putty send the same escape sequence for `up` and `ctrl+up`?

**Comment by bjoe2k4** [comment]
No. up is `^[[A`, ctrl+up is `^[OA` and alt+up is `^[^[[A`

**Comment by romkatv** [comment]
In the short term I suggest that you rebind some keys with `bindkey` in your `~/.zshrc`. I'll take a look if it's possible to better support Putty when I get a free minute. Might take a long time.

**Comment by bjoe2k4** [comment]
Actually, i was trying out the new [Windows Terminal application ](https://github.com/microsoft/terminal) yesterday, and i think it will replace my ancient putty for good. It will become available with the next Windows update. All keybindings work except for those already defined by Windows Terminal itself (which can be unbound easily). It's already usable in the current Windows 10 Version as a preview.

So it might not be worth tinkering this out. But thanks for looking into it and feel free to close.

**Comment by romkatv** [comment]
> Does putty send the same escape sequence for `up` and `ctrl+up`?

Just tried it. For me both produce `^[[A`.

Closing because I don't intend to do anything here. Putty is supported *somewhat*.
