### ISSUE TITLE
Environment Variables, macOS, and Emacs

### ISSUE THREAD

**Issue by dylanjm** [romkatv/zsh4humans#160]
Feel free to close this issue as I don't think it's necessarily a problem in the code, but I wanted to get your input before I start adding custom variables to my `.zshenv`

When working on macOS and using emacs, if you want your GUI instance of emacs to share the same variables as your shell, you have to install a package called `exec-path-from-shell` which will allow you to keep a consistent emacs whether it was launched from spotlight or from the command line. And if you want to access those environment variables during your init you have to specify those variables via a customized variable in emacs. 

I noticed yesterday, after installing zsh4humans and moving my env vars to my new `.zshrc` that my emacs launched via spotlight stopped working and it appears to be that if I don't specify these variables in my `.zshenv` they won't be available to be read during emacs's initialization. 

I'm fine with moving my variables back to my `.zshenv`, but I know you specifically advise against that in the comments of the file. Would this be an instance where I could move my needed variables back to `.zshenv`? Is there a rule of thumb I should follow so I don't break anything when putting variables in there?

Thanks for your time.

**Comment by romkatv** [comment]
Yep, move them to zshenv. The rule of thumb is that you should put stuff in zshenv if putting it in zshrc doesn't work.

**Comment by dylanjm** [comment]
Sounds great. thanks for the quick response.
