### ISSUE TITLE
Issue with ssh teleportation and array expressions for path manipulation in .zshenv

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#161]
When I try to use ssh teleportation I get the following error
```
/tmp/.z4h-ssh.local-username.31496.1635935958.2494: 15: /home/remote-username/.zshenv: Syntax error: word unexpected (expecting ")")
```

The following is the changed fragment of my .zshenv:
```zsh
  # If you are certain that you must export some environment variables
  # in ~/.zshenv (see comments at the top!), do it here:
  #
  #   export GOPATH=$HOME/go
  export skip_global_compinit=1 # Needed because of global Debian zshrc in /etc
  path+=($HOME/bin)
  #
  # Do not change anything else in this file.
```
If I instead use
```zsh
  # If you are certain that you must export some environment variables
  # in ~/.zshenv (see comments at the top!), do it here:
  #
  #   export GOPATH=$HOME/go
  export skip_global_compinit=1 # Needed because of global Debian zshrc in /etc
  export PATH="$PATH:$HOME/bin"
  #
  # Do not change anything else in this file.
```
then it works.

This seems really strange and inconsistent. The temporary file from the error message appears to be removed immediately, so there is no way for me to debug this further.

**Comment by romkatv** [comment]
Yep, in v5 you need to do `export PATH="$PATH:$HOME/bin"` if you want to put it in zshenv, just like in the example. In v6 it'll work both ways.

By the way, that comment about needing `skip_global_compinit` is false. In general I highly recommend not putting anything in your config unless you can verify that it makes a difference.

**Comment by VorpalBlade** [comment]
Hm, it absolutely made a difference before using zsh4human, in that the startup for a zsh shell was over a second. I assume then that z4h does something fancy so this is no longer needed?

**Comment by romkatv** [comment]
> Hm, it absolutely made a difference before using zsh4human

No argument there. Before copying anything from your old configs, verify that it makes a difference.
