### ISSUE TITLE
Working directory of integrated tmux causes issues with terminal emulator tabs.

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#162]
When running a "normal" shell (bash, standard zsh, ...) opening a new tab in the terminal emulator (at least for both konsole and mate-terminal) uses the working directory of the current terminal. This does not happen when using zsh4humans. Presumably because the working directory of the integrated tmux hides the "true" working directory of zsh.

I realise that this may be really difficult to solve, so I'm also wondering if there are any workarounds for this.

**Comment by romkatv** [comment]
Add this:

```zsh
zstyle ':z4h:' propagate-cwd yes
```

This will become the default in v6 unless someone complains.

You might also want to add this next to other bindings:

```zsh
z4h bindkey z4h-eof Ctrl+D

setopt ignore_eof
```

This fixes transient prompt when closing ssh connections. It'll also become the default in v6 if no one complains.

**Comment by VorpalBlade** [comment]
Awesome, thanks.

I have to say though, I'm not convinced that having people opening bugs and having to reply to them will take you less time than actually writing documentation ;-)

**Comment by romkatv** [comment]
That would be true only if you opened bugs and asked questions for a large chunk of functionality.
