### ISSUE TITLE
Trailing space handling in history

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#164]
This was a bit of a subtle difference. It seems with z4h, spaces at the end of lines are trimmed before going into the history. This was definitely not the case on the previous zsh setup I was using. And I can't quite figure out what is causing it. I looked at setopt and zstyle without finding anything obvious.

I want to keep these trailing spaces as I often do tab completion (leaves a trailing whitespace), run a command, then up arrow to add extra parameters. Before I didn't have to type a space after the up arrow, now I suddenly do. Muscle memory and all. Pretty sure this muscle memory dates dates back to the days of using bash even.

**Comment by romkatv** [comment]
This is probably fixable but it'll end up so low on my priority list that it's unlikely to ever get fixed. Just setting expectations.

**Comment by VorpalBlade** [comment]
If you can point me to where this might be happening (z4h code base is quite large) I'm more than happy to fix it myself and make a pull request.

**Comment by romkatv** [comment]
Here: https://github.com/romkatv/zsh4humans/blob/0029ed672a55ad9a109c3ce32893affff35f9e90/fn/-z4h-zle-line-finish#L15-L24

If you add a zstyle to control this and send a PR, I'll merge it.

**Comment by VorpalBlade** [comment]
The fix seems to work as expected, so I'm closing this issue now.
