### ISSUE TITLE
Issue with environment variable leak to cron causing z4h terminfo to be used in turn triggering AppArmor security policy

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#168]
Somehow z4h environment variables leaks to cron! This issue might be so obscure that I can see you don't want to bother with it. However, I don't know what other environment variables leaks to cron as well.

I have a raspberry pi that is set up with z4h for root (I get confused if I use different shells, so I'm not going to use bash for root and zsh for my normal user). It also have AppArmor set up for some additional protection, as some ports are exposed to the internet.

In my root crontab I run certbot (from LetsEncrypt) to renew the internet facing SSL certificate. I have an AppArmor profile set up for certbot (though it is still running in complain mode, I had forgotten to change it over to enforce mode apparently). I was a bit surprised when I checked the log today:

```console
❯ aa-logprof
Reading log entries from /var/log/audit/audit.log.
Updating AppArmor profiles in /etc/apparmor.d.
Complain-mode changes:

Profile:  /usr/bin/certbot
Path:     /root/.terminfo/64/dumb
New Mode: owner r
Severity: unknown

 [1 - owner /root/.terminfo/64/dumb r,]
(A)llow / [(D)eny] / (I)gnore / (G)lob / Glob with (E)xtension / (N)ew / Audi(t) / (O)wner permissions off / Abo(r)t / (F)inish
```

Seems it is *somehow* picking up z4h terminfo? Do I need to set `SHELL=/bin/bash` in the crontab or what would you suggest? Would that even help? The crontab(5) man page suggests that SHELL defaults to /bin/sh, but that doesn't seem to have helped.

Also crontab calls a *bash script* that runs certbot and reloads the services using the certificate. So I really don't see how zsh gets involved here...

The setup is as follows:
```console
root@pi ~ ❯ crontab -l
# m h    dom mon dow   command
0   4,16 *   *   *     /root/bin/renew-cert
root@pi ~ ❯ cat /root/bin/renew-cert
#!/bin/bash -e
/usr/bin/certbot renew <parameters referring to specific domain name etc redacted>
systemctl reload nginx.service >/dev/null
systemctl reload dovecot.service >/dev/null
systemctl reload postfix@-.service > /dev/null
```

**Comment by romkatv** [comment]
Everything linked to ncurses looks at `~/.terminfo`. It doesn't seems like there is a problem unless I'm missing something.

By the way, it's a bad idea to change *anything* under `/root`. There is no good reason to do that given that you can use something like `sudo -Es`. z4h is cool and all but it's *massive* and with a dependency on the internet.

**Comment by VorpalBlade** [comment]
Hm, I assumed it was due to `TERMINFO=$HOME/.terminfo` which seems to come from z4h.

The problem with sudo -Es is that $HOME points to your normal user, so some tools (such as htop) that write their own config file will mess up permissions in your home directory. Some method that still set HOME=/root would be nice.

**Comment by romkatv** [comment]
> Hm, I assumed it was due to `TERMINFO=$HOME/.terminfo` which seems to come from z4h.

Do you have any evidence for that? Your issue report didn't indicate any environment variable leaks.

> The problem with sudo -Es is that $HOME points to your normal user, so some tools (such as htop) that write their own config file will mess up permissions in your home directory.

Yep. That's why I never actually use it. I never create an interactive shell with superuser privileges at all. Doing so causes all sort of trouble. Using `sudo` with specific commands seems a much better way to go.

> Some method that still set HOME=/root would be nice.

You already have that. The problem is that it's dangerous. By running random stuff with `/root` as writable home directory you make it more likely to pwn yourself and to break your root shell. This isn't specific to zsh4humans though.

**Comment by romkatv** [comment]
The way I see it, you have three options w.r.t. running commands as root:

1. `sudo` on every command: `sudo mkdir /foo`, `sudo touch /foo/bar`, etc.
   - pros: safe
   - cons: can be cumbersome
2. Create an interactive root shell with `sudo -Es` or `sudo -E zsh`.
  - pros: the convenience of your shell environment; won't break root's login shell
  - cons: can break your home directory if the commands you run create files under it
3. Create an interactive root shell with `sudo -i`.
  - pros: won't break your home directory
  - cons: have to set up z4h on root account; command history is in two places; can break root login shell

If you aren't willing to go with (1), I think the next best thing is (2) with some mitigation. The only problem you can encounter is that some files under your home directory are owned by root, and the solution is to chown them. Not that of a big deal compared to the risk of borking your root account with (3). I can even automate chowning with an option like this:

```zsh
# When you close a root shell in which $HOME is not owned
# by root, chown all files under $HOME owned by root to the
# owner of $HOME.
#
# - 'no': don't chown; this is the default
# - 'async`: chown them in the background
zstyle :z4h: chown-root-files-in-home-dir async
```

WDYT?

**Comment by romkatv** [comment]
Closing as WAI. As far as I can tell, there is no environment variable leak here. The extra stuff I've proposed in my previous comment is a speculative feature that could be implemented if warranted.
