### ISSUE TITLE
Don't replace system stat with zsh/stat unconditionally

### ISSUE THREAD

**Issue by ratorx** [romkatv/zsh4humans#173]
The module `zsh/stat` is unconditionally loaded in `main.zsh`, which overrides the system `stat`.

Would it be possible to opt-out of this behaviour, or load it as zstat instead (using `zmodload -F zsh/stat b:zstat`)? I prefer the system stat (from coreutils) over the ZSH builtin because it is a lot more readable. Compare the outputs:

zstat:
```
device  39
inode   732
mode    33188
nlink   1
uid     1000
gid     100
rdev    0
size    0
atime   1636595217
mtime   1636595217
ctime   1636595217
blksize 131072
blocks  1
link
```

coreutils stat:
```
  File: test
  Size: 0         	Blocks: 1          IO Block: 131072 regular empty file
Device: 27h/39d	Inode: 732         Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/   reeto)   Gid: (  100/   users)
Access: 2021-11-11 01:46:57.723831239 +0000
Modify: 2021-11-11 01:46:57.723831239 +0000
Change: 2021-11-11 01:46:57.723831239 +0000
 Birth: -
```

I think the latter is a lot nicer for interactive use.

**Comment by romkatv** [comment]
> The module `zsh/stat` is unconditionally loaded in `main.zsh`, which overrides the system `stat`.

That was unintended. Thanks for reporting this. Fixed. You can pick up the fix with `z4h update`.
