### ISSUE TITLE
Not working with tmuxp

### ISSUE THREAD

**Issue by iomari** [romkatv/zsh4humans#174]
Greetings,
I started using zsh4hmans yesterday and I am very pleased with it. When I boot into my system, I use tmuxp to load my tmux session. To my surprise, this does not work with zsh4humans. I'm getting the error: "ValueError: Session requires a `session_id`".
If I remove zsh4humans and go back to my own.zshrc file, the problem goes away.
Any suggestions?

thanks in advance
iomari

**Comment by romkatv** [comment]
Does it work if you add the following line at the top of `~/.zshrc` and restart your terminal?

```zsh
zstyle ':z4h:' start-tmux 'no'
```

**Comment by iomari** [comment]
same error

**Comment by iomari** [comment]
I just notice that when I add the above line, the prompt o longer appears on the bottom.

**Comment by romkatv** [comment]
I don't use tmuxp myself and don't know what it does. To debug this I would need to dive into it. This might happen but not soon. Think months, or maybe even never. If you decide to debug this yourself and figure it out, please post a comment.

**Comment by iomari** [comment]
No Problem. I understand. Thanks.
