### ISSUE TITLE
Start new session in previous session's directory

### ISSUE THREAD

**Issue by matschaffer** [romkatv/zsh4humans#175]
I use the "Reuse previous session's directory" feature of iTerm2 so I can split out a new tab and retain my current working directory.

![Screen Shot 2021-11-17 at 15 57 55](https://user-images.githubusercontent.com/690/142149670-9ee95fc5-cc74-4c85-9da4-66dc46e602d9.png)

Since switching to zsh4humans, this setting seems not to work. Is there a setting to avoid my new session starting back in `$HOME` and retaining the current directory in my terminal?

Thanks in advance!

**Comment by romkatv** [comment]
Add this:

```zsh
zstyle ':z4h:' propagate-cwd yes
```

This will become the default in v6 unless someone complains.

**Comment by matschaffer** [comment]
Hrm... doesn't seem to have worked. Is the ordering important? I just appended it to the end

![recording of opening a new terminal without retaining cwd](http://g.recordit.co/1CpJhxrhSe.gif)

**Comment by romkatv** [comment]
When adding stuff to `~/.zshrc`, add it where similar things already are. All zstyles are at the top, so add a new one at the top too.

**Comment by romkatv** [comment]
You also need to restart all shells after setting this option. The option needs to be set not only when you are cloning a session but also when the source session is created.

**Comment by matschaffer** [comment]
Ah, thanks! Adding it to the top did the trick.

**Comment by yogesh-hackx** [comment]
> Add this:
> 
> ```shell
> zstyle ':z4h:' propagate-cwd yes
> ```
> 
> This will become the default in v6 unless someone complains.
![Screenshot_20211209_201323](https://user-images.githubusercontent.com/38541966/145417628-e1d1d872-a523-44e9-b2d0-172861934351.png)

Seems to work, but changes the title bar and tab title to something like as shown in image.

**Comment by romkatv** [comment]
@yogesh-hackx See https://github.com/romkatv/zsh4humans/issues/147#issuecomment-950521708

**Comment by yogesh-hackx** [comment]
> @yogesh-hackx See https://github.com/romkatv/zsh4humans/issues/147#issuecomment-950521708

Working now, thanks✌🏻
