### ISSUE TITLE
feature request: vi-mode

### ISSUE THREAD

**Issue by magnetophon** [romkatv/zsh4humans#176]
Thanks for the wonderful config!

The only thing missing for me is vi-mode.
I read some old issues, commits and reddit posts, but was not able to figure out how to enable it.

**Comment by romkatv** [comment]
You can enable vi keymap in zsh by adding the following line to your `~/.zshrc`:

```zsh
bindkey -v
```

Is this what you are looking for?

**Comment by romkatv** [comment]
Oh, I got confused about which project this is. Sorry about that. Please disregard my last comment.

See https://github.com/romkatv/zsh4humans/issues/152 instead.

**Comment by magnetophon** [comment]
Thanks for the quick response!

I have not been able to get it to work,
Either the vi or the z4h bindings get overwritten. :(

Anyway, I'll respect your priorities and close this issue.

**Comment by romkatv** [comment]
You need to add `bindkey -v` below `z4h init` and then call `bindkey` as you normally would.

**Comment by magnetophon** [comment]
That overwrites z4h bindings (I tested history sjubstring search).
Do I need to manually re-bind all commands?

**Comment by romkatv** [comment]
It doesn't override any bindings. z4h simply doesn't define any bindings for `viins` and `vicmd`. You need to define your own bindings for these keymaps. You can do it exactly the same way as with any other zsh config. z4h doesn't interfere with your vi bindings in any way.

**Comment by magnetophon** [comment]
Ah, of course, that was the missing puzzle-piece, thanks!  <3
