### ISSUE TITLE
Where do I put my custom fzf preferences?

### ISSUE THREAD

**Issue by sagarkar10** [romkatv/zsh4humans#178]
I am very much liking the experience of `z4h`, but I am finding it difficult to tweak things towards my own liking.
I could not figure why preview is not working in `fzf` search, nor could I find the relevant files that's enabling the things.

Furthermore, I would like to suggest either we document the repo well enough to accommodate new users or use a more segmented file systems for specific use cases.

I also want to see how to interact with z4h command, it has only `help` command, that is pretty much it.
I am moving from ohz and here I am at a loss to tweak things.

For example, from my previous `.zshrc` where do I accommodate these configs:
```
#autojump
[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh


# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='fd --type f'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
# Use ~~ as the trigger sequence instead of the default **
export FZF_COMPLETION_TRIGGER='**'

# Options to fzf command
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --info=inline'

# Use fd (https://github.com/sharkdp/fd) instead of the default find
# command for listing path candidates.
# - The first argument to the function ($1) is the base path to start traversal
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  fd --hidden --follow --exclude ".git" . "$1"
}

# Use fd to generate the list for directory completion
_fzf_compgen_dir() {
  fd --type d --hidden --follow --exclude ".git" . "$1"
}

# (EXPERIMENTAL) Advanced customization of fzf options via _fzf_comprun function
# - The first argument to the function is the name of the command.
# - You should make sure to pass the rest of the arguments to fzf.
_fzf_comprun() {
  local command=$1
  shift

  case "$command" in
    cd)           fzf "$@" --preview 'tree -C {} | head -200' ;;
    export|unset) fzf "$@" --preview "eval 'echo \$'{}" ;;
    ssh)          fzf "$@" --preview 'dig {}' ;;
    vi|vim)           fzf "$@" --preview 'bat --style=numbers --color=always --line-range :500 {}' ;;
    *)            fzf "$@" ;;
  esac
}

```

Any help from seasoned users or @romkatv will be very much appreciated.

**Comment by romkatv** [comment]
I could not figure why preview is not working in `fzf` search

zsh4humans doesn't support preview in fzf-based widgets. There is a feature request for this but I don't plan to work on it in the near future.

> Furthermore, I would like to suggest either we document the repo well enough to accommodate new users

Documentation would be nice to have. I don't intend to write any in the near future.

> or use a more segmented file systems for specific use cases.

What's that?
 
> I also want to see how to interact with z4h command, it has only `help` command, that is pretty much it.

`z4h help` is the only documentation that currently exists for `z4h` command.

> For example, from my previous `.zshrc` where do I accommodate these configs:

zsh4humans isn't the kind of project that you can configure to make it look and behave like some other project. If you want high degree of control and flexibility with decent documentation, zsh4humans isn't the right choice.
