### ISSUE TITLE
Add completions for hashicorp terraform

### ISSUE THREAD

**Issue by iamhsa** [romkatv/zsh4humans#179]
I saw in #55 that you added the completion for hashicorp vault.
I wanted to suggest you add the completion for hashicorp terraform.

Currently their [docs](https://www.terraform.io/docs/cli/commands/index.html#shell-tab-completion) says to run `terraform -install-autocomplete`, which in turn places the following lines to the end of .zshrc:
```
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/iamhsa/.asdf/installs/terraform/1.0.11/bin/terraform terraform
```

To test I have modified the `~/.cache/zsh4humans/v5/zsh4humans/fn/-z4h-compinit` file by adding:

``` zsh
if (( $+commands[terraform] && ! $+_comps[terraform] )); then
  complete -o nospace -C =terraform terraform
fi
```
It seems to me that it works correctly (I tested with terraform 0.12.31, 0.13.7, 0.14.11, 0.15.5 and 1.0.11).

**Comment by romkatv** [comment]
Done. Thanks for doing all the work on this issue 🤗

**Comment by iamhsa** [comment]
Thank you sir ! Works great !

**Comment by romkatv** [comment]
Thanks for verifying.
