### ISSUE TITLE
How to set custom title?

### ISSUE THREAD

**Issue by pathetic-lynx** [romkatv/zsh4humans#180]
Before z4h I could add a `zsh:` prefix to the zsh title by defining a `function precmd()` in `.zshrc`.

With z4h this works only one time when starting zsh. After one `cd` or one command it reverts back to only showing the path. How or where do I do this?

I read about `_z4h-set-term-title-precmd()` in some other issue but defining that function in `.zshrc` changes nothing.

My precmd function:

```
function precmd () {
    if [[ $UID == 0 || $EUID == 0 ]]; then
        prefix="root@"
    fi
    window_title="\033]0;zsh:${prefix}${PWD/#$HOME/~}\007"
    echo -ne "$window_title"
}
```

**Comment by romkatv** [comment]
See https://github.com/romkatv/zsh4humans/issues/147#issuecomment-950947452. 

If you want different format for privileged and non-privileged, use `%(#...)`. See https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html

**Comment by pathetic-lynx** [comment]
Thanks!

For reference, this is what I use now:

```
zstyle ':z4h:term-title:local' preexec 'zsh:%(!.root@.)${1//\%/%%}'
zstyle ':z4h:term-title:local' precmd  'zsh:%(!.root@.)%~'
```

**Comment by romkatv** [comment]
Are  you sure you want to see "root@sleep 5" while `sleep 5` is running? Nothing wrong with that, it just looks unusual. `preexec`  sets title before each command and `$1` in it is the command.

Are you sure you want to override the title only when working locally but not when working over ssh? If you want to override the title when working over ssh, you'll need to either define the same zstyles but with "ssh" in place of "local" or replace "local" with "*".
