### ISSUE TITLE
Add completions for hashicorp packer

### ISSUE THREAD

**Issue by iamhsa** [romkatv/zsh4humans#181]
Sorry I could have asked that in #179, to save you some extra work.
I wanted to suggest you add the completion for hashicorp packer.

Currently their [docs](https://www.packer.io/docs/commands#autocompletion) says to run `packer -autocomplete-install`, which in turn places the following lines to the end of .zshrc:
```
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /home/hug0/.asdf/installs/packer/1.7.8/bin/packer packer
```

To test I have modified the `~/.cache/zsh4humans/v5/zsh4humans/fn/-z4h-compinit` file by adding:

``` zsh
if [[ -v commands[packer] && ! -v _comps[packer] ]]; then
  complete -o nospace -C =packer packer
fi
```
It seems to me that it works correctly (I tested with packer 1.4.5, 1.5.6, 1.6.6, 1.7.8).

**Comment by romkatv** [comment]
> Sorry I could have asked that in #179, to save you some extra work.

Don't worry about it. These issues are great and I thank you for filing them.

I've applied your patch.

**Comment by iamhsa** [comment]
Thank you !
Works great with most packer versions.

Just a note, this does not work with versions prior to version 1.2.4. On the packer side that seems poorly done : completion is a mix between arguments and descriptions ( screenshot bellow )
![image](https://user-images.githubusercontent.com/1255925/143845241-6de17eb6-be1c-4e82-b61d-3d8b07724f53.png)

That doesn't sound too bad ,to me, as version 1.2.4 is dated from May 29, 2018!

**Comment by romkatv** [comment]
If someone is running an older version of packer, they can either upgrade or add `compdef _default packer` to their zshrc. Seems fine to me.

**Comment by iamhsa** [comment]
AFAIC, upgrade is the best alternative.
Thanks again.
