### ISSUE TITLE
Conflict with startx and z4h

### ISSUE THREAD

**Issue by Spoons** [romkatv/zsh4humans#183]
Xorg.wrap is a root suid wrapper for X11 that detects if root permissions are needed to run the xserver. It's default parameters are:

```
allowed_users = console
needs_root_rights = auto
```

When starting the xserver through xinit, some aspect of zsh4humans breaks the `allowed_users = console` detection in Xorg.wrap causing it to state: `only console user are allowed to the X server`. The xserver fails to start under this configuration.

Frankly, I'm not sure what aspect of zsh4humans (or Xorg.wrap) causes this to happen but I certainly am curious to know why.

**Comment by romkatv** [comment]
> zsh4humans breaks Xorg.wrap

Alternative wording: Xorg.wrap breaks when one is using zsh4humans.

Don't use xinit. It's broken. https://unix.stackexchange.com/questions/554592/how-to-manually-run-init-start-a-xorg-server-on-a-different-vt-tty/554603#554603

**Comment by Spoons** [comment]
> Alternative wording: Xorg.wrap breaks when one is using zsh4humans.
Apologies. There is a conflict.
> Don't use xinit. It's broken. 
Ah my mistake, I observe an incompatibility between startx and zsh4humans. I incorrectly thought startx called xinit under the hood and was the source of the issue.

**Comment by romkatv** [comment]
> I certainly am curious to know why.

It's because zsh4humans create a tty. For historical reasons it's called integrated tmux even though it's not actually tmux. You can turn it off like this:

```zsh
zstyle ':z4h:' start-tmux no
```

This will disable several z4h features (unspecified which ones). This option is only meant to be used for debugging.

**Comment by romkatv** [comment]
Is this issue resolved? I'm having trouble parsing your last comment.

**Comment by Spoons** [comment]
I was feverish from the flu vaccine that day.

Adding,
```
[[ ! -v $DISPLAY && $XDG_VTNR ]] && zstyle ':z4h:' start-tmux no
```
to the zshrc causes z4h to work well in the Linux TTY. I believe there would be value in disabling the 'integrated' tmux when a TERM value of 'linux' is detected. I propose this because setting a TERM value of tmux-256color will not work correctly under the Linux TTY. Additionally, having to add the aforementioned line in order for startx to work will be confusing for other startx users.

Yes, the issue is resolved for me and I appreciate you taking the time to answer my questions.

**Comment by romkatv** [comment]
>     [[ ! -v $DISPLAY && $XDG_VTNR ]] && zstyle ':z4h:' start-tmux no

This doesn't look right. It's equivalent to this:

```zsh
if [[ -n $XDG_VTNR ]]; then
  zstyle ':z4h:' start-tmux no
fi
```

If your distro uses systemd, the condition is always true. If your distro doesn't use systemd, the condition is always false.

I think you want this instead:

```zsh
if [[ -z $DISPLAY && XDG_VTNR -eq 1 ]]; then
  zstyle ':z4h:' start-tmux no
fi
```

Or perhaps this:

```zsh
if [[ -z $DISPLAY && $TERM == linux ]]; then
  zstyle ':z4h:' start-tmux no
fi
```

Alternatively, you can leave this setting be and change the command that you use to start X. The TTY check in it isn't particularly useful.

> [...] setting a TERM value of tmux-256color will not work correctly under the Linux TTY.

Are you saying that zsh4humans set `TERM=tmux-256color` when the underlying `TERM` was `linux`? Can you confirm this and describe how this can be reproduced?

**Comment by Spoons** [comment]
> > ```
> > [[ ! -v $DISPLAY && $XDG_VTNR ]] && zstyle ':z4h:' start-tmux no
> > ```
> 
> This doesn't look right. It's equivalent to this:
> 
> ```shell
> if [[ -n $XDG_VTNR ]]; then
>   zstyle ':z4h:' start-tmux no
> fi
> ```

In an attempt to learn and use more of the ZSH specific options, it seems I completely misunderstood -v. 

> 
> If your distro uses systemd, the condition is always true. If your distro doesn't use systemd, the condition is always false.
> 

This is true under systemd in a VT. However, under non-login shells, this variable is undefined.

> I think you want this instead:
> 
> ```shell
> if [[ -z $DISPLAY && XDG_VTNR -eq 1 ]]; then
>   zstyle ':z4h:' start-tmux no
> fi
> ```
> 
> Or perhaps this:
> 
> ```shell
> if [[ -z $DISPLAY && $TERM == linux ]]; then
>   zstyle ':z4h:' start-tmux no
> fi
> ```
> 

I agree, either solution would be better.

> Alternatively, you can leave this setting be and change the command that you use to start X. The TTY check in it isn't particularly useful.

What makes you say that? Do you have a preferred display manager? I've never felt compelled to use anything more than scripts for managing my environment.

> 
> > [...] setting a TERM value of tmux-256color will not work correctly under the Linux TTY.
> 
> Are you saying that zsh4humans set `TERM=tmux-256color` when the underlying `TERM` was `linux`? Can you confirm this and describe how this can be reproduced?

Yes, I can confirm. Using zsh4humans, the TERM variable is redefined to tmux-256color under VT.

OS: Arch
1. Install zsh4humans. Use default zshrc.
2. Switch to zsh for default shell (if not already.)
3. Switch to a VT and login. 
4. TERM variable has been set to 'tmux-256color'

**Comment by romkatv** [comment]
>> Alternatively, you can leave this setting be and change the command that you use to start X. The TTY check in it isn't particularly useful.
> I've never felt compelled to use anything more than scripts for managing my environment.

I don't mean to suggest that you should stop using scripts for managing your environment. My suggestion is to change the command that you use to start X. You can either disable the TTY check in the command you are using (this check isn't particularly useful), or use a different command altogether that doesn't fail when executed from under tmux.

> Yes, I can confirm. Using zsh4humans, the TERM variable is redefined to tmux-256color under VT.

Thanks. That's a regression. Should be fixed now.
