### ISSUE TITLE
Question: how do I set a variable to a different value per user?

### ISSUE THREAD

**Issue by magnetophon** [romkatv/zsh4humans#185]
I hope you don't mind me using the issue tracker for support, feel free to close the issue if you do.

When I ``cd`` as ``root``, my users zoxide db gets owned by root, so unwritable as user.
There is a [similar issue](https://github.com/ajeetdsouza/zoxide/issues/181) reported in zoxide, and there the following solution is proposed:

```zsh
if [ "$USER" = "root" ]; then
    export _ZO_DATA_DIR="/root/.local/share/zoxide"
fi
```

That doesn't work in z4h.
Any ideas?

**Comment by romkatv** [comment]
> I hope you don't mind me using the issue tracker for support

This is very much appropriate. GitHub issues is my preferred medium for questions about z4h.

> When I `cd` as `root` ...

How do you `cd` as `root`?

> There is a [similar issue](https://github.com/ajeetdsouza/zoxide/issues/181) reported in zoxide

It's unfortunate that the issue was closed without a fix. The bug report is of high quality.

> That doesn't work in z4h.

Doesn't work *how*?

Does it work without z4h?

FWIW, the command doesn't look right. I'd do it like this:

```zsh
export _ZO_DATA_DIR=${userdirs[$USERNAME]}/.local/share/zoxide
```

This changes a couple of things:

- The file is under the correct home directory.
- The export is unconditional so that the path always matches the current effective user.

Ideally, the bug should be fixed in zoxide. It shouldn't change ownership or mode of its database file. The issue doesn't say whether mode gets changed but I suspect it does. That would also be a bug.

**Comment by magnetophon** [comment]
> How do you `cd` as `root`?

Sorry, I meant: ``su`` to root and then run ``cd $some_dir``.

> Doesn't work _how_?

From my tests, it seems that when I ``su`` to a new user, the code in ``.zshrc`` is not ran again, so any variables will not be redefined to take the new user in to account.

> Does it work without z4h?

Without z4h, each user has their own ``.zshrc``, so there is no problem.

> FWIW, the command doesn't look right. I'd do it like this:
> 
> ```shell
> export _ZO_DATA_DIR=${userdirs[$USERNAME]}/.local/share/zoxide
> ```

Same issue: if Ijust put it in my ``.zshrc``,  it's not ran when I do ``su``.

> Ideally, the bug should be fixed in zoxide. It shouldn't change ownership or mode of its database file. The issue doesn't say whether mode gets changed but I suspect it does. That would also be a bug.

Agreed, but there seems to be [no easy solution](https://github.com/ajeetdsouza/zoxide/issues/181#issuecomment-819025228) there.

**Comment by romkatv** [comment]
> Sorry, I meant: `su` to root

Do you meant that you literally run `su` without arguments? Can you run it and post a screenshot?

> Without z4h, each user has their own `.zshrc`, so there is no problem.

If you use something like `sudo su -` or `sudo -i`, you'll log in as root using root's login shell and root's rc files.

If you use something like `sudo -E zsh`, you'll run zsh as root but with `$HOME` pointing to your own home directory. Thus, rc files from your home directory will be used.

It's the same with and without z4h. z4h does not change how `sudo` and `su` work.

> Agreed, but there seems to be [no easy solution](https://github.com/ajeetdsouza/zoxide/issues/181#issuecomment-819025228) there.

There is an easy solution. Here's how one can "atomically" append to a file without changing its mode and permissions:

```zsh
cp -p foo foo.tmp
echo extra >>foo.tmp
mv -f foo.tmp foo
```

I realize that zoxide is implemented in rust but this doesn't make the task any harder.

**Comment by magnetophon** [comment]
Doh!  I had copied my user ``.zshrc`` to root and forgot about it.
All this time I thought z4h was automatically carrying over my zsh settings.

All good now, sorry for the noise!

In any case, I'll forward your solution proposal to the zoxide issue.

Thanks!!!
