### ISSUE TITLE
DOCS: give more context as to why ~/.zprofile and ~/.zlogin should generally not be used, and how to use them appropriately

### ISSUE THREAD

**Issue by vinayluzrao** [romkatv/zsh4humans#186]
From https://github.com/romkatv/zsh4humans#additional-zsh-startup-files :

> Zsh supports several additional startup files with complex rules governing when each file is sourced. The additional startup files are ~/.zprofile, ~/.zlogin and ~/.zlogout. Do not create these files unless you are absolutely certain you need them.

---

I'll provide some (optional) context as to why I'm interested in using them:

I'm writing the build for a docker container that my team will use for all of their development. Their IDEs will connect to the container, and they will SSH into it to run any commands that interact with development dependencies. I'm recommending that they use and adding support for z4h due to its amazing SSH teleportation. The issue is I need ZSH to source some env vars that are required for development. Right now, the solution I'm using is having developers add this to their `.zshrc`:
```zsh
ide_container_source_file=/etc/profile.d/ide-container-dev-env-vars.sh;
if [[ -f $ide_container_source_file ]]; then
    z4h source $ide_container_source_file;
fi
unset ide_container_source_file
``` 
I don't like this. I want to avoid configuration that happens outside the container as much as possible. I believe an easy fix for this would be to use one of ~/.zprofile or ~/.zlogin, and preconfigure it during `docker build` itself, with something like
```Dockerfile
RUN echo "source /etc/profile.d/ide-container-dev-env-vars.sh"  >> ~/.zlogin
```
or
```Dockerfile
ARG dev_env_vars_file=/etc/profile.d/ide-container-dev-env-vars.sh
# Additional question: is this more appropriate than the above? I'm not sure if z4h has initialized at this point, nor do I know when `z4h source` is more appropriate then `source`
RUN echo "if (which z4h > /dev/null); then z4h source $dev_env_vars_file; else source $dev_env_vars_file; fi"  >> ~/.zlogin
```
I'm worried about unknown problematic behavior when going with one of these two solutions because of the z4h docs recommendation to not use them.

**Comment by romkatv** [comment]
Where do developers get their zshrc from?

Where will they get zlogin from?

**Comment by vinayluzrao** [comment]
.zshrc will come from their own machines; it will be SSH-teleported into the container.

.zlogin will already be present in the container.

**Comment by romkatv** [comment]
Where do they get zshrc to begin with?

**Comment by vinayluzrao** [comment]
They install and configure it in their own machines, via the normal installation process.

**Comment by vinayluzrao** [comment]
I tried ~/.zlogin, ~/.zprofile and ~/.env.zsh. None of them work; all three are deleted during SSH teleportation.
As a reminder, ~/.env.zsh is sourced in the default z4h .zshrc:
```zsh
# Source additional local files if they exist.
z4h source ~/.env.zsh
```
Having ~/.zlogin, ~/.zprofile present during the normal z4h install (i.e. completely unrelated to SSH teleportation) will make the installation wizard prompt this:
```
You have the following Zsh startup files:

    ~/.zprofile
    ~/.zlogin

What should I do with them?

  (1)  Move them to ~/zsh-backup/20211217-033721. Recommended.
  (2)  Delete them.
  (q)  Quit and do nothing.

Choice [12q]: 
```

And I can confirm that .env.zsh is deleted due to this line in the default .zshrc:
```zsh
# Send these files over to the remote host when connecting over SSH to the
# enabled hosts.
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'
```
Removing the '~/.env.zsh' entry will preserve it in the container. But again, I want z4h's default installation (albeit with SSH teleport on) to just work, I want to avoid having this extra configuration step outside of the container.

**Comment by romkatv** [comment]
There are several ways to achieve what you want.

## Client-centric

zsh4humans installer simply creates `~/.zshrc` and `~/.zshenv`. It doesn't do anything else. Instead of asking devs to go through the installer, you can give them these two files. If you also give them `~/.p10k.zsh`, they won't have to go through prompt configuration wizard (please read [this](https://github.com/romkatv/powerlevel10k#what-is-the-best-prompt-style-in-the-configuration-wizard) if you go this route).

To pick up `/etc/profile.d/ide-container-dev-env-vars.sh` when in SSH, `~/.zshrc` needs to have this line:

```zsh
z4h source /etc/profile.d/ide-container-dev-env-vars.sh
```

This doesn't do anything if the file doesn't exist, so you don't need to guard it with conditionals.

As a slight variation of this approach you can give devs `~/.ide-container-dev-env-vars.sh` and configure SSH teleportation to send that file over. In this case `~/.zshrc` should have `z4h source ~/.ide-container-dev-env-vars.sh` and the file should do nothing unless `$HOST` indicates otherwise.

## Server-centric

Add this to `/etc/ssh/sshd_config` on the server:

```zsh
ForceCommand /usr/libexec/run-with-dev-env-vars
```

Create `/usr/libexec/run-with-dev-env-vars` (owned by root; permissions 0755):

```zsh
#!/usr/bin/env zsh

source /etc/profile.d/ide-container-dev-env-vars.sh

if [[ -n $SSH_ORIGINAL_COMMAND ]]; then
  exec ${SHELL:==sh} -c $SSH_ORIGINAL_COMMAND
else
  exec -l ${SHELL:==sh}
fi
```

This approach is vastly superiors to all alternatives:

1. It doesn't depend on SSH teleportation.
2. It doesn't depend on the specific login shell and config that devs use on their local machines. If they want to use bash, or zsh without zsh4humans, that's fine.
2. It doesn't depend on the specific login shell that devs will want to use in the container. Again, bash is fine, and so is zsh without zsh4humans.
3. It works with non-interactive ssh commands: `ssh host env` will show env vars set by `/etc/profile.d/ide-container-dev-env-vars.sh` while with ssh teleportation the same command won't show these env vars if you've never teleported to this machine before.

I would recommend the server-centric setup.

**Comment by romkatv** [comment]
> I would recommend the server-centric setup.

That said, if you still chose zsh4humans as a recommended shell config for dev machines, give users `~/.zshrc`, `~/.zshenv` and `~/.p10k.zsh` instead of asking them to run through the installer. Also tell them that it's enough to backup/copy these files to another machine if they want to migrate their shell environment.

**Comment by vinayluzrao** [comment]
The server-centric setup is what I was looking for, and much more, due to the four great points you mentioned.
The instructions worked flawlessly. I altered the zsh script to use bash instead (I believe most devs, including myself, will have a better time maintaining it due to its ubiquity/familiarity), but the idea is the same. Here is the Dockerfile snippet, for anyone who might want it in the future.
```Dockerfile
ARG sshd_env_augment_script=/usr/libexec/augment-sshd-with-dev-env-vars.bash
RUN \
    echo -e '#!/bin/bash --login \n\
        ${SHELL:=$(which sh)} ${SSH_ORIGINAL_COMMAND:+ -c "$SSH_ORIGINAL_COMMAND"}\
        ' > $sshd_env_augment_script; \
    chmod 755 $sshd_env_augment_script; \
    echo "ForceCommand $sshd_env_augment_script" >> /etc/ssh/sshd_config;
```
Note that since the file that actually contains the env vars is inside /etc/profile.d/, `#!/bin/bash --login` is already `source`ing it.

An anecdote: this was a great solution and it didn't even use any z4h functionality, so I was thinking to myself in hindsight
"Why didn't I think of that? It was likely that sshd had something like ForceCommand, being as mature as it is."
I then realized that, even knowing about ForceCommand, I would still not have been confident about this, due to:
- the z4h recommendation to not use other zsh startup files,
- since z4h is so "magical", in that it does so much, so quick and seamlessly (really fast and easy installation, configuration wizard, p10k, SSH teleportation), it made me feel (and I'm extrapolating that others do too) that there is probably complicated stuff going on behind the scenes, and complicated usually means brittle.
And so, I would probably have made this issue even then.

Thanks a lot for the awesome solution @romkatv! I'll let you close this when you want as perhaps you might think there is some value in documenting some of what was discussed here. Interest in remote development is rapidly growing; VSCode/Microsoft have invested heavily in remote development as can be seen from their [comprehensive documentation](https://code.visualstudio.com/docs/remote/remote-overview). VSCode is even going as far as providing base container images purpose-made for remote dev. JetBrains is ramping up investment [as well](https://www.jetbrains.com/remote-development/).
And in this area, SSH teleportation makes z4h is the easiest solution for shell customization on an individual dev level, from what I've seen, at least.

**Comment by romkatv** [comment]
> Here is the Dockerfile snippet, for anyone who might want it in the future.

Your script has a few problems that aren't present in my version:

1. It starts a non-login shell. Normally sshd starts a login shell, so this difference can be surprising. If a user's shell is `zsh`, they expect `~/.zslogin` to be sourced when they ssh but it won't be.
2. It keeps the parent `bash` process running for the whole duration of `$SHELL`.
3. It performs an unnecessary fork (`which`).
4. If the full path to `sh` contains `IFS`, the script will execute a wrong command or fail.
5. If `sh` is not in `PATH`, the script will either do nothing or attempt to execute `-c` as a command.
6. It performs unnecessary initialization of bash login shell: sets bash prompt, sets up bash completions, etc. Even if `$SHELL` is bash, this initialization is a waste.

> the z4h recommendation to not use other zsh startup files

Looks like this recommendation worked in your favor: it made you cautious w.r.t. using zsh startup files for solving this problem, which led to opening this issue and eventually discovering a better solution.

> since z4h is so "magical", in that it does so much, so quick and seamlessly (really fast and easy installation, configuration wizard, p10k, SSH teleportation), it made me feel (and I'm extrapolating that others do too) that there is probably complicated stuff going on behind the scenes, and complicated usually means brittle.

This point is well taken. It's difficult for users to build a model of zsh4humans. It's nice that ssh teleportation works seamlessly but sometimes (like in your case), it's necessary to understand *how* it works. Documentation could help with this.

---

Going back to the rc files on dev machines, you might want to enable shared command history in there. Basically, if you ssh to a container and run some commands, then rebuild the container and ssh again -- it's really nice to have your command history intact. See https://github.com/romkatv/zsh4humans/issues/150#issuecomment-966190428 for how to configure this.

You might also want to check out https://github.com/romkatv/zsh4humans/issues/149.

**Comment by vinayluzrao** [comment]
Thanks for catching those regressions, I updated the script in my previous comment and believe I've dealt with all of them. 

I'll be giving the shared command history a try, indeed it does sound very nice. I expect I'll end up recommending it as well once you make those mentioned API simplifications. 

#149 was helpful. I'll get into customizing and trying out the more exotic shortcuts and related features later, recently I've made many changes to my workflow and already have a lot to get used to.

**Comment by romkatv** [comment]
> I'll be giving the shared command history a try, indeed it does sound very nice. I expect I'll end up recommending it as well once you make those mentioned API simplifications.

Just to set the expectations right, it may take a long time before I introduce a new API for this. Could be a month. Could be year. Could be longer. This feature is fully functional as is though, and you can enable it by copy-pasting the config I pointed to. If it sounds useful, give it a try. Up to your of course. (FWIW, to me it's incredibly useful.)

**Comment by romkatv** [comment]
I believe I've answered all questions here. Closing.
