### ISSUE TITLE
"^R" z4h-fzf-history returns incorrect selection

### ISSUE THREAD

**Issue by Spoons** [romkatv/zsh4humans#187]
When using control-r / z4h-fzf-history, the line that is selected is not the one that is returned to the line editor. Instead, it returns a different line from the history.

When a new shell is created, initially the history function works correctly. After 1 to 8 invocations, the incorrect line is always returned.

**Comment by romkatv** [comment]
Is it reproducible after `exec zsh`?

Is it reproducible with the stock `~/.zshrc` and `~/.zshenv`?

Can you attach `~/.zsh_history` file that demonstrates the issue? Also specify what I need to search and select in `Ctrl-R` to get the wrong line printed.

**Comment by Spoons** [comment]
It does not occur with stock zshrc. I, just now, found that one of these parameters is responsible:
```
setopt hist_find_no_dups
setopt hist_ignore_all_dups
```

It occurs after a 'duplicate' command is used. It might be worthwhile unsetting the problematic option in z4h or adjusting the function to handle them.

**Comment by romkatv** [comment]
While waiting for your reply I blindly tried different things that could reproduce this. I found a bug that is reproduced like this:

1. Hit <kbd>Ctrl+R</kbd> and accept anything.
2. Press <kbd>Alt+J</kbd> to clear the command line.
3. Hit <kbd>Ctrl+R</kbd> and accept anything.

On the last step a wrong history entry (or none at all) gets inserted into the command line. I've fixed this. Please run `z4h update`.

Does this fix the issue you are having? If no, I'll need answers to the questions I posted earlier.

**Comment by romkatv** [comment]
I posted my comment before seeing your reply.

> `setopt hist_find_no_dups`

This option is set by default.

> `setopt hist_ignore_all_dups`

This option is not set by default.

Are you saying that you enabled this option manually? If so, what were you trying to achieve?

**Comment by romkatv** [comment]
It's likely that https://github.com/romkatv/zsh4humans/commit/d4267009b617a412bfb72f6ae83b912ee3cdfc16 fixes this bug, too. Could you `z4h update` and verify?

With regards to options, zsh4humans is configured to keep all events, including dups, for the current session. However, dups aren't saved into the persistent history. Thus, if you run `exec zsh`, you'll have no dups in history.

The advantage of keeping all events for the current session is that you can easily recall all commands, in the right order, that you ran with `fc -Il 0`. This is very useful when you run many commands and then want to put them in a script.

**Comment by Spoons** [comment]
I can confirm d426700 fixes the issue. 

My intention with ```setopt hist_ignore_all_dups``` is to minimize the history file size so I can store my entire command history. 

However, since HISTFILE and SAVEHIST can be set to the trillions, as per LONG_INT in limits.h, this is probably unnecessary and the loss of the order of commands may be more detrimental than the additional consumed space and memory.

```fc -Il 0``` is very useful. I've had that same use case come up and was not aware that could be done. I appreciate the thorough explanations.

Pardon me on the long response times, I'm traveling in an area with limited internet access to say the least.

Closing this issue.

**Comment by romkatv** [comment]
> I can confirm [d426700](https://github.com/romkatv/zsh4humans/commit/d4267009b617a412bfb72f6ae83b912ee3cdfc16) fixes the issue.

Thanks for the confirmation!

> My intention with `setopt hist_ignore_all_dups` is to minimize the history file size so I can store my entire command history.

As I mentioned above, this option has no effect on the history file size. Persistent history already gets deduplicated with the stock z4h options.

This may sound obvious but I've seen this happen so many times that it's worse saying. When you make a change your zsh config, it's a really good idea to verify that it has the effect you intended. E.g., if you believe that `setopt hist_ignore_all_dups` will reduce history file size, check the file size with and without this option.
