### ISSUE TITLE
`compdef function=app` doesn't work from .zshrc

### ISSUE THREAD

**Issue by maximbaz** [romkatv/zsh4humans#188]
Hello,

Have `.zshrc` with the following contents on fully updated z4h:

```zsh
z4h init || return

vvv() { vim "$@" }
compdef vvv=vim
```

Open a new terminal, try `vvv -<Tab>`. Nothing happens, while `vim -<Tab>` shows completions.
Now manually run `compdef vvv=vim` and retry above, after this `vvv -<Tab>` works as expected.

It used to work before, I'm lagging behind on the Feedback thread, I _think_ this issue has started to happen since performance optimizations, but as I'm not sure, I haven't immediately noticed and as enough time has passed I'm simply not sure anymore.

**Comment by romkatv** [comment]
Ack. Thanks for reporting this. Will take a look tomorrow.

**Comment by romkatv** [comment]
An embarrassingly stupid bug that I should've noticed a long time ago. Fixed.

**Comment by maximbaz** [comment]
Fix confirmed, thanks!
