### ISSUE TITLE
Respect TERMINFO when doing z4h update

### ISSUE THREAD

**Issue by pn-santos** [romkatv/zsh4humans#189]
Hi, I've noticed that when doing `z4h update` (v5), the `~/.terminfo` dir will be created unconditionally even though I have the following set when running `z4h update`:
```bash
export XDG_DATA_HOME="$HOME/.local/share"

export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
```

Shouldn't the update use the `TERMINFO` dir if set?

**Comment by romkatv** [comment]
Can you describe what expect to happen w.r.t. terminfo when you run `z4h update` and which issues it'll solve for you?

**Comment by pn-santos** [comment]
I would expect it to use the location `TERMINFO` specifies instead of creating `~/.terminfo` dir. I'm in no way an expert but from what I understand, based on https://wiki.archlinux.org/title/XDG_Base_Directory `TERMINFO` env var should override the default dir `~/.terminfo`

I guess the problem is that after running the update I end up with duplicate locations and have to manually delete `~/.terminfo` (

**Comment by romkatv** [comment]
The problem is disk usage? If so, I'll keep the code as is because it works and the disk usage isn't that big.

**Comment by pn-santos** [comment]
It's not about disk usage really, I mean it's 3.3 Mb, irrelevant nowadays. It's more about avoiding having duplicate dirs and the general expectation of `TERMINFO` location being used if specified instead of the default `~/.terminfo`.

If it's not worth the effort to change then feel free to close.

Thanks for z4h btw it's the first thing I install on my machines :+1: 

Happy holidays and thanks for all your work!

**Comment by romkatv** [comment]
If I change the code, things will likely break in subtle cases. I don't want that. I'll change it only if something doesn't work right now. The creation of `~/.terminfo` when you think it's not needed is not enough motivation to risk breakages.
