### ISSUE TITLE
ctrl-r (fzf) doesn't list history

### ISSUE THREAD

**Issue by seanfarley** [romkatv/zsh4humans#190]
I'm trying to get `ctrl+r` to work but it only displays `0/0`. `fzf` seems to work with other commands, though (such as tab complete with a list of items to select).

Follow up question, is there a way to disable `fzf` or is it pretty baked in?

Any help on how to debug this would be greatly appreciated! Also, thanks for an awesome package!

**Comment by romkatv** [comment]
> I'm trying to get `ctrl+r` to work but it only displays `0/0`.

What does `history` say?

> Follow up question, is there a way to disable `fzf` or is it pretty baked in?

The latter.

> thanks for an awesome package!

You are welcome. It doesn't seem like it works for you though.

**Comment by seanfarley** [comment]
> > I'm trying to get `ctrl+r` to work but it only displays `0/0`.
> 
> What does `history` say?

For me, it shows:

```
❯ history
56780  z doom
56781  bin/doom upgrade
56782  sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"
56783  zsh
56784  ls
56785  zsh
56786  cat ~/.bash_history | awk '{print ": :0:;"$0}' >> ~/.zsh_history
56787  wc -l ~/.zsh_history 
56788  zsh
56789  exec zsh
56790  zsh
56791  wc -l ~/.zsh_history 
56792  zsh
56793  ls
56794  ssh gcc304.fsffrance.org
56795  ls
```

Maybe my bash history is confusing it?

**Comment by romkatv** [comment]
Let's try this:

1. Close all interactive zsh sessions.
2. Open one interactive zsh.
3. Verify that it's the only interactive zsh (use `ps` or whatever).
4. Run `z4h update`.
5. Check whether <kbd>Ctrl+R</kbd> works. If it doesn't, post the output of the following command:
  ```zsh
  typeset -pm 'HISTFILE|HISTSIZE|SAVEHIST' &&
    emulate &&
    print -r -- $(setopt) &&
    zstyle -L ':z4h:*' &&
    fc -l -2 -2 &&
    print -r -- ${#${history[@]}} ${(qqq)${history[@]}[1]}
  ```

**Comment by seanfarley** [comment]
Okie dokie, I did all that and it didn't work so this is the output:

```
❯ typeset -pm 'HISTFILE|HISTSIZE|SAVEHIST' &&
  emulate &&
  print -r -- $(setopt) &&
  zstyle -L ':z4h:*' &&
  fc -l -2 -2 &&
  print -r -- ${#${history[@]}} ${(qqq)${history[@]}[1]}
typeset HISTFILE=/Users/sean/.zsh_history
export -i10 HISTSIZE=1048576
typeset -i10 SAVEHIST=1000000000
zsh
alwaystoend autocd noautomenu autopushd noautoremoveslash nobeep nobgnice cbases extendedglob extendedhistory noflowcontrol noglobalrcs globdots histexpiredupsfirst histfcntllock histfindnodups histignoredups histignorespace histsavenodups histverify interactive interactivecomments nolisttypes promptsubst sharehistory shinstdin typesetsilent
zstyle :z4h: auto-update no
zstyle :z4h: auto-update-days 28
zstyle :z4h:ssh:example-hostname1 enable yes
zstyle ':z4h:ssh:*.example-hostname2' enable no
zstyle :z4h:direnv enable no
zstyle ':z4h:ssh:*' enable no
zstyle :z4h:autosuggestions forward-char accept
zstyle :z4h:bindkey keyboard mac
zstyle :z4h:direnv:success notify yes
zstyle :z4h: prompt-at-bottom yes
zstyle :z4h:fzf-complete recurse-dirs no
zstyle ':z4h:ssh:*' send-extra-files '~/.nanorc' '~/.env.zsh'
zstyle :z4h: term-shell-integration yes
13557  killall Dock
zsh: failed to find end of command substitution
```

I'm not sure what that means but it gave me an idea about bisecting my history file. Low and behold, I found the culprit: bad encoding! I'm going to try to attach a minimal history file:

[bad-zsh-history.txt](https://github.com/romkatv/zsh4humans/files/7785729/bad-zsh-history.txt)

And here is a copy/pasta of the bad history but I'm afraid it'll get autocorrected to utf8 and fixed:

```
: 1640639562:0;beet ls artist:pillows
: 1640639562:0;res = lib.items(['title:Runners High'])
: 1640639562:0;print(シートベ)
: 1640639562:0;print("シートベ")
: 1640639562:0;which python2
: 1640639562:0;python2 -c "print 'シートベ'"
: 1640639562:0;python2 -c "print b'シートベ'"
: 1640639562:0;python2 -c "print 'シートベ'[1]"
: 1640639562:0;python2 -c "print u'シートベ'[1]"
: 1640639562:0;python -c "print u'シートベ'[1]"
: 1640639562:0;python -c "print 'シートベ'[1]"
: 1640639562:0;python3 -c "print 'シートベ'[1]"
: 1640639562:0;python3 -c "print('シートベ'[1])"
: 1640639562:0;python3 -c "print(u'シートベ'[1])"
: 1640639562:0;python3 -c "print(b'シートベ'[1])"
: 1640639562:0;            print(line[0:15])
```

Finally, just to visually show how mangled it is, a screenshot (I know, really lame) as a last resort to show what FileMerge displays:

<img width="400" alt="Screen Shot 2021-12-28 at 11 12 33 AM" src="https://user-images.githubusercontent.com/20887/147590581-2f9f16f1-d90f-4b3f-8efc-edf9ead9b237.png">

Opening the file in emacs and saving it with utf8 fixes the problem for me ^_^

**Comment by romkatv** [comment]
I'm glad you figured it out.
