### ISSUE TITLE
Automated install

### ISSUE THREAD

**Issue by seanfarley** [romkatv/zsh4humans#191]
I'm trying to write a script to install z4h when it doesn't exist on a remote machine but the install script seems to force a user interaction. Is there a way to supply the answers that the install script is looking for programmatically?

**Comment by romkatv** [comment]
zsh4humans installer creates three files: `~/.zshrc`, `~/.zshenv` and `~/.p10k.zsh`. It doesn't do anything else. To install zsh4humans non-interactively, simply create these files. If you have a git repo where you store dotfiles (it's a really good idea), store these files in that repo.

Also note that zsh4humans can automatically teleport from a local machine to remote over SSH. See https://github.com/romkatv/zsh4humans#SSH.

**Comment by seanfarley** [comment]
> zsh4humans installer creates three files: `~/.zshrc`, `~/.zshenv` and `~/.p10k.zsh`. It doesn't do anything else. To install zsh4humans non-interactively, simply create these files. If you have a git repo where you store dotfiles (it's a really good idea), store these files in that repo.

Aha, just tested today and it works brilliantly!

> Also note that zsh4humans can automatically teleport from a local machine to remote over SSH. See https://github.com/romkatv/zsh4humans#SSH.

I saw that and am definitely going to get there one day!

**Comment by riotrah** [comment]
Hi! I'm sorry if the following questions don't make sense, and/or if they may burden you given the limited support you're still graciously offering ( I think ):

If I track the z4h-relevant dotfiles the installer creates via my dotfiles manager, how might I also ensure that 
- the `z4h` cli tool
- the various `install`ed/cloned git repos
- and the `$Z4H` env var 
exist in a new, dotfiles-automated setup ?

Thanks so much for creating this project, by the way. I used to spent _crazy_ amounts of time bikeshedding/half-setting-up my own zsh setup, and needed a turnkey setup like this to finally stop me from endlessly "fine-tuning" :)
