### ISSUE TITLE
Integrate with package managers?

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#194]
Is it possible for zsh4humans to play nicely with package managers? The installation and update scripts seem to assume the system has no package manager and consequently vendors all dependencies inside the user's cache.

The main goal is to manage (install and update) zsh4humans and dependencies through the system's package manager. Auto-updating feels wrong and is one of the main reasons for moving away from oh-my-zsh and yet manual invocation of `z4h update` also feels wrong. It would be great to manage zsh4humans alongside other system packages.

As such, I'm interested in writing an [AUR](https://aur.archlinux.org/) package but am struggling to understand how best to do so. The [oh-my-zsh-git](https://aur.archlinux.org/packages/oh-my-zsh-git/) package seems to use a patch file to override the installation directory to `/usr/share/oh-my-zsh/`. Would you be able to offer any advice?

Thanks!

**Comment by romkatv** [comment]
One of the most important features of zsh4humans for me personally is its ability to teleport over SSH to any system. This requires vendoring all dependencies. That's why zsh4humans packages zsh, fzf, etc.

When powerlevel10k was packaged as AUR and, at a later point, Arch Linux Community Package, it results in massive amount my time wasted. I didn't enjoy that experience. My advice is to not create a public AUR package for zsh4humans. If you do create it, please make it very clear that users of your package should file bug reports to you and not to me. It would be even better if you change the name to something that cannot be confused with zsh4humans.

**Comment by romkatv** [comment]
> Is it possible to have it both ways? As I understand from #142, it appears that zsh4humans will prefer the system binary.

zsh4humans uses its own `fzf` even if there is another `fzf` in `PATH`.

> I'm not interested in burdening you, and so will make active effort to avoid doing so.

Thank you. I really appreciate it.

**Comment by uhthomas** [comment]
I see.

Something I just noticed; In some cases, zsh4humans _does_ rely on a package manager. Specifically `brew` is used for [command-not-found](https://github.com/romkatv/zsh4humans/blob/df5c473d344124f74f3c6a36825f460d4aef97b6/fn/-z4h-command-not-found).

How does this behave with SSH teleporting? Does it make sense to unify behaviour?

**Comment by romkatv** [comment]
> How does this behave with SSH teleporting?

It does not.

Another optional dependency that doesn't get packaged is `bfs`. If you install it, zsh4humans wii work better.

> Does it make sense to unify behaviour?

Yes. Ideally zsh4humans should package all dependencies.

**Comment by romkatv** [comment]
Closing as I don't intend to do anything here.

**Comment by luxus** [comment]
> Another optional dependency that doesn't get packaged is `bfs`. If you install it, zsh4humans wii work better.
is there any other tools that helps z4h?

**Comment by romkatv** [comment]
The full list:

- `bsf` provides better ranking of recursive file completions.
- If you have `brew`, zsh4humans will tell you how you can install something when you attempt to run a command that doesn't exist.
- If you install command-not-found package for your package manager, zsh4humans will utilize it the same way as `brew` above. E.g., on Debian-based systems you need to run `apt install command-not-found`.
