### ISSUE TITLE
SSH teleport overwrites target .zsh* files

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#195]
Correct me if I'm wrong but it seems that SSH teleport overwrites `.zshrc`, `.zshenv`, `.zprofile` and `.zlogin` with no backup.

**Comment by romkatv** [comment]
You are correct.

**Comment by romkatv** [comment]
Closing as I've answered the question.

**Comment by uhthomas** [comment]
Oh.

This is a little scary. Is it possible to reopen this issue as a feature request for backing up those files? I did not expect this at all and those files are gone forever now.

**Comment by romkatv** [comment]
I have it on my TODO list. No need to have an issue open.

Did those files really have useful content and did you really lose them forever? If so, I highly recommend finding a solution to that problem that will prevent such disasters in the future.
