### ISSUE TITLE
tmux used despite answering no

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#196]
The guided installation poses the question:

```sh
Do you want zsh to always run in tmux?

  (y)  Yes.
  (n)  No.
  (q)  Quit and do nothing.

Choice [ynq]: n
```

Despite answering `n`, it's apparent that tmux is being used as the terminal window is titled `~ (tmux)` and the `TERM` environment variable contains `tmux`. 

```sh
❯ grep -i tmux .zshrc # no mention of tmux in .zshrc
❯ printenv TMUX # no TMUX env var
❯ printenv TERM
tmux-256color
```

Manually setting `start-tmux` to `no` in `.zshrc` produces the expected result.

```zsh
zstyle ':z4h:' start-tmux 'no'
```

**Comment by romkatv** [comment]
What's the issue?

**Comment by romkatv** [comment]
To expand on my previous comment:

> Despite answering `n`, it's apparent that tmux is being used

No, tmux is not being used.

> the terminal window is titled `~ (tmux)`

You can fix this by instructing your terminal to allow programs to change its title. All terminals have a setting for that.

> the `TERM` environment variable contains `tmux`.

Does this cause issues?

> Manually setting `start-tmux` to `no` in `.zshrc` produces the expected result.

What is the expected result? Can you describe what doesn't work as you expect?

Manually setting `start-tmux` to `no` disables several features. This option exists for debugging purposes.

**Comment by uhthomas** [comment]
> No, tmux is not being used.

What makes you think that? Why does `TERM` contain `tmux` otherwise?

> You can fix this by instructing your terminal to allow programs to change its title. All terminals have a setting for that.

I don't mind the window title, it was just there to demonstrate evidence to suggest tmux is being used.

> Does this cause issues?

Mouse events (scrolling) don't work correctly inside tmux. Without manually setting `start-tmux` to `no`, scrolling doesn't work in `vim`, `less` or any other program. Partially related; the default flags for less set by zsh4humans break scrolling (see https://github.com/ohmyzsh/ohmyzsh/issues/7025).

> What is the expected result?

I would expect tmux to not be used at all if I answer `no` to using tmux.

**Comment by romkatv** [comment]
> I don't mind the window title, it was just there to demonstrate evidence to suggest tmux is being used. I would expect tmux to not be used at all if I answer `no` to using tmux.

`tmux` is not being used in this case. I know it's confusing because there is the word "tmux" in a few places. I really need to clean that up.

> Without manually setting `start-tmux` to `no`, scrolling doesn't work in `vim`, `less` or any other program.

Now, *that's* a useful bug report. Unlike the previous statements this one says that some feature doesn't work as expected. This is a regression that I need to take a look into.

Scrolling works in programs that explicitly enable mouse. Try `htop`, `nano --mouse` or `less --mouse`. As a temporary solution I suggest defining aliases that enable mouse explicitly in applications that you care about. This can even bring advantages such as cursor positioning with a mouse click in `vim`, `nano`, etc. It'll also enable mouse wheel scrolling in `less -X` (terminal heuristics don't kick in when this option is used).

>  Partially related; the default flags for less set by zsh4humans break scrolling (see [ohmyzsh/ohmyzsh#7025](https://github.com/ohmyzsh/ohmyzsh/issues/7025)).

If you don't like the default value of `LESS`, go ahead and override it.

**Comment by uhthomas** [comment]
Hmm, I see. I can confirm that mouse scrolling does work when explicitly enabled (i.e `--mouse`, `set mouse=a`). Thanks for the help!

Will zsh4humans see mouse support added for common commands like `less` and `vim`?

**Comment by romkatv** [comment]
> Hmm, I see. I can confirm that mouse scrolling does work when explicitly enabled (i.e `--mouse`, `set mouse=a`). Thanks for the help!

👍 

> Will zsh4humans see mouse support added for common commands like `less` and `vim`?

Yes for `less`, no for `vim`. Vim users usually have their own elaborate configs. I don't want to intrude on them.

**Comment by davidbgonz** [comment]
A side note: setting `zstyle ':z4h:' start-tmux 'no'` explicitly will cause the prompt to be at the top no matter what you set for `prompt-at-bottom`.

**Comment by romkatv** [comment]
> A side note: setting `zstyle ':z4h:' start-tmux 'no'` explicitly will cause the prompt to be at the top no matter what you set for `prompt-at-bottom`.

It disables several other features. It's undocumented which ones but basically anything that requires knowing what's on the screen.

**Comment by uhthomas** [comment]
I also noticed this. I imagine that tmux is probably required for this functionality?

**Comment by romkatv** [comment]
Either tmux or definitely-not-tmux (which is called "integrated tmux" for historical reasons in some places).
