### ISSUE TITLE
Automatic blank lines on new terminal instances?

### ISSUE THREAD

**Issue by robmonte** [romkatv/zsh4humans#197]
I can't figure out which part of z4h is putting blank lines into new terminal sessions. Currently when I launch iTerm there is a scrollbar despite the window being mostly empty.

I set prompt-at-bottom to 'no' and that puts the prompt to the top, yet the blank lines are still present (now below the prompt instead of above) and it makes the window have a scrollbar. It seems to always scroll down to hide the "Last login: xyz" text on a new terminal. I haven't been able to isolate what causes this.

**Comment by romkatv** [comment]
That's correct, zsh4humans scrolls screen when starting. The scrollbar appears when the screen wasn't empty to begin with.

What are you trying to fix? Do you want to get rid of the scrollbar or do you want to see "Last login: xyz"?

**Comment by robmonte** [comment]
Ah, I guess I didn't exactly state my goal. I was hoping to turn off whatever it is that's inserting the blank lines/scroll the window.

**Comment by romkatv** [comment]
Can you explain why you want that?

**Comment by robmonte** [comment]
I just dislike a scrollbar being present for no reason. If there was a single less blank line then there wouldn't be a scrollbar and the "last login" text would be visible with the prompt still being on the bottom of my window. Personally I'd prefer to not have the scrollbar on new/empty terminal windows, plus to still be able to see the last login message. I was trying to figure out how to customize that myself but couldn't find where it was happening.

On top of that, I somewhat think it is unexpected behavior to disable prompt-at-bottom yet continue to have a bunch of blank lines inserted below the prompt. Though, I think I'd possibly prefer the prompt-at-bottom to be on _if_ there was a way for me to customize the above behavior.

**Comment by romkatv** [comment]
> What are you trying to fix? Do you want to get rid of the scrollbar or do you want to see "Last login: xyz"?

Can you answer this again? I'm confused by your last two comments.

**Comment by robmonte** [comment]
Sorry I'm not explaining myself well. Let me show you visually instead:

Current new terminal windows:
![Screen Shot 2022-01-19 at 9 09 40 AM](https://user-images.githubusercontent.com/17119716/150159902-943a7fbf-1fc7-45fe-9cff-78dadf8d93ec.png)

&nbsp;
&nbsp;

Desired behavior:
![desired](https://user-images.githubusercontent.com/17119716/150160416-d0fb2187-2926-46fa-bc80-3a56a7f17dd4.png)

**Comment by romkatv** [comment]
Just to confirm, you really need both, right? You need that message and you need there to be no scrollbar. Correct?

**Comment by robmonte** [comment]
Ideally yes, but I can compromise on the "Last login" message going away if it needs to. I care more about the scrollbar.

Additionally, here's an alternate desire where the prompt-on-bottom is on
![desired-with-bottom](https://user-images.githubusercontent.com/17119716/150163340-a7f240b9-a660-44ba-aabf-65b8f8716def.png)

Again, I can compromise on the "Last login" message here too.

**Comment by romkatv** [comment]
You can remove the "last login" message with this command:

```zsh
touch ~/.hushlogin
```

That message is just noise, so silencing it would improve UX even when not using zsh4humans.

**Comment by robmonte** [comment]
Awesome, that works! I didn't think just hiding it would solve the issue.

With prompt-on-bottom turned on, it shrunk the scrollbar but is still visible. If you don't want to waste any more time on this, I can close the issue and by happy with the prompt on top.

**Comment by romkatv** [comment]
> With prompt-on-bottom turned on, it shrunk the scrollbar but is still visible.

Right. Because your prompt takes two lines.

> If you don't want to waste any more time on this, I can close the issue and by happy with the prompt on top.

I'm certainly not going to change anything. That scrollbar will appear the moment you execute the first command. By the way, you can hide the scrollbar in settings.

Another by the way: prompt at bottom is better. If it starts on top, then it won't be at the constant position. Instead, it'll slowly creep to the bottom on every command and eventually you'll have it in the same position at the bottom.

**Comment by robmonte** [comment]
That all makes sense. I'm still wondering _where_ this logic takes place though. It seems like just removing a single extra line would produce the effect I desire. I'm not looking for you to change anything in the repo, but I would like to look into altering it myself.

**Comment by romkatv** [comment]
> It seems like just removing a single extra line would produce the effect I desire.

No, this is pretty much unfixable. z4h needs to know the content on the screen and the only way to do that when it starts is too scroll. It cannot just ask your terminal what's on the screen.

**Comment by robmonte** [comment]
I see. Thanks for the help & learning in this
