### ISSUE TITLE
.zprofile not being used

### ISSUE THREAD

**Issue by smenzer** [romkatv/zsh4humans#2]
Since your `.zshrc` file will get overwritten upon update, I want to use `.zprofile` to store some of my personal aliases/functions that I will use. However, the file doesn't seem to be loading properly, as my aliased commands show as undefined.

My setup is:

~/.zshenv
```
export ZDOTDIR=$HOME/zdotdir
```

~/zdotdir/.zshrc
```
contents of your file
```

~/zdotdir/.zprofile
```
alias ll='ls -lAhG'
...
```

when I open a new zsh session, if i type in `ll` i get `zsh: command not found: ll`

Any idea why this setup isn't working?

**Comment by romkatv** [comment]
`.zprofile` is automatically sourced by zsh in login shells. If you start a non-login shell, it won't get sourced.

If you want to keep `zsh4humans/.zshrc` in pristine state and add stuff around it, I suggest saving it as `z4h.zsh` and sourcing from your own `.zshrc`.

**Comment by smenzer** [comment]
> .zprofile is automatically sourced by zsh in login shells. If you start a non-login shell, it won't get sourced.
yea I knew that, which is why i thought it would work.

I like your idea better, anyway, so I'll go with that...thanks!

**Comment by smenzer** [comment]
quick question related to this - since I'm not doing a `source ${ZDOTDIR}/zsh.zsh` within my `.zshrc` file, what's the best way to reload if I make changes? In bash, I would just do `source ~/.bash_profile`, in zsh this would be `source ${ZDOTDIR}/.zshrc`, but z4h gives an error:

```
z4h: please use exec /Users/scott/zdotdir/z4h.zsh instead of source ~/.zshrc
```

If I do `exec /Users/scott/zdotdir/z4h.zsh` or `exec /Users/scott/zdotdir/.zshrc` I get permission denied errors, probably because neither file has execute privileges...do I need to enable that? Or is there another way to reload everything if I make changes to one of the files, without having to exit zsh shell completely and reopen it?

**Comment by romkatv** [comment]
This error message looks wrong. I suppose there was a bug in it that I've since fixed. The current error message reads:

```text
z4h: please use `exec zsh` instead of source `~/.zshrc`
```

This is a generally good advice for any zsh (or even bash) configuration. zsh4humans just prevents you from shooting yourself in the foot.

**Comment by romkatv** [comment]
FYI: I've just fix a bug that triggers when you source `zsh4humans/.zshrc` from another script. You might want to apply it. See https://github.com/romkatv/zsh4humans/commit/788987ad0e329ea95307b27ea2f571386215ba7e.

**Comment by smenzer** [comment]
awesome thank you! the fixes look great and thanks for the advice on reloading zsh!
