### ISSUE TITLE
Recovery mode entered when using Warp: "confusing config origin: -zsh"

### ISSUE THREAD

**Issue by JakeChampion** [romkatv/zsh4humans#200]
Howdy, first off, thank you so much for zsh4humans, it is fantastic ☺️ 

I've just been accepted into the beta for the [Warp terminal](https://www.warp.dev/) and tried it out and the first thing that happens is z4h enters into recovery mode and I unfortunately can't resolve the issue myself.

The full error I see is this:
```
z4h: confusing config origin: -zsh

z4h: command failed: . "$Z4H"/z4h.zsh
z4h: enabling recovery mode

See error messages above to identify the culprit.

Edit Zsh configuration:

  vi ~/.zshrc

Retry Zsh initialization:

  exec zsh

If nothing helps and you are about to give up:

  # nuke the entire site from orbit
  sudo rm -rf -- "/Users/jake.champion/.cache/zsh4humans"

Give up and start over:

  sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v2/install)"
```

I can get z4h to work by using  `exec zsh` and I have ran `z4h update` but the issue still occurs.

Is there anything else I could run to help provide a more detailed bug report? I'm using macOS Catalina and zsh 5.8

**Comment by romkatv** [comment]
I've backported a fix from v5 to v2. Please run `z4h update` and let me know whether it fixes the issue.

**Comment by JakeChampion** [comment]
That has fixed the issue 🙌 thank you so much 🙇

**Comment by romkatv** [comment]
You are welcome.
