### ISSUE TITLE
[Question] fzf highlight color

### ISSUE THREAD

**Issue by davidbgonz** [romkatv/zsh4humans#204]
Hello, I recently installed z4h and p10k using the installer. When searching using the tab completion, the highlight color is not a color in my terminal color palette. I was thinking it was a matter of configuring something on the fzf side, bit I can't seem to change the highlight color in zsh. I tried setting `FZF_DEFAULT_OPTS="--color=16"` and it does change some of the colors in the tab completion but not the highlight color. 

fzf from tab completion:
![image](https://user-images.githubusercontent.com/10837237/151602828-7617e177-4365-472d-9db0-fe1e9cfef8f5.png)

fzf command itself:
![image](https://user-images.githubusercontent.com/10837237/151603438-8f4c3fbf-e9c4-41c3-84d1-f70183641caf.png)

Do you know if the search highlight color is configurable and do you know why the tab completion has a different color than when running the fzf command itself?

**Comment by romkatv** [comment]
Try this:

```zsh
zstyle ':z4h:*' fzf-flags --color=hl:16,hl+:16
```

**Comment by davidbgonz** [comment]
That did the trick! Thanks for the quick response.

**Comment by romkatv** [comment]
You are welcome.
