### ISSUE TITLE
ohmyzsh/kubectl: `command not found: complete`

### ISSUE THREAD

**Issue by uhthomas** [romkatv/zsh4humans#206]
Load the ohmyzsh kubectl plugin in `~/.zshrc`.

```zsh
z4h load -c ohmyzsh/ohmyzsh/plugins/kubectl
```

Update zsh4humans.

```zsh
❯ z4h update
z4h: fetching z4h.zsh
z4h: updating zsh4humans
z4h: updating systemd completions
z4h: updating zsh-history-substring-search
z4h: updating zsh-autosuggestions
z4h: updating zsh-completions
z4h: updating zsh-syntax-highlighting
z4h: updating terminfo
z4h: updating fzf
z4h: updating fzf binary
z4h: updating tmux
z4h: updating ohmyzsh/ohmyzsh
z4h: updating powerlevel10k
z4h: updating gitstatus binary
z4h: initializing zsh
/proc/self/fd/14:12290: command not found: complete
z4h: update successful
z4h: restarting zsh
```

**Comment by romkatv** [comment]
What are you trying to achieve by loading ohmyzsh/ohmyzsh/plugins/kubectl?

**Comment by uhthomas** [comment]
Just aliases and completions.

**Comment by romkatv** [comment]
If you haven't seen this yet, might be of interest to you: https://github.com/romkatv/zsh4humans/issues/35#issuecomment-1027193022

**Comment by romkatv** [comment]
> Completions should just work. Do they not?

To expand on this, my suggestion is to define the aliases you want explicitly. It unlikely that you want all aliases from ohmyzsh/ohmyzsh/plugins/kubectl. Completion should just work.
