### ISSUE TITLE
z4h update cert issue

### ISSUE THREAD

**Issue by leslieamartinez** [romkatv/zsh4humans#207]
I am getting the follow error when trying to update. BTW amazing work.

z4h: fetching z4h.zsh
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not establish a secure connection to it. To learn more about this situation and how to fix it, please visit the web page mentioned above.

z4h: update failed

**Comment by romkatv** [comment]
This error means either a man-in-the-middle attack or misconfiguration.

This fetching happens in `~/.zshenv`. Here's the command:

```zsh
curl -fsSL -- "$Z4H_URL"/z4h.zsh
```

Try running that. You need to find a way to make it work. You can see the full URL with this command:

```zsh
print -r -- "$Z4H_URL"/z4h.zsh
```

It should https://raw.githubusercontent.com/romkatv/zsh4humans/v5/z4h.zsh if you are on v5. However, all versions are on githubusercontent.com, so the self-signed cert issue originates from your environment and not from the remote host.

**Comment by leslieamartinez** [comment]
I am getting https://raw.githubusercontent.com/romkatv/zsh4humans/v5/z4h.zsh. It was working fine till about a week ago. I am using it on a work laptop on WSL (Windows Subsystem for Linux) and I am wondering if SecOps or MS patching had something to do with it. Can you please provide troubleshooting ideas (I am no cert expert)? If you can't no problem. I love love love zsh4humans. First thing I do on any linux system. It has everything you need and nothing more. Bravo good sir.

**Comment by romkatv** [comment]
The link in the error message has details. This error is not specific to z4h, so I don't think I can add anything valuable on top of that documentation.

Given that it's a work laptop, the error is probably caused by your employer spying on your encrypted traffic.

**Comment by leslieamartinez** [comment]
Thanks for your help
