### ISSUE TITLE
Unwanted blue triangle indicator on past commands

### ISSUE THREAD

**Issue by jannismain** [romkatv/zsh4humans#208]
Hey,

I switched over from ohmyzsh and the pure theme, because I was experiencing significant lag and your zsh setup is respectful of that. Great job and thank you for your great work. Your setup and configuration wizards are what I aspire to when implementing command line interfaces. :)

I'm having this strange bug (blue triangle at the left of the past commands) I was hoping you could help me figure out. It appeared in iTerm.app after setting up zsh4humans:
![2022-02-10 9 44 45 AM](https://user-images.githubusercontent.com/14290527/153371129-74abf31b-00f4-4b78-aaf0-149ada2dfd8b.gif)

In Terminal.app and VSCode's integrated Terminal, everything looks as it should:
![2022-02-10 9 54 37 AM](https://user-images.githubusercontent.com/14290527/153372184-cf4dec29-7600-44b1-895c-aa27e347feda.gif)

Maybe this is something that looks familiar to you? If not, feel free to close (as it seems to be related to my iTerm setup).

I followed your installation instructions for macOS and I'm using your recommended font (MesloLGS NF).

**Comment by romkatv** [comment]
See https://stackoverflow.com/a/41661660/1095235

**Comment by jannismain** [comment]
Ah, I see... iTerms configuration options are really extensive. I just wonder why they didn't show up with my previous zsh configuration, if this checkmark was always set 🤷🏻‍♂️ .

**Comment by romkatv** [comment]
Your previous configuration didn't enable terminal-shell integration. zsh4humans does. It's actually very useful. There are key shortcuts to navigate to the previous command and other goodies.

**Comment by jannismain** [comment]
There is so much more I can learn about the Terminal. Feels like stepping back in time a bit, but in all the good ways.

Thank you for your explanation!
