### ISSUE TITLE
History being removed/cleared

### ISSUE THREAD

**Issue by Syphdias** [romkatv/zsh4humans#21]
Hi, I carefully open this bug report since it might be my own fault.

I tried z4h in a docker container, played with it. I decided to copy the `.zshrc` to my maschine then but before I did that I moved `~/.zshrc` and `~/.zlogin` away. I didn't move `~/.zsh_history` aka my `HISTFILE`.
I think I did a `exec zsh` then.

I would have liked to reproduce it but I am not sure how to wipe z4h.

PS: I still have terminal open so I can probably easily restore my history (maybe even with timestamps).

**Comment by romkatv** [comment]
> I would have liked to reproduce it but I am not sure how to wipe z4h.

All configs are in `$ZDOTDIR` and all state is in `$Z4H`. If you remove `$ZDOTDIR/.zshrc` and `$Z4H`, everything will be gone.

Please do try to reproduce this. At this point I've no idea what might have happened so that your history got deleted.

By the way, what do you mean by history being deleted/cleared? Is some file gone? Is some file truncated? Is history within zsh (`fc`) empty?

**Comment by Syphdias** [comment]
> By the way, what do you mean by history being deleted/cleared? Is some file gone? Is some file truncated? Is history within zsh (`fc`) empty?

```
❯ head -2 ~/.zsh_history
: 1589644250:0;echo foo
: 1589644273:0;ls ~/.p*
```

Let's see if I can reproduce it

**Comment by romkatv** [comment]
Another by the way. Do you store your history in a git repo? If not, I highly recommend it. I store history from each machine in a separate file, all files in the same repo, and I load history from all files. History from local host is loaded last. See https://github.com/romkatv/dotfiles-public/blob/master/dotfiles/history.zsh. This works well.

**Comment by romkatv** [comment]
Are you sure your history used to be stored in the same file?

**Comment by Syphdias** [comment]
> Are you sure your history used to be stored in the same file?

:facepalm: no comment

**Comment by Syphdias** [comment]
My past self is a monster:
```
❯ head -1 ~/.histfile
: 1571779000:0;bind -e
```

How do you keep the histroy repo up to date?

**Comment by romkatv** [comment]
> My past self is a monster:

Have you seen your avatar? I wouldn't expect anything less.

> How do you keep the histroy repo up to date?

I have two git repos where I store my stuff: dotfiles-public and dotfiles-private. Both are overlaid over `$HOME`, so I can version any file without moving it. I sync with this: https://github.com/romkatv/dotfiles-public/blob/master/dotfiles/functions/sync-dotfiles. The point of using a separate file for history on every machine is twofold. The first reason is that it gives local history precedence (it's loaded last). The second reason is that it avoids merge conflicts (every history files is modified only on one machine, so no conflicts when pulling).

My goal is to move to z4h, so I'll need to add this functionality in there. Now I can run z4h without safety measures such as VMs and containers (I review all code changes in all dependencies) but I still cannot replace my normal dotfiles with it due to the lack extended history support. It'll come eventually.

**Comment by romkatv** [comment]
There are two more important bits to my dotfiles management.

This: https://github.com/romkatv/dotfiles-public/blob/ae571837d2ab612397411608fa931bc89bb7e23a/.zshrc#L135-L145

And this: https://github.com/romkatv/dotfiles-public/blob/078e578482fbaa48bdc191333e55e571a0e3d9a0/dotfiles/bindings.zsh#L122-L139

The latter is a zle widget bound to <kbd>Ctrl-P</kbd>. When I press it once, I get `public` showing up in prompt and Git status corresponds to dotfiles-public repo. All `git` commands also target this repo. So if I'm in `~/foo/bar` and want to add `./baz` to dotfiles-public, I hit `Ctrl-P` and type `git add baz`, etc. If I hit `Ctrl-P` another time, I switch to dotfiles-private. Another `Ctrl-P` gets me to normal state.

This is probably not easy to understand but it's *very* convenient. It's much better than anything else I've tried.

**Comment by Syphdias** [comment]
I use bare repos for my dotfiles as well and I love it. (I think you recommended it)
Have an alias for each one and an alias to do actions on all of them (simple loop). But I think you had some magic to just use git in `~` and switch via keybind or command.

**Comment by Syphdias** [comment]
> This is probably not easy to understand but it's _very_ convenient. It's much better than anything else I've tried.

Yes, this is what I meant!

**Comment by romkatv** [comment]
> I use bare repos for my dotfiles as well and I love it. (I think you recommended it)
> Have an alias for each one and an alias to do actions on all of them (simple loop). But I think you had some magic to just use git in `~` and switch via keybind or command.

Right. And I don't use bare repos anymore (but still use "overlaid" repo over `$HOME`). The reason is that `gitstatusd` doesn't support bare repos, so it cannot show their sate in prompt. There is no advantage to choosing bare repos as far as I know, so I'm not losing anything.

**Comment by Syphdias** [comment]
> There is no advantage to choosing bare repos as far as I know, so I'm not losing anything.

Only if there is no `gitstatusd` to keep your prompt in check if it tries to find out about the status I gues :smile:.

**Comment by Syphdias** [comment]
Little heads up, I got to run now but later or tomorrow I'll open a help or discussion issue after I fully migrated to z4h. I'm gathering some questions how to approach some stuff and I'm not sure if the prompt eating issues I have with fzf tab completion is a zsh, fzf or p10k issue...

**Comment by romkatv** [comment]
Sorry, I couldn't parse your last comment.

When gitstatus opens a repo, it check if it's bare. If it is, it simply ignores. It replies with `no-repo`. It doesn't get confused, it simply refused to work with bare repos. I did this because handling bare repos requires extra code and I don't want to write it unless someone will benefit. No one ever asked "why no prompt for bare repos", so it was a good call to save effort.

When this limitation affected *me*, I could either add extra code to gitstatus or convert my bare repo to non-bare. The latter was much easier and didn't seem to have any disadvantages, so I went with it.

**Comment by romkatv** [comment]
> later or tomorrow I'll open a help or discussion issue

Looking forward to it! I really appreciate your feedback. Without it p10k wouldn't be nearly as useful. Fingers crossed z4h will achieve comparable level of impact.

**Comment by Syphdias** [comment]
> When gitstatus opens a repo, it check if it's bare. If it is, it simply ignores. It replies with `no-repo`. It doesn't get confused, it simply refused to work with bare repos. I did this because handling bare repos requires extra code and I don't want to write it unless someone will benefit. No one ever asked "why no prompt for bare repos", so it was a good call to save effort.

Maybe I got the "bare" part wrong. I didn't mean the place where the git dir went; i never go there anyway.  I use it via this alias_ `dotpublic='/usr/bin/git --git-dir="${XDG_CONFIG_HOME:-${HOME}/.config}/dotgit/public/" --work-tree="${HOME}"'`
If I got this right there is no way to tell that part of my `$HOME` is actually managed by git since the git dir is tugged away, so no git status is displayed in the prompt.

What I meant with "keeping prompt in check" was: If you just do a `git init` (not bare) in `$HOME` with hundreds of files and every prompt render it tried to get a new git status it might take a while to show up while being in `$HOME`. Unless you use `gitstatusd`, of course.

**Comment by romkatv** [comment]
What does `dotpublic --get core.bare` say? That's what I mean by "bare".

You can see how I set up my dotfiles repo in here: https://github.com/romkatv/dotfiles-public/blob/master/bin/bootstrap-dotfiles.sh. Note `status.showuntrackedfiles no`.

Switching to a non-bare repo doesn't require any changes to what you store on github. You only need to change your local clone. After that you can keep using your local clone the same way as before, with that alias. In addition, you'll be able to display the status of that repo in prompt. See this binding: https://github.com/romkatv/dotfiles-public/blob/078e578482fbaa48bdc191333e55e571a0e3d9a0/dotfiles/bindings.zsh#L122-L139. It's very simple. No rocket science there.

**Comment by Syphdias** [comment]
I'm making the case that you are in fact using bare repositories (while lying to your git).

For me "bare" means "no working directory" unless you specify one (at least that is how I understand it).
This means everything that is usually in `/.git` will be in the `GIT_DIR`. This is exactly the same for your and my setup. You will also find the git config file at `~/.dotfiles-public/config` I reckon. Or do you have two working trees?
The `core.bare` config  – which does yield `true` for me – seems arbitrary and only to disable commands like `git add` while being in the bare directory. You set it to `false`, but I don't see why (besides `gitstatusd` ignoring it, if you don't).

What I didn't know is, that you could set `GIT_DIR` and `GIT_WORK_TREE` as environment variables. This makes it easy indeed to switch and ditch my aliases.

**Comment by romkatv** [comment]
> I'm making the case that you are in fact using bare repositories

`git config` disagrees.

>  (while lying to your git).

I don't think I do. If anything, your setup is more unusual. Your dotfiles repo is bare but has a working tree. Normally bare repositories don't have working trees.

My repo is a normal repo in every sense except that its gitdir is not at its usual place. I want this repo to be as usual as possible, so I don't make it bare.

**Comment by Syphdias** [comment]
> Normally bare repositories don't have working trees.

I can still use `git add` etc. so while I have a working tree git doesn't treat it as bare, or it wouldn't let me add. The `core.bare=true` has no effect on me; besides preventing me from stupidity while in the git dir. So yes you could argue I am not using a bare repo.

> so I don't make it bare.

By your definition (having a working tree). It couldn't be bare since you obviously have a working tree. :wink:

I guess it comes down to the opinion who is lying to his git :smile:

**Comment by romkatv** [comment]
> By your definition

My definition of bare is the same as git's. I don't invent new definitions. My repo is not bare, yours is.

My point is that it's better to not make it bare.

**Comment by Syphdias** [comment]
Agree to disagree I guess :wink:

**Comment by romkatv** [comment]
> Agree to disagree I guess 😉

I'm confused by this discussion to be honest. I'm not interested in arguments about definitions of words, I just use whatever gets the meaning across. Do you disagree that a non-bare repo is better? If so, why?

A non-bare repo can have its status shows in p10k prompt. This is an advantage. I'm not aware of any disadvantages, so I conclude that a non-bare repo is better. Does it make sense?

(I use the word "bare" to mean `core.bare = true`.)

**Comment by Syphdias** [comment]
> A non-bare repo can have its status shows in p10k prompt. This is an advantage. I'm not aware of any disadvantages, so I conclude that a non-bare repo is better. Does it make sense?

In the sense that this is the status quo, yes. But that's a disadvantage you built yourself for not reason if they have to disadvantages or what am I missing? You probably had a reason to make it ignore bare repos.

**Comment by romkatv** [comment]
> You probably had a reason to make it ignore bare repos.

Less code. Supporting bare repos requires time investment.

Also, it doesn't make sense to me to create a repo bare and then revert everything that actually differentiates bare repos from their regular counterparts. Bare repos are meant for sharing code, so they don't have work trees or default remotes. But we need both, so we add them. If you want a regular repo (work tree, default remote and no sharing), why create a bare repo?

I originally created a bare repo because I was following a guide that was either outdated or was written by someone who didn't know what bare repos are and what they are for.

> In the sense that this is the status quo, yes.

This makes sense. If the advantages of a non-bare repo don't outweigh the cost of switching, it's rational to keep using a bare repo. Your repo is already set up to behave like non-bare in almost every way. If you don't need to display its status in p10k prompt, and don't care that other tools based on libgit2 won't work for it, then there is no difference.

**Comment by romkatv** [comment]
You mentioned a few times that `git add` works differently in bare and non-bare repos. What did you mean? I'm not aware of any difference.

**Comment by Syphdias** [comment]
I suppose we followed the same guide and it just didn't click for me to ignore the bare part. I did have to setup tracking manually, indeed the first time. This is probably the main reason bare sucks.

> You mentioned a few times that `git add` works differently in bare and non-bare repos.

I took this from the [docs](https://git-scm.com/docs/git-config#Documentation/git-config.txt-corebare) but I can only see a difference if I have `core.bare = true` and `core.worktree = $something` (would make sense to set `core.worktree` in the boostrapping process and eliminate the need for `GIT_WORK_TREE`). With a `GIT_WORK_TREE` set it does not prevent adding files. If you don't even have a work tree set, adding will not work no matter what.

Can I try a new phasing for what I thing about the "bare" repository? Cloning or initializing a repository as "bare" means certain things are setup differently. You get a config flag, no working directory by default, no remote tracking, no branch set up and no reflog.

Which can make it quite a pain to use normally, I understand now. I had totally forgotten about the manual branch setup...

I looked at the different config files for different clone methods:
![image](https://user-images.githubusercontent.com/16988672/82241820-1570f300-993d-11ea-8022-fba95162c344.png)

I believe you could also use `--separate-git-dir` to lose some [bootstrapping](
https://github.com/romkatv/dotfiles-public/blob/b5b8dbc/bin/bootstrap-dotfiles.sh#L22-L30)].

**Comment by Syphdias** [comment]
> I believe you could also use `--separate-git-dir` to lose some [bootstrapping](https://github.com/romkatv/dotfiles-public/blob/b5b8dbc/bin/bootstrap-dotfiles.sh#L22-L30).

Seems not to work since the directory is unlikely to be empty...

**Comment by romkatv** [comment]
> Can I try a new phasing for what I thing about the "bare" repository?

Right, "bare" is an overloaded term. Informally git users usually use this word to refer to repositories without working trees. Neither your nor mine dotfiles repository is bare in this sense. There is also `core.bare` config option and `--bare` flag in different `git` commands. These are different things.

`core.bare` doesn't do anything useful for a dotfiles repo. If you care about gitstatus, it does some harm. That's all I wanted to say.
