### ISSUE TITLE
Weird interactions with vscode

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#210]
I realise this one will likely fall under the "won't fix" category (and possibly "can't fix"), but thought it might still be useful to document this behaviour, especially if it by chance is easy to fix.

When reloading a VS Code workbench that previously had a terminal open I sometimes end up getting error popups along the lines of: "The terminal process failed to launch: Starting directory (cwd) "/tmp/z4h-tmux-cwd-1000-2110924-.dev.pts.12" does not exist."

Presumably VS Code tries to relaunch a terminal in the working directory of tmux for whatever reason. This is particularly weird as I have `zstyle ':z4h:' propagate-cwd yes`. I have not tested changing that option.

Even when VS Code manages to relaunch the terminal (when the tmux directory has not been removed by a reboot perhaps?), the working directory is set to `~`, not properly restored.

**Comment by romkatv** [comment]
> Presumably VS Code tries to relaunch a terminal in the working directory of tmux for whatever reason.

Correct. This behavior makes sense.

> This is particularly weird as I have `zstyle ':z4h:' propagate-cwd yes`.

That's expected.

> I have not tested changing that option.

If you flip this option, the error message will disappear but the working directory after reloading a workbench will be the home directory.

Closing as Won't Fix.

**Comment by romkatv** [comment]
> If you flip this option, the error message will disappear but the working directory after reloading a workbench will be the home directory.

This isn't as bad as it sounds because you can press <kbd>Alt-Left</kbd> to go back to the previous directory. Might be good enough.

**Comment by VorpalBlade** [comment]
Thanks for the suggestions. `zstyle ':z4h:' propagate-cwd yes.` is really nice in that opening extra tabs in for example konsole or gnome-terminal does the expected thing. Maybe I can detect if I'm in vscode and turn that style off in that case.

**Comment by romkatv** [comment]
This should do it:

```zsh
if [[ $TERM_PROGRAM != vscode ]]; then
  zstyle ':z4h:' propagate-cwd yes
fi
```
