### ISSUE TITLE
Question: When is the capital version of `DIRSTACK` ever set?

### ISSUE THREAD

**Issue by lmburns** [romkatv/zsh4humans#213]
Reference here: https://github.com/romkatv/zsh4humans/blob/75033df71c61ad2087c84ca4554d31a3b55bddca/fn/-z4h-update-dir-history#L27

I was just combing through the code and noticed this. I looked through the rest of your code and never saw it being set. Also, I couldn't find anything in the `zsh` manual besides the array `dirstack` and `DIRSTACKSIZE`.

**Comment by romkatv** [comment]
Thanks for reporting this bug. Fixed.

**Comment by lmburns** [comment]
Closing due to it being fixed.
