### ISSUE TITLE
Top of terminal

### ISSUE THREAD

**Issue by Martin-2019** [romkatv/zsh4humans#214]
Dear Maintainer!

Please provide information in a way that is accessible to a non-IT person on how to place the command line at the top of the Terminal window. In my case, it is the system terminal in OS X.

**Comment by romkatv** [comment]
```zsh
zstyle ':z4h:' prompt-at-bottom 'no'
```

**Comment by Martin-2019** [comment]
Thank you - that solves the problem.

Great software - I wish You continued success.

M.

**Comment by romkatv** [comment]
I'm glad it helped.

The default is better though. Now you'll have prompt at random places instead of always having it in a fixed spot.
