### ISSUE TITLE
Single tab to accept auto-suggestion / double tab to bring fzf

### ISSUE THREAD

**Issue by Quentin-M** [romkatv/zsh4humans#215]
Dear zsh4humans community,

I have been used for years to have a single TAB auto-complete / accept the current suggestion, and double TAB to present the other choices. The current behavior of zsh4humans's setup is to auto-complete with any cursor moving action (e.g. right arrow), and bring other options (with fzf) with a single TAB press.

I am absolutely noob when it comes to the zsh world and don't expect to be able to sort it out quickly.. Would anyone happen to know could we make a single TAB accept (aka `zstyle ':z4h:autosuggestions' tab-char 'accept'
`) while keeping the fzf suggestion behavior with double TAB (instead of one)? `bindkey '\t' autosuggest-accept` obviously doesn't cut it as it will autocomplete with TAB but completely remove the fzf bevavior.

Thanks all!

**Comment by romkatv** [comment]
Autosuggestions are not the same as completions. From https://github.com/romkatv/zsh4humans/blob/master/README.md:

> ![Zsh for Humans](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-highlight.png)
> 
> Everything within the highlighted areas on the screenshot is *prompt*. It is produced by
> [Powerlevel10k](https://github.com/romkatv/powerlevel10k). See
> [Customizing prompt](#customizing-prompt).
> 
> The listing of files produced by `ls` command is colored by `ls` itself. Different commands have
> different ways of customizing their output, and even different version of `ls` have different flags
> and environment variables related to colors. Zsh for Humans enables colored output for common
> commands such as `ls` and `grep`. For further customization consult documentation of the respective
> command.
> 
> `echo hello` is the current command being typed. Syntax highlighting for it is provided by
> [zsh-syntax-highlighting](https://github.com/zsh-users/zsh-syntax-highlighting). See its homepage
> for documentation on how to customize it.
> 
> After `echo hello` you can see `world` in grey. This is not a part of the command, so pressing
> <kbd>Enter</kbd> will print only `hello` but not `world`. The latter is an autosuggestion provided
> by [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions) that you can
> [accept](#accepting-autosuggestions) in part or in full. It comes from command history and it's a
> great productivity booster. See [zsh-autosuggestions](
>   https://github.com/zsh-users/zsh-autosuggestions) homepage for more information.

Autosuggestions are accepted by moving the cursor up to the point of what you want to accept. So, moving the cursor by one word will accept one word, etc.

zsh4humans doesn't support what you are asking and it's not something I'm eager to implement.
