### ISSUE TITLE
Portable Z4H questions

### ISSUE THREAD

**Issue by arrrgi** [romkatv/zsh4humans#216]
In #191 you mention just 3 files are needed for Z4H. I'm interested too in having a portable and non-interactive installation as part of my own dotfiles repo, thus I have a couple of questions I hope you don't mind fielding:

- I'd like to put these files into $ZDOTDIR (for me this will be in **$XDG_CONFIG_HOME/zsh**), will this break Z4H?
- With just these three files, does Z4H still `git clone` the rest of it's dependencies from OMZ, powerlevel10k and zsh-users repos?

**Comment by romkatv** [comment]
> * I'd like to put these files into $ZDOTDIR (for me this will be in **$XDG_CONFIG_HOME/zsh**), will this break Z4H?

It'll work as long as you manage to set `ZDOTDIR` early enough.

> * With just these three files, does Z4H still `git clone` the rest of it's dependencies from OMZ, powerlevel10k and zsh-users repos?

Yes.

**Comment by arrrgi** [comment]
Thanks, will definitely test that out and report back.

Besides having options to keep itself updated (I noted options to enable/disable this and set a check period), does this keep the other plugins updated too?

**Comment by romkatv** [comment]
This might be relevant: https://gist.github.com/romkatv/ecce772ce46b36262dc2e702ea15df9f

**Comment by arrrgi** [comment]
Fixed. Added `export TERM=xterm-256color` to ~/.config/zsh/.zshenv

**Comment by arrrgi** [comment]
> That's a workaround at best. It's always a bad idea to define `TERM` in rc files. Never do that.

Consider me still as a learner. I know this should normally be sent by whatever terminal emulator I'm using (iTerm 2), but this doesn't seem to be passed on to Tmux. What would be the better way to resolve this if not defining this somewhere in an RC file?

**Comment by romkatv** [comment]
That's right, `TERM` is set by the terminal to let programs know which language the terminal speaks. You have two terminals -- iTerm2 and tmux -- that speak different languages.

My guess is that without the hack your `TERM` is `screen`. This is a valid `TERM` value under tmux, and `xterm-256color` is not. By invalid I mean that `tmux` does NOT speak the language of `xterm-256color`, so by setting `TERM` to this value programs will talk to tmux in a language it does not understand.

There is more than one `TERM` value that's valid for tmux. `screen-256color` is a good one. You can tell `tmux` to use that by adding this line to `~/.tmux.conf`:

```text
set -g default-terminal "screen-256color"
```

Whatever you do, don't set `TERM` in shell rc files. Terminal tells shell which language the terminal speaks, not the other way around. Shell *cannot* tell the terminal which language to speak.

**Comment by romkatv** [comment]
Closing as resolved.

**Comment by arrrgi** [comment]
Thanks, appreciate the tips. Happy this is resolved.
