### ISSUE TITLE
[Question] How to customize z4h to match substring in commands?

### ISSUE THREAD

**Issue by fredguth** [romkatv/zsh4humans#219]
I have a folder `~/1_Projects` and when I try `cd Proj<TAB>` it is not found.  When I just try `Proj<TAB>` it is not matched either. 
I also have a folder `~/Code`. If I try `Co` it matches (showing `de` in gray and I can select with right arrow), but `ode` does not nor `ode<Tab>`.  The match only happens with the beginning of the folder name. 

Is it possible to match with substring?

**Comment by romkatv** [comment]
It's a valid use case but zsh4humans doesn't support it.

**Comment by fredguth** [comment]
Ok Thanks!
