### ISSUE TITLE
How to use starship instead of p10k for prompt?

### ISSUE THREAD

**Issue by sandangel** [romkatv/zsh4humans#222]
Hi, is it possible to disable p10k and use starship instead?

**Comment by romkatv** [comment]
You can achieve it with a bit of hacking but this isn't officially supported.

Could you share why you want to do this? Powerlevel10k can do everything that Starship does and it's a lot faster.

**Comment by sandangel** [comment]
I already have starship config that supports nix-shell, kubecontext, direnv... I don't have all of that configs in p10k. I enabled those components in config file but the color looks odd (I use pure). I managed to change colors for the `time`, but others doesn't match my terminal colors (like nix-shell in the pic).

<img width="346" alt="image" src="https://user-images.githubusercontent.com/22189661/173175686-3efed83f-6421-46e5-81af-ac7c04ea1891.png">

**Comment by romkatv** [comment]
Thanks for the additional details.

Pure style is for those who are used to https://github.com/sindresorhus/pure. If you aren't one of those, try Lean style instead -- it's superior in every way. If you choose the 256-color version, you'll see the same colors as [here](https://raw.githubusercontent.com/romkatv/powerlevel10k-media/master/prompt-styles-high-contrast.png). With the 8-color version colors will come from your terminal (if you want to customize them, change color scheme/palette in the terminal settings). Lean style enables nix-shell, kubecontext and direnv by default, so you won't need to enable them manually.

**Comment by sandangel** [comment]
oh nice. let me try that.

**Comment by sandangel** [comment]
perfect. thanks a lot for your help. I think I like using p10k now. Brilliant!

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/22189661/173176254-b38e5de7-1e20-4774-9f7e-41a21f2c3bd0.png">

**Comment by romkatv** [comment]
Great!

If you are wondering why kubernetes context doesn't get shown, see https://github.com/romkatv/powerlevel10k#show-on-command.

**Comment by sandangel** [comment]
Awesome!!

thanks a lot for your help. I was afraid to use z4h because I saw not too much support can be provided in the README. But I really appreciate when you can spend some time to reply to my issue. Have a nice day. 🥰

**Comment by kakulukia** [comment]
For anyone thats still wondering how to get starship working .. no hacking needed:

    ZSH_PROMPT_STYLE=starship  # comment to use powerlevel10k
    if [[ $ZSH_PROMPT_STYLE == "starship" && $+commands[starship] ]]; then
      # Disable z4h prompt (P10K)
      zstyle ':z4h:powerlevel10k' channel none
    fi

    ...
    z4h init || return
    ...

    # Check if starship is installed
    if [[ $ZSH_PROMPT_STYLE == "starship" && $+commands[starship] ]]; then
      # Check if cache file exists
      if [[ ! -f ~/.cache/starship-init.zsh ]]; then
        echo "Creating Starship init cache..."
        mkdir -p ~/.cache
        starship init zsh > ~/.cache/starship-init.zsh
      fi

      # Load cached initialization with z4h
      z4h source -c -- ~/.cache/starship-init.zsh
    fi

Maybe i get powerlevel customised in the same way, but its hard and for now this snippet works well.
Its an extra 6ms for startup time (according to hyperfine) and thats fine with me.
