### ISSUE TITLE
prompt-at-bottom doesn't work that well on guake and yakuake dropdown terminals

### ISSUE THREAD

**Issue by shawarden** [romkatv/zsh4humans#229]
Would it be feasable to allow a manually set or minimum terminal size for `prompt-at-bottom`?

Likely due to how `guake` and `yakuake` operate, enabling `prompt-at-bottom` has messy results: The prompt starts half-way down the screen. This is not unique to z4h's `prompt-at-bottom` as `tput line` and `stty size`, both report this incorrectly.

Having a `zstyle ':z4h:' prompt-at-bottom 'yes'` would try to do it automatically.
Having `zstyle ':z4h:' prompt-at-bottom '54'` could try to do it automatically only if the number of lines it detects is more than 54?

You can detect `guake` with `[ ! -z $GUAKE_TAB_UUID]` but `tmux` screws with your process parentage so figuring out if you're in a `yakuake` session will need to be done before you spawn a `tmux` session... Assuming you really want to use both `*uake` and `tmux`

**Comment by romkatv** [comment]
> Having a `zstyle ':z4h:' prompt-at-bottom 'yes'` would try to do it automatically. Having `zstyle ':z4h:' prompt-at-bottom '54'` could try to do it automatically only if the number of lines it detects is more than 54?

You can try this:

```zsh
if (( LINES > 54 )); then
  zstyle ...
else
  zstyle ...
fi
```

Also see https://github.com/romkatv/zsh4humans/issues/135#issuecomment-907607824 and comments below.

> You can detect `guake` with `[ ! -z $GUAKE_TAB_UUID]` but `tmux` screws with your process parentage so figuring out if you're in a `yakuake` session will need to be done before you spawn a `tmux` session...

I added `GUAKE_TAB_UUID` to the list of environment variables that get propagated through tmux. If you run `z4h update`, close all terminals and open a new one, you should see it getting through.
