### ISSUE TITLE
[Discussion/Help/Bugs?] Some Impressions from the first days of using z4h

### ISSUE THREAD

**Issue by Syphdias** [romkatv/zsh4humans#23]
## Preamble
I switched from omz, so some things that I expect might be opinionated towards the way omz did it. This will probably lean between disagreement, searching for help to configure z4h correctly for myself and some bug reports.

## Unexpected defaults
* <kbd>ctrl-r</kbd>: not cycling through history (and <kbd>ctrl-s</kbd> to reverse it)
  I expected `export FZF_CTRL_R_COMMAND='--bind ctrl-r:up --bind ctrl-s:down'` to introduce this behavior but it didn't.
* in completion menu: <kbd>tab</kbd> not for cycling through the results threw me off hard and combined with the prompt eating (see below) it was quite painful to use.

## Possible Bugs in z4h, zsh or a used plugin
* `z4h-up-global-history`: If I understand this correctly this should work:
```
❯ echo foo
foo
❯ zsh
❯ echo bar
bar
❯ exit
❯ <alt-x>
execute: z4h-up-global-history<enter>
```
  I would expect this to yield `exit` but it goes to `zsh`
  I also wondered why `INC_APPEND_HISTORY` wasn't set which sounds like a good idea?
* tab completion was really buggy for me until I switched off the accept on tab. It regularly ate the prompt line leaving me guessing what the command even was. I thought switching it off solved that since I wasn't planing on sticking with that behavior anyway. But I still have eaten prompt syndome:
```
docker run -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec 'sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v2/install)"'
[setup stuff, mostly 1, twi line prompt, no transient prompt]
~                                                                                      root@1313e4dc2cad
❯ sed -i "/fzf-tab/d" ~/.zshrc && exec zsh
~                                                                                      root@1313e4dc2cad
❯ ls /<tab>etc/
```
![image](https://user-images.githubusercontent.com/16988672/82147922-5ee41400-9851-11ea-93c2-c1b007c38f24.png)

## (Feature) Wishes
* The completion menu I used to use also had a horizontal axis, `fzf` only seems to have vertical entries. Any way to make more use of the available space to the right?
* I use [this](https://www.zsh.org/mla/users/2015/msg00652.html) to make the undo (<kbd>ctlr-_</kbd>) also bring back interrupted prompts (<kbd>ctrl-c</kbd>). It feels natural (to me) and might be a nice addition.
I dirtily patched it to the `zle-line-init` function so I wouldn't lose other functionality.
```
functions[zle-line-init]="
    $functions[zle-line-init]
    after_zle-line-init
```

PS: Jeez, there are some [useless](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/history/history.plugin.zsh) plugins...

**Comment by romkatv** [comment]
What terminal do you use and what is the output of `typeset -p TERM`?

**Comment by Syphdias** [comment]
tilix
```
❯ typeset -p TERM
export TERM=xterm-256color
```

**Comment by Syphdias** [comment]
For the tab prompt eating: https://asciinema.org/a/D3Y6L52vpqrlmKu8r95wCG8Wp

**Comment by romkatv** [comment]
Thanks for the bug report and feedback. I'll get to it a bit later. Swamped.

**Comment by Syphdias** [comment]
Take your time :smile:

**Comment by pkazmier** [comment]
I, too, did not care for FZF, so I bound `TAB` back to standard zsh behavior. I also prefer fish-style history search over the default FZF fuzzy search, so I install `zsh-history-substring-search.zsh`, which allows me to type part of a command, then press up/down arrow. I actually bind to `^P`/`^N`, so hands don’t have to off keyboard—arrow keys are for weaklings 😄.
```
z4h clone zsh-users/zsh-history-substring-search
...
z4h init || return
z4h source $Z4H/zsh-users/zsh-history-substring-search/zsh-history-substring-search.zsh
...
bindkey -M emacs '^I' expand-or-complete
bindkey -M emacs '^H' backward-kill-word # ctrl-h and ctrl-backspace: delete previous word
bindkey -M emacs '^P' history-substring-search-up
bindkey -M emacs '^N' history-substring-search-down
bindkey -M emacs '^ ' z4h-cd-back
bindkey -M emacs '^[ ' z4h-cd-forward
```

**Comment by romkatv** [comment]
Thanks for sharing. This is a useful customization.

**Comment by romkatv** [comment]
@Syphdias Thanks a lot for filing this issue.

> * ctrl-r: not cycling through history (and ctrl-s to reverse it)

Noted. I'll expose key bindings for `z4h-fzf-history` and other widgets based on `fzf` in some way.

> * in completion menu: tab not for cycling through the results threw me off hard

This is sort of expected.

I've placed all settings that can be surprising directly into `~/.zshrc`. Eventually all of these will be folded into the interactive installation wizard similar to p10k wizard but for now you need to go through `~/.zshrc` and edit it. It's fairly small and well documented.

By the way, continous trigger on <kbd>Tab</kbd> works really well if you can change your muscle memory.

> * `z4h-up-global-history`: If I understand this correctly this should work [...]:

Share history is read when you hit `ENTER` and before the typed command is executed (if any). So if you hit `ENTER`, shared history will be up to date but otherwise it can be missing the latest events. That's just how zsh works and there is no work around that I'm aware of.

> I also wondered why `INC_APPEND_HISTORY` wasn't set which sounds like a good idea?

It sets `SHARE_HISTORY` instead. It's better.

> * tab completion was really buggy for me [...]. It regularly ate the prompt line

Sent https://github.com/Aloxaf/fzf-tab/pull/87.

> The completion menu I used to use also had a horizontal axis, `fzf` only seems to have vertical entries. Any way to make more use of the available space to the right?

Not that I know of. It might be one of those things that you'll prefer if you get used to it. Scanning a single column is something humans can do very efficiently. It's also consistent. Try `git <TAB>` and `git clone --<TAB>`. It makes sense for these to be single-column. Consistency calls for everything else to be single column.

Eventually there will be more than one option for completion UI in zsh4humans. At the very least there will be "classic" zsh completion. It's primarily for folks who don't want to change habbits. New users can be much better served by fzf widgets. They are incomparably better.

> * I use [this](https://www.zsh.org/mla/users/2015/msg00652.html) to make the undo (ctlr-_) also bring back interrupted prompts (ctrl-c). It feels natural (to me) and might be a nice addition.

I don't want to encourage users to press <kbd>Ctrl-C</kbd>. It can cause hard-to-debug issues when you interrupt zsh code.

I think there are two use cases where zsh users hit <kbd>Ctrl-C</kbd> while editing the command line:

1. To clear the command line. There is <kbd>Alt-J</kbd> for it. Try it, it looks much cleaner than <kbd>Ctrl-C</kbd>.
2. To "stash" the command line. E.g., sometimes you type a long command and before you execute it you realize you need to run another command. There is a built-in widget in zle for it but I don't like it. I'll add another one that visually looks the same as <kbd>Alt-J</kbd> (clear buffer) but also adds the command to history.

WDYT?

**Comment by romkatv** [comment]
> > * tab completion was really buggy for me [...]. It regularly ate the prompt line
> 
> Sent [Aloxaf/fzf-tab#87](https://github.com/Aloxaf/fzf-tab/pull/87).

This has been merged. To pick it up:

```zsh
z4h update
```

**Comment by Syphdias** [comment]
> It's fairly small and well documented.

Yes, I easily found it, indeed.

> By the way, continous trigger on Tab works really well if you can change your muscle memory.

Since you are right a lot of the times, I will give it a try again. :wink: But for people who'd like to return to the omz way:
```
z4h source $Z4H/ohmyzsh/ohmyzsh/lib/completion.zsh
zstyle ':completion:*' list-colors $LS_COLORS   # fix colors after omz completion
bindkey -M emacs '^I' expand-or-complete    # bind tab back to normal completion (from omz)
```
If fzf doesn't work for me I will come back to this.

> New users can be much better served by fzf widgets. They are incomparably better.

I can totally understand that.

> 1. To clear the command line. There is Alt-J for it. Try it, it looks much cleaner than Ctrl-C.

Interesting, this is undo-able, but it's not possible in bash. Hm, let's see if I can retrain myself.

> 2. To "stash" the command line. E.g., sometimes you type a long command and before you execute it you realize you need to run another command. There is a built-in widget in zle for it but I don't like it. I'll add another one that visually looks the same as Alt-J (clear buffer) but also adds the command to history.

Hm, to history seems a bit weird since it wasn't executed yet. Otherwise sounds great. It sounds like another copy buffer that you can control within the shell. Could also store multiple values and either pop them from the stack or rotate through them. My thought had a bit of a feature creep there...
No idea if it would be useful to anyone.

**Comment by Syphdias** [comment]
> Share history is read when you hit `ENTER` and before the typed command is executed (if any). So if you hit `ENTER`, shared history will be up to date but otherwise it can be missing the latest events. That's just how zsh works and there is no work around that I'm aware of.

Are you saying if I hit enter one more time after the `exit` I should see the exit? Is `z4h-up-global-history` the correct widget?
https://asciinema.org/a/XaPidSXOSuRQkD7nMgoKWnRdh

> > I also wondered why `INC_APPEND_HISTORY` wasn't set which sounds like a good idea?

> It sets `SHARE_HISTORY` instead. It's better.

Does it make sense to use both?

**Comment by romkatv** [comment]
> Are you saying if I hit enter one more time after the `exit` I should see the exit?

Yes, that's what *should* happen.

> Is `z4h-up-global-history` the correct widget?

Yes.

> https://asciinema.org/a/XaPidSXOSuRQkD7nMgoKWnRdh

Crap... Thanks for the report. fixed.

> Does it make sense to use both?

No. `SHARE_HISTORY` does everything that `INC_APPEND_HISTORY` does and more. From the docs:

> `SHARE_HISTORY <K>`
> 
> This option both imports new commands from the history file, and also causes your typed commands to be appended to the history file (the latter is like specifying `INC_APPEND_HISTORY`, which should be turned off if this option is in effect).

**Comment by romkatv** [comment]
By the way, you can use this command to quickly spawn a docker container with the latest version of z4h and your local `~/.p10k.zsh`:

```zsh
docker run -v ~/.p10k.zsh:/root/.p10k.zsh -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec '
  apk add zsh
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v2/install)"'
```

**Comment by romkatv** [comment]
> Hm, to history seems a bit weird since it wasn't executed yet.

A bit weird indeed. This command won't be persisted in `HISTFILE` though, so shouldn't be too confusing.

I've added it as `z4h-stash-buffer` with the default binding of <kbd>Alt-O</kbd>. Give it a try, see if you like it. I'll be using it myself instead of my custom clone of `pound-insert`.

**Comment by romkatv** [comment]
> <kbd>ctrl-r</kbd>: not cycling through history (and <kbd>ctrl-s</kbd> to reverse it)

I added bindings for <kbd>Ctrl-R</kbd> and <kbd>Ctrl-S</kbd> within `z4h-fzf-history`. They are equivalent to <kbd>Up</kbd> and <kbd>Down</kbd> respectively.

**Comment by Syphdias** [comment]
> the latter is like specifying `INC_APPEND_HISTORY`, which should be turned off if this option is in effect

I did look up the section in the man page. But sounds a bit like it has an effect, which confused me in to thinking it might have.

> By the way, you can use this command to quickly spawn a docker container with the latest version of z4h and your local `~/.p10k.zsh`:

I wanted to avoid any configurations I might have made in me `~/.p10k.zsh` even though I mainly do that in an `after-p10k-lean.zsh`.

> A bit weird indeed. This command won't be persisted in `HISTFILE` though, so shouldn't be too confusing.

Makes sense. I'll give it a try!

> I added bindings for Ctrl-R and Ctrl-S within `z4h-fzf-history`. They are equivalent to Up and Down respectively.

Thanks

**Comment by romkatv** [comment]
> I wanted to avoid any configurations I might have made in me `~/.p10k.zsh` even though I mainly do that in an `after-p10k-lean.zsh`.

For reproducing results something like this works well:

```zsh
docker run -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec '
  apk add zsh
  echo 'POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true' >~/.p10k.zsh
  sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v2/install)"'
```

And if you even need to inline a complex docker command, you can use this type of quoting:

```zsh
docker run -e TERM -e COLORTERM -w /root -it --rm alpine sh -uec "$(<<\END
  you can freely use $, single quotes or doubles quotes here
END
)"
```

**Comment by romkatv** [comment]
Has all feedback been addressed or did I miss something?

**Comment by Syphdias** [comment]
Yes, thank you, keep up the great work!
