### ISSUE TITLE
Problem with substring search when in vicmd

### ISSUE THREAD

**Issue by janlee** [romkatv/zsh4humans#230]
I have the following keybindings declared 

```
bindkey -M vicmd "^[[A" z4h-up-substring-local
bindkey -M vicmd "^[[B" z4h-down-substring-local
bindkey -M viins "^[[A" z4h-up-substring-local
bindkey -M viins "^[[B" z4h-down-substring-local

bindkey -M vicmd "k" z4h-up-substring-local
bindkey -M vicmd "j" z4h-down-substring-local
```

When I'm in `viins`, it's working great

https://user-images.githubusercontent.com/39638241/181844110-83f4ecb6-5dfb-4362-8c20-a964d7681dbd.mov

When I hit escape to enter `vicmd`, it doesn't appear to be working. The search doesn't seem correct and there is no highlighting.

https://user-images.githubusercontent.com/39638241/181844098-46125371-c84f-49d1-8ac7-cb938390c658.mov

**Comment by romkatv** [comment]
Thanks for reporting this bug. I've reproduced this. No ETA for fixing yet.

**Comment by romkatv** [comment]
Should be fixed now. I'd appreciate if you could run `z4h update` and verify. If you've already moved on, I'll understand if you'd rather not do it.
