### ISSUE TITLE
fzf ctrl+t keybinding is not set

### ISSUE THREAD

**Issue by francois-pasquier** [romkatv/zsh4humans#231]
Is there a proper way to enable this part of the `key-bindings.zsh` of fzf using zsh4humans?

```zsh
fzf-file-widget() {
  LBUFFER="${LBUFFER}$(__fsel)"
  local ret=$?
  zle reset-prompt
  return $ret
}
zle     -N   fzf-file-widget
bindkey '^T' fzf-file-widget
```

For the moment, I am using `source ~/.cache/zsh4humans/v5/fzf/shell/key-bindings.zsh`

**Comment by romkatv** [comment]
zsh4humans has a better alternative. See https://github.com/romkatv/zsh4humans/blob/master/tips.md#completions.

**Comment by francois-pasquier** [comment]
Oh my, I guess I skipped this part of the doc :(

Thank you, it fits my need totally!
