### ISSUE TITLE
TTY implementation (no X), using fbterm, additional characters

### ISSUE THREAD

**Issue by panv-00** [romkatv/zsh4humans#232]
Hi.
I am trying to use zsh4humans on a machine that i have no intention of installing Xorg or anything X.
Had some challenges with fonts, but i solved all by installing fbterm.
Using Meslo font, all icons and characters look awesome.
The only problem I am facing (and not sure if it is from oh-my-zsh) is that every command is echoed again.
and every prompt is preceded with 
33;A
or
33;B
or 
33;C

TTY reads all colors...

for example:
if I type "ls" in a directory having files a, b, and newfile
I get the below...

```
33;A> 33;Bls
33;C;;lsa  b  newfile
33;A
```

that's really weird...

I am attaching a video below..

https://user-images.githubusercontent.com/84442305/183129980-f6775324-9569-4b43-a7d1-5470b1e7b1fe.mp4

**Comment by romkatv** [comment]
Perhaps `TERM` or the corresponding terminfo don't match the terminal? Just a guess. Unfortunately I don't have the time to debug this. If you find out the reason, please post a comment.
