### ISSUE TITLE
Problem in vscode

### ISSUE THREAD

**Issue by LeonardoTrapani** [romkatv/zsh4humans#233]
Only when in vscode and I open the terminal, I get this error: 

```
z4h: core parameters have unexpectedly changed

Expected:

  ZDOTDIR=/Users/*******

Found:

  ZDOTDIR=/var/folders/0f/**************/T/vscode-zsh

Restore the parameters or restart Zsh with exec zsh.
```

**Comment by romkatv** [comment]
Looks like a bug in vscode's terminal integration. It shouldn't source user rc files with a modified `ZDOTDIR`.

**Comment by LeonardoTrapani** [comment]
> Looks like a bug in vscode's terminal integration. It shouldn't source user rc files with a modified `ZDOTDIR`.

Any way to fix this?

**Comment by romkatv** [comment]
That's a question for vscode devs.

**Comment by jayree** [comment]
@romkatv it looks like that the framework doesn't allow modifications to `ZDOTDIR`:

```zsh
  if (( _z4h_zle )); then
    typeset -gr _z4h_param_pat=$'ZDOTDIR=$ZDOTDIR\0Z4H=$Z4H\0Z4H_URL=$Z4H_URL'
    typeset -gr _z4h_param_sig=${(e)_z4h_param_pat}
    function -z4h-check-core-params() {
      [[ "${(e)_z4h_param_pat}" == "$_z4h_param_sig" ]] || {
        -z4h-error-param-changed
        return 1
      }
    }
  else
    function -z4h-check-core-params() {}
  fi
```

I've modified `_z4h_param_pat`  to get this to work: 
```zsh
typeset -gr _z4h_param_pat=$'Z4H=$Z4H\0Z4H_URL=$Z4H_URL'
```

**Comment by romkatv** [comment]
> @romkatv it looks like that the framework doesn't allow modifications to `ZDOTDIR`

That's not quite right. zsh4humans detects a bug in vscode where it exposes an incorrect value of `ZDOTDIR` to user rc files. Your change disables the detection of this bug but the bug itself remains.

**Comment by Lunchb0ne** [comment]
For anyone stumbling on this, vscode switches the user's ZDOTDIR to inject their terminal integration in your shell. As z4h already uses and has Final Term integration, which is supported in vscode if you have the following enabled in zshrc

```zsh
# ~/.zshrc
# Mark up shell's output with semantic information.
zstyle ':z4h:' term-shell-integration 'yes'
```

You can turn this integration off by searching for `shell integration` in vscode settings and disabling it or just add the following in the config json
```json
"terminal.integrated.shellIntegration.enabled": false
```

I haven't really noticed any diff with using their terminal integration script, but they do add some more features according to [their documentation](https://code.visualstudio.com/docs/terminal/shell-integration#_supported-escape-sequences) via `OSC 633` custom sequences.

If some feature is really needed, you can manually source their integration script as instructed on [their docs](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation).

So just grab their integration's script path by running `code --locate-shell-integration-path zsh` and then adding the following to your zsh config when you load external plugins.
```zsh
# Load VSCODE's integration if we are running in a VSCODE environment.
export ZDOTDIR_CP="$ZDOTDIR" # copy the zdotdir path
[[ "$TERM_PROGRAM" == "vscode" ]] && source "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh"
export ZDOTDIR="$ZDOTDIR_CP" # restore the zdotdir path
unset ZDOTDIR_CP             # remove the copy
```
(There might be a better way of doing this properly)

It might also be worthwhile to unset `$VSCODE_SHELL_INTEGRATION` var on initialization as that seems like the [recommended way (?)](https://code.visualstudio.com/docs/terminal/shell-integration#_when-does-automatic-injection-not-work) of forcing the integration off. Not sure if this goes against z4h fundamentals.

**Comment by romkatv** [comment]
It bears repeating that shell integration in VSCode has a bug that manifests itself in incorrect `ZDOTDIR` being set when user rc files are sources. It's fixable but I don't know if anyone has reported it.

**Comment by Lunchb0ne** [comment]
Yup, the bug was being tracked in https://github.com/microsoft/vscode/issues/157128.

As per https://github.com/microsoft/vscode/issues/157128#issuecomment-1227559325, the fix is out for insiders and should be in stable soon.

**Comment by romkatv** [comment]
@Lunchb0ne Thanks for the link!
