### ISSUE TITLE
Hang on opening new zsh instance with a "bad" directory in the dir history

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#234]
When you have a problematic directory (one that eventually times out on accessing it) in `~/.cache/zsh4humans/v5/stickycache/dir-history-1000` z4h will hang on opening a new zsh instance even if you are nowhere near that directory.

You may ask why a directory would time out, this almost always involves a network file system where the server has become inaccessible for whatever reason. This can happen with NFS or Samba. It can also happen due to Gnome or KDE fuse file systems when using those to access a network file system (eg `/run/user/1000/kio-fuse-*/smb/user@server-ip`, similar exists for Gnome gvfs). This typically happens when opening a terminal from within the file manager (Dolphin on KDE) while on a network share.

I would like a way to turn off the persistent directory history as it is not a feature I find particularly useful. Another option would be a `zstyle` to blacklist certain paths from entering the persistent cache (i.e. `/run/user/*/kio-fuse-* /run/user/*/gvfs/* /mnt/nfs/*`)

**Comment by romkatv** [comment]
What's the output of `df --output=fstype` for the problematic directories while they exist?

> When you have a problematic directory (one that eventually times out on accessing it)

How long does it take for it to time out?

> z4h will hang on opening a new zsh instance

Does it hang for good or only for as long as the timeout?

I'm just trying to explore options for fixing this that don't require user configuration. In the worst case I'll add a flag to disable persistent directory as you suggested but perhaps there is a better way.

**Comment by VorpalBlade** [comment]
> What's the output of df --output=fstype for the problematic directories while they exist?
I'll get back to you when I'm home and can replicate this again (should be this evening or tomorrow).

> How long does it take for it to time out?
Over a minute for sure until zsh gets unstuck from the KDE kio case, I'll get back with a time measurement if you want.

> Does it hang for good or only for as long as the timeout?
It does get unstuck again after the timeout. But again, this takes well over a minute.

**Comment by VorpalBlade** [comment]
>  What's the output of df --output=fstype for the problematic directories while they exist?

Here are some I have seen:
* `fuse.kio-fuse`
* `fuse.gvfsd-fuse`
* `fuse.sshfs` (hangs for much shorter than the others, only ~10 seconds)
*  `cifs` -- Note if this is inaccessible, `df` hangs, as does a lot of other commands such as `umount`.
*  `smb3` -- Note if this is inaccessible, `df` hangs, as does a lot of other commands such as `umount`.

I'm not set up to test nfs.

I have also noticed that many other things hangs, such as even typing in the path, it seems to hang as it is trying to do syntax highlighting and decide if the path should be underlined for it being a valid path. Presumably this is a feature of zsh-syntax-highlighting and should be reported separately to there.

**Comment by romkatv** [comment]
> * `cifs` -- Note if this is inaccessible, `df` hangs, as does a lot of other commands such as `umount`.
> * `smb3` -- Note if this is inaccessible, `df` hangs, as does a lot of other commands such as `umount`.

That's rough. I cannot think of a good automated solution that would handle this. Seems like disabling persistent dir history is the best option for you. You can do it like this:

```zsh
zstyle ':z4h:dir-history:' max-size 0
```

> I have also noticed that many other things hangs, such as even typing in the path, it seems to hang as it is trying to do syntax highlighting and decide if the path should be underlined for it being a valid path. Presumably this is a feature of zsh-syntax-highlighting and should be reported separately to there.

There is [ZSH_HIGHLIGHT_DIRS_BLACKLIST](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#parameters).

**Comment by VorpalBlade** [comment]
> There is [ZSH_HIGHLIGHT_DIRS_BLACKLIST](https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md#parameters).

Thanks, I already found that out separately after writing my previous post. That does help a bit.

> That's rough. I cannot think of a good automated solution that would handle this. 

An option similar to `ZSH_HIGHLIGHT_DIRS_BLACKLIST` for Z4H purposes could perhaps work here.

As for umount hanging etc, there seem to be some mount options that could help `echo_interval=n` for cifs/smb3 for example. From what I can read, NFS will have similar behaviour, but be more complicated to set up for sensible timeouts (`-o soft,timeo=20` though apparently using `soft` might cause data corruption on NFS. I have not had time to test any of this yet, and I normally use the KDE kio approach for remote file systems anyway.

**Comment by romkatv** [comment]
> ```shell
> zstyle ':z4h:dir-history:' max-size 0
> ```

Is this ☝️ good enough for you? I'd rather not add a new option if an existing option solves your use case.

**Comment by VorpalBlade** [comment]
> Is this point_up good enough for you? I'd rather not add a new option if an existing option solves your use case.

Yes, it seems to work correctly. I'm happy with this solution as persistent directory history is not something I use, and normal `popd` to go back one level of `cd` seems to still work.

**Comment by romkatv** [comment]
Closing as *Good Enough*.
