### ISSUE TITLE
fzf gitignore directories

### ISSUE THREAD

**Issue by francois-pasquier** [romkatv/zsh4humans#235]
Is there any way to respect .gitignore files when using tab directory completion with fzf?

I am getting a ton of node_modules results

**Comment by romkatv** [comment]
Are you using recursive for completions?

Can you give an example of a command you want to complete, the completion you want to choose, and a node_modules completion that you don't want to see?

**Comment by francois-pasquier** [comment]
Yes, I am using recursive for completions.

For example, let's say I am in a react directory and I want to quickly edit a file with neovim.

I would go in the directory, do `nvim <TAB>` and type the name of the component I want to edit.

It takes a while to give me the "right" results because of fzf checking up the "node_modules" directory first.

![image](https://user-images.githubusercontent.com/19970734/186189113-5cd42120-b1a2-4140-b340-371bb6fcfccf.png)

I don't really want to see the node_modules directory in fzf because this directory is referenced in the `.gitignore` of this project.

**Comment by romkatv** [comment]
Thanks for the specific example.

Filtering out files matching `.gitignore` patterns in all completions may backfire. These patterns specify what shouldn't be version controlled, which doesn't necessarily match the concept of what shouldn't be *used* by a human operator. For example, after running `make` you might want to execute what `make` has compiled. Or you might want to `scp` a package that was create by the build system, or open a log file in a pager. It would be unfortunate if build artifacts and other machine generated files couldn't be completed.

What you can do instead is blacklist `node_modules` by name similarly to how it is currently done for directories that start with a dot. For that you need to define `zstyle ':z4h:fzf-complete' find-flags`. This style lets you control flags that are passed to `find` when generating a list of files for the input to `fzf`. The default value is `-name '.*' -prune -print -o -print`, which says that directories that start with a dot should be included but not recursed. You can request `node_modules` to be handled similarly.

```zsh
zstyle ':z4h:fzf-complete' find-flags '(' -name '.*' -o -name node_modules ')' -prune -print -o -print
```

Check `man find` for details about this syntax.

It's also possible to skip `node_modules` completely but I wouldn't recommend it. If they are printed and not recursed, you can still expand them manually in a rare case where you need that. If you've followed [this tip](https://github.com/romkatv/zsh4humans/blob/master/tips.md#current-directory) and bound <kbd>Tab</kbd> to `repeat` in fzf completions (I recommend doing this), you can hit <kbd>Tab</kbd> to "focus" on the selected directory. It works for any directory, not just for those that are blacklisted as above.

Does this work for you?

**Comment by maximbaz** [comment]
Would like to add that some apps (e.g. `rg` or `fd`) respect `.ignore` files, the purpose of which is exactly to separate the semantics of "files I don't want to find" and "files I don't want to commit". That's why for example I have in my global gitignore `*.log` (I want to find them, but never to commit) and in `$HOME/.ignore` I have `.git` (I never want to list files inside `.git` folders).

The described solution of setting a custom `find-flags` is what I am using personally 👍 

I don't know if it makes sense to automatically read `.ignore` files (it seems `fd` looks for `.ignore` files current and all parent folders) or just let the user construct `find-flags` matching their `.ignore` files, just wanted to bring this to your attention.

**Comment by francois-pasquier** [comment]
Thank you both, the tips are much appreciated!

It fits my need perfectly : )

**Comment by romkatv** [comment]
Thanks for the additional context and info.

All solutions that were mentioned here (`find-flags` and various patterns with ignore patterns) have one large downside: they aren't ware of the command being completed. It's not unthinkable that I might to delete a directory with build artifacts or a specific artifact, so it makes sense for `rm` to complete all files. However, a command like `vim` should usually avoid completing `.gitignore` files *except when it's the only match*. This isn't supported though, so you'll have to come up with some kind of approximation that suits you.
