### ISSUE TITLE
fzf: empty suffix is ignored

### ISSUE THREAD

**Issue by rsteube** [romkatv/zsh4humans#238]
When using [compadd](https://github.com/romkatv/zsh4humans/blob/v5/fn/z4h-fzf-complete#L104) with an empty suffix a `space` suffix is added after fzf selection.
```sh
#compdef example

function _example_completion {
  compadd -S "" a b c
}

compquote '' 2>/dev/null && _example_completion
compdef _example_completion example
```

related https://github.com/rsteube/carapace-bin/issues/1277#issuecomment-1229521892

**Comment by romkatv** [comment]
Thanks for reporting this.

It's unlikely that I'll do anything here. If this affects completions only of one command, consider changing the code of its completion so that it works more similarly to all other completions.

**Comment by romkatv** [comment]
Closing because I don't intend to do anything here.
