### ISSUE TITLE
Numeric arguments don't work in z4h widgets

### ISSUE THREAD

**Issue by edshamis** [romkatv/zsh4humans#241]
How can make z4h-backward-kill-word repeat 3 times? Usually it would be Alt-3 Ctrl-w in emacs mode

**Comment by romkatv** [comment]
If you say it doesn't work, then it doesn't work. I don't use it myself, so I wouldn't know. I don't know how difficult it would be to fix this. If you send a clean PR, I'll merge it. If not, there is virtually zero chance I'll implement it.

**Comment by edshamis** [comment]
Ok, I'll look into it and make PR

**Comment by edshamis** [comment]
PR #242

**Comment by romkatv** [comment]
Thank you for filing an issue with a perfectly understandable description and submitting a PR with working code. 👍

**Comment by edshamis** [comment]
My pleasure. Actually I learned a lot from your code and your replies here, so thank you. And it's my first pr on gh)))

**Comment by edshamis** [comment]
My pleasure. Actually I learned a lot from your code and your replies here,
so thank you. And it's my first pr on gh)))
