### ISSUE TITLE
PATH not preserved after changing to a directory with another .envrc

### ISSUE THREAD

**Issue by creedasaurus** [romkatv/zsh4humans#244]
Hi there!

Appreciate all the excellent stuff you've written. It has taught me a lot.

Anyway, I noticed a strange issue when using `zsh4humans/v5` with direnv recently. The best way I can describe it is that after changing to a directory with a new `.envrc`, the exported `PATH` is missing a few different directories set in the `.zshrc`. I couldn't find anything in other issues and didn't see anything in the code that stood out to me in this regard. Here is my basic repro as best as I can describe it:

1. Setup zsh4humans, answer yes to `direnv` at least (this assumes you have it installed and working with something (I'm using `asdf` with it).
2. Extend path in `.zshrc` on the indicated line:
   ```
   path=(~/bin ~/.toolbox/bin $path)
   ```
   After loading zsh again, check it's in the path:
   ```
   print -l $path
   /Users/user/bin
   /Users/user/.toolbox/bin   <------ see here
   /Users/user/.cache/zsh4humans/v5/zsh4humans/zb
   /Users/user/.asdf/installs/ruby/3.1.2/bin <----- this would be from direnv
   /Users/user/.local/bin
   /Users/user/.cargo/bin
   /opt/homebrew/bin
   /opt/homebrew/sbin
   /usr/local/bin
   /usr/bin
   /bin
   /usr/sbin
   /sbin
   /Users/user/.cache/zsh4humans/v5/fzf/bin
   ```
3. Create a directory with a new .envrc. Then direnv allow it.
   ```
   mkdir testdir
   touch testdir/.envrc
   cd testdir
   direnv allow .
   ```
4. Check the path again:
  ```
  print -l $path
  /Users/user/.local/bin
  /Users/user/.cargo/bin
  /opt/homebrew/bin
  /opt/homebrew/sbin
  /usr/local/bin
  /usr/bin
  /bin
  /usr/sbin
  /sbin
  /Users/user/.cache/zsh4humans/v5/fzf/bin
  ```
  The path is now missing `~/.toolbox/bin` and `~/bin`
  
If I move the path extension line _just_ above the `z4h init` line, it actually preserves that path like it should. Either that or add the `direnv` hook manually and disable the `z4h` integration with it. I'm not sure if it's something to do with direnv returning the exports back to a different shell or something, or what.

**Comment by romkatv** [comment]
Cannot reproduce. Here's what I've tried.

1. Run:
   ```zsh
   docker run -e TERM -e COLORTERM -e LC_ALL=C.UTF-8 -w /root -it --rm alpine sh -uec '
     apk add zsh curl direnv
     sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v5/install)"'
   ```
2. Answer: PC keyboard, standard keybindings, no tmux, yes direnv, yes to change login shell.
3. Quit powerlevel10k wizard.
4. Run:
   ```zsh
   sed -i.bak -E 's|^path=.*|path=(~/bin ~/.toolbox/bin $path)|' ~/.zshrc
   ```
5. Run: `exec zsh`
6. Quit powerlevel10k wizard.
7. Run:
   ```zsh
   mkdir testdir
   touch testdir/.envrc
   cd testdir
   direnv allow .
   ```
8. Run: `print -rC1 -- $path`

Output from the last step:

```text
/root/bin
/root/.toolbox/bin
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/root/.cache/zsh4humans/v5/fzf/bin
```
