### ISSUE TITLE
[Question] FreeBSD Support

### ISSUE THREAD

**Issue by ngortheone** [romkatv/zsh4humans#249]
I see that FreeBSD support was dropped here https://github.com/romkatv/zsh4humans/commit/97955760649e8099e82195979d84969080e72ea0

What is the reason? Are there technical reasons/limitations or is lack of testers/maintainers?

**Comment by romkatv** [comment]
I dropped FreeBSD support to save time.

**Comment by ngortheone** [comment]
I run FreeBSD, would you be interested in reinstating FreeBSD support if I help testing FreeBSD releases?

**Comment by romkatv** [comment]
No, sorry.
