### ISSUE TITLE
Disable brew integration?

### ISSUE THREAD

**Issue by atwok** [romkatv/zsh4humans#250]
Hi.

Sometimes I get into situations where I need to install linuxbrew or reinstall linuxbrew and I run into issues with linuxbrew.  Is there an easy way to keep z4h from looking for and leveraging brew to install command-not-found until I'm ready?  Right now it kicks off on login and since my linuxbrew install is borked at the moment, brew fails and I end up in z4h recovery mode.

If I could just disable this piece of z4h until I'm ready for it, that would be awesome.

Thanks in advance.

**Comment by romkatv** [comment]
What exactly happens at login that trips on linuxbrew?

**Comment by atwok** [comment]
z4h: installing homebrew-command-not-found

This is the piece I'd like to skip until I'm ready.

**Comment by romkatv** [comment]
Can you try this?

```zsh
zstyle -a :z4h:homebrew-command-not-found channel none
```

I'm not 100% sure whether it'll work but it might.

**Comment by romkatv** [comment]
Sorry, drop that `-a`.

**Comment by atwok** [comment]
It worked!  Awesome!

Thank you very much.

**Comment by romkatv** [comment]
I'm glad that my past self was kind enough to implement that flag 😆
