### ISSUE TITLE
z4h sets `LC_ALL=C.UTF-8` if no locale is set, should set `LANG` instead

### ISSUE THREAD

**Issue by VorpalBlade** [romkatv/zsh4humans#253]
z4h sets (apparently very early on, before `.zprofile`) `LC_ALL=C.UTF-8` if no locale is set. At least on some distros (Arch), locale is set during `/etc/zsh/zprofile` phase normally. ZSH of course ignores this. If I set my locale in `~/.zprofile` (by setting `LANG` and some `LC_*`) that gets overridden by the `LC_ALL` that was already set.

One way to work around this is to set the locale you want and then unset `LC_ALL`. However, I believe that ZSH should set `LANG` not `LC_ALL` in the first place. As `LANG` is the default (that can be overridden per category), and `LC_ALL` is a debugging "override-everything". It makes more sense to set `LANG` early on, and then have the user's LANG and `LC_*` settings override it when set at a later point. This would follow the rule of least surprise and be the most transparent to override for the user.

**Comment by romkatv** [comment]
z4h attempts to implement the following logic: if the encoding in the current locale isn't utf-8, make it utf-8. Setting `LANG` won't achieve this.

In any case, unless there is no workaround for this issue, I'm unlikely to do anything here even if the current behavior is "wrong".

**Comment by VorpalBlade** [comment]
Yeah, I guess there are two cases to consider (I was only thinking of one): 

* No locale is set at all
* A bad (non-UTF-8) locale is set, possibly a complicated one involving LANG, one or more of LC_* or even LC_ALL.

I was only thinking about the former case.

**Comment by romkatv** [comment]
Is it OK with you if we close this? It's not really blocking you, right? I prefer to keep the current behavior.

**Comment by VorpalBlade** [comment]
No problem. This will at least serve as documentation and rationale if someone else runs into this.
