### ISSUE TITLE
Please help me figure out why hcgraf/zsh-sudo isn't working

### ISSUE THREAD

**Issue by AnimiVulpis** [romkatv/zsh4humans#255]
I have used https://github.com/hcgraf/zsh-sudo as a zsh plugin in the past (with multiple different plug managers).

I don't think it should be hard to figure out why it's not working as intended.

A pointer or a few keywords would already be enough to help me understand what needs to be changed to get this working.

### How to reproduce

* Use the docker example environment
* Modify `.zshrc` to include `z4h install hcgraf/zsh-sudo || return` and `z4h load hcgraf/zsh-sudo` in the places where indicated
* Run `z4h update`
* Type something (e.g. `echo test`)
* Hit `Esc` twice (it should prepend the current line with `sudo`)
* Observer that nothing happens and the next key hit is ignored (seems like the shell is in "escape" mode or something)

**Comment by romkatv** [comment]
Sorry, no.

**Comment by AnimiVulpis** [comment]
I don't know why it took me so long.
But the by far easiest solution is to replace [hcgraf/zsh-sudo](https://github.com/hcgraf/zsh-sudo) with [ohmyzsh/ohmyzsh/plugins/sudo](https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/sudo/sudo.plugin.zsh)

Before:

```bash
# install part of .zshrc
z4h install hcgraf/zsh-sudo || return

# more

# load and source part of .zshrc
z4h load hcgraf/zsh-sudo
```

After:

```bash
# install part of .zshrc
z4h install ohmyzsh/ohmyzsh || return

# more

# load and source part of .zshrc
z4h load ohmyzsh/ohmyzsh/plugins/sudo
```

Maybe that helps someone else

**Comment by johnstegeman** [comment]
The problem here is that hcgraf/zsh-sudo has it's plugin file called sudo.zsh.plugin. z4h doesn't like that.

**Comment by romkatv** [comment]
> The problem here is that hcgraf/zsh-sudo has it's plugin file called sudo.zsh.plugin. z4h doesn't like that.

Does this work?

```zsh
z4h source hcgraf/zsh-sudo/sudo.zsh.plugin
```

**Comment by johnstegeman** [comment]
Yes, that's what I was using to get it to work
