### ISSUE TITLE
Using fast-syntax-highlighting instead of zsh-syntax-highlighting

### ISSUE THREAD

**Issue by vqcuong** [romkatv/zsh4humans#257]
Hi there,
I want to try using fast-syntax-highlighting (https://github.com/zdharma-continuum/fast-syntax-highlighting) instead of default zsh-syntax-highlighting, but the default zsh-syntax-highlighting is always overwrite the fast-syntax-highlighting. Can you guide me how to do that. Thank alot

**Comment by romkatv** [comment]
This isn't a supported configuration change. I don't know how hard or easy it would be to do.

**Comment by hochshi** [comment]
Quite easy.

Disable the builtin syntax highlighting:
`zstyle ':z4h:zsh-syntax-highlighting' channel 'none'`

And z4h install and z4h load fast-syntax-highlighting:
`z4h install zdharma-continuum/fast-syntax-highlighting || return`
`z4h load zdharma-continuum/fast-syntax-highlighting`

**Comment by romkatv** [comment]
This will almost certainly result in visual artifacts but if it works well enough for you, by all means.

Note that it won't make anything faster.

**Comment by hochshi** [comment]
> This will almost certainly result in visual artifacts but if it works well enough for you, by all means.
> 
> Note that it won't make anything faster.

Yeah, I don't think you could notice a difference, z4h is blazingly fast as it is.

Thank you for that by the way.
