### ISSUE TITLE
Automatic VSCode commands being cut out

### ISSUE THREAD

**Issue by MicaelJarniac** [romkatv/zsh4humans#258]
When working on a Python project, for example, Visual Studio Code will automatically run `source /path/to/project/venv/bin/activate` to activate the virtual environment on a new terminal.

For some reason, though, it's often failing, and trying to run `ject/venv/bin/activate` instead, for example, with the beginning of the command being cut out.

This also happens for other commands, like `git` commands, that VSCode tries to run automatically.

I believe this is due to the shell taking a bit of time to properly initialize and accept commands.

I'm not sure where to ask for help about this issue. I think adding a small delay to VSCode's automatic commands would help, but I can't seem to find a way to do that.

**Comment by romkatv** [comment]
Visual Studio Code doesn't inject any code into *my* terminal. How did you make it do it to your own terminal and why?

**Comment by MicaelJarniac** [comment]
I don't think I've done anything special. Simply having the Python extension for VSCode installed and pointing it to a virtual env makes it run the `source .../activate` command whenever I open a terminal.

And some `git` commands also happen to run on the integrated terminal, like when I right-clicked a different branch, chose to "merge into current branch", and chose "fast-forward only".

I think also asking it to run a file, or start debugging, might also make it automatically open a terminal and run some commands.

**Comment by MicaelJarniac** [comment]
Seems like the longer the path to a project, the higher the likelihood of this issue happening.

**Comment by MicaelJarniac** [comment]
### Long path
![image](https://user-images.githubusercontent.com/19514231/222566830-15fba845-23d3-49b6-9a37-5ba7790126c2.png)

### Short path
![image](https://user-images.githubusercontent.com/19514231/222566570-e4767d26-ef75-4094-accb-b770e1960320.png)

**Comment by romkatv** [comment]
What happens if you use a different zsh theme?

**Comment by MicaelJarniac** [comment]
I temporarily deleted my `.zshrc` and it works fine now, nearly instantaneous.

**Comment by romkatv** [comment]
What happens if you don't detele your .zshrc but simply disable powerlevel10k or replace it with something else?

**Comment by MicaelJarniac** [comment]
I'm unfortunately not quite sure how to do that. I can't seem to find where `.zshrc` sources it, to comment it out.

Deleting `.p10k.zsh` just forces me back to the wizard.

I'll read the docs here again to see if it mentions how to do this.

**Comment by romkatv** [comment]
My bad, I didn't realize this issue was filed under zsh4humans. For some reason I though this was a powerlevel10k repo.

I don't provide support for zsh4humans for environments I don't personally care about. I used to, but then I stopped because it's very time consuming. Sorry.

**Comment by romkatv** [comment]
Closing. If you find the culprit, please post an update here.

**Comment by MicaelJarniac** [comment]
Adding the following to `.zshrc` seems to have helped a lot with this issue:
```zsh
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  zstyle ':z4h:' start-tmux no
fi
```
This makes it so that shells being opened from within VS Code do not try to use tmux, and it seems like that speeds up the shell enough so that it doesn't cut out the commands as often.

**Comment by MicaelJarniac** [comment]
Upon further investigation, it appears that the culprit is actually `prompt-at-bottom`, and not tmux by itself.

I haven't, however, figured out how to selectively disable it only when using VS Code.

tmux changes the `$TERM_PROGRAM` variable to `tmux`, so it can't be used on a conditional.

**Comment by MicaelJarniac** [comment]
Fixed by https://github.com/romkatv/zsh4humans/commit/bf39c3b2f3a5e2ba0c916222ba39eaafdb624262 it seems.

**Comment by MicaelJarniac** [comment]
https://github.com/romkatv/zsh4humans/issues/260#issuecomment-1462114874

**Comment by romkatv** [comment]
Thanks for reporting this issue, and for your help with debugging and testing it.
