### ISSUE TITLE
How to use touchpad to scroll instead of pg-up and pg-down

### ISSUE THREAD

**Issue by avie10eee** [romkatv/zsh4humans#259]
hello, I just started using z4h and it is AMAZING, but there is one problem, My keyboard does not contain pg-up and pg-down keys, so I need to edit the config for scrolling. I was just wondering if that is possible and if it is, how to do it.

**Comment by romkatv** [comment]
I don't know.

**Comment by avie10eee** [comment]
I figured it out. All you need to do is add ` set -g mode-mouse on ` to ~/.tmux.conf and then you can scroll.

**Comment by nucflash** [comment]
In newer versions of tmux, we need `set -g mouse on`; source: [stackoverflow](https://stackoverflow.com/a/33336609)
