### ISSUE TITLE
Can't disable `start-tmux` inside VSCode's terminal

### ISSUE THREAD

**Issue by MicaelJarniac** [romkatv/zsh4humans#260]
When I first installed Z4H, I chose to use the integrated tmux thing.

I wanted to disable it to test something, so I saw on the docs that I can add the following to `.zshrc`:
```zsh
# Don't start tmux.
zstyle ':z4h:' start-tmux no
```
https://github.com/romkatv/zsh4humans/blob/master/tips.md#tmux

I did that, and now on my normal terminal, it no longer uses tmux (I think, am not sure how to verify, but at least the "prompt at the bottom" thing stopped working), but on the terminal inside Visual Studio Code it's still using tmux, with the title of the terminal tab being `-/home/micael/.cache/zsh4humans/v5/tmux/bin/tmux`.

So I believe there's something else that's keeping the tmux option enabled when I'm using VSCode.

I was trying to do this in order to test if it was tmux that was slowing down the startup of the shell and causing what I reported on #258.

**Comment by romkatv** [comment]
If I understand correctly, you've now described 4 bugs you are experiencing in vscode:

1. Slow shell startup whenever you are opening the terminal.
2. Some text (presumably sent to the TTY) disappears.
3. Some zstyle options not being respected.
4. Terminal title doesn't update.

These look bizarre and very surprising to me. I've never seen anything like this in any terminal myself and I don't recall anybody reporting this either.

The first thing I suggest trying is disabling vscode terminal integration (`terminal.integrated.shellIntegration.enabled`). As a rule of thumb, you should do this whenever you experience any shell weirdness in vscode. The shell integration in vscode is of the most invasive kind among all terminals and has been the cause of many terminal issues in the past.

**Comment by romkatv** [comment]
> Terminal title doesn't update.

I think this might be fixed if you set `terminal.integrated.tabs.title` in vscode settings to `${sequence}`.

**Comment by MicaelJarniac** [comment]
> > Terminal title doesn't update.
> 
> I think this might be fixed if you set `terminal.integrated.tabs.title` in vscode settings to `${sequence}`.

This worked nicely, thanks! Now the title works, at least.

**Comment by MicaelJarniac** [comment]
> If I understand correctly, you've now described 4 bugs you are experiencing in vscode:
> 
>   1. Slow shell startup whenever you are opening the terminal.
> 
>   2. Some text (presumably sent to the TTY) disappears.
> 
>   3. Some zstyle options not being respected.
> 
>   4. Terminal title doesn't update.
> 
> 
> These look bizarre and very surprising to me. I've never seen anything like this in any terminal myself and I don't recall anybody reporting this either.
> 
> The first thing I suggest trying is disabling vscode terminal integration (`terminal.integrated.shellIntegration.enabled`). As a rule of thumb, you should do this whenever you experience any shell weirdness in vscode. The shell integration in vscode is of the most invasive kind among all terminals and has been the cause of many terminal issues in the past.

I believe 2 is caused by 1. 4 I managed to fix using your suggestion (and I think it was "broken" because of it using tmux). I think there's a chance that tmux is also causing 1. So what's left is basically to figure out 3.

I tried disabling the shell integration, along with a few other things, and nothing seemed to help.

I'm pretty sure the `.zshrc` is being sourced correctly, as I added some `echo` stuff to it and I can see it on the terminal, so only parts of it are being ignored, for whatever reason.

I opened this issue because I thought it'd be possible that something inside Z4H was detecting VS Code and modifying the tmux behavior.

For example, if I add `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` to `.zshrc`, on my normal terminal it'll start the shell inside a full tmux window, but on VS Code it still seems to use the minimal tmux (without the bottom bar).

**Comment by romkatv** [comment]
> I believe 2 is caused by 1. 4 I managed to fix using your suggestion (and I think it was "broken" because of it using tmux). I think there's a chance that tmux is also causing 1. So what's left is basically to figure out 3.

Saying that slow startup causes the TTY content to be dropped requires explaining:

1. The mechanism of the slow startup itself.
2. How the slow startup can cause the TTY content to be dropped.

I don't have plausible explanations for either of these.

I should also repeat that I'm using vscode integrated terminal myself, and I'm not experiencing these issues.

**Comment by romkatv** [comment]
> For example, if I add `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` to `.zshrc`, on my normal terminal it'll start the shell inside a full tmux window, but on VS Code it still seems to use the minimal tmux (without the bottom bar).

Are you perchance starting one terminal from another?

**Comment by MicaelJarniac** [comment]
> > For example, if I add `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` to `.zshrc`, on my normal terminal it'll start the shell inside a full tmux window, but on VS Code it still seems to use the minimal tmux (without the bottom bar).
> 
> Are you perchance starting one terminal from another?

I have no idea if VS Code is doing that, but I just tested it on another terminal (I have Konsole), and indeed, opening it from the application launcher has the intended behavior, while opening it by running `konsole` from another terminal seems to have the broken behavior I'm experiencing with VS Code.

**Comment by MicaelJarniac** [comment]
Yes, I always open VS Code by running `code foo/bar` from within Yakuake, that's the terminal I use most of the time.

**Comment by MicaelJarniac** [comment]
What can be done about this, then? Seems like the issue is exactly what you thought, opening VS Code by running `code` has a different result from running it from a normal launcher.

I do prefer to open it by running `code`, since I can much more quickly open specific projects and such, so it'd be nice if opening it with `code` could have the behavior of opening it from a launcher.

I'm not even sure what keywords to use to search for a solution, in case this is something that can be fixed from the VS Code's side.

**Comment by MicaelJarniac** [comment]
I'm guessing it might be possible to do it by aliasing `code` to some special form that adds arguments for the shell to emulate it being opened by a launcher, but I have no idea what that would be like.

**Comment by romkatv** [comment]
It's a bug in z4h. I've made a small change in the code that might fix it. Could you run `z4h update` and see if it helps?

I still don't have any explanation for the original issue that you've reported as happening without any `zstyle ':z4h:' start-tmux`.

**Comment by MicaelJarniac** [comment]
I ran `z4h update` and the bug still happens when I launch `konsole` from within Konsole and when I launch `code foo/bar` from a terminal.

**Comment by MicaelJarniac** [comment]
Nice, so the following now works:
```zsh
if [[ "$TERM_PROGRAM" == "vscode" ]]; then
  zstyle ':z4h:' start-tmux no
fi
```
When I launch a normal terminal, it uses tmux, but when I'm on VS Code, it doesn't.

That's what I was originally trying to accomplish, so that's great, thanks a lot!

I do think that the `start-tmux command ...` thing is still broken when launching a terminal from a terminal, but I don't use that, was just testing to see if it worked.

**Comment by romkatv** [comment]
> but if I have `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` it doesn't.

What are you trying to do while having option? You cannot open two terminals on the same machine while having it. If you aren't a tmux user (the fact that you are attempting this suggests that you aren't), you should either set `zstyle ':z4h:' start-tmux no` or (highly recommended) not set this option at all.

**Comment by romkatv** [comment]
> Nice, so the following now works:
> 
> ```shell
> if [[ "$TERM_PROGRAM" == "vscode" ]]; then
>   zstyle ':z4h:' start-tmux no
> fi
> ```
> 
> When I launch a normal terminal, it uses tmux, but when I'm on VS Code, it doesn't.
> 
> That's what I was originally trying to accomplish, so that's great, thanks a lot!

Why were you trying to accomplish this? Why do you want to have tmux in some terminals and not in others?

> I do think that the `start-tmux command ...` thing is still broken when launching a terminal from a terminal, but I don't use that, was just testing to see if it worked.

How can I reproduce this?

**Comment by MicaelJarniac** [comment]
> Why were you trying to accomplish this? Why do you want to have tmux in some terminals and not in others?

Because of #258, I was trying to see if it was tmux slowing down the startup of the shell, so I wanted to disable it to test, but I couldn't get it to disable properly because I was launching `code` from a terminal, and that bug you just fixed made it so it was impossible to disable tmux then.

> How can I reproduce this?

As you guessed, I'm not a tmux user, so I don't know if this is actually the intended behavior, but what I experienced was as follows:
 - add `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` to `.zshrc`
 - open Konsole from app launcher
 - verify tmux works (has bar at bottom)
 - run `konsole` from within Konsole
 - verify tmux no longer works (has no bar at bottom) (it's likely defaulted to the `integrated` mode, instead of the custom one defined in `.zshrc`)

**Comment by MicaelJarniac** [comment]
By the way, disabling tmux did in fact help with the issue I was having on #258. It now manages to complete the command without cutting out. I haven't texted extensively, but it did seem to help a lot.

**Comment by MicaelJarniac** [comment]
I'm now trying to figure out how to disable `prompt-at-bottom` only for VS Code. I can't use the same conditional with `$TERM_PROGRAM`, as I think tmux changes it to `tmux` instead of `vscode`.

**Comment by romkatv** [comment]
Sorry, this is somewhat outside of "very limited support". Please try figuring it out by yourself.

**Comment by romkatv** [comment]
> what I experienced was as follows:
> 
> * add `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t z4h` to `.zshrc`
> * open Konsole from app launcher
> * verify tmux works (has bar at bottom)
> * run `konsole` from within Konsole
> * verify tmux no longer works (has no bar at bottom) (it's likely defaulted to the `integrated` mode, instead of the custom one defined in `.zshrc`)

Thanks! I reproduced this and fixed. Now upon opening the second terminal the first will close (as intended).

**Comment by romkatv** [comment]
> I see. That's a very useful observation. This means that the integrated vscode terminal fails to report cursor position when asked about it soon after startup. I recall several bugs in this terminal that manifest only during a short time after the TTY is created. This might be something similar. Interestingly enough, I do not (and never have) experience this exact bug.

Now that I think of it, it's not a bug in vscode. I don't know what exactly makes your vscode send text to the TTY, but I can imagine that this happens as soon as the TTY is created. When z4h is initializing, it sends a few queries to the TTY (e.g., for the cursor position), and it doesn't expect to find anything except the answer to the query. If there is indeed something else besides the answer to the query, this content gets dropped. The code is here: https://github.com/romkatv/zsh4humans/blob/v5/fn/-z4h-get-cursor-pos.

I've now changed that code to not drop the extra content but instead forward it to zle. Could you update z4h and check whether it helped? You'll need to remove `start-tmux` and enable `prompt-at-bottom` and verify that text no longer gets eaten when you open a terminal in vscode.

**Comment by MicaelJarniac** [comment]
> I've now changed that code to not drop the extra content but instead forward it to zle. Could you update z4h and check whether it helped? You'll need to remove start-tmux and enable prompt-at-bottom and verify that text no longer gets eaten when you open a terminal in vscode.

Thanks a lot, that did seem to fix it!

**Comment by MicaelJarniac** [comment]
I'll close this issue now I think, thanks a lot again!
