### ISSUE TITLE
"Start tmux if not already in tmux" does not work with Fedora Toolbox

### ISSUE THREAD

**Issue by owittek** [romkatv/zsh4humans#261]
Hey!

I recently ran into the issue that I tried to enter a Fedora Toolbox (it's podman container that maps through specific user settings like the $HOME directory) and I like tend to primarily work with tmux so I've set `zstyle ':z4h:' start-tmux command tmux -u new -A -D -t main` in my .zshrc. Unfortunately I get instantly kicked out of the container if I try to enter it with this setting as tmux prevents me from nesting sessions.

I don't know if it is an issue relevant for enough people to fix it but I want to at least document it in case someone else runs into this issue and has to find out whats wrong as there are no logs or other information indicating this interaction as the culprit.

**Comment by romkatv** [comment]
This setting causes interactive zsh to run `exec tmux -u new -A -D -t main` if not already running under tmux. Is this what you really want? If not, go ahead and change it.

**Comment by owittek** [comment]
> This setting causes interactive zsh to run `exec tmux -u new -A -D -t main` if not already running under tmux. Is this what you really want? If not, go ahead and change it.

Yes that is what I want but lets say I have 2 terminals open in tmux. One is to work with my system and one is there to work inside of the Toolbox (inside of a container basically). If I try to enter the toolbox in my second terminal it loads the .zshrc and tries to open a nested tmux session within the toolbox and that causes the terminal to automatically close. So I'm unable to enter a toolbox from a tmux session if I have this setting in my .zshrc

**Comment by romkatv** [comment]
Try the following.

1. Disable tmux in zsh4humans with `zstyle ':z4h:' start-tmux no`.
2. Close all terminals and shells.
3. Open all terminals and shells that you want and figure out which `tmux` commands you need to execute in each of them in order to achieve what you want.
4. Codify (3) in your zshrc so that the same tmux commands are executed automatically. I can help you with this step if you describe (3) in enough detail.

**Comment by owittek** [comment]
Actually I've tried it again as this issue has occured to me a few weeks ago and it seems to work now for some reason. No idea why removing that line fixed it in the first place then. Thank you for your time!

**Comment by owittek** [comment]
Okay it still appears to be an issue, I had to restart my entire SSH to get the issue again. It even kicks me out of the SSH session entirely.

I don't think there's a tmux command that would fix the issue as there seems to be an issue with the detection of whether the terminal is already in a session or not.

**Comment by romkatv** [comment]
If you cannot figure out which commands to run manually after you disable tmux in z4h, there is nothing I can do.

**Comment by owittek** [comment]
I am just assuming that nesting is the issue. How does z4h detect if you're already in a tmux session?
