### ISSUE TITLE
Does zsh4humans have the Oh My Zsh plugins?

### ISSUE THREAD

**Issue by chris122380** [romkatv/zsh4humans#262]
I have figured out how to apply Oh My Zsh plugins but are these included in zsh4humans? I uninstalled Oh My Zsh as I found zsh4humans was much lighter and had just about everything I needed. I downloaded one of the Oh My Zsh plugins I thought I would need but found a better option creating my own kill script with the help of chatGPT. So I deleted the old plugin but then noticed that all the Oh My Zsh plugins are also located at ~/.cache/zsh4humans/v5/ohmyzsh/ohmyzsh/plugins/. I deleted ~/.cache/zsh4humans thinking it must have been caching old data. Reloaded zsh4humans and to be on the safe side ran z4h update. Noticed that the same files returned later. So does this mean that the Oh My Zsh plugins are included with zsh4humans? Are they safe to use from the ~/.cache folder rather then from maybe a ~/.config or ~/.zsh folder? 

If zsh4humans includes the Oh My Zsh plugins can the documentation be updated to include where to find them and how to implement them in the ~/.zshrc? For now I am using source <Destination of the plugin> but I am thinking that I'm probably doing that wrong or could be called by using z4h source or z4h load

**Comment by romkatv** [comment]
Open `~/.zshrc` and search for "ohmyzsh". Read comments above every command that you find this way. Note thigs like this:

```zsh
# If you don't plan to use Oh My Zsh, delete this line.
```

**Comment by chris122380** [comment]
> Open `~/.zshrc` and search for "ohmyzsh". Read comments above every command that you find this way. Note things like this:
> 
> ```shell
> # If you don't plan to use Oh My Zsh, delete this line.
> ```

Yes I saw that but it doesn't tell me anything. I made the assumption it means it's pulling stuff from their GitHub which it says. It then gives an option for what looks like loading a plugin. I was just hoping for better details or explanation. I will go and comment out what could be my duplicate and try with the ohmyzsh plugin. 

You could say I'm a newbie to Linux who's just been learning more on customizations.

**Comment by romkatv** [comment]
> Yes I saw that but it doesn't tell me anything. 

This may not be the right project for you. No offense.

I don't intend to write any documentation see the top of the homepage.

**Comment by chris122380** [comment]
ok I figured it out. Example of adding the sudo plugin (for anyone searching the issues like I did first): `z4h load   ohmyzsh/ohmyzsh/plugins/sudo` just under `# This is just an example that you should delete. It does nothing useful.`

**Comment by romkatv** [comment]
There is already an example that looks just like that.
