### ISSUE TITLE
Enable file tab autocompletion on long options, e.g., `--flag=`

### ISSUE THREAD

**Issue by nucflash** [romkatv/zsh4humans#263]
Thank you for the really great work on zsh4humans! It's a great piece of software. So well thought throughout. It's certainly the best configuration of zsh that I've ever tried. Since I started using it, I've fallen in love working on the terminal. Everything is  snappy, smooth, and intuitive.

One question: I want to enable file completion after long options, e.g., "cmd --flag=/tmp/doc.txt". I [read on SO](https://unix.stackexchange.com/a/599449) that this can accomplished with:
```
setopt magic_equal_subst
```

I wonder what is the best way to enable this. For example, is it already in zs4humans and I can enable it with some zstyle-type of flag, or can I just add it at the end of my `.zshrc` and be ok? 

Thanks again!

**Comment by romkatv** [comment]
Search for `setopt` in `~/.zshrc`. You can add your own options there.

**Comment by nucflash** [comment]
Thank you!

One follow up question, if you, or anyone else in the community, know (I appreciate taking the time to respond to all of our questions!):

The above option, although it allows for tab completion after the equal sign:
```
cmd --flag=<TAB>
```
It doesn't trigger autocomplete when I use a command from history and try to edit value of the option like this:
```
# previous instance of the command
cmd --flag=/a/path

# want to change `a` to `b`
cmd --flag=<TAB>/path
```
In the second case, pressing tab doesn't trigger the file viewer, and valid paths are not underlined. 

Is there a way trigger the file viewer in the second case, and also underlying valid paths as we do for short options? Thanks!

**Comment by romkatv** [comment]
This might be possible but I cannot say for sure from the top of my head. Unfortunately, this isn't the kind of issue that I'm willing to spend time on. If you figure out the answer, please post an update.

**Comment by nucflash** [comment]
I totally understand. It would be a really minor enhancement, anyway. I'll close the issue for now, and I'll post an update if I find a solution. Thanks again for all of your work!
