### ISSUE TITLE
Default fzf keybinds don't work

### ISSUE THREAD

**Issue by owittek** [romkatv/zsh4humans#264]
Hey, thanks for the awesome project!

A minor inconvenience I just can't seem to fix is that `ctrl+j` & `ctrl+k` do not work to navigate with fzf which is a default behavior. `ctrl+p` & `ctrl+n` do work. I tried to use the `--bind` for fzf but it does not work either.

**Comment by romkatv** [comment]
If you can describe what you are doing and what you are expecting, I might be able to help. No guarantees though.

**Comment by owittek** [comment]
When using fzf (for example on TAB completion) I want to go through the search results. [Here are the default keybinds for that](https://github.com/junegunn/fzf#using-the-finder) but `CTRL+J` and `CTRL+K` do not work.

**Comment by romkatv** [comment]
You can redefine bindings within `z4h-fzf-complete` like this:

```zsh
zstyle ':z4h:fzf-complete' fzf-bindings ctrl-k:up
```

You can specify more than one binding there. See `man fzf` for the specification of the format.

**Comment by romkatv** [comment]
There are several widgets that use fzf. If you want to redefine bindings in all of them, do this:

```zsh
zstyle ':z4h:*' fzf-bindings ctrl-k:up
```

**Comment by owittek** [comment]
Thanks, I'll try it out tomorrow and give feedback. Is there a reason why you've changed the default behavior?

**Comment by owittek** [comment]
It works, thank you!

**Comment by codyhan94** [comment]
@romkatv is it expected to need both
```
zstyle ':z4h:fzf-complete' fzf-bindings ctrl-k:up
zstyle ':z4h:*' fzf-bindings ctrl-k:up
```
to make fzf's `ctrl-k` keybind go up in all fzf widgets? I tried just setting the latter (assuming that it would imply the former) and noticed that it worked for both `z4h-fzf-history` and `z4h-fzf-dir-history` (`ctrl-r` and `alt-r` respectively) but not for `z4h-fzf-complete`. For example, the fzf widget instantiated by `ls -<tab>` would use the kill-line `ctrl-k` keybind.

On the other hand, only setting the first one makes the desired behavior happen only in the `ls -<tab>` scenario but not the other two.

I'm setting both for now to get the behavior I want; curious because for https://github.com/romkatv/zsh4humans/issues/60 I tried
```
zstyle ':z4h:*' fzf-flags '--no-exact'
```
instead of
```
zstyle ':z4h:(fzf-history|fzf-complete|cd-down)' fzf-flags '--no-exact'
```
like you suggested and got the `--no-exact` behavior on all of the widgets (includg fzf-complete!) as expected.

**Comment by romkatv** [comment]
@codyhan94 Perhaps this will help?

```zsh
grep fzf-bindings ~/.zshrc
```

**Comment by codyhan94** [comment]
ah yep, I was in the middle of `set -x` and `echo $...` debugging in your source and think I found it.
```
❯ rg -N fzf-bindings ~/.zshrc
zstyle ':z4h:fzf-complete' fzf-bindings tab:repeat
zstyle ':z4h:*' fzf-bindings ctrl-k:up
zstyle ':z4h:fzf-complete' fzf-bindings ctrl-k:up
```
when it works:
```
+-z4h-fzf:42> kv=( ctrl-k up )
```
and when it breaks:
```
+-z4h-fzf:42> kv=( tab repeat )
```
looks like the more specific `zstyle ':z4h:fzf-complete' fzf-bindings tab:repeat` is shadowing the `:z4h:*`.  Should I just add `ctrl-k:up` to the first one or is there perhaps a cleaner way?

**Comment by romkatv** [comment]
> looks like the more specific `zstyle ':z4h:fzf-complete' fzf-bindings tab:repeat` is shadowing the `:z4h:*`.

That's how `zstyle` works. There is pretty good documentation for it in `man zshmodules`.

> Should I just add `ctrl-k:up` to the first one or is there perhaps a cleaner way?

`fzf-binding` is an array, so you can specify more than one binding in there.

I'm not sure what exactly you are trying to do but you should be able to figure it out after reading about `zstyle`.

**Comment by codyhan94** [comment]
thank you for the quick response and great tools -- I ended up doing this:
```
❯ rg -N fzf-bindings ~/.zshrc
zstyle ':z4h:*' fzf-bindings ctrl-k:up
zstyle ':z4h:fzf-complete' fzf-bindings tab:repeat ctrl-k:up
```
to have `ctrl-k` work in all contexts and to have the functionality you mentioned in the [tips document](https://github.com/romkatv/zsh4humans/blob/master/tips.md#completions) for tab to accept the selection and open fzf again in fzf-complete. From the man page: `The definition stored for the most specific pattern that matches will be returned.` suggests that what I've ended up on is the correct way to achieve the configuration I want.

**Comment by romkatv** [comment]
Your config looks good to me.
