### ISSUE TITLE
improving performance | slow startup times | cutting the bloat

### ISSUE THREAD

**Issue by danielkrajnik** [romkatv/zsh4humans#270]
How do you remove unnecessary features?

Where do you configure zsh files/plugins/modules?

How do you speed up z4h?

How do you diagnose what slows down startup times (20s+) ?

Anything?

**Comment by danielkrajnik** [comment]
Thank you for the docs and for the fast response. Apologies for lack of details in the questions, but I wasn't sure if the projects is still maintained.

**Comment by romkatv** [comment]
You are welcome.

**Comment by danielkrajnik** [comment]
Unfortunately, the guides above don't address the problem of removing widgets from z4h to actually speed up zsh (I've read them all yesterday thoroughly and run benchmark now):

There is definitely a problem, but benchmark doesn't show you how it can be solved. I've also tried profiling with `zmodload zsh/zprof`  in .zshrc and it only shows z4h-init taking 15 seconds to start.

Is there by any chance any way to just remove widgets from z4h? Or is it a "tight-system" that either works or doesn't?

**Comment by romkatv** [comment]
> Unfortunately, the guides above don't address the problem of removing widgets from z4h

These are all the docs. There are no other docs.

> Is there by any chance any way to just remove widgets from z4h? Or is it a "tight-system" that either works or doesn't?

If it's not in the docs, then there is no documented way. There are of course undocumented ways. The whole project is open source after all.

You may have noticed that I'm not providing much support or handholding for this project. You can use it, modify, redistribute, etc., but please don't expect user support beyond the bare minimum.

**Comment by danielkrajnik** [comment]
Would you be able to answer [the previous question](https://github.com/romkatv/zsh4humans/issues/271#issuecomment-1620271939) though? Unless this is asking something complicated I would appreciate your help.

**Comment by romkatv** [comment]
I've answered all questions that didn't require excessive amount of my time.
