### ISSUE TITLE
How do you get list of zstyle options to debloat z4h?

### ISSUE THREAD

**Issue by danielkrajnik** [romkatv/zsh4humans#271]
I'm having a hard time trying to understand how to remove features from zsh4humans that cause significant slow downs or even how to find them. Is there any documentation or could you please advise how you unload parts of the code?

Currently shell freezes for 20 seconds on each boot and occasionally for 10 seconds on start. It happens very irregularly and I'm trying to understand what causes it. There are also problems with autocompletion (TAB) on a certain network mounted directory, which would be good to troubleshoot.

The easiest method would be to turn off each of the widgets/functions/plugins one by one to find out what causes it. However, it's not clear from what I've read how to do it or if it's possible at all.

**Comment by romkatv** [comment]
There are no docs other than those I mentioned in https://github.com/romkatv/zsh4humans/issues/270#issuecomment-1618593891. I realize that these docs may very well be inadequate for your task.

**Comment by danielkrajnik** [comment]
Sorry, just to be sure - if your shell was slowing down on start how would you troubleshoot it?

I'd be grateful for your help.

**Comment by romkatv** [comment]
I cannot describe what I would do. I don't know that.

**Comment by danielkrajnik** [comment]
Can I ask another question - is there any way to temporarily remove zsh-syntax-highlighting for z4h from loading (as an example) if you suspect that it may be causing an issue?
