### ISSUE TITLE
Warp integration not working with integrated tmux mode

### ISSUE THREAD

**Issue by esambo** [romkatv/zsh4humans#272]
[Warp.dev](https://www.warp.dev) mentions _zsh4h (ZSH for Humans)_ in the [List of incompatible tools](https://docs.warp.dev/help/known-issues#list-of-incompatible-tools). 
Although, after a bit of trial and error, I noticed that it does work if I do one of the following in my `~/.zshrc`:
- disable `z4h init || return`
- not using the [integrated tmux](https://github.com/romkatv/zsh4humans/blob/master/tips.md#tmux) mode where `zstyle ':z4h:' start-tmux` line is removed

It might be helpful to mention this somewhere, e.g. in the configuration template file, or the README or the TIPS.

**Comment by romkatv** [comment]
I don't want to document these workarounds because they may stop working and also because they actually disable a massive chunk (removing `z4h init` disables virtually the whole z4h).
