### ISSUE TITLE
Error while installing zsh4humans 

### ISSUE THREAD

**Issue by ciscohack** [romkatv/zsh4humans#273]
Hi Roman,

I am having some errors while installing the zsh4humans tool. please help me to fix this issue. I know you are not doing any active work on this beautiful project but I request you, please help me to get out of this error... I think this error is not a major issue but locale play an important role in some places. please spice up this tool once again with some new features ..

Have you seen oh-my-posh it has lots of cool theme can we achieve it through powerlevel10K by default some of

**Comment by romkatv** [comment]
Sorry, I don't provide user support in this project.

**Comment by ciscohack** [comment]
I can understand Roman and respect your decision... I was aware but thought to take your help to solve my problem.. But no issue thank you sir... I wish some day this wonderful project gets a life once again or you start some thing even better again... Or if any always new project started help me to know for testing... Thanks once again
