### ISSUE TITLE
[Question] Way to disable "ambiguous completions automatically start fzf?"

### ISSUE THREAD

**Issue by PlusEVPlease** [romkatv/zsh4humans#274]
Is there a way to disable:

Ambiguous completions automatically start [fzf](https://github.com/romkatv/zsh4humans#interactive-search-with-fzf)

I really like the project but this feature drives me crazy. Fzf is cool but I would rather launch it when intend to rather than when I was not specific enough for the completion.

**Comment by romkatv** [comment]
No, there's no option for that.
