### ISSUE TITLE
"z4h: standard input is not a TTY" on Alacritty startup

### ISSUE THREAD

**Issue by svalbardsleeperdistrict** [romkatv/zsh4humans#276]
I've been getting this message on startup in Alacritty after replacing bash with zsh. I've used this installation many times in the past, including in my current distro, and it has never resulted in this message. It does not prevent any functions that I use in Alacritty, but is annoying.

I did some search on this, but the only results I'm getting are emacs/git-related solutions when running some command that results in this.

I'm running Nobara 38 with Gnome 44.2.

**Comment by romkatv** [comment]
What do you do that results in the error message saying "z4h: standard input is not a TTY"? This message is printed by the installer. You run the installer only once. You should not run it on every Alacritty startup.

**Comment by svalbardsleeperdistrict** [comment]
> What do you do that results in the error message saying "z4h: standard input is not a TTY"? This message is printed by the installer. You run the installer only once. You should not run it on every Alacritty startup.

Nothing, I just run Alacritty before that is posted. I will check Alacritty config files to see if any installation script somehow got into there and is being executed on startup. Thanks for the reply.

**Comment by svalbardsleeperdistrict** [comment]
I could not find anything relevant in rc.conf, but just re-ran installation and now it runs without the error.
