### ISSUE TITLE
Installing zsh4humans without internet connection

### ISSUE THREAD

**Issue by codyhan94** [romkatv/zsh4humans#277]
On a server without outside connection to the internet, but where I am able to copy source packages downloaded from a local machine, how would you manually install zsh4humans? Starting point would be with the following downloaded:

1. all of the github archives for fzf, powerlevel10k, systemd, zsh-completions, ... found in -z4h-install-one
2. zsh4humans v5

**Comment by romkatv** [comment]
How are you connecting to the machine? Over SSH?

**Comment by codyhan94** [comment]
yes, over SSH on a windows machine, openssh 8.1.0.1

**Comment by romkatv** [comment]
If the remote machine has the same OS kernel and CPU, you can run this command on your local machine to copy z4h over to the remote:

```zsh
tar -C ~ -chz .{zshrc,zshenv,p10k.zsh}{,.zwc}(N) .terminfo .cache/zsh4humans |
  command ssh HOSTNAME 'tar -C ~ -xz' &&
  command ssh HOSTNAME 'Z4H_BOOTSTRAPPING=1 . ~/.zshenv'
```

Replace `HOSTNAME` with the actual hostname/ip before running the command.

If you are using WSL on your local Windows host and Linux on the remote host, this should work.

**Comment by codyhan94** [comment]
I connect to the remote machine through windows without WSL, but I copied over the files from my setup and untarred/sourced zshenv as you suggested, and it works. There's a little funny business in tmux; when I exec zsh in tmux it tries to download tmux since my old config did not have a tmux setup, but that's OK, I have the tmux features in z4h turned off since I have tmux configured outside of z4h.

There's one slight startup speed issue that I can't track down (that seems less pronounced with my old setup which was also using p10k); every once in a while when I open a new terminal tab from windows terminal (which logs into the remote machine via `ssh username@hostname`), all of my config loads but the shell prompt takes a while to appear. I can type keystrokes that appear on the prompt when it shows up, but nothing until then. If I place `zmodload/zprof` at the start of my zshrc and `zprof` at the end, it prints out all of the zprof lines and hangs for a moment until the prompt shows up. If I place an `echo "done with zshrc"` after the zprof call, that also shows up before the prompt does. The sum of time spent in each function and its descendants never adds up to more than ~100ms, which is far shorter than the delay that I'm seeing occasionally.

This only happens if I don't open a new terminal/session for a while, and does not seem to happen in tmux.

As far as I can tell, I am using the instant prompt that comes configured with z4h.

What I've tried:
- Move as many things to local disk as possible in my config to reduce NFS latency (zsh binary, most of the paths in my fpath)
- Check the zcompdump file to make sure it's not getting regenerated over and over (it's not, zprof would show this too)

Some extra possibly related context:
- My "shell" as reported by chsh is `/bin/bash` and I do not have permissions to change this
- I use a `~/.profile` file suggested by https://unix.stackexchange.com/questions/136423/making-zsh-default-shell-without-root-access to start zsh on login. Its contents are
```
export SHELL=/path/to/local/zsh
exec /path/to/local/zsh -l
```

I'm closing the issue with this comment as the question has been answered satisfactorily, any extra help or suggestions you could make to help me track down this (startup?) delay would be appreciated but it's not a big deal.

**Comment by romkatv** [comment]
The slowdown you are describing sounds like instant prompt being disabled. This can happen if one interactive zsh has one value of `TERM` and the next has a different `TERM`. For example, if you run plain `zsh` when you ssh and then manually run `tmux` from it, you'll have no instant prompt. The workaround is to run `tmux` over ssh bypassing the intermediate shell. Alternatively, instruct z4h to start tmux for you.

**Comment by codyhan94** [comment]
Would it be possible to prevent instant prompt from being disabled by
configuring tmux to not use a different value of TERM? Or the same one as
my normal session? I like to keep one tmux session open (that I manually
start as you mentioned) but use new windows and tabs on the side without
tmux.

Is there a way that I can conclusively determine that what you're talking
about regarding instant prompt being disabled is happening?

Thanks for the help.

**Comment by codyhan94** [comment]
I printed out the value of TERM at the end of my zshrc and found that it
was xterm-256color outside of tmux and tmux-256color inside tmux.

I added `set-option -g update-environment "TERM"` to my tmux config to have
it inherit the value from outside.

Maybe it would be better to set it to tmux-256color in my zshenv outside
but I don't believe I use anything inside tmux that relies on tmux specific
behavior so I will run with this for now.

Thank you for the compliment and help :)

**Comment by codyhan94** [comment]
Actually got confused about what setting made it work - had to set

set -g default-terminal "xterm-256color"

in tmux conf. This apparently can break some things inside tmux but I have
not noticed any issues.

**Comment by codyhan94** [comment]
No - I do not, as my (work) machine does not have WSL. So I just ssh via
powershell/command prompt.

**Comment by codyhan94** [comment]
I tried doing the following in my windows ssh config:

RemoteCommand /path/to/tmux -u -2 new || /path/to/tmux -u

and changed the ssh command for my terminal profile to ssh -t.

Now new terminal windows create new sessions and everything has TERM set to
tmux-256colors.

For fun/to test, I ran `tmux kill-server` and removed the tmux directory in
/tmp. When I try to connect after that, I get a connection but no prompt; I
can enter characters and keystrokes but it is not interactive. If I set
RequestTTY to force in my local ssh config, it starts a tmux server but it
does not source my tmux settings.

Haven't found an answer to this in my searching yet, but I can work around
it for now by starting tmux once manually first.

**Comment by codyhan94** [comment]
It may be worth noting that I sometimes start a terminal here through
VSCode's integrated terminal which appears to set term to xterm-256color as
well. I believe that would cause issues with this setup if I always use
tmux outside of it.

Can you point me to some references about tmux being incompatible with
TERM=xterm-256colors? for all of my searching I haven't found any specific
examples and I haven't run into anything yet.

**Comment by romkatv** [comment]
From `man tmux`:

> For tmux to work correctly, [default-terminal] must be set to ‘screen’, ‘tmux’ or a derivative of them.

**Comment by romkatv** [comment]
You can the incompatibility by comparing the output of `infocmp screen` and `infocmp xterm`.
