### ISSUE TITLE
Undefine Keys

### ISSUE THREAD

**Issue by euh2** [romkatv/zsh4humans#280]
In [fn/-z4h-init-zle](https://github.com/romkatv/zsh4humans/blob/e2db4190502df9758f1b6a1792069de10dc14be0/fn/-z4h-init-zle#L478C3-L478C63) the letter `ø` is assigned to `z4h-stash-buffer`. How can I undo this in my .zshrc? I sometimes need this letter in my shell.

**Comment by romkatv** [comment]
`bindkey -r 'ø'`

**Comment by euh2** [comment]
> bindkey -r 'ø'

Thanks!
