### ISSUE TITLE
SSH teleport is not working in WSL when SSH config folder is mounted with fstab

### ISSUE THREAD

**Issue by mcshosho** [romkatv/zsh4humans#281]
When ssh config folder form Windows is [mounted](https://blog.gabrielmajeri.ro/2022/01/21/how-to-share-ssh-credentials-between-windows-and-wsl-2.html) with fstab on a WSL instance (Ubuntu, does not matter the version 22.04 or 23.10), ssh connection fails with this error: 

```shell
unix_listener: cannot bind to path /home/andrei/.ssh/s/e8ce35630dc6ae7e3892ed896558821d73a6618f.lemWZfRZ3qy2fx0n: Operation not supported
```

The temporary solution is to change in -z4h-ssh-cmd ControlPath to be somewhere outside of ".ssh" folder (like .tmp/s instead of .ssh/s), but this change is overwritten at next "z4h update" command. 

Can this folder (or whole ssh comand parameters block) be set as a configurable item?

**Comment by romkatv** [comment]
Create `~/.ssh/config` with the content suggested by https://github.com/romkatv/zsh4humans/blob/master/tips.md#ssh-config and modify `ControlPath` in there.

**Comment by mcshosho** [comment]
Thanks. This kind of solved my initial problem, but now I got into another one: ControlPath is not supported on Windows side, which means that I can't use the same config file on Windows and WSL in same time.

**Comment by romkatv** [comment]
That's unfortunate. This falls into the category of issues that I'm not going to work on (see the disclaimer at the top of https://github.com/romkatv/zsh4humans). If you find a solution, please post an update here.

**Comment by mcshosho** [comment]
I found the solution: in WSL add the [ssh configuration](https://github.com/romkatv/zsh4humans/blob/master/tips.md#ssh-config) configuration not in ~/.ssh/config directly, but into another file ~/.ssh/wsl_config.

**Comment by romkatv** [comment]
Thanks for posting the solution!
