### ISSUE TITLE
Is it necessary to be online to initialize z4h?

### ISSUE THREAD

**Issue by danielkrajnik** [romkatv/zsh4humans#282]
On slow internet connection it may take a few seconds for zsh shell with z4h to startup. Sorry, but it's unclear which function specifically is causing it, but I'd be grateful for any hint as to, which features are likely to require inernet connection and whether it's possible to disable them?

**Comment by romkatv** [comment]
z4h always says when it's downloading something. If it's not saying that, then it's not using network.

**Comment by danielkrajnik** [comment]
Thank you, it must be something else that's causing slowdowns. I've tried restarting the machine with all network card unplugged, but the shell came up fine.

I remember this issue becoming more apparent on very slow wifi connections (e.g. coffee shops). I will be roaming in a couple days and will test it again if anything comes up.
