### ISSUE TITLE
Is it possible to only install the ssh teleportation part of z4h?

### ISSUE THREAD

**Issue by Samsu-F** [romkatv/zsh4humans#283]
Hi,
z4h looks fantastic, but since I already have tons of my own configuration exactly to my liking, I am only interested in the ssh teleportation. Is it possible to just use this feature without the rest?

**Comment by romkatv** [comment]
Not possible.

**Comment by adRn-s** [comment]
You can try a tool like [xxh](https://github.com/xxh/xxh), good luck!

**Comment by Samsu-F** [comment]
All right, thank you for the quick answers!
