### ISSUE TITLE
fzf <ctrl-r> + searchable command history not activating

### ISSUE THREAD

**Issue by TheOdd** [romkatv/zsh4humans#289]
Hi! I recently installed z4h, moving over from oh-my-zsh, and I have a few strange issues. When pressing <kbd>CTRL</kbd>-<kbd>R</kbd>, nothing happens; no `fzf` prompt appears. Similarly, if I type out a command prefix (i.e. `grep`) and then press <kbd>Up</kbd>, it just cycles through the most recent commands, regardless of prefix. Other features seem to be working, like the autocompletion. I've tried running a zsh instance both in and out of a tmux instance, completely shutting down all zsh instances, and updating/re-sourcing z4h, but none of those have helped.

I'd love some ideas on how to troubleshoot this, and please let me know if there's any information I can provide to make this easier.

**Comment by romkatv** [comment]
Have you made any changes to zsh startup files after installing zsh4humans? If yes, please reinstall and try without any changes. If the problem persists, post all zsh startup files and let me know the OS and the terminal you are using.

**Comment by TheOdd** [comment]
Yep, I made some minor changes to the zshrc after installation, which seems to be what's breaking the feature. A default installation works fine. I'll do a little more digging to figure out what line exactly did it in case anyone else has the problem.

**Comment by TheOdd** [comment]
Ah, this is embarrassing, it was a `bindkey -v` near the end of the file. I know I saw somewhere in the documentation about enabling vim bindings properly, I didn't realize I still had that in there. Sorry for the trouble!

**Comment by romkatv** [comment]
No worries! Thanks for posting your findings after resolving the issue.
