### ISSUE TITLE
Configure ssh_config to use z4h ssh 

### ISSUE THREAD

**Issue by Syphdias** [romkatv/zsh4humans#29]
I am wondering if it is possible to use `z4h ssh` for some host when connecting via the `ssh` command.
I tried to use `ProxyCommand` but with little success. I tried stuff like using `zsh -ic 'z4h ssh %h'` or sourcing: `source ${Z4H:=${XDG_CACHE_HOME:-$HOME/.cache}/zsh4humans}/romkatv/zsh4humans/fn/-z4h-ssh %h`. The most far I could get was getting spammed by "Pseudo-terminal will not be allocated because stdin is not a terminal."

Any way to make this work or is it a bad idea to begin with? Would `scp` break for example.

**Comment by romkatv** [comment]
I'd do this by defining function `ssh`. Nothing should break. Unfortunately, this would require that you figure out hostname by yourself. In practice looking at the last argument would suffice. You'll still be able to use plain `ssh` via `command ssh`, which is nice.

By the way, one of the things that I know isn't good in the current incarnation of `z4h` is `z4h ssh`. I think I know how to implement this properly but I don't know when I'll have the time. The issues aren't bugs, so you can use `z4h ssh` just fine if it does what you want. What I don't like is that it's missing crucial features.

- Cannot specify which files to send.
- Cannot specify whether to override files.
- Cannot push large amount of data.
- Cannot push history.
- Cannot pull history back.

Moving history back and forth would be really awesome.

**Comment by Syphdias** [comment]
> I'd do this by defining function `ssh`. [...] figure out hostname by yourself.

Yeah, an easy workaround but would be kind of cool to have it in the `ssh_config`.
Dirty first draft if anyone is interested:
```
function ssh() {
    local -a z4h_ssh_hosts=(host1 host2)
    for h in $z4h_ssh_hosts; do
        if [[ $@[(I)$h] != 0 ]]; then
            z4h ssh $@
            return
        fi
     done
     command ssh $@
}
```

> Moving history back and forth would be really awesome.

Indeed, but like with `z4h-stash-buffer` it could be weird if remote commands would show up in the history.

**Comment by romkatv** [comment]
> Indeed, but like with `z4h-stash-buffer` it could be weird if remote commands would show up in the history.

I guess it was weird the first time people saw a carriage move without a horse.

The ability to send history to remote host and to retrieve it from remote host will be optional. I'll use it. Others are free not to use it. Same deal as with `z4h-stash-buffer`.

**Comment by Syphdias** [comment]
> I guess it was weird the first time people saw a carriage move without a horse.

To the future!

I'll close this issue, since there is a workaround via function even if it's not quite what I was looking for.
