### ISSUE TITLE
Integrated tmux print underlines without color

### ISSUE THREAD

**Issue by edshamis** [romkatv/zsh4humans#290]
Integrated tmux print underlines without color, while with tmux set to no: underlines are printed with colors. I expect colored underlines in integrated tmux as well.
Tested with `printf "\x1b[58:2::255:0:0m\x1b[4:1msingle\x1b[4:2mdouble\x1b[4:3mcurly\x1b[4:4mdotted\x1b[4:5mdashed\x1b[0m\n"` on new user account with fresh z4h install in Wezterm terminal.

**Comment by romkatv** [comment]
Unfortunately, it's not the kind of issue that I'm willing to spend my time on. I recognize that it's likely a bug or at least an indication of a missing feature in z4h, but still: I won't offer to look into it. Sorry.
