### ISSUE TITLE
Version of fzf installed doesn't support --preview-window

### ISSUE THREAD

**Issue by pnodet** [romkatv/zsh4humans#291]
Using fzf with `--preview-window=down,3,wrap` fails on my mac with message: invalid preview window option: down,3,wrap

`--preview-window=down` works but not combined with other options.
This preview window setting is used by some other tools I use like zoxide. 

Installing the latest version solves this issue, but not sure if some z4h features  relies on outdated options

Version installed by z4h:
```
❯ fzf --version
0.25.1 (f55c990)
```

Version installed by brew:
```
❯ fzf --version
0.46.1 (brew)
```

**Comment by romkatv** [comment]
> not sure if some z4h features relies on outdated options

If you encounter an issue, please let me know.
