### ISSUE TITLE
How can I make TAB completion case sensitive?

### ISSUE THREAD

**Issue by dserodio** [romkatv/zsh4humans#292]
First, thank you for this great project. I gave up on the .zshrc I'd been maintaining manually for over 10 years and replaced it with zsh4h :)

I have one question, please forgive me if this is not the best place to ask:
How can I make TAB completion case sensitive?

I have a file called `list-deployments` in my home directory, and is the only file that begins with `li`. If I type `cat li<TAB>` I expect it to complete with the filename, but instead it opens a fzf widget including `list-deployments` but also listing all directories under `Libraries/` instead of completing the filename directly as I expected.

Thanks!

**Comment by romkatv** [comment]
Put this in `.zshrc` under `z4h init`:

```zsh
zstyle ':completion:*' matcher-list ''
```

**Comment by dserodio** [comment]
Thank you very much for the prompt reply, it's now working as I expected.
