### ISSUE TITLE
zsh-completions won't update its completion files when using `z4h update`

### ISSUE THREAD

**Issue by Farid-NL** [romkatv/zsh4humans#293]
Tinkering with nvm an its awful loading time in the shell I figured that some arguments where missing when using the completion feature. The `exec` argument was missing.

z4h uses [zsh-completions](https://github.com/romkatv/zsh4humans?tab=readme-ov-file#completing-commands) for additional completions, so I compared both `_nvm` files in `$HOME/.cache/zsh4humans/v5/zsh-completions` and in the [gh repo](https://github.com/zsh-users/zsh-completions/blob/master/src/_nvm). They are different.

I use V5 of Z4H

Steps to reproduce:

1. Run `z4h update`
2. Compare `_nvm` files in `$HOME/.cache/zsh4humans/v5/zsh-completions` with [gh repo](https://github.com/zsh-users/zsh-completions/blob/master/src/_nvm)
3. Notice that the local `_nvm` file is not updated

I tried to [uninstall](https://github.com/romkatv/zsh4humans?tab=readme-ov-file#uninstalling) Z4H with no avail, the issue it's still there

Also I noticed that when `ls -la $HOME/.cache/zsh4humans/v5/zsh-completions` the `.git` directory is missing, maybe that's why?

Here's the [diff](https://github.com/zsh-users/zsh-completions/commit/27e61dfbaf7984b18a7c5cdde7c42d04636c7f89) if it's worth something

**Comment by romkatv** [comment]
The core dependencies of z4h are vendored: `z4h update` gives you the latest version of zsh-completions that I've looked at and blessed as stable.

I've blessed a new version just now. Please run `z4h update` and let me know whether it fixes the issue.

**Comment by Farid-NL** [comment]
Gotcha, they're vendored. 
It fixed the issue. Thank you so much.

**Comment by romkatv** [comment]
Thank you for verifying.
