### ISSUE TITLE
Vi mode/bindings with tab completion menu

### ISSUE THREAD

**Issue by ManuGraiph** [romkatv/zsh4humans#294]
Hi!

For some reason (i'm on zsh), when i have vi-mode set with `bindkey -v` and a couple other bindings (none on tab), the completion/suggestion menu doesn't work when i press tab. It's just that, if i comment the bindings and bindkey -v, it works properly.

Any idea what could it be?

Thanks in advance!

**Comment by romkatv** [comment]
Please post a .zshrc where TAB works, and another one (as similar as posssible to the first) where it does not.

**Comment by ManuGraiph** [comment]
I managed to fix it! The vim-mode was removing the zh4-fzf-complete binding, i had to explicitly write it for N/I modes and then it works.

Thanks a lot anyway!

**Comment by romkatv** [comment]
Great! Thanks for posting an update describing your solution.

**Comment by ManuGraiph** [comment]
Oh, another question about the same topic...

I saw that the completion menu can be shown in the upward direction instead of below the prompt, which is specially useful when you use the prompt at bottom; how can i configure it to show the complete menu that way (above the prompt)?

**Comment by romkatv** [comment]
It's automatic if remove `start-tmux no`. See https://github.com/romkatv/zsh4humans/blob/master/tips.md#tmux

**Comment by ManuGraiph** [comment]
Worked flawless, thanks a lot!

But this means it now runs zsh in a tmux session?

**Comment by romkatv** [comment]
Yes and no.
