### ISSUE TITLE
bug: .zshrc turned into numbers on backup folder

### ISSUE THREAD

**Issue by its-19818942118** [romkatv/zsh4humans#295]
alright so i just installed this framework but boy was that my biggest mistake of my life that just ruined everything now i am pissed. cuz broo it said it gonna backup my zshrc in zsh-backup folder but it turned it into ```20240323-235507``` this file. and there is nothing in it. i lost every single configs in my zshrc. i thought because oh-my-zsh was great it would be good too. the main reason i installed this was so that i get a bottom prompt now i lost everything. just great ruined my day. **** pls reveiw stuff. even if not many people use it or just blindly trusts projects like me. and do better although i know i couldnt pull off great projects and its not my place to say all this

**Comment by its-19818942118** [comment]
💯 👎🏻

**Comment by romkatv** [comment]
What is the output of the following command?

```zsh
ls -Rl -- ~/zsh-backup
```

**Comment by its-19818942118** [comment]
oh wait my bad i am extremly sorry for being rude its just that i was too depressed. pls dont take it to heart. cuz when i nvimed into the the numbers. it just showed it a file and not as a directory. i even ls -a to it but it didnt show anything. i am extremly sorry.

> What is the output of the following command?
> 
> ```shell
> ls -Rl -- ~/zsh-backup
> ```

**Comment by its-19818942118** [comment]
pls dont hate me or feel disheartened. its my fault

**Comment by its-19818942118** [comment]
the thing is before installing zsh4humans. my system update failed due to power outage and i didnt notice. and all and all stuff just happened.

**Comment by romkatv** [comment]
No worries.

Is everything alright now? Were you able to restore your zsh startup files?

**Comment by its-19818942118** [comment]
i shouldnt have vented up on here.

**Comment by romkatv** [comment]
Don't worry about. Enjoy the rest of the weekend!
