### ISSUE TITLE
[question]: How to remove p10k. and prompt on bottom option doesnt seem to work

### ISSUE THREAD

**Issue by its-19818942118** [romkatv/zsh4humans#296]
@romkatv Hey sorry to bother. after being rude and all. i decided to give z4h a second chance.
but to be honest. p10k is very configurable. but i dont really like it. so i am trying to remove it. also the bottom prompt option doesnt seem to work. sorry for bothering you. once again thank you

**Comment by romkatv** [comment]
> the bottom prompt option doesnt seem to work

See https://github.com/romkatv/zsh4humans/blob/master/tips.md#prompt-at-bottom. Note the reference to https://github.com/romkatv/zsh4humans/blob/master/tips.md#tmux.

> p10k is very configurable. but i dont really like it. so i am trying to remove it.

There is an option that disables powerlevel10k:

```zsh
zstyle :z4h:powerlevel10k channel none
```

This option is meant for debugging. I can offer no guarantees, even informally, about the functionality of z4h when you disable powerlevel10k. If anything breaks, you'll be on your own.

It's worth noting that I have intimate knowledge of all popular zsh themes and I'm not aware of a good reason to use any theme other than powerlevel10k with z4h. It's likely that whatever you are trying to achieve is not only possible with powerlevel10k but better.

**Comment by its-19818942118** [comment]
i am using p10k. but i prefer starship over p10k as starship is cross platform and all my prompts are same across shell :). but yeah sure if it breaks then i will try to fix it. if i can

**Comment by its-19818942118** [comment]
i will give you an update
but there seems to be no greeter. in oh-my-zsh. so i was planning to see what my puny knowledge of scripting and chatgpt goes.

**Comment by romkatv** [comment]
Sure, it's your choice.

If you google "starship vs powerlevel10k", you'll find posts like this: https://www.reddit.com/r/zsh/comments/10k0g93/starship_or_powerlevel10k/

**Comment by romkatv** [comment]
Also keep in mind that with z4h you don't need to use other shells, not even on remove machines to which you connect over ssh.

If I've answered your questions here, let's close the issue.

**Comment by its-19818942118** [comment]
> > the bottom prompt option doesnt seem to work
> 
> See https://github.com/romkatv/zsh4humans/blob/master/tips.md#prompt-at-bottom. Note the reference to https://github.com/romkatv/zsh4humans/blob/master/tips.md#tmux.
> 
> > p10k is very configurable. but i dont really like it. so i am trying to remove it.
> 
> There is an option that disables powerlevel10k:
> 
> ```shell
> zstyle :z4h:powerlevel10k channel none
> ```
> 
> This option is meant for debugging. I can offer no guarantees, even informally, about the functionality of z4h when you disable powerlevel10k. If anything breaks, you'll be on your own.
> 
> It's worth noting that I have intimate knowledge of all popular zsh themes and I'm not aware of a good reason to use any theme other than powerlevel10k with z4h. It's likely that whatever you are trying to achieve is not only possible with powerlevel10k but better.

yeah a problem. none of it seem to work. i think something is broken

**Comment by its-19818942118** [comment]
i dont use tmux. and keybindings dont work except ctrl+L. plus i am using kitty terminal. on arch linux. idk if that is hindering something or not

**Comment by romkatv** [comment]
It's possible that z4h isn't the right choice for you. No harm in trying something else. Perhaps a project with active support (z4h does not have that).

**Comment by its-19818942118** [comment]
damn i really wanted to try the bottom prompt. **sigh** 
i guess karma for being rude

**Comment by its-19818942118** [comment]
oh well thanks though for your time and support. i might disturb you in the feature

**Comment by romkatv** [comment]
Sure thing.

**Comment by poslat-pismo** [comment]
is it possible to include "prompt ay bottom" in p10k without z4h?

**Comment by romkatv** [comment]
no
