### ISSUE TITLE
Aliasing an existing command to multiple commands hangs the line editor

### ISSUE THREAD

**Issue by dancek** [romkatv/zsh4humans#299]
Making an alias like
```
alias ls="echo hello && ls"
```
causes typing the command name to hang the line editor. This seems to happen with existing commands but not if the aliased name doesn't overlap an existing command.

**Comment by romkatv** [comment]
Fixed.

**Comment by romkatv** [comment]
Please run `z4h update` and let me know whether the problem is fixed for you.

**Comment by dancek** [comment]
Yes, the bug is fixed. Thank you!
