### ISSUE TITLE
error in debian

### ISSUE THREAD

**Issue by smenzer** [romkatv/zsh4humans#3]
Hi again! I got everything working beautifully on my mac, so I started moving it to my servers. Doing so, though, is giving me an error:

```bash
$ zsh
z4h:29: unknown file attribute: \n
```

It then spits out what looks like my bash PS1 but all with the encoded characters:

```bash
$ zsh
z4h:29: unknown file attribute: \n
\[\033[00m\][\[\033[0;32m\]\H\[\033[00m\]:\[\033[01;36m\]\w\[\033[00m\]] [\[\033[0;94m\]\D{ 17:56 }\[\033[00m\]]\[\033[0;33m\]$(__git_ps1)\n$\[\033[00m\]
```
I can't seem to figure out why this is happening...is it something to do with the `z4h` file (seems to be pointing to line 29, but that line didn't seem wrong to me)

Any ideas? Let me know if you need any other info to help debug or point me in a direction...

Some background info:

```bash
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

$ zsh --version
zsh 5.0.7 (x86_64-pc-linux-gnu)
```

**Comment by romkatv** [comment]
It won't work on zsh < 5.1.

**Comment by romkatv** [comment]
Debian Jessie is going to EOL in a few months. Time to upgrade? You can also upgrade just zsh.

The requirement for zsh >= 5.1 [comes from powerlevel10k](https://github.com/romkatv/powerlevel10k#what-is-the-minimum-supported-zsh-version) and it's very difficult to remove.

You could use another theme but you would lose a lot of value from this setup.

**Comment by smenzer** [comment]
Ok, I'll try to get it upgraded to 5.1.

Yea, probably will need to upgrade the OS, but I don't manage that, my CTO does :)

Thanks!

**Comment by romkatv** [comment]
> Ok, I'll try to get it upgraded to 5.1.

If you can upgrade, might as well get 5.8 (the latest) or at least 5.7.1 (Buster has it). In the worst case 5.4.2 (Stretch has it). You'll have massive increase in zsh performance if you get at least 5.4.2.

I suppose on mac you are using Zsh from brew?

**Comment by smenzer** [comment]
Ok cool...sounds like we can upgrade to Stretch for sure, so that's good.

on my mac i have this ... i'm pretty sure i'm just using the OS X default... 

```
❯ zsh --version
zsh 5.7.1 (x86_64-apple-darwin19.0)
```

and my `brew list` doesn't include zsh, so i must not have installed with brew.

**Comment by romkatv** [comment]
You have Catalina. It ships with 5.7.1. Good. Previous versions shipped 5.3, so you had to use brew.

**Comment by jkrauska** [comment]
Can you update README to say zsh > 5.1 is required?

RHEL/Centos 7 still uses 5.0.2

**Comment by romkatv** [comment]
> Can you update README to say zsh > 5.1 is required?

Done.
