### ISSUE TITLE
Support MSYS2/MINGW64

### ISSUE THREAD

**Issue by pedrohgmacedo** [romkatv/zsh4humans#301]
When I tried to install zsh4humans in an MSYS2 platform, it complains that it is unsupported (unsupported platform: MINGW64_NT-10.0-22631 x86_64). 
I would like to know if it is too dificult to support it, or any pointers on where to begin working if I wanted to patch it myself.

**Comment by romkatv** [comment]
I'm afraid I cannot afford to spend time on this in any capacity, be it providing pointers or answering questions.
