### ISSUE TITLE
getting annoying symbol

### ISSUE THREAD

**Issue by gopi2507** [romkatv/zsh4humans#302]
<img width="1680" alt="image" src="https://github.com/romkatv/zsh4humans/assets/51022180/1ee99c78-c912-4e85-9884-e983db0c7787">

**Comment by romkatv** [comment]
If you are referring to the blue triangles on the left, these are drawn by iTerm2. You can disable them via *Preferences* → *Profiles* → *(your profile)* → *Terminal*, scroll down to *Shell Integration*, and turn off *Show mark indicators*.

**Comment by gopi2507** [comment]
found the mark indicators option.
