### ISSUE TITLE
SSH HOST suggestion issue

### ISSUE THREAD

**Issue by gopi2507** [romkatv/zsh4humans#303]
getting add on characters at end "$'\r'"

<img width="587" alt="image" src="https://github.com/romkatv/zsh4humans/assets/51022180/032aa906-c380-4b9e-ad29-61ad419abaf0">

**Comment by romkatv** [comment]
I suppose the file from which this completion comes has CRLF instead of LF. Could be `~/.ssh/config` or something else. If you figure out which file that is, remove CR from it. And maybe figure out why it got that way in the first place so that it does not happen again.
