### ISSUE TITLE
Question/Issue with terminfo and alacritty

### ISSUE THREAD

**Issue by Syphdias** [romkatv/zsh4humans#307]
Hi Roman, I hope you are doing well!

A few months back I noticed that undercurls did not work properly in neovim. They were just white lines instead of red undercurls.

I found https://github.com/neovim/neovim/issues/21182 and thought I found a way to fix it. But after a while it appeared again. But at least I knew how to "fix" it. Two things seem to work:
- deleting `~/.terminfo/a/alacritty` or
- copying over the terminfo form the package `/usr/share/terminfo/a/alacritty` to `~/.terminfo/a/alacritty`

Today I discovered what reverted to the broken state: `z4h update`. There is one line that looks suspicious to me:
```
z4h: updating terminfo
```

This is probably not z4h itself but using `terminfo` that does something or the `zsh/terminfo` module. I couldn't trigger the breakage without `z4h update` though.
I do not know where to report this properly. The core issue could be in a bunch of places.

**Comment by romkatv** [comment]
Thanks for the bug report. Should be fixed now. Please run `z4h update` and let me know if it works for you.

**Comment by Syphdias** [comment]
Jup, that worked. Thank you!

Why do you use your own database of terminfos? Is that for compatibility or maybe used for `z4h ssh`?

**Comment by romkatv** [comment]
This is mainly for `z4h ssh`: servers are often lacking terminfo definitions for exotic terminals like `alacritty` or `tmux-255color`.
