### ISSUE TITLE
[Question/Bug] tmux prompt at the bottom

### ISSUE THREAD

**Issue by Semnodime** [romkatv/zsh4humans#308]
Is it expected behavior that the **prompt inside tmux resides at the bottom**?
If yes, can this be **configured** somhow?
If no, **why** not?
Thanks!
![demo](https://github.com/romkatv/zsh4humans/assets/19511852/2c9bc94c-5a05-4118-9365-c4451aef79e6)

**Comment by romkatv** [comment]
> Is it expected behavior that the **prompt inside tmux resides at the bottom**?

Yes.

> If yes, can this be **configured** somhow?

Yes.

https://github.com/romkatv/zsh4humans/blob/master/tips.md#prompt-at-bottom

**Comment by Semnodime** [comment]
I was able to comprehend your motivation for choosing the default setting to have the prompt reside at the bottom as per your explanation in https://github.com/romkatv/powerlevel10k-media/issues/2#issuecomment-725277867
> [A] non-constant prompt position means you cannot set up your terminal window in such a way that it's always convenient to look at the most important information in it -- the prompt and the output of the last command.
> This issue has been bothering me enough that I've configured my own shell to always have prompt at the bottom.

So it's rather a feature than a bug.

I just noticed this (contemporarily) uncommon behavior and enquire your motivation as well as did some people before me:
https://github.com/romkatv/zsh4humans/issues/246

Since it's the place hosting your most concise argumentation for having the prompt reside at the bottom, I'll continue communication over there.
