### ISSUE TITLE
Report invalid zstyle options

### ISSUE THREAD

**Issue by Semnodime** [romkatv/zsh4humans#309]
[  zstyle :z4h: start-tmux [arg]...](https://github.com/romkatv/zsh4humans/blob/d2bb1377863272299693aa5086b934f15b32f87f/changelog.md?plain=1#L49-L54)

When fiddeling with my `.zshrc`, I noticed this option and wanted to experience it's feature-set.
Thus I soon convinced myself to try the implied other option and set it to `zstyle ':z4h:' start-tmux 'yes'`.

As I read through code, manual and options (due to grappling with a different issue), I noticed that doing so had no effect, since `yes` is an invalid option for the `start-tmux` setting and concluded that **zsh4humans then proceeds silently by defaulting** to `no`.

**I hereby suggest to**
- have z4h **report invalid options** in some way.
- include some **comment** along each setting with non-trivial **valid option strings** which informs the user about those.
- use only option strings different from both `yes` and `no` (or anything similar) in case the **setting is not binary** (or might not be in the future)

Note that the requested comment might already exist for `start-tmux` specifically, I can't tell since my `.zshrc` is quite old and it lacks a version identifier which could (be used to) inform me of changes since running the z4h installer.

**Comment by romkatv** [comment]
I provide very limited support to zsh4humans. Types of requests in the order of likelihood of my addressing them, from highest to lowest:

1. Something cannot be accomplished without modifying zsh4humans.
2. Something can be done with zsh4humans but the requestor is unable to figure out how.
3. The requestor has already figured out how to achieve what they want. They are now asking for improvements that could have made their past journey easier. Alternatively, they are trying to make the life of future users easier.

If I understand the description of this issue correctly, it falls into the last category: you've already figured out how to achieve what you want. If so, the requested improvements are outside of the level of support I provide.
