### ISSUE TITLE
Disable fzf-tab and iTerm2 alt/option key issue

### ISSUE THREAD

**Issue by tumd** [romkatv/zsh4humans#31]
Hi,

I would like to give z4h a try, but currently what's holding me back is the fzf-tab behavior.
What is the recommended way to disable fzf-tab and restore the default tab-completion?

---

In iTerm2 the alt-arrow key-mapping doesn't work. It only outputs `[C`& `[D`.
Here is the output from `cat`. First is alt-right, second is alt-left.
```
❯ cat
^[^[[C
^[^[[D
```

If I install and source `belak/zsh-utils/editor/editor.plugin.zsh` the alt-arrows works as expected.
Thank you for another interesting looking project!

**Comment by romkatv** [comment]
> I would like to give z4h a try, but currently what's holding me back is the fzf-tab behavior.

Then I would recommend *not* trying z4h at this time. Maybe in the future.

z4h is not a configuration framework for zsh. It'll become more flexible over time but it'll still be a complete shell configuration first and foremost. Making it easy to *add* extra things is an important goal. Making it easy to *disable* is important but not as much. Swapping core components out will get only passing support if any. That said, there is a fair chance there will be a choice between two completion engines -- fzf-tab and traditional.

> In iTerm2 the alt-arrow key-mapping doesn't work. It only outputs `[C`& `[D`.
> Here is the output from `cat`. First is alt-right, second is alt-left.
> 
> ```
> ❯ cat
> ^[^[[C
> ^[^[[D
> ```

Thanks for the report! This is useful. I've fixed it in the dev branch.

**Comment by pkazmier** [comment]
@tumd I, too, did not like FZF tab completion. See my comment in this thread for how I disabled it:

https://github.com/romkatv/zsh4humans/issues/23#issuecomment-629848797

**Comment by tumd** [comment]
Thanks @romkatv, Alt-arrows seem to be working now.
However I was curious to test some of the other bindings you've added. More specifically Alt+j & Alt+o. But they only result in obscure signs.
```
❯ cat
√  # alt+j
œ  # alt+o
```
And the same thing goes for presumably all other custom key-binds involving the Alt-key.
Let me know if you want `cat`'s of all of them :)

---

Regarding disabling fzf-tab, I noticed how you used the form `zstyle ':z4h:XXX' channel none` in your dotfiles-public repo, but using that for fzf-tab returns an error upon invoking `z4h update`.
I know this way most likely isn't at all supported (and that v3 should be considered 'dev'), but just wanted to mention it. :)
I'll go for @pkazmier method instead. Thanks!

**Comment by romkatv** [comment]
@tumd Could you send me escape codes for one alt binding?

1. Run `zsh -f`.
2. Run `echoti smkx`
3. Press <kbd>ctrl-v</kbd> followed by <kbd>alt-j</kbd>. Let me know what appears on your screen.
4. Press <kbd>ctrl-g</kbd> to abort current command.
5. Run `echoti rmkx`.
6. Press <kbd>ctrl-v</kbd> followed by <kbd>alt-j</kbd>. Let me know what appears on your screen.

---

Thanks for letting me know about errors from `channel none`.

Using v3 is not advised. Unlimited damage possible. It's as bleeding edge as it gets.

**Comment by tumd** [comment]
Running this on my localhost instead of the VM I use for my z4h-experiments.

```
% zsh -f
rupert% echo $ZSH_VERSION
5.8
rupert% echoti smkx
rupert% √ # ctrl-v shows '^', alt-j produces the check-mark. ctrl-g does nothing
zsh: command not found: √
rupert% echoti rmkx
rupert% √ # ctrl-v shows '^', alt-j produces the check-mark. ctrl-g does nothing
zsh: command not found: √
rupert%
```
I'm not sure this gives you the information you were looking for.

**Comment by romkatv** [comment]
> I'm not sure this gives you the information you were looking for.

You have a way to figure out which keys your terminal sends on keystrokes, right? Could you tell me what it sends on <kbd>alt-j</kbd>?

It's also noteworthy that `zsh -f` is broken. I've never seen <kbd>ctrl-v</kbd> and <kbd>ctrl-g</kbd> broken when no rc files are loaded. Perhaps there is no point it trying to debug <kbd>alt-j</kbd> when things are this bad.

**Comment by tumd** [comment]
Sorry, I might have confused you (and my self). iTerm2 has three modes for the Alt-keys (in macos-lingo the key is named 'option'); Normal, Meta & Esc+. In my last post I must have had this set to 'Normal' which seems to produce the the macos default characters. I.e. typing 'Alt-j' in this textbox types '√'. Thus no escape-codes is sent in iTerm2 when Normal-mode is selected.
The recommended mode is 'Esc+' which I will continue to use from now on.
Apart from the above Alt-modes, there are a few different Key Mappings presets. The default preset is 'xterm Defaults'.
This is what the sequence;
alt-j
alt-o
alt-left
alt-right
looks like with 'xterm Defaults'-presets and 'Esc+' setting;
```
% cat
^[j
^[o
^[[1;9D
^[[1;9C
```
In the above preset alt-left & alt-right does not currently work in z4h.

The preset called 'Terminal.app Compatibility' looks like this;
```
% cat
^[j
^[o
^[b
^[f
```
This preset contains modifiable key combinations for alt-left & alt-right (and more) set to what's shown in the above output.

I validated the above with the actual Terminal.app having the option "Use Option as Meta key" checked on the active profile, to give the same output as the 'Terminal.app Compatibility' preset in iTerm2.

Confusing, but hopefully it's useful and that I got everything right :)

**Comment by romkatv** [comment]
@tumd Super useful stuff! I went ahead and experimented with different iTerm2 presets. I think I understand what they do and how to deal with this diversity. I've applied some temporary fixes in v3 and made a plan for a proper fix before this version goes live.

Using "Esc+" is a great idea. It'll make iTerm2 behave like a normal terminal. In general, if some terminal binding says <kbd>alt+blah</kbd>, you can use <kbd>esc+blah</kbd>. In most terminals these are equivalent. With "Esc+" they are equivalent in iTerm2 as well.

By the way, do I understand it correctly that <kbd>ctrl+arrows</kbd> are by default intercepted by the OS on macOS?

**Comment by tumd** [comment]
Yes, `ctrl+arrows` seem to be bound to Mission Control shortcuts by default in macOS. See [screenshot](https://cdnblob.moshi.com/images/upload/Luna/en03.png).
Disabling these shortcuts results in;
```
% cat
^[[1;5D # <
^[[1;5C # >
^[[1;5A # ^
^[[1;5B # v
```

**Comment by romkatv** [comment]
Going to close as the original issue has been solved (primarily by changing iTerm2 settings) and I don't plan to do anything about this in the short term.

Thanks, @tumd for your help on this.
