### ISSUE TITLE
Include a version identifier and time stamp in the initial `.zshrc` during installation

### ISSUE THREAD

**Issue by Semnodime** [romkatv/zsh4humans#310]
A **version identifier** could be of use to users who try to inform themselves of changes since the z4h installer created the `.zshrc` without re-running the installer from scratch.

Pro argument implicitly conveyed in https://github.com/romkatv/zsh4humans/issues/309

**Comment by romkatv** [comment]
The argument from https://github.com/romkatv/zsh4humans/issues/309#issuecomment-2154222947 applies here, too.
