### ISSUE TITLE
Completion list-dirs-first

### ISSUE THREAD

**Issue by poslat-pismo** [romkatv/zsh4humans#311]
Hello, is it possible to make fzf completion show directories first?

```
zstyle ':z4h:fzf-complete' sort false
zstyle ':z4h:fzf-complete' list-dirs-first true
```

or

```
zstyle ':completion:*' sort false
zstyle ':completion:*' list-dirs-first true
```

Both options are not working. What am I doing wrong?

**Comment by romkatv** [comment]
This works for me: https://github.com/romkatv/dotfiles-public/blob/b6657778b5a30b7dcf413ae0604a148741b40b5d/.zshrc#L167-L168

**Comment by poslat-pismo** [comment]
OK, I found that
```zstyle ':completion:*' file-patterns '^codeium:directories'```
was the problem
Thank You
