### ISSUE TITLE
z4h-fzf-history widget fails with special characters in command history

### ISSUE THREAD

**Issue by LangLangBart** [romkatv/zsh4humans#313]
When a user runs the command below and executes the `z4h-fzf-history` widget, an error is encountered.

To reproduce:
1. Run
```sh
fc -p =(print -r -- 'echo デ')
```

2. Press <kbd>⌃ Control</kbd> + <kbd>R</kbd> to execute the `z4h-fzf-history` widget
3. Notice the error

```sh
z4h-fzf-history:133: no matches found: echo \M-c\n
```

<img src="https://github.com/romkatv/zsh4humans/assets/92653266/85d951c2-0a2c-48e5-97f5-fa55b24f9ca8" width="400">

---

### Possible solution

Prepending `noglob` or unsetting either the `nomatch` or `glob` option prevents the error. 

```diff
--- a/fn/z4h-fzf-history
+++ b/fn/z4h-fzf-history
@@ -131,5 +131,5 @@ local preview='printf "%s" {} | command cut -f2- -d'$'\1'
       unsetopt pipe_fail
       {
-        (( $#history )) && printf '%s\000' "${history[@]}"
+        (( $#history )) && noglob printf '%s\000' "${history[@]}"
       } | {
         {
```

Related: https://github.com/junegunn/fzf/pull/3855

**Comment by romkatv** [comment]
Thanks!

**Comment by romkatv** [comment]
I reported this zsh bug upsteam: https://www.zsh.org/mla/workers/2024/msg00513.html
