### ISSUE TITLE
Install fzf completions without the rest of the zsh4human framework

### ISSUE THREAD

**Issue by pjhfggij** [romkatv/zsh4humans#314]
Is it possible to install fzf completions that z4h provides without installing all the other components? On archlinux most of the packages are already provided and can be installed just by sourcing their .plugin.zsh files. However, there [doesn't seem to be](https://github.com/junegunn/fzf/issues/3886) any easy way to install the great collection of fzf completion integrations that come with z4h (command line flags, recent directories, etc.).

Are these fzf completion integrations available anywhere else as a separate repository? I couldn't any corresponding folder in the default `.cache/zsh4humans/v5`.

**Comment by romkatv** [comment]
> Is it possible to install fzf completions that z4h provides without installing all the other components?

I'm not sure I understand the question but the answer is most likely "No".

> Are these fzf completion integrations available anywhere else as a separate repository?

Ditto.

**Comment by pjhfggij** [comment]
No worries, I wasn't aware that so many fzf completion integrations were included in zsh4humans. Now trying to write zshrc from scratch I was caught off guard that none of them work (even after sourcing completion.zsh script that comes with fzf). It's very minimal. I am looking at alternative projects ([pmy](https://github.com/relastle/pmy), [fzf-zsh-completions](https://github.com/chitoku-k/fzf-zsh-completions), [fzf-tab](https://github.com/Aloxaf/fzf-tab)).
