### ISSUE TITLE
`setopt no_global_rcs` breaks `snap` (Snapcraft)

### ISSUE THREAD

**Issue by playday3008** [romkatv/zsh4humans#315]
#### This

https://github.com/romkatv/zsh4humans/blob/0f9781871d461697f9689c704f6f80f7cfe6818d/.zshenv#L18

#### How

Snap during installation creates `/etc/profile.d/snapd.sh` with snap specific initialization code, which will never be loaded (alongside with everything in `/etc/profile.d`) by zsh if `no_global_rcs` is set and zsh set as login shell (which `zsh4humans` recommends to do)

#### Solution

- Just don't set that option (I don't know how it will affect  `zsh4humans`)
- Prompt user to set or not `no_global_rcs` (with pros. and cons. provided)
- Implement loading of profile on `zsh4humans` side

**Comment by romkatv** [comment]
You can add `z4h source /etc/profile.d/snapd.sh` in an appropriate place to work around this. It's unlikely I'll be making this this change in z4h proper.

**Comment by playday3008** [comment]
Can you explain to newbie what effect removing `setopt no_global_rcs` from `.zshrc` will have?

**Comment by romkatv** [comment]
Not without spending more time than I can afford.

**Comment by playday3008** [comment]
I'll try to simplify answer, except theoretical loading of everything in `/etc/profile.d` and possible incompatibility with all that stuff, does it have any other effect?

**Comment by romkatv** [comment]
The meaning of this option is described in `man zshoptions`. Disabling this option will have the documented effect, no more and no less.

**Comment by playday3008** [comment]
Okay, thank you
