### ISSUE TITLE
why zsh prompt always in the bottom of pane when using tmux 

### ISSUE THREAD

**Issue by rmGFW** [romkatv/zsh4humans#317]
<img width="1166" alt="image" src="https://github.com/user-attachments/assets/8d376665-4edd-4bc9-b4bf-d8180fbd7ff2">

after clear window (ctrl + l ) , the prompt always in the bottom of screen . how can i disable this feature

**Comment by romkatv** [comment]
https://github.com/romkatv/zsh4humans/issues/308

**Comment by rmGFW** [comment]
> #308

thanks!!!!!!
