### ISSUE TITLE
Question on where specific syntax highlighting is being handled

### ISSUE THREAD

**Issue by davidbgonz** [romkatv/zsh4humans#327]
Hello. I recently moved machines and figured it was a good time as any to do some housekeeping with my configs. I was adjusting some color settings on fzf and I had a question about syntax highlighting during fzf searches.

I'm using your handy color table for this example:

This is how it normally looks for me from fzf-styntax-highlighting.
![image](https://github.com/user-attachments/assets/88a8577c-4d02-473e-b9e7-de743643c657)

This is after I do a recursive search.
![image](https://github.com/user-attachments/assets/6b79429a-c089-476a-8f4c-890a55d70a1c)

What is handling the syntax highlighting on the bottom line in the 2nd image?

**Comment by romkatv** [comment]
The second screenshot shows `z4h-fzf-history`, bound to Ctrl-R by default. Highlighting in there is done by `bat`.

https://github.com/romkatv/zsh4humans/blob/2a27b0d585ec7b70d6889a921accfc450cd2f73a/fn/z4h-fzf-history#L3-L14

**Comment by davidbgonz** [comment]
Thank you! Going on 3 years of using these configs and I'm still learning what it can do. Thanks for such a great setup! Going to close this now.
