### ISSUE TITLE
disable tab completion?

### ISSUE THREAD

**Issue by rsperl** [romkatv/zsh4humans#33]
Is there a way to disable tab completion, but rely on `FZF_COMPLETION_TRIGGER=**` instead? I'd rather have `cd` completion the old way, and only use fzf if I give `**`.

**Comment by romkatv** [comment]
I'm not sure I understand the question. Nevertheless, the answer most likely fitting your question is to check out https://github.com/romkatv/zsh4humans/issues/31.
