### ISSUE TITLE
[Question] how do I change the color of the initial/non-suggested part of a suggestion?

### ISSUE THREAD

**Issue by cgahr** [romkatv/zsh4humans#331]
Thanks a lot for this cool project. On the third/fourth try I finally managed to stick with it, and now I'm using it everywhere!

How do I change the color of the purple area?
![image](https://github.com/user-attachments/assets/8bd5a324-d277-48af-8954-49c56cbb67e0)
**how:** type `ls` + `up-arrow`

How do I change the color of the read area (less important)?
![image](https://github.com/user-attachments/assets/8d6b2578-36b3-4cd1-890e-0aba7c9350a0)
**how:** type `ls` + `up-arrow` + `down-arrow`

I know that I can use e.g.
```
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=15"
```
to style the suggestion part of the prompt, i.e. everything but the purple/red part. But I'm unclear on how to style this part.

Thanks a lot! I hope this is not a duplicate, but I wasn't able to find any information.

**Comment by romkatv** [comment]
Try this:

```zsh
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_FOUND='bg=magenta,fg=white,bold'
HISTORY_SUBSTRING_SEARCH_HIGHLIGHT_NOT_FOUND='bg=red,fg=white,bold'
```

These are the default values. Adjust to your liking.

**Comment by cgahr** [comment]
Works like a charm, thanks a lot!
