### ISSUE TITLE
Plugin installation: support submodule recursion for git hosted plugins

### ISSUE THREAD

**Issue by arrrgi** [romkatv/zsh4humans#335]
Hi @romkatv 

Thanks again for your help on past issues, it's been good to have your assistance.

I recently ran `z4h update` to fetch any upstream changes to zsh4humans and plugins that are installed by my config. I have been using the **zsh-abbr** plugin and noticed an error message in the output from reloading zsh.

```console
z4h: restarting zsh
abbr: Finishing installing dependencies
abbr: There was a problem finishing installing dependencies
```

A quick search of issues on https://github.com/olets/zsh-abbr and I see they have a submodule as part of their most recent breaking version bump to 6.0, and the fix (per this [issue](https://github.com/olets/zsh-abbr/issues/156)) of course is to install via Brew, or use the `--recurse-submodules` switch when cloning with git.

Whilst I think it's extremely rare for zsh plugin authors to use submodules, I think this plugin is popular enough that it might warrant adding something to handle this in zsh4humans.

Does zsh4humans support this if the full repo URL is used like this `z4h install git+https://github.com/olets/zsh-abbr` ?

Keen for your thoughts and whether you could propose a fix.

**Comment by romkatv** [comment]
zsh4humans does not use `git` to download dependencies, so it's not trivial. I wish olets used subtrees instead of submodules, as they are better in pretty much every way.

You might be able to work around this issue by defining a post-install hook:

```zsh
zstyle :z4h:olets/zsh-abbr postinstall recurse-submodules

function recurse-submodules() {
  # TODO: do something with $Z4H_PACKAGE_DIR
}
```

Alternatively, stick to the previous version of zsh-abbr:

```zsh
z4h install olets/zsh-abbr@v5
```

**Comment by olets** [comment]
Here's another workaround concept if that first one doesn't pan out:

z4h install <user>/zsh-plugin-z4h-extension-install-via-git postinstall z4h-extension-install-via-git olets/zsh-abbr [other/repo[, others...]]

where the command z4h-extension-install-via-git runs a clone command with at least the --recurse-submodules flag, and then tells z4h to source the result. Building a plugin manager inside a plugin manager shouldn't be the first thing you try 😅 but it might turn out okay, and others might find it valuable too

**Comment by romkatv** [comment]
This will add a dependency on `git`. There is a very good reason why z4h currently does not have this dependency, for it allows you to teleport your shell environment to any UNIX box via ssh. Pretty much anything has wget or curl, but lots of machines out there don't have git.

If you are going to create another repo as a workaround, then you might as well fork zsh-abbr and convert its submodule to a subtree. It's strictly better for all users.
