### ISSUE TITLE
pyenv

### ISSUE THREAD

**Issue by jonaspaulo** [romkatv/zsh4humans#338]
Hi,

First of all thanks for the great project! It eases the burden of configuring zsh manually by a mile.
I am running zsh4humans on Mac and followed the following to install pyenv:

```
brew install xz
brew install pyenv
pyenv install 3.13.1
```

Rebooted the shell

And now should it work out of the box? 
I am asking this because when I try to use it without changing anything on .zshrc it doesn't seem to work:

```
❯ pyenv local 3.13.1
❯ python3 --version
Python 3.9.6
```

But if I add the recommended settings to .zshrc:
```
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
```

it starts to work:

```
❯ pyenv local 3.13.1
❯ python3 --version
Python 3.13.1
```

So the question is if the options are really needed is there a best practice to add them to .zshrc?

Second question is that even with the addition of the recommended settings the "global" option never works:

```
❯ pyenv global 3.13.1
❯ python3 --version
Python 3.9.6
```

Thanks a lot once again for the great work.

BR

**Comment by romkatv** [comment]
zsh4humans does not do anything special w.r.t. pyenv. You need to install and use it according to the pyenv documentation. If they say you need to add something to `.zshrc`, do that.

**Comment by jonaspaulo** [comment]
ok thanks for the confirmation.

and regarding the pyenv global not working any tips that could be related to zsh4 ?

**Comment by romkatv** [comment]
I'd be very surprised if z4h was relevant to this issue.

**Comment by jonaspaulo** [comment]
Thanks for the help.
