### ISSUE TITLE
How to complete things that are not files?

### ISSUE THREAD

**Issue by extremepayne** [romkatv/zsh4humans#34]
Apology offered in advance, this is probably just me being dumb or something.

Coming from prezto, I am used to completing things like git branch. For example, I type 
`git checkout fix-` and hit tab to complete with `fix-bad-formatting`(or some such.) But when I try that with z4h, it gives me fzf with completing files instead of branches, which I don't want. I understand `checkout` could be used for both, but I most often use it for branch switching, and it doesn't seem to be working at all (e.g. If I type enough where it doesn't fuzzy match to any files but precisely matches branches, fzf offers no branches nor files). I thought this was maybe my mistake for not learning the keybinds, but <kbd>Ctrl-Space</kbd> offers me nothing at all. Reading the docs it seems that completion functions are indeed supported, and this led me to believe completion worked similarly (albeit fuzzy) to my previous setup, but that isn't the case. 

Pretty much, if I type `git checkout ` and then the enough of a git branch to be unique, what key should I press to get the rest of that branch in there? Is this not a feature of z4h? It was one of my most-used features from my previous setup (although I will admit that z4h's alt-arrow dir navigation and the simplicity of the system are big pros for me).

**Comment by romkatv** [comment]
<kbd>Tab</kbd> should do what you are asking for. E.g., if I type `git che` and hit <kbd>Tab</kbd>, I get automatic completion to `git checkout`. If I then type `--` and hit <kbd>Tab</kbd>, I get completion for all flags that `git checkout` accepts. Similarly for branch completions.

Is it not the same for you? What about `grep --` <kbd>Tab</kbd>`? Does it give you grep flags?

**Comment by extremepayne** [comment]
I wasn't talking about subcommands nor flags (although those are both important), but branch names. 
Actually, though, `grep --` <kbd>Tab</kbd> completes to files. Same with `git checkout --`<kbd>Tab</kbd>. You might be on to something. 

Version info:
Ubuntu 20.04, relatively fresh install
Latest z4h as of `z4h update`
I'm happy to provide configs and such if neccesary.

**Comment by extremepayne** [comment]
![image](https://user-images.githubusercontent.com/46696318/85794431-dbd99780-b6f3-11ea-950b-98b9fa1fbed1.png)
Here's another example of it breaking.

**Comment by romkatv** [comment]
> I wasn't talking about subcommands nor flags

I know.

Your screenshots show `fzf-completion` (bound to <kbd>Alt+I</kbd>) rather than `z4h-expand-or-complete` (bound to <kbd>Tab</kbd> and <kbd>Ctrl+I</kbd>).

> I'm happy to provide configs and such if necessary.

Have you made any changes to `~/.zshrc` after installing z4h? If so, try installing z4h once again and see if it fixes the issue.

If you haven't made any changes to `~/.zhsrc` then perhaps your terminal is configured to send `^[I` or `^[i` when you press <kbd>Tab</kbd>? (This is very unlikely.) Try running `zsh -f`, typing `ls /` and hitting <kbd>Tab</kbd>.

**Comment by extremepayne** [comment]
I had a whole two aliases in `~/.zshrc`, as well as a few changes recommended by the README, which may or may not have been related to how <kbd>Ctrl-I</kbd> <kbd>Alt-I</kbd> and <kbd>Tab</kbd> were somehow bound to the same widget. In any case, reinstalling and carefully sequentially reapplying all .zshrc  customization fixed it. 

Thanks for your patience.

**Comment by romkatv** [comment]
Thanks for the update. I’m glad it works for you now.
