### ISSUE TITLE
Automatically changing zdotdir?

### ISSUE THREAD

**Issue by kvndrsslr** [romkatv/zsh4humans#37]
Hello, first and foremost thank you for all of your incredible efforts!
I am using z4h for a couple of weeks now and it is really nice, however when I open up a terminal inside IDEA I get the following message:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/46481738/86772076-a3bb4880-c053-11ea-8fab-aff67b26e1d2.png">

I would like to understand how z4h knows that it is being called from IDEA and why it chose to change the ZDOTDIR and create a new configuration branch on my disk. Will this happen for every terminal emulator?

**Comment by romkatv** [comment]
IDEA is doing something awful. I've opened a bug: https://youtrack.jetbrains.com/issue/IDEA-245380. Let's see what they say.

**Comment by romkatv** [comment]
FWIW, when prompt shows up, you can get your normal shell with this command: `ZDOTDIR=~ exec zsh`.

**Comment by kvndrsslr** [comment]
Thanks for the explanation. Tbh I thought this was a feature rather than a bug haha.

**Comment by romkatv** [comment]
It's a feature but it shouldn't be triggered here.

For the record, I sent a PR to IDEA: https://github.com/JetBrains/intellij-community/pull/1408. Closing this issue as I don't intend to do anything in zsh4humans related to this.
