### ISSUE TITLE
Deploying zsh remotely without internet with z4h ssh

### ISSUE THREAD

**Issue by cyrinux** [romkatv/zsh4humans#38]
Hi Roman, 

I continue to play with v3, its awesome.
Do you plan to handle the case where a remote server dont got internet and so in this case, two cases:
* i would like to pass a proxy_http to z4h ssh
* i would like to use my laptop as a gateway, laptop will download the zsh binary(and other stuff is need) needed, then push them to the remote server

Tell me you need more information ;)

Thanks you!

**Comment by romkatv** [comment]
I have no immediate plans to support this but you can hack something up. There are enough hook to give you freedom.

Here's what I would try.

1. Install an HTTP proxy on local host. Let's say it's listening on `localhost:9999`.
2. Use `zstyle ':z4h:ssh:remote-host-name' ssh-command ssh -R 9999:localhost:9999` forward connections to the remote port 9999 to the local HTTP proxy.
3. Define `z4h-ssh-configure` and extend `z4h_ssh_prelude` with `export all_proxy=localhost:9999; export ALL_PROXY=localhost:9999`.

I haven't tried it, so I don't know if it actually works.

I would also advise you to consider whether bypassing no-internet restrictions and installing a ton of ~~crap~~ zsh code is a wise idea.

Standard disclaimer: v3 is unstable. Expect backward compatibility to be broken with no notice.

**Comment by cyrinux** [comment]
Thanks you very much, i will try this, this talk me. Don't worry, i know what i do ;)

**Comment by cyrinux** [comment]
Could you please tell me more about this "z4h_ssh_prelude" ? I can't find any related code about this.

I tried to do the export my proxies here:

```
function z4h-ssh-configure() {
 export here
 ...
}
```

But I think its not what you mean 🤔 

Regards

**Comment by romkatv** [comment]
See the top of https://github.com/romkatv/zsh4humans/blob/v3/fn/-z4h-ssh.

**Comment by cyrinux** [comment]
Thanks sorry man, i discover github index only master branch for search 🤦 I take a look.
