### ISSUE TITLE
Transfer of other dotfiles besides those for zsh

### ISSUE THREAD

**Issue by RickCogley** [romkatv/zsh4humans#39]
This is such an interesting project - impressive and well done. 

I wonder, would it be overly difficult to have `z4h ssh` transfer not only `zsh` configs, but also other configs such as for vim or git?

**Comment by romkatv** [comment]
This is implemented in v3 -- the next release currently in the works. Here's how the configuration looks like:

```zsh
zstyle ':z4h:ssh:*' send-extra-files '~/.vimrc' '~/bin/stuff'
```

The last component in zstyle context is hostname.

You can install v3 with the following command:

```zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v3/install)"
```

Keep in mind that v3 is under active development. There is no backward compatibility guarantee for it.

**Comment by RickCogley** [comment]
Hi @romkatv thanks for the extra info. I'm glad to see it's included so, I will try it.
