### ISSUE TITLE
ls alias doesn't work on mac

### ISSUE THREAD

**Issue by ahmedre** [romkatv/zsh4humans#4]
thanks for writing this (and for powerlevel10k!)

one small point - `ls --color=auto` doesn't work on Mac out of the box because it's a different `ls` than the Linux one - have to do `ls -G` instead (otherwise, a default install of z4h complains every time `ls` is run).

**Comment by romkatv** [comment]
Ouch! Thanks for letting me know.

About the other aliases? Do they work?

**Comment by ahmedre** [comment]
* grep works
* tree isn't installed by default
* diff doesn't work (can't find any recommended color flags for diff on OS X - a quick search shows people recommending using colordiff or grc with it  ¯\_(ツ)_/¯).

**Comment by romkatv** [comment]
So `diff` also complains about unknown flag?

**Comment by romkatv** [comment]
> So `diff` also complains about unknown flag?

Answering my own question: Yes, it does.

Fixed.
