### ISSUE TITLE
GPG git commit signing stopped working

### ISSUE THREAD

**Issue by woss** [romkatv/zsh4humans#41]
for the record, i love this repo much faster than zprezto and much nicer to work in general. 
BUT!

gpg completely  fails on git commit signing. how to resolve this issue?

gitconfig didn't change nor I deleted any packages. it worked before migration

**Comment by romkatv** [comment]
zsh4humans doesn't have any effect on git or gpg. If you want your commits to be signed, either pass `-S` to `git commit` or run `git config --global commit.gpgsign true` to sign all commits by default.

**Comment by woss** [comment]
why then you have `export GPG_TTY=$TTY` ?

issue was that I had in my prev zshrc this `export GPG_TTY=$(tty)` and that was overriding the one above. it started working the moment I deleted my setting

**Comment by romkatv** [comment]
> why then you have `export GPG_TTY=$TTY` ?

It's an example of an exported variable. This is not part of zsh4humans code. It also shows how to properly initialize `GPG_TTY` in zsh.

> issue was that I had in my prev zshrc this `export GPG_TTY=$(tty)`

Indeed, if you incorrectly initialize `GPG_TTY`, gpg won't work. The default `~/.zshrc` from zsh4humans correctly initializes `GPG_TTY` to help users spot this particular mistake.
