### ISSUE TITLE
using OMZ plugins ?

### ISSUE THREAD

**Issue by ycardon** [romkatv/zsh4humans#42]
Hi, I'm a regular fish user and a zsh noob (discovering it with Z4H).

I'm trying to enable some of the Oh-my-Zsh plugins, let's say `kubectl`: how am I supposed to do so ?
- `plugins=(kubectl)` does nothing by itself, should I source OMZ ? how ?
- as in the examples section : `z4h source $Z4H/ohmyzsh/ohmyzsh/plugins/kubectl/kubectl.plugin.zsh`. It works but I have to define the `ZSH_CACHE` variable (that seems to be used in many OMZ plugins). I added `export ZSH_CACHE_DIR=$Z4H/cache`. If it the right way to do so, should it be in the Z4H default .zshrc ?

The examples in "Use additional Git repositories pulled in with `z4h install`" show different strategies (sourcing or adding a directory in the fpath). Do I have to choose one / both depending on the OMZ plugin I'm using ? Is it safe to do both and if so, is there a shorter way to include a OMZ plugin ?

**Comment by romkatv** [comment]
May I ask why you want to use `kubectl` plugin? What do you need that this plugin provides?

**Comment by ycardon** [comment]
The completions and the aliases (but I took it as an example)

**Comment by romkatv** [comment]
> * as in the examples section : `z4h source $Z4H/ohmyzsh/ohmyzsh/plugins/kubectl/kubectl.plugin.zsh`.

This is the way.

> It works but I have to define the `ZSH_CACHE` variable (that seems to be used in many OMZ plugins). I added `export ZSH_CACHE_DIR=$Z4H/cache`. If it the right way to do so, should it be in the Z4H default .zshrc ?

I've just added `ZSH_CACHE_DIR`, so if you are using zsh4humans/v3 (it's much better than v2 but offers no backward compatibility guarantees; it's the "next" version still in development), you can run `z4h update` and remove your override of `ZSH_CACHE_DIR`.

If you are on v2, keep the override. You can remove the unnecessary `export`.

> The examples in "Use additional Git repositories pulled in with `z4h install`" show different strategies (sourcing or adding a directory in the fpath). Do I have to choose one / both depending on the OMZ plugin I'm using ? Is it safe to do both and if so, is there a shorter way to include a OMZ plugin ?

When using a third-party project, you should do what the documentation for that project tells you to do.

Oh My Zsh is special, for it doesn't document (nor officially support) how its plugins can be used individually without the whole of Oh My Zsh framework. In practice, you should add the plugin's directory to `fpath` if that directory has completion functions (files whose names start with an underscore). And if there is `*.plugin.zsh`, you should source it.

P.S.

Oh My Zsh is not a good source of zsh plugins. It's very probably that overall effect from using Oh My Zsh plugins will be net negative. If your system doesn't come with `kubectl` completions by default, you can add these lines to `~/.zshrc`:

```zsh
if (( $+commands[kubectl] )); then
  () {
    [[ ! -e $1 ]] && kubectl completion zsh >$1.$$ && zf_mv -f $1.$$ $cache
    z4h source -c $1
  } $Z4H/cache/kubectlcomp.zsh

  # Add kubectl aliases here.
fi
```

You can add a few aliases there. You probably don't need as many as Oh My Zsh defines. It virtually never makes sense to reuse aliases from someone else.

**Comment by ycardon** [comment]
That was quick :) thank you for the commits and your detailed answer.

I struggled a little with the update mechanism (playing with the channel, then discovering v2 will never update to v3 and finally starting from scratch with `sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v3/install)"`).

About OMZ, I've incorrectly inferred from the default `.kshrc` that it was an ok source and that there was already a kind of integration between Z4H and OMZ (there is now with the `ZSH_CACHE_DIR` ^^). I will do my homework and read about the different configuration frameworks and plugin managers.

About `kubectl`, I get your point (and looking at your example : ksh seems to offer very interesting constructions), but I will rely on plugins, at least for the beginning.

**Comment by romkatv** [comment]
> I struggled a little with the update mechanism (playing with the channel, then discovering v2 will never update to v3 and finally starting from scratch with `sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v3/install)"`).

That's the way.

zsh4humans is still being developed and I simply snapshot my work-in-progress code every now and then so that folks can use what's already there. The latest snapshot is v2, and v3 is the dev branch. There is no migration procedure because the whole point of a new version is to allow me to break backward compatibility. My current plan is for v4 to be the last version that I'll support indefinitely. In a way it'll essentially be the first release. There will be no need for the major version upgrade mechanism because major versions won't change after that.

> About `kubectl`, I get your point (and looking at your example : ksh seems to offer very interesting constructions), but I will rely on plugins, at least for the beginning.

There is very little you can gain by using Oh My Zsh plugins over not using any plugins. On the other hand, the damage to your zsh setup can be massive.

FWIW, I just committed https://github.com/romkatv/zsh4humans/commit/15f18109685db57a42a5efb4a5167009c225a760, which makes kubectl completions work out of the box in zsh4humans (and without doubling zsh startup time, like what you get with `kubectl` plugin in Oh My Zsh). There are a handful of useful things that Oh My Zsh plugins do (or at least what they attempt to do), and enabling `kubectl` completions was one of those. If you think there is another Oh My Zsh plugin that does something useful, please let me know.

My advice to not `source` anything for the sake of picking up a million aliases stands. It's better to copy the aliases you actually want and have the freedom to customize them.

**Comment by ycardon** [comment]
Ok, I'm progressing little by little: I'm managing `kubeclt` with `brew`, the package already provided completions but they were not in the fpath. In fact I was missing all the `brew` completions (it was done automatically on fish). So I added this to the `.zshrc` (and removed the OMZ/kubetcl plugin)
```sh
# brew.sh path and completions.
[[ -e /home/linuxbrew ]] && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
[[ -v HOMEBREW_PREFIX ]] && fpath+=($HOMEBREW_PREFIX/share/zsh/site-functions)
```
Speaking of completions, would it be difficult to have `z4h ssh` to use existing `ssh` completions ? Having the declared hosts autocompleted is really useful

I completely agree on your advice on only copying the aliases I need.

**Comment by tumd** [comment]
I do think Helm uses the same approach for completions as kubectl. It would be _nice to have_ that included too.

**Comment by romkatv** [comment]
> edited: ok, you will say that `brew shellenv` is adding 100ms to the zsh startup time ^^

It does, doesn't it? A few customizations like that and you can get yourself a coffee while zsh is booting up.

There is no reason why brew completions shouldn't Just Work, so I added this to z4h (again, at no startup costs). You can remove your customization.

Thanks for bringing this up. If you notice anything else where thing don't Just Work, please do let me know.

> Speaking of completions, would it be difficult to have `z4h ssh` to use existing `ssh` completions ? Having the declared hosts autocompleted is really useful

Having completions for `z4h` is on my TODO list. That said, it's more convenient to define a function:

```zsh
function ssh() z4h ssh "$@"
```

When you want to use plain `ssh`, use `command ssh`. This basically just flips the default, which is sensible if you want to use `z4h ssh` more often than `command ssh` (at least this is how I use it). You can also use `zstyle` to specify that `z4h ssh` should simply delegate to `command ssh` for some hosts. It looks like this:

```zsh
zstyle :z4h:ssh:foo.com passthrough yes
```

I list all hosts I ssh to in `~/.ssh/config`. These completions settings go well with it:

```zsh
zstyle ':completion::complete:ssh:argument-1:'    tag-order          hosts users
zstyle ':completion::complete:scp:argument-rest:' tag-order          hosts files users
zstyle ':completion:complete:ssh:argument-1'      sort               true
zstyle ':completion:complete:scp:argument-rest'   sort               true
zstyle ':completion::complete:(ssh|scp):*:hosts'  hosts
```

**Comment by romkatv** [comment]
> I do think Helm uses the same approach for completions as kubectl. It would be _nice to have_ that included too.

This is done. Thanks for the tip.

**Comment by romkatv** [comment]
> That said, it's more convenient to define a function:
> 
> ```shell
> function ssh() z4h ssh "$@"
> ```

I should've clarify that this will make completions for `ssh` work, including host completions.

**Comment by romkatv** [comment]
For those using `brew`, install `command-not-found` if you haven't yet.

```zsh
brew tap homebrew/command-not-found
```

Once you run that command and restart zsh (`exec zsh`), z4h will provide integration automatically. Now, when you invoke a command that doesn't exist, instead of seeing this:

```text
zsh: command not found: kubectl
```

You'll see this:

```text
The program 'kubectl' is currently not installed. You can install it by typing:
  brew install kubernetes-cli
```

See https://github.com/Homebrew/homebrew-command-not-found. The integration provided by z4h is faster and better than the default that ships with this tap.

**Comment by ycardon** [comment]
Thanks again for the clarifications.

I should have add that I use `brew` both on mac (where https://github.com/romkatv/zsh4humans/commit/1dca7f3f9985aa34167adf14b8740e65e4286e6c works out of the box) and linux machines (ubuntu and raspbian based).

For the latter, linux brew will be installed either in `~/.linuxbrew` or `/home/linuxbrew/.linuxbrew`. And a few variables will be set by `eval $(my/brew/path/bin/brew shellenv)`

If I follow you, it's better not to call `brew shellenv` when zsh starts but add the "already calculated" result somewhere.

```
❯ brew shellenv
export HOMEBREW_PREFIX="/home/linuxbrew/.linuxbrew";
export HOMEBREW_CELLAR="/home/linuxbrew/.linuxbrew/Cellar";
export HOMEBREW_REPOSITORY="/home/linuxbrew/.linuxbrew/Homebrew";
export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin${PATH+:$PATH}";
export MANPATH="/home/linuxbrew/.linuxbrew/share/man${MANPATH+:$MANPATH}:";
export INFOPATH="/home/linuxbrew/.linuxbrew/share/info:${INFOPATH}";
```

For now, I can put it inside my `.zshrc`, protected by a `[[ -e /home/linuxbrew ]]` test. Do you see a better way ? Linux brew documentation suggests `.profile`, is it read by z4h ?

**Comment by romkatv** [comment]
Oh, *that's* what `/home/linuxbrew` check in your code was about. I had no idea you can install `brew` on Linux (or that anyone would want to, for that matter).

I'll install it, time different things and get back to you. Most likely the conclusion will be that it'll Just Work in z4h.

**Comment by ycardon** [comment]
> or that anyone would want to, for that matter.

This is mean ! ^^ 

On Archlinux, I'm using AUR for non official packages, but on debian based system I find `brew` to be much more complete for development than any other package manager, probably due to the mac counterpart traction.

For the `z4h ssh`, I was using an alias and I couldn't get it auto-completed. Using a function is much better (I'm keeping a different name than ssh for now)

```sh
function zssh() z4h ssh "$@"
compdef zssh=ssh
```

**Comment by romkatv** [comment]
> > or that anyone would want to, for that matter.
> 
> This is mean ! ^^

I don't think declaring one's own ignorance is mean.

I don't use macOS myself and my perception is that non-Linux package managers are lagging behind. I don't have a strong basis for this perception. I've never heard Linux users wishing they could use `brew`. That's what my previous comment meant.

I've installed Homebrew on Linux, played around with it and added integration to z4h. You can remove your own integration if you have it.

> I find `brew` to be much more complete for development than any other package manager, probably due to the mac counterpart traction.

That sounds nice. I'll keep `brew` on my machine and will try using it at the next opportunity.

> Linux brew documentation suggests `.profile`, is it read by z4h?

`.profile` is a Bash rc file. Zsh doesn't read it and neither does z4h. When using z4h, you should put all your shell customization into `~/.zshrc`.

> For the `z4h ssh`, I was using an alias and I couldn't get it auto-completed.

This is expected. If `z4h ssh` doesn't support completions then an alias that expands to `z4h ssh` won't have completions either. On the positive side, if a command has completions (say, `git`), then aliases for this command will also have completions. Zsh *sees through* aliases.

> Using a function is much better (I'm keeping a different name than ssh for now)
> 
> ```shell
> function zssh() z4h ssh "$@"
> compdef zssh=ssh
> ```

This would require you to remember to which hosts you should ssh via `ssh` and to which via `zssh`. If you rename the function to `ssh`, you'll be able to encode this information in `~/.zshrc`. Note that even with function `ssh` you can set the default behavior to `command ssh` and employ the full-fledged `z4h ssh` only for whitelisted hosts.

```zsh
function ssh() z4h ssh "$@"

# Pass-through by default.
zstyle ':z4h:ssh:*' passthrough yes

# Use full-fledged `z4h ssh` when connecting to `foo.com` or `bar`.
zstyle `:z4h:ssh:(foo.com|bar)` passthrough no
```

**Comment by ycardon** [comment]
_It Just Works ©_ now with brew ! (I was not so worried it will)

Thank you again for sharing your time and skill. Your z4h project was exactly what was needed to bootstrap me onto zsh and I sure stick with it now (I really like fish, but it seems the zsh ecosystem is richer and a little more standard). Oh, you also got me on p10k and the "show on command" :)

**Comment by romkatv** [comment]
> _It Just Works ©_ now with brew !

Thanks for the confirmation!

If (or rather when) you discover similar usability issues, please do let me know. For z4h to succeed in its mission it needs a lot of polish, which in turn requires bug reports akin to the ones you've filed.
