### ISSUE TITLE
Cannot retrieve function definitions, v3

### ISSUE THREAD

**Issue by RickCogley** [romkatv/zsh4humans#43]
Hello - I took @romkatv's advice and moved my functions to external files. 

~~~~~
fpath+=(~/bin/zsh/functions)
autoload -Uz -- ~/bin/zsh/functions/[^_]*(.)
compdef _directories md
~~~~~

Actually they are in my cloned dotfiles at `~/.dotfiles/zsh/bin/zsh/functions` and linked into 
`~` with gnu `stow`. 

I wanted to prove the md function was loaded by viewing its definition. I did `which md` which normally would output the function definition to std-out, but it doesn't. Rather it just outputs the below: 

~~~~~
❯ which md
md () {
	# undefined
	builtin autoload -XUz /path/to/bin/zsh/functions
}
~~~~~

Also tried `whence -f md`, `type -f md`, `declare -f md`, `functions md`, `typeset -f md`, but all gave the same result. 

I could write a function to show function contents by just doing i.e. a `cat` on the external file, but I am wondering if viewing the contents of functions declared from external files, can be performed in the usual way?

**Comment by romkatv** [comment]
What you are seeing is expected. The whole point of autoloading functions is that they don't get read and parsed until the first use. What you are seeing with `functions md` is a stub. This stub will load the proper function once you invoke `md`. Try it`. Type `md` and then `functions md`.

You can forcefully load a function without invoking it with `autoload +X -Uz md`.

P.S.

This project is not an appropriate place for generic zsh questions. Please ensure the question has something to do with zsh4humans before opening an issue.

**Comment by RickCogley** [comment]
thank you for the answer, and sorry about that.

**Comment by romkatv** [comment]
You can read about autloading by typing `autoload` and pressing <kbd>Alt+H</kbd>. This shortcut works for builtin commands as well as external commands. E.g., try it on `git clone`.

**Comment by RickCogley** [comment]
Yeah, I meant to suss out why some of the shortcuts are not working for me. I must have something else on my mac that's conflicting with them ... 

When I type opt+H it just enters a symbol, so, something is up.

**Comment by romkatv** [comment]
You can press <kbd>ESC h</kbd> instead.

A better solution is to open your terminal settings and tell it to use Option as Alt. iTerm2 and Kitty have this setting. The stock Apple Terminal doesn't (I think). It's a bad terminal anyway, so it's a good idea to switch either to iTerm2 (more popular) or Kitty.

**Comment by RickCogley** [comment]
the `esc h` does it, thank you, I can confirm I can see help for builtins and external commands. I'll try to find that setting in iTerm2.

**Comment by romkatv** [comment]
It's in Preferences > Keys. Set preset to "xterm defaults". It's the one that iTerm2 says you should set. See https://www.iterm2.com/documentation-preferences-profiles-keys.html.

**Comment by RickCogley** [comment]
Thanks for pointing me in the right direction! There's no "xterm defaults" and it's rather "factory defaults" but, it could be because I'm using a beta of iterm2 v3. I need to figure out what's conflicting but, meanwhile I just added a binding in iTerm2 prefs, Keys, based on how the bindings are set up in z4h (in `zsh4humans/fn/-z4h-init`), and that worked. 

<img width="1327" alt="image" src="https://user-images.githubusercontent.com/512328/87770720-58c2e180-c85a-11ea-967a-8ea0d57d1a90.png">

**Comment by romkatv** [comment]
> Thanks for pointing me in the right direction! There's no "xterm defaults" and it's rather "factory defaults"

Maybe it's in Remap Modifiers now. All you need is to tell iTerm2 to treat Option key as Alt.

> I just added a binding in iTerm2 prefs, Keys, based on how the bindings are set up in z4h (in `zsh4humans/fn/-z4h-init`), and that worked.

This is not a good idea. It's much better to configure your terminal to behave the way terminals are expected to behave.

**Comment by RickCogley** [comment]
Well noted. I'll look for it. I tried in kitty as well, but the same thing happens: text is entered when I press alt-h. It may be something universal or global.

**Comment by romkatv** [comment]
It's not universal or global. Terminal emulators on macOS by default copy the awful behavior of Apple Terminal. You just need to change it through settings. Kitty has this setting. It's called `macos_option_as_alt`.

**Comment by RickCogley** [comment]
Thanks for the extra info. Removed the hacky shortcut. Here's what I found: 

* iTerm, Prefs, Profiles (select my profile), Keys, then
* Right/Left option key: Esc+

Now pressing right or left option plus h on my external or built-in keyboard acts as expected and the help appears. 

Doing a little research, the normal setting for option+h is to insert a superscript dot. This was happening in both iterm and kitty. I'll try that setting you mentioned for kitty and see how it goes. I haven't used that terminal at all yet. 

Another wrinkle in my setup is, I'm in Japan and have Japanese input set up. My keyboards are US layout, but I have the Japanese input set as an option. That being said, I doubt it's an issue, because when I tested I made sure the US English input was selected. 

Also I found the "xterm defaults" you mentioned and set it. It was in the _profile_ keys pane rather than in the generic keys pref pane.

**Comment by romkatv** [comment]
> Doing a little research, the normal setting for option+h is to insert a superscript dot.

That's what it does (and it makes sense) in graphical applications on macOS. For some reason Apple has made the mistake (probably due to not paying attention) of giving Option key the same behavior in Apple Terminal. And then all alternative terminals on macOS felt the pressure to copy this as the default and urge users to change it through settings.

> I'll try that setting you mentioned for kitty and see how it goes. I haven't used that terminal at all yet.

Sure, as long as you have a reason to switch your terminal.

> Another wrinkle in my setup is, I'm in Japan and have Japanese input set up. My keyboards are US layout, but I have the Japanese input set as an option. That being said, I doubt it's an issue, because when I tested I made sure the US English input was selected.

I also have several keyboard layouts. I believe most people in the world do. Any software that breaks in this setting won't survive.

Also just to make it clear, this whole discussion about Option, Alt, macOS terminals and key bindings is not specific to zsh4humans. <kbd>Alt+H</kbd> bindings is the default in Zsh. Other default Zsh bindings with <kbd>Alt</kbd> include <kbd>Alt+B</kbd> and <kbd>Alt+F</kbd>.

**Comment by RickCogley** [comment]
Yes, it's OT for sure. Sorry to have dragged you into this but I appreciate the guidance. Hopefully someone can gain something from this tangent. :)

**Comment by tumd** [comment]
A little note about the kubectl completions. I think more than kubectl use this form to distribute their completions. Helm uses a similar approach.
Also, it would be _nice to have_ this completion-loading to some how automagically update when the completions have changed - i.e. when the (kubectl-, helm-, others-) binary have been updated to a newer version.

**Comment by romkatv** [comment]
>
> A little note about the kubectl completions. I think more than kubectl use
> this form to distribute their completions. Helm uses a similar approach.
>

Thanks, that's good to know.

By the way, the code produced by `kubectl completion zsh` is awful.
Someone's made a design mistake of incorporating code patching into the
produced script instead of applying it inside `kubectl`. Simply sourcing
the script takes over 100ms on my machine. In z4h I've deferred it until
the first use of `kubectl` completion.

Also, it would be *nice to have* this completion-loading to some how
> automagically update when the completions have changed - i.e. when the
> (kubectl-, helm-, others-) binary have been updated to a newer version.
>

In z4h it does that. In Oh My Zsh it does not.

>

**Comment by RickCogley** [comment]
by the way, now that the <kbd>ALT+H</kbd> and other bindings are working, it's just such a nice environment to work in.

**Comment by romkatv** [comment]
> by the way, now that the ALT+H and other bindings are working, it's just such a nice environment to work in.

Thank you 😉
