### ISSUE TITLE
linux brew breaks man pages

### ISSUE THREAD

**Issue by ycardon** [romkatv/zsh4humans#46]
Hi @romkatv, since the linux brew integration, the `man` command only list brew manpages.

```sh
❯ echo $MANPATH
/home/linuxbrew/.linuxbrew/share/man
```

When I type `MANPATH=$MANPATH:` (note the trailling `:`), I get all the manpages back.

**Comment by romkatv** [comment]
Thanks for the bug report! Fixed.

I haven't uncovered this bug during testing because `man` on my system automatically searches `$dir/../man` and `$dir/../share/man` for every `dir` from `PATH`. It's a handy feature but it can hide issues like this one.
