### ISSUE TITLE
prompt visual glitch inside Dolphin terminal view when clicking folders

### ISSUE THREAD

**Issue by ycardon** [romkatv/zsh4humans#48]
note: maybe I should have opened this in https://github.com/romkatv/powerlevel10k

KDE Dophin file manager can open a terminal view which stays synchronized with the folder tree view: whenever you `cd` inside the terminal, the folder tree view switches to this directory, whenever you click a folder, the terminal `cd` to this directory.

It works great with z4h/p10k but when I click a folder in the tree view, I get a visual glitch:

![image](https://user-images.githubusercontent.com/1177253/90240870-52f4f780-de2a-11ea-8fe5-9e10b37ab32f.png)

It looks like Dolphin is pasting a '\n cd myfolder` or something close, as a result I get extra "dirty" lines inside the terminal view. In the previous example, I successively clicked on the '\' folder, then on the '\etc' one.

I'm using p10k with pure theme and a transient prompt.

Note that it's really a very minor thing, I really rarely use that Dolphin terminal view. Feel free to close it.

**Comment by romkatv** [comment]
Could you run `cat -v`, click on a folder and post a screenshot here? I'd like to know the exact command Dolphin pastes but I'm too lazy to install KDE for it.

**Comment by ycardon** [comment]
This does not output anything (Dolhpin might detect a command is running).
I'm looking for a way to find the command, I will come back to you.

**Comment by ycardon** [comment]
I've found the source code:
https://github.com/KDE/dolphin/blob/97a14db70d9d16e595d1bced0d77ccdbba298bd9/src/panels/terminal/terminalpanel.cpp#L211-L244

**Comment by romkatv** [comment]
If you just type that, it'll work fine. Maybe it's because they don't send `\r`? I'm not sure. Either way, going to close as it's unclear what I can do.
