### ISSUE TITLE
slow autocomplete for files and directories

### ISSUE THREAD

**Issue by woss** [romkatv/zsh4humans#51]
in my repo i have `scripts` folder with 1 file inside. it takes seconds to autocomplete. any idea how can i make it faster? or how to diagnose what is going on

thanks

**Comment by romkatv** [comment]
This is likely fixed in v3 but it’s not public yet. You can either upgrade now or wait until v3 is released. The only way to upgrade is by installing v3 and then moving your customizations to the new zshrc.

**Comment by romkatv** [comment]
v3 installation instructions in case you want to try it: https://github.com/romkatv/zsh4humans/tree/v3#installation

**Comment by woss** [comment]
do i have to uninstall prev version first?

**Comment by romkatv** [comment]
No, it shouldn’t be necessary.

**Comment by woss** [comment]
```sh
❯ if command -v curl >/dev/null 2>&1; then
then>   sh -c "$(curl -fsSL https://raw.githubusercontent.com/romkatv/zsh4humans/v3/install)"
then> else
else>   sh -c "$(wget -O- https://raw.githubusercontent.com/romkatv/zsh4humans/v3/install)"
else> fi
z4h: platform linux x86_64 is supported
z4h: z4h startup files already exist

    ~/.zprofile
    ~/.zshrc

  (1)  Move them to ~/zsh-backup/2020-09-25-17-10-09
  (2)  Delete them.
  (q)  Quit and do nothing.

Choice [12q]: 1
z4h: fetching ~/.zshenv from romkatv/zsh4humans
z4h: fetching ~/.zshrc from romkatv/zsh4humans
z4h: bootstrapping zsh environment
z4h: fetching z4h.zsh
z4h: installing zsh4humans
z4h: cannot find usable zsh
z4h: fetching zsh 5.8 installer
sh: 59: /home/USERNAME/.cache/zsh4humans/v3/zsh4humans/sc/exec-zsh-i: Z4H_SSH: parameter not set
```
hm, how come `z4h: cannot find usable zsh`

**Comment by woss** [comment]
hm, when i opened new terminal it required me to download zsh and install it and 
```sh
 export PATH="/home/daniel/.local/bin:$PATH"
  zsh
```

**Comment by woss** [comment]
now adding custom stuff to new zshrc, i have this
```sh
/usr/bin/keychain --nogui /pat/to/pvt1
/usr/bin/keychain --nogui /path/to/pvt2
source $HOME/.keychain/$HOST-sh
```

in which part of the new zshrc i have to add this?

**Comment by romkatv** [comment]
If it can perform console IO, add it above `z4h init`, otherwise add it below. (This is in the comments btw.)

**Comment by woss** [comment]
then it seems i've read the comments because it was before in my old zshrc that way. good, i just wanted to make sure that that I/O didn't messed up the powerline. now v3 works without any issues and the autocomplete is WAY faster

thanks a lot :)

**Comment by romkatv** [comment]
> ```shell
> sh: 59: /home/USERNAME/.cache/zsh4humans/v3/zsh4humans/sc/exec-zsh-i: Z4H_SSH: parameter not set
> ```

Thanks for reporting this. Fixed.
