### ISSUE TITLE
Add completions for hashicorp vault

### ISSUE THREAD

**Issue by maximbaz** [romkatv/zsh4humans#55]
I noticed you have a few built-in completions for apps that generate them directly (kitty, helm, cargo, rustup, etc). I'd like to propose adding completions for hashicorp vault, which I think is a very common tool these days to manage secrets.

Currently their [docs](https://github.com/hashicorp/vault/blob/master/website/pages/intro/getting-started/index.mdx#command-completion) says to run `vault -autocomplete-install`, which in turn places the following lines to the end of `.zshrc`:

```
autoload -U +X bashcompinit && bashcompinit
complete -o nospace -C /usr/bin/vault vault
```

**Comment by romkatv** [comment]
Thanks for filing a feature request and making it very easy for me to implement it.

Done.
