### ISSUE TITLE
How to bind the Space key using z4h bindkey?

### ISSUE THREAD

**Issue by pkazmier** [romkatv/zsh4humans#59]
In v2, I used to have the following to bind Ctrl Space and Alt Space (so hands don't have to leave keyboard to use the default Shift Left and Shift Right)

```
bindkey -M emacs '^ ' z4h-cd-back
bindkey -M emacs '^[ ' z4h-cd-forward
```

I upgraded to v4 today and noticed it seems the preferred way to bind keys is with `z4h bindkey`, but I can't seem to figure out how to bind the Space key. Any tips?

**Comment by romkatv** [comment]
Plain `bindkey`  still works, so you can keep using it. `z4h bindkey` is a front-end that makes it a bit easier to specify key combos such as <kbd>Ctrl+Shift+Left</kbd>.

I've just added support for <kbd>Space</kbd>, <kbd>Ctrl+Space</kbd> and <kbd>Alt+Space</kbd>/<kbd>Option+Space</kbd>.

**Comment by pkazmier** [comment]
Thank you @romkatv! Works wonderful. I know I say this each time, but this project is amazing and really makes zsh approachable and usable with **minimal** fuss. Keep up the great work!

**Comment by romkatv** [comment]
Thank you :hugs:
