### ISSUE TITLE
Zstyle settings documentation

### ISSUE THREAD

**Issue by anstadnik** [romkatv/zsh4humans#60]
Hi. I would like to disable `--exact` setting for fzf. I've found `zstyle ':z4h:fzf-history' fzf-flags    '--no-exact'`, which works for history search, but I couldn't do the same for file matching (when I type `ls ~/` and press TAB). I tried `style ':z4h:expand-or-complete:fzf' flags    '--no-exact'`, as I found in notes.md, but it doesn't seem to work. Is there a place where those options are documented?

**Comment by romkatv** [comment]
There are three widgets that use this zstyle: fzf-history, fzf-complete and cd-down. You can set the style for all of them like this:

```zsh
zstyle ':z4h:(fzf-history|fzf-complete|cd-down)' fzf-flags '--no-exact'
```

Note that <kbd>Tab</kbd> inserts an anchored query by default, so when you complete `ls --d`, you get `^--d` as the initial query in fzf. This query performs exact prefix match even if you pass `--no-exact`.

Depending on what UX you want you might want to change the query. Perhaps remove the `^` anchor.

```zsh
zstyle ':z4h:fzf-complete' fzf-command my-fzf

function my-fzf() {
  emulate -L zsh
  # Replace all arguments that start with "--query=^" with "--query=".
  fzf "${@/#--query=^/--query=}"
}
```

You could also clear the query, or add a space after it.

**Comment by anstadnik** [comment]
Thanks! It fixed the issue, though, it'd still be great to see a bit more documentation for those kinds of settings. It was hard for me to find any clues about tweaking such stuff. I'd like rather not bother you and figure that out myself. Hope you're planning to do something like that, cause the setup is amazing!
BTW, thank you for this project, I moved to it after 2+ years of tweaking my dotfiles, as it behaves almost the same, but works faster and is not as messy as my dotfiles were :)

**Comment by romkatv** [comment]
> it'd still be great to see a bit more documentation for those kinds of settings.

For sure.

zsh4humans is in active development. Every now and then I snapshot the current version and it becomes a new release that's guaranteed to have backward compatibility forever (no new features, only fixes for serious bugs). v4 is one of those. v5 is planned to be the last release. After than no more backward incompatible new versions, only backward compatible improvements. At that point I'll write docs. Right now I cannot find the time for it, sorry.

> BTW, thank you for this project

You are very welcome!

**Comment by danielkrajnik** [comment]
It's 2023 and nothing changed. This project is still very poorly documented.

You will have easier time configuring zsh from scratch than using z4h.

**Comment by danielkrajnik** [comment]
I've mentioned it in [a new issue](https://github.com/romkatv/zsh4humans/issues/271) before reading this - there still doesn't appear to be any documentation how to debug problems in zsh. 

Is there any way to remove features from zsh to find out what's causing slow downs? It can get really really slow (20+ seconds)

**Comment by romkatv** [comment]
> there still doesn't appear to be any documentation how to debug problems in zsh.

You aren't wrong. This project has very limited documentation and even more limited support.

**Comment by danielkrajnik** [comment]
Sorry, but how would you troubleshoot your shell if it was slow on start? Any hint would be really appreciated. Are there anything you can remove to track down the reasons?
