### ISSUE TITLE
fzf + promp char in v5

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/zsh4humans#63]
I am on v5 (latest as of 20h ago 73cb7c8). When I go to ctrl+R, depending on the number of lines already present in my buffer the prompt char for fzf and my terminal prompt char look... weird. Not sure that it is necessarily a bug or just a function of how fzf window gets drawn + my p10k prompt char customization. 
This is how I am drawing my prompt. If there is a better/more compatible way, open to suggestions.
```
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%238F╭─'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%238F├─'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%238F╰─%015F▪'
```
<img width="1680" alt="Screen Shot 2020-10-29 at 11 47 55" src="https://user-images.githubusercontent.com/5804477/97558737-cd222a80-19dc-11eb-9afc-9e8b74a66796.png">

<img width="1680" alt="Screen Shot 2020-10-29 at 11 48 11" src="https://user-images.githubusercontent.com/5804477/97558764-d6ab9280-19dc-11eb-8156-1bf98c37b2f2.png">

<img width="1680" alt="Screen Shot 2020-10-29 at 11 48 50" src="https://user-images.githubusercontent.com/5804477/97558769-dad7b000-19dc-11eb-8cff-10195fecfca2.png">

**Comment by romkatv** [comment]
This is working as intended. Or at least as intended for now. It looks weird because you have "frame" in prompt. Without the frame it'll look better.

**Comment by kurktchiev** [comment]
kk, i am taking everything as default so as of the moment I am trying to not steer too far from vanilla. if intended i will just close this.
