### ISSUE TITLE
Git command with ^ outputs "zsh: no matches found"

### ISSUE THREAD

**Issue by pnsantos** [romkatv/zsh4humans#64]
First off I just want to thank you @romkatv for this wonderful piece of labour - it works wonderfully well and it's a productivity booster with daily impact! Thank you!

I ran into a minor issue, not sure if it's just a zsh thing or if it's somehow related to zsh4humans.

When I run this:
```
git cherry-pick 0276966^..b7b9a05
```
it fails with output:
```
zsh: no matches found: 0276966^..b7b9a05
```
using double quotes works:
```
git cherry-pick "0276966^..b7b9a05"
```
(using `v4` with no additional plugins)

**Comment by romkatv** [comment]
This is how zsh works. When `extended_glob` shell option is enabled, `^` is a glob metacharacter similar to `*` and `?`, so it needs to be quoted.

**Comment by pnsantos** [comment]
Thx for the quick reply. Will close.
