### ISSUE TITLE
WSL init breaks when windows C: drive is mounted at /c and not /mnt/c

### ISSUE THREAD

**Issue by gerryg80** [romkatv/zsh4humans#66]
I saw an error about /mnt/c/ not existing at least twice while installing zsh4humans but wasn't able to capture it. Then after install I get this when starting a new shell - guessing all errors were coming from the same place.

    -z4h-init-wsl:3: no such file or directory: /mnt/c/Windows/System32/cmd.exe

From this line:
```zsh
local lines=("${(@f)${$(cd /mnt/c && /mnt/c/Windows/System32/cmd.exe /c set)//$'\r'}}")
```
The cd /mnt/c and prefixing the call to cmd.exe with the full path are unnecessary.  cmd.exe is available on the wsl path, so simply "cmd.exe /c set" will dump the DOS environment.

I tested that change on my local and the error went away. I also see ~w in the prompt now when on my windows home directory where previously the script died before setting that up.

**Comment by romkatv** [comment]
Thanks for the report! Fixed.

**Comment by gerryg80** [comment]
The error is gone but it's still trying to run cmd.exe from /mnt/c/

This:
```zsh
local cmd=${commands[$cmd]:-/mnt/c/Windows/System32/cmd.exe}
```
should be

```zsh
local cmd=${commands[cmd.exe]:-/mnt/c/Windows/System32/cmd.exe}
```
That gets me back to having ~w in the prompt when on my windows home directory

Also a bit further down I found this if expression that appears to expect DOS drives to be off /mnt 

```zsh
if [[ $home != [a-zA-Z]':\'* || ! -d ${home::=/mnt/${(L)home[1]}/${${home:3}//\\//}} ]]; then
```

I don't know how common it is to move the mount point to /c instead of /mnt/c but you'll find that in a lot of recommendations on wsl configuration and it's easy to do. /etc/wsl.conf is optional but when present it can contain the setting to alter the mount point like this:

```ini
[automount]
options="metadata"
root="/"
```
btw this is really cool stuff and thank you for all the effort on this. I only recently discovered this for my full time linux machines and was happy to see it works well in wsl too.

**Comment by romkatv** [comment]
> The error is gone but it's still trying to run cmd.exe from /mnt/c/

Sorry about that. It was sloppy on my part. Fixed.

> Also a bit further down I found this if expression that appears to expect DOS drives to be off /mnt

It's an optimization to avoid the slow `wslpath`. I've added a check for `/c` mounts in there.

**Comment by gerryg80** [comment]
thank you - looks good now. And thanks for the quick fixes.

**Comment by romkatv** [comment]
Thanks for filing a high quality and on point bug report!
