### ISSUE TITLE
iSH and z4h v5

### ISSUE THREAD

**Issue by kurktchiev** [romkatv/zsh4humans#69]
So I know this is an edge case at best, so feel free to tell me to pound sand :). I am using iSH, which is similar to Termux for android, on iPadOS and when I go to install I get `z4h: sorry, unsupported platform: linux i686`

**Comment by romkatv** [comment]
Yep, it’s not supported. Not only is it hassle to build for 32-bit Intel, iSH also doesn’t correctly implement process substitution so a good chunk of pure zsh (or bash) code cannot work there. See https://github.com/ish-app/ish/issues/783.
