### ISSUE TITLE
Neofetch starts twice on shell startup

### ISSUE THREAD

**Issue by thepreacher** [romkatv/zsh4humans#70]
Hello, I'm on v5 now and had some issues as reported on #62 . Glad to say all the issues have been resolved. Thanks a ton! Just one slight new issue though, as in the previous issue I start `neofetch` for every new login shell with the ff code:

```
if [[ -o login ]]; then
    neofetch
fi
```
at the top of my `.zshrc` as you suggested previously. When I start a new login shell, I get this

<img width="861" alt="image" src="https://user-images.githubusercontent.com/219075/98331716-0e29c880-1ff5-11eb-9911-427a485fc24d.png">

Neofetch gets started twice. Hoping you can help me fix this. 

Also, I tried to dig deeper in order to understand your core code and I've got say most of it feels like magic to me. I'm hoping when things settle down for you, you can put together some documentation to help those who may want to study or understand you code a little deeper. Cheers.

**Comment by romkatv** [comment]
v5 is a bleeding edge development branch. If you want to use it, be prepared for frequent backward incompatible changes, meaning that you shell will break after `z4h update` until you change your config file. It's highly recommended to follow https://github.com/romkatv/zsh4humans/issues/35 where I post about backward-incompatible changes. This issue has fairly high traffic. As for `neofetch`, the solution in v5 for now is to not invoke `neofetch`.

Judging by our conversation in https://github.com/romkatv/zsh4humans/issues/62, I would strongly recommend not using v5.

**Comment by thepreacher** [comment]
Yeah you're right I'll. I'll leave v5 alone for a while. Cheers.
