### ISSUE TITLE
Fails to install on Fedora 33 with nosudo user

### ISSUE THREAD

**Issue by abitrolly** [romkatv/zsh4humans#72]
```
z4h: installing zsh4humans
z4h: login shell isn't the same as this shell

  user         abitrolly
  login shell  /bin/bash
  this shell   /usr/bin/zsh

Change login shell of abiroot to /usr/bin/zsh? [y/N]: n

Won't ask again unless $Z4H/stickycache/no-chsh is deleted.
-z4h-run-process-tree:trap:20: undefined signal: ABRT
z4h: installing zsh-autosuggestions
```
If I press `y` it asks for `sudo` password, which is strange. As a user, I should be able to change my shell without `sudo`.

**Comment by romkatv** [comment]
> ```
> -z4h-run-process-tree:trap:20: undefined signal: ABRT
> ```

Thanks for reporting this error. Fixed.

> If I press `y` it asks for `sudo` password, which is strange.

I suppose `/usr/bin/zsh` isn't listed in `/etc/shells`. Adding it requires root access.

> As a user, I should be able to change my shell without `sudo`.

Do you mean that you can change your login shell to `/usr/bin/zsh` without `sudo`? If so, how?

**Comment by romkatv** [comment]
> Fails to install on Fedora 33 with nosudo user

Could you clarify what exactly doesn't work? From the description of the issue I gathered two points:

1. There is an error saying "undefined signal: ABRT". This is fixed.
2. Changing logging shell to `/usr/bin/zsh` requires `sudo` when you believe it shouldn't be required. I can improve this if you can tell me how you can change login shell to `/usr/bin/zsh` without `sudo`.

Note that the second point isn't a part of installation. You can change login shell manually if you want to. You can also use zsh4humans without making `/usr/local/zsh` your login shell.

Is there anything else?

**Comment by abitrolly** [comment]
```
❯ cat /etc/shells
/bin/sh
/bin/bash
/sbin/nologin
/usr/bin/sh
/usr/bin/bash
/usr/sbin/nologin
/usr/bin/zsh
/bin/zsh
/usr/bin/xonsh
/bin/xonsh
/usr/bin/tmux
/bin/tmux
```

> Do you mean that you can change your login shell to /usr/bin/zsh without sudo? If so, how?

No, I can not. :-(

**Comment by romkatv** [comment]
> > Do you mean that you can change your login shell to /usr/bin/zsh without sudo? If so, how?
> 
> No, I can not. :-(

Then I'm afraid that zsh4humans also cannot. It could with root access though, that's why it's asking for it. But it's fine to say "no" and keep bash as your login shell. zsh4humans will still work. If you are feeling brave, you can even add `[[ $- == *i* ]] && exec zsh` at the top of `~/.bashrc`.

Is there anything else or can this issue be closed?

**Comment by abitrolly** [comment]
I think that's it for now. Thanks. )
