### ISSUE TITLE
Screen clears when logging in, switching users, etc. 

### ISSUE THREAD

**Issue by eddyg** [romkatv/zsh4humans#73]
Hi Roman.

Is there a way to disable the screen-clearing that occurs upon login, logout, switching users via `sudo`, etc. when using **zsh4humans**? I prefer to have the context of "where I came from" on my screen.

Thanks for any insight!

**Comment by romkatv** [comment]
Please attach your `.zshenv` and `.zshrc`.

**Comment by eddyg** [comment]
This is literally a brand-new install of Ubuntu Server 20.04.1; about the only thing I did was `sudo apt -y install zsh; chsh -s /bin/zsh` and then installed the latest `z4h` with the documented `sh -c "$(curl ...`.

The only "customization" I've done so far is commenting out the `ohmyzsh` lines from `.zshrc` and then running `rm -fr .cache/zsh4humans/v5/ohmyzsh .cache/zsh4humans/v5/cache/ohmyzsh`.

If you're curious, this is what I see. Notice the screen clears when I `ssh` in, when I run `sudo`, when I exit `sudo`, and when I logout.
![ScreenShot 2020-11-07-11 01 31](https://user-images.githubusercontent.com/3235109/98446093-52969080-20e9-11eb-9235-7e230f4151ed.gif)

and for reference, the only other zsh files are the "stock" ones:
![ScreenShot 2020-11-07-11 13 00@2x](https://user-images.githubusercontent.com/3235109/98446262-45c66c80-20ea-11eb-80db-93251d42c726.png)

[dot-zshenv.txt](https://github.com/romkatv/zsh4humans/files/5505054/dot-zshenv.txt)
[dot-zshrc.txt](https://github.com/romkatv/zsh4humans/files/5505055/dot-zshrc.txt)

As always, thanks for your time!

**Comment by romkatv** [comment]
Thanks for the details.

You can disable "clearing the screen" like this:

```zsh
zstyle :z4h:start-tmux no
```

This would make it pointless to use v5. You would get all the disadvantages of the unstable version (frequent backward-incompatible updates, bugs, etc.) without any advantages. Currently all new features in v5 compared to v4 (the latest stable release) rely on tmux.

zsh4humans is meant to be used slightly differently. You install it on the local machine and that's it. You don't need to install it on remote machines. Instead, you let z4h teleport itself over ssh automatically. If you do this, screen "clears" only when you start a local terminal, which you won't notice because the screen is empty anyway. It won't clear when you ssh. However, `sudo -i` will still "clear" the screen. Did you really install z4h as a regular user and then again as root? It's really not a good idea to install z4h as root, especially the unstable version. If you want to open your regular zsh shell as root, use `sudo -Es`.

Is there a reason you don't install zsh4humans on the local machine but do install it on the remote?

(I use "clear" in quotes because what actually happens is tmux starting.)

**Comment by eddyg** [comment]
Thanks for the explanation, Roman!

I didn't realize there was an "architectural" change with v5. I will occasionally need to login to this server from the "console" (i.e. plug in a keyboard and monitor) since it will be located remotely, and there are some tasks that are just easier (or required, since it has no remote management capability) to do standing in front it, and it's nice to have a consistent environment. Hence, the desire for a local install. I've removed v5 and installed v4 and all is well.

I do normally `sudo -Es` but I did a manual install as `root` as part of my debugging to see if it made any difference.

While I'm writing, I am curious what the two extra `zsh` processes I see with each login (one is the interactive shell, one is `gitstatusd`, curious about the other two):

```
❯ w
 18:50:41 up 1 day, 18:37,  2 users,  load average: 0.00, 0.00, 0.00
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
alfred   pts/0    10.101.0.101     18:38   10:52   0.83s  0.03s less
alfred   pts/1    10.101.0.101     18:39    1.00s  3.25s  0.00s w

❯ pstree -au alfred
sshd
  └─zsh
      └─pstree -au alfred

sshd
  └─zsh

systemd --user
  └─(sd-pam)

zsh
  └─gitstatusd-linu -G v1.3.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 8
      └─8*[{gitstatusd-linu}]

zsh

zsh

zsh
  └─gitstatusd-linu -G v1.3.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 8
      └─8*[{gitstatusd-linu}]

zsh

zsh

❯ ps axo stat,euid,ruid,tty,tpgid,sess,pgrp,ppid,pid,pcpu,comm,args | grep '[z]sh'
STAT  EUID  RUID TT         TPGID    SESS    PGRP    PPID     PID %CPU COMMAND         COMMAND
Ss    1000  1000 pts/0      52675   52539   52539   52538   52539  0.1 zsh             -zsh
S     1000  1000 pts/0      52675   52539   52540       1   52541  0.0 zsh             -zsh
S     1000  1000 pts/0      52675   52539   52549       1   52550  0.0 zsh             -zsh
S     1000  1000 pts/0      52675   52539   52549       1   52551  0.0 zsh             -zsh
Sl    1000  1000 pts/0      52675   52539   52540   52541   52553  0.0 gitstatusd-linu /home/alfred/.cache/zsh4humans/v4/cache/gitstatus/gitstatusd-linux-x86_64 -G v1.3.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 8
Ss    1000  1000 pts/1      52728   52643   52643   52642   52643  0.4 zsh             -zsh
S     1000  1000 pts/1      52728   52643   52644       1   52645  0.0 zsh             -zsh
S     1000  1000 pts/1      52728   52643   52653       1   52654  0.0 zsh             -zsh
S     1000  1000 pts/1      52728   52643   52653       1   52655  0.0 zsh             -zsh
Sl    1000  1000 pts/1      52728   52643   52644   52645   52657  0.0 gitstatusd-linu /home/alfred/.cache/zsh4humans/v4/cache/gitstatus/gitstatusd-linux-x86_64 -G v1.3.1 -s -1 -u -1 -d -1 -c -1 -m -1 -v FATAL -t 8

~ ································································· alfred@butler 18:51:02
❯
```

**Comment by romkatv** [comment]
> Hence, the desire for a local install.

It's fine to install locally.

In the issue description you were either connecting from a non-z4h shell to a remote host with z4h, or using plain `ssh` (rather than `z4h ssh`) to connect from a z4h shell to a remote host with z4h. Do you have a reason for doing this? I don't expect people to do this because I don't know why they would. I'd like to know if you have a use case for this.

> I've removed v5 and installed v4 and all is well.

v4 may also function suboptimally in this case. At this point I don't consider this a downside because I don't know how the need to use z4h in this way may arise.

To clarify, here's my questions:

- If you are connecting from a non-z4h shell to a remote host with z4h: Why don't use install z4h on the local host?
- If you you've installed z4h on both the local and the remote host and then use plain `ssh` (rather than `z4h ssh`) to connect from local to remote: Why don't you use `z4h ssh`?

> While I'm writing, I am curious what the two extra `zsh` processes I see with each login (one is the interactive shell, one is `gitstatusd`, curious about the other two):

Could be async workers from p10k, or a watchdog from gitstatus. If you really want to know, `strace` them or attach a debbuger.

**Comment by eddyg** [comment]
> you were either connecting from a non-z4h shell to a remote host with z4h, or using plain ssh (rather than z4h ssh) to connect from a z4h shell to a remote host with z4h

I was connecting from a non-z4h shell. I haven't made the jump to "z4h everywhere". z4h seemed like an easy way to get a nice, well-appointed zsh environment on a new box with minimal effort to make zsh more agreeable while doing the rest of the setup and config.

> If you are connecting from a non-z4h shell to a remote host with z4h: Why don't use install z4h on the local host?

I have a customized zsh config (with a lot of machine-specific options, aliases, etc.) on my Mac that is a mish-mosh of *years* of tweaks. Honestly it's kind of a mess since it pre-dates any kind of "zsh framework".  In any case, it doesn't make sense to copy that config directly to a new Linux box (especially because of the BSDisms in various aliases, etc.). Right now it's lower on my priority list to compare my zsh config to the z4h defaults, figure out what functionality is duplicated and that I no longer need to worry about, add back other stuff I still want, and then combine it all together to make a "grand unified" config that would work on both Mac and Linux...

> Could be async workers from p10k, or a watchdog from gitstatus.

Sounds like I'll have to do some investigating to see how they're used. A new set of props appears with each login, regardless of whether I'm in a git repo or not. (I was thinking an option in p10k to defer launching `gitstatusd` until the first time you entered a git repo would actually be nice, since I often open short-lived transient terminal windows). This new Linux box is an older "thin client" type PC with limited CPU and memory, so I noticed the extra forks of zsh when I was checking resource utilization, and that's why I was curious if/why they were necessary. (Although admittedly, they don't seem to be using too much in the way of resources.)

**Comment by romkatv** [comment]
> z4h seemed like an easy way to get a nice, well-appointed zsh environment on a new box with minimal effort to make zsh more agreeable while doing the rest of the setup and config.

Sounds sensible. v4 (stable release) is a better choice for this use case than v5 (unstable, changing frequently, etc.).

> I have a customized zsh config (with a lot of machine-specific options, aliases, etc.) on my Mac that is a mish-mosh of _years_ of tweaks.

It's likely easier to migrate to z4h than you think, should you wish to do that. z4h configures the interactive zsh environment -- completions, history, widgets, etc. (think GUI) -- without touching the meat of the shell (think commands). If you separate your aliases, environment variables and functions in `~/.zshrc.mac`, you can simply `z4h source` that file from the `~/.zshrc` provided by z4h. You can also add `~/.zshrc.linux` and do conditional sourcing based on `$OSTYPE`:

```zsh
# common stuff goes here

case $OSTYPE in
  darwin*) z4h source ~/.zshrc-mac;;
  linux*) z4h source ~/.zshrc-linux;;
esac
```

You can also do conditional stuff based on `$HOST`.

The advantage of this approach is that you don't need to manage dotfiles on any machine except the local dev station.

No pressure though. If you are satisfied with your shell, there is no need to make any changes.

> > Could be async workers from p10k, or a watchdog from gitstatus.
> 
> This new Linux box is an older "thin client" type PC with limited CPU and memory, so I noticed the extra forks of zsh when I was checking resource utilization, and that's why I was curious if/why they were necessary.

These forked zsh processes are extremely unlikely to have measurable effect on any resources no matter how underpowered the machine. They are idle, and use very little memory thanks to COW.

> I was thinking an option in p10k to defer launching `gitstatusd` until the first time you entered a git repo would actually be nice, since I often open short-lived transient terminal windows.

What positive user-visible effects would you expect from this?

**Comment by eddyg** [comment]
Thanks for the tips, Roman! Maybe a “grand unified zsh config” will be less work than I’m expecting it to be.

> What positive user-visible effects would you expect from this?

I doubt there would be any user-visible effects. As an old-school sysadmin, I have an (admittedly unnecessary, in this day and age) awareness of a “clean” `ps` where every process has a purpose.

Thanks again!

**Comment by romkatv** [comment]
I've verified that p10k async worker is responsible for the creation of those two `zsh` forks. Note that the async worker is used only when you enable prompt segments that require it. There aren't that many of them. In my own dotfiles I don't use such segments so I don't normally see these two `zsh` forks.

If you remove everything you don't care about from `POWERLEVEL9K_{LEFT,RIGHT}_PROMPT_ELEMENTS`, you might notice that these forks are gone. Everything will also be marginally faster.

Also note that gitstatusd starts only if you enable `vcs` segment and there is `git` command on the machine. I never use `git` on machines I ssh to, so I add `vcs` to `POWERLEVEL9K_LEFT_PROMPT_ELEMENTS` conditionally.

**Comment by eddyg** [comment]
Ah! I was running with the "stock" z4h config of p10k when I posted all of the above, so I had not adjusted any of the default prompt segments yet. That also explains why I hadn't noticed it on my local p10k config.

Great tip about conditionally adding the `vcs` segment too.

Thanks again for following up with that extra bit of insight. Really appreciate it!
