### ISSUE TITLE
$path missing sbin directories

### ISSUE THREAD

**Issue by e28eta** [romkatv/zsh4humans#74]
Hello! I've just installed zsh4humans into an new zsh install. (I'm looking at switching from bash to zsh, and liked your project philosophy - very impressive work :tada:).

I've just noticed that neither `/usr/sbin` nor `/sbin` are part of my `$PATH` when I use zsh4humans, and that seems broken.

As a longtime mac user, my expectation is `/usr/libexec/path_helper` (and `/etc/paths{,.d}`) would be used. I use `/etc/paths` to put `/opt/local/bin` and `/opt/local/sbin` early in my path, so that macports-installed executables have priority. My machine also has some entries in `/etc/paths.d` that I'd like to have access to (ex: [rvictl](https://developer.apple.com/forums/thread/125402?answerId=392314022#392314022), installed by Xcode). 

I found https://github.com/romkatv/zsh4humans/commit/a2853e88ec2f53b6dd615363f5e84565c920e41b :tada: - but I also found your warning that v5 is [changing often](https://github.com/romkatv/zsh4humans/issues/70#issuecomment-722940473), so I'm hesitant to try it. I _think_ my personal preference would be for the `path_helper` fix to be back ported to v4 (I realize it's only been 4 days, and I don't know if there are any downsides). Especially if it retains (some?) control over path entry order.

Alternatively, I know I can update my `~/.zshrc` to set the PATH up how I want it. However, it seems like a bug worth fixing that `/sbin` and `/usr/sbin` are not on the `$PATH` out of the box. (Feel free to tell me I'm wrong!)

I don't know if this behavior is specific to a macports-installed version of zsh, or something else in my environment that I've overlooked. If it were common, I'd expect other users to have already complained about it (ex: `/usr/sbin/chown`). Looking at discussion in #62, and trying to read between the lines, it looks like that user *did* have the sbin directories on their path by default, so... 🤷‍♂️ 

---

My environment:
- macOS 10.15.7
- zsh v5.8, installed as `/opt/local/bin/zsh` via macports (since `/bin/zsh` is v5.7.1 & macports is my pkg mgr of choice)
- zsh4humans v4, installed ~12 hours ago (latest commit e6e20a79068141be9ac5d92ad349d0648b314a1e)
- default shell for my user set to `/opt/local/bin/zsh` via `chsh`, and Terminal.app preferences to open "Default login shell" for new shells
- no `~/.zprofile`, no `~/.zlogin`. Un-edited/macOS-provided `/etc/{zprofile,zshrc,zshrc_Apple_Terminal}`
- `~/.zshenv` and `~/.zshrc` from zsh4humans

When I create a new Terminal.app window:
```
$PATH at beginning of ~/.zshenv: /usr/bin:/bin
❯ echo $path
/Users/daniel/bin /usr/local/bin /opt/local/bin /Users/daniel/.cache/zsh4humans/v4/fzf/bin /usr/bin /bin
❯ echo "${_z4h_exe:h}"
/opt/local/bin
```

I *think*:
- `~/bin` and `/usr/local/bin` come from `-z4h-init`
- `/opt/local/bin` and `.../fzf/bin` are coming from `main.zsh`
- `/usr/bin` and `/bin` were set prior to `~/.zshenv`, based on the echo that I added to the top of that file.

The only reference I can find to `sbin` is in `main.zsh`, but that block only executes for `$OSTYPE == linux*`

---

I certainly don't want this to be "help me diagnose my weird setup", and I'm only reporting because I believe there's a good chance it *isn't* something weird and this is something you'd want to address.

One last thing I thought of, using `ps ewww <PID>` to attempt to inspect ENV variables:

1. Terminal.app *has* `PATH=/usr/bin:/bin:/usr/sbin:/sbin`
2. Terminal.app launches (or at least is the Parent PID for): 
**`login -pf daniel`**` TMPDIR=... XPC_FLAGS=0x0 LaunchInstanceID=... TERM=xterm-256color LANG=en_US.UTF-8 SSH_AUTH_SOCK=... SECURITYSESSIONID=... XPC_SERVICE_NAME=... TERM_PROGRAM=Apple_Terminal TERM_PROGRAM_VERSION=433 TERM_SESSION_ID=...`
I do *not* see the `PATH` environment variable listed, but the `-p` is supposed to tell it to *keep* the existing environment.

3. `login` launches zsh with the bin-only path I'm seeing in `~/.zshenv`:
**`-zsh`**` TMPDIR=... XPC_FLAGS=0x0 LaunchInstanceID=... TERM=xterm-256color LANG=en_US.UTF-8 SSH_AUTH_SOCK=... SECURITYSESSIONID=... XPC_SERVICE_NAME=0 TERM_PROGRAM=Apple_Terminal TERM_PROGRAM_VERSION=433 TERM_SESSION_ID=... SHELL=/opt/local/bin/zsh HOME=/Users/daniel LOGNAME=daniel USER=daniel `**`PATH=/usr/bin:/bin`**

I see the same `PATH=/usr/bin:/bin` if I launch bash instead of zsh, but because it rebuilds the PATH using `/usr/libexec/path_helper`, everything works as expected. So I don't know if that's useful at all.

**Comment by romkatv** [comment]
I've backported https://github.com/romkatv/zsh4humans/commit/a2853e88ec2f53b6dd615363f5e84565c920e41b to v4. Please run `z4h update` and check whether `PATH` is fixed.

**Comment by e28eta** [comment]
@romkatv looks great and seems to work perfectly.

```
PATH before any zsh4humans code runs: /usr/bin:/bin
❯ echo $path
/Users/daniel/bin /Users/daniel/.cache/zsh4humans/v4/fzf/bin /opt/local/sbin /opt/local/bin /usr/local/bin /usr/sbin /sbin /usr/local/MacGPG2/bin /Library/Apple/usr/bin /usr/bin /bin
```

Thank you so much!

**Comment by romkatv** [comment]
Thanks for verifying.
