### ISSUE TITLE
Change fzf binary path

### ISSUE THREAD

**Issue by BenoitPingris** [romkatv/zsh4humans#77]
Hi !
I have `fzf` already installed on my machine (0.24.1), however when I install/update z4h, it installs in the `.cache` folder another version of fzf, the 0.23.1.
I need the 0.24 version otherwise I have warnings while I use vim so it's a bit annoying. 
I can't find a way to change the fzf binary z4h will use. If I remove the one from the `.cache` folder the auto-completion breaks.
How can I change it and how can I prevent that future update won't reinstall  another older version of fzf ?

Thanks!

**Comment by romkatv** [comment]
You've asked several different questions. I'd like to understand which ones are important to you and why.

> I need the 0.24 version otherwise I have warnings while I use vim so it's a bit annoying.

This should be fixed now. Please run `z4h update` and restart your terminal (it's not enough to restart zsh in this case). After than `vim` should use your own fzf rather than the one from z4h.

> I can't find a way to change the fzf binary z4h will use. 

Why do you want to do that?

> how can I prevent that future update won't reinstall another older version of fzf ?

Why this?

**Comment by BenoitPingris** [comment]
I just want to control the fzf version I have so the one installed by z4h does not conflict with mine.
Isn't it possible to check if fzf is installed and if it is, skip this part?

If your update fixes that, that's cool :+1:

**Comment by romkatv** [comment]
> Isn't it possible to check if fzf is installed and if it is, skip this part?

Before considering potential solutions, I need to know what problems are in need of being solved.

On you run `z4h update` and restart your terminal, `fzf` should resolve to the system version you have installed. Please verify. If after that problems still remain, please describe them.

**Comment by romkatv** [comment]
> Once you run `z4h update` and restart your terminal, `fzf` should resolve to the system version you have installed. Please verify. If after that problems still remain, please describe them.

Please ☝️

**Comment by romkatv** [comment]
Closing do to inactivity.
