### ISSUE TITLE
[v5] Truecolor support

### ISSUE THREAD

**Issue by weirdan** [romkatv/zsh4humans#78]
### Issue

It appears the integrated tmux prevents 24bit ANSI colors from properly showing up in capable terminals (using Tilix 1.9 / VTE 0.62 here). Usually this is fixed in tmux by specifying `set -ga terminal-overrides ",xterm-256color*:Tc"` but adding that to `.cache/zsh4humans/v5/zsh4humans/tmux-256color.conf` doesn't seem to do the trick.

### Configuration

* Tilix 1.9 / VTE 0.62
* TERM is initially to `xterm-256color` by Tilix
* `~/.tmux.conf` that fixes the issue when running the same tmux binary standalone (shown at the bottom of the screenshot below):
  ```
  set -g default-terminal "tmux-256color"
  set -ga terminal-overrides ",xterm-256color*:Tc"
  ```
* <details><summary>Test awk script</summary>

  ```sh
  awk 'BEGIN{                                                                       
    s="/\\/\\/\\/\\/\\"; s=s s s s s s s s;
    for (colnum = 0; colnum<77; colnum++) {
        r = 255-(colnum*255/76);
        g = (colnum*510/76);
        b = (colnum*255/76);
        if (g>255) g = 510-g;
        printf "\033[48;2;%d;%d;%dm", r,g,b;
        printf "\033[38;2;%d;%d;%dm", 255-r,255-g,255-b;
        printf "%s\033[0m", substr(s,colnum+1,1);
    }
    printf "\n";
  }'
  ```

### Results

Z4H is shown above, with bash+tmux session underneath to show correct results

![image](https://user-images.githubusercontent.com/57403/99894064-20f5fb80-2c8b-11eb-803e-bb01ff71bc53.png)

**Comment by romkatv** [comment]
Thanks for the report. Should be fixed now. Please verify.

For future reference, here's a zsh version of the same script:

```zsh
() {
  emulate -L zsh -o prompt_percent -o ksh_arrays
  autoload -Uz zmathfunc && zmathfunc
  local bg fg
  local -i i r g b
  for i in {0..$((COLUMNS-1))}; do
    b='i * 255 / COLUMNS'
    r='255 - b'
    g='255 - abs(r - b)'
    printf -v bg '%02x' $r $g $b
    printf -v fg '%06x' "16#ffffff - 16#$bg"
    print -nP "%K{#$bg}%F{#$fg}${${:-/\\}[i%2]}"
  done
  print
}
```

**Comment by weirdan** [comment]
Thanks, working now. I've had a head-scratching moment when it didn't work after update, but then I realized that z4h must be reusing the tmux server (after all, the socket path hasn't changed). Once I've killed all tmux processes and restarted Tilix everything worked perfectly.

**Comment by weirdan** [comment]
>  I realized that z4h must be reusing the tmux server 

Also this must be the reason why my original attempts to fix the tmux config failed.

**Comment by romkatv** [comment]
Yeah, probably.

Thanks for verifying the fix.
