### ISSUE TITLE
Permission denied error during installation on WSL Ubuntu

### ISSUE THREAD

**Issue by Vizzard** [romkatv/zsh4humans#80]
Hi,

I have this error during installation on WSL1 Ubuntu 20.04:
```
z4h: installing zsh-autosuggestions
z4h: installing zsh-completions
z4h: installing zsh-syntax-highlighting
z4h: installing fzf
z4h: fetching fzf binary
-z4h-install-one:zf_mv:106: /home/user/.cache/zsh4humans/v4/fzf.new.dPjML4V7GJ/fzf: permission denied
z4h: installing ohmyzsh/ohmyzsh
z4h: installing powerlevel10k
z4h: fetching gitstatus binary

z4h: init failed
```

WSL2 works.

When I was looking for a solution I found this: romkatv/powerlevel10k#610
It made me try WSL2 version of the same Ubuntu 20.04 to see if there is something going on with the filesystem on WSL1.

If this won't be fixed due to how WSL1 works then I just want to leave it here as a hint for people with the same issue to use WSL2 if possibie.

Thanks!

**Comment by romkatv** [comment]
> I have this error during installation on WSL1 Ubuntu 20.04 [...]

Thanks for the bug report. I cannot reproduce this. I've made a few changes in the hope that maybe they'll fix this for you. I don't know if they help or not. Could you check?

> When I was looking for a solution I found this: [romkatv/powerlevel10k#610](https://github.com/romkatv/powerlevel10k/issues/610)

This looks unrelated.

**Comment by Vizzard** [comment]
It works now. Thank you!

**Comment by romkatv** [comment]
Thanks for verifying.
