### ISSUE TITLE
Man....

### ISSUE THREAD

**Issue by shoemoney** [romkatv/zsh4humans#81]
For the longest time...  over a year or so when I discovered p10k I wanted to thank you.   Everyone else is stuck in the mud and your doing some really cutting edge stuff.   Well the guy that made zplug is doing some neat things but doesn't seem nearly as cutting edge.

I wish I had more time to learn it but so much going on and only so much new things you can learn at once (even with the wonders of adderall and al nighters.    Although I do spend probably 95% of the time in my shell should probably just buckle down....

Anyway just wanted to say thank you.   I know open source can seem like a thankless job at times but there are many out there that really appreciate your work!!!!!!!!!!!!!

**Comment by romkatv** [comment]
Thank you! Made my day ❤️

**Comment by JSamir** [comment]
As someone with adhd I would appreciate if you remove the Adderall reference.

It makes me assume you take it although you do not have adhd but still take it, and this makes life unnecessarily harder (in many ways) for people with adhd.

**Comment by romkatv** [comment]
Locking.
