### ISSUE TITLE
[feature request] on z4h ssh, do not overwrite .zshrc when target is newer

### ISSUE THREAD

**Issue by ycardon** [romkatv/zsh4humans#82]
Hi Roman,

I have the following use case : I usually work from 2 different workstations (PC1, PC2) to access remote servers (S1, S2...) by ssh.

If make some changes on `.zshrc` on PC1  ssh to S1, then I've got latest `.zshrc` on S1, this is expected (and great).
It I then connect to S1 from PC2, the latest `.zshrc` gets overwritten with the "old" version of PC2.
It's even worse if I ssh from PC2 to PC1: I loose the `.zshrc` and the changes I made.

Could there be a mechanism to prevent that ? I was thinking of a modification time check but it also could be versionned. Maybe you could warn the user about the potential overwrite (showing the diffs) ?

**Comment by romkatv** [comment]
The idea is that you get the same shell environment on the remote host as you have on local. I think this is a good property. It's easy to understand and it makes sense.

Now, to solve your problem you need some way to synchronize dotfiles between PC1 and PC2. My favorite solution is to store your dotfiles in git an to sync them via a remote. You can also store command history this way (obviously, don't expose it to the public). z4h allows you to *pull* history from remote machines and to configure which history is available where. You can store history from all machines in a single private git repo and specify how history is shared between machines (when logged in to machine "foo", make past command history from "foo", and "*.bar.com" available). Your workflow can be as follows:

1. Log in to PC1 locally.
2. Run a script that synchronizes your dotfiles and history.
3. Do stuff.
4. Run a script that synchronizes your dotfiles and history.
5. Log out of PC1.

If you don't run the script, no big deal. Everything can always be merged later without conflicts.

This is roughly how I work. You can find details in https://github.com/romkatv/zsh4humans/issues/35#issuecomment-675908718. Most of my dotfiles are private but the public part still has decent amount of configuration related to synchronization, history and zsh. This is how I manage dotfiles: https://github.com/romkatv/zsh4humans/issues/35#issuecomment-678109125.

**Comment by ycardon** [comment]
I also think that having the same shell environment on the remote host as you have on local is a good property, but in certain cases it can be risky. My proposal was to warn the user about a potential risk, I think it's a sane behaviour, especially when design goals of zsh4humans is to make zsh accessible for new comers (which it does !).

I also do manage my dotfiles in a private git repo (with a detached bare repo, cf. below) and to prevent accidental erasure of local modifications, I excluded PC1 and PC2 form the z4h ssh list. In // I also ssh to my different servers to force a change everywhere but it's a little overkill and less effective as slowly propagating the new config whenever I need it.

Anyway, thank you again for your time and effort on this project !

```sh
# Function: manage dotfiles in a bare git repo: https://news.ycombinator.com/item?id=11071754
function dotfiles() {
  if [[ -d $HOME/.dotfiles ]]; then
    git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME "$@"
  else
    echo 'First time intitalization'
    git init --bare $HOME/.dotfiles
    dotfiles config --local status.showUntrackedFiles no
  fi
}
```

**Comment by romkatv** [comment]
> I also think that having the same shell environment on the remote host as you have on local is a good property, but in certain cases it can be risky.

This is a good point. So far my plan has been to back up files on the remote host but only once. Do it without asking and only print a message that this has been done. This would alleviate the most serious damage that one could inflict on one's config files by logging in to a dev machine with original dotfiles. Your comment made me think that maybe more safety measures would be a good idea. I'll think about it.

Knowing that you are an experienced and intelligent user, it's not obvious to me whether you are making a suggestion for the future development of z4h *for others* or requesting a feature *for yourself*. In general, I very much prefer the latter. Could you clarify whether for *you* the current behavior of z4h is what you want or not? Given that you already sync your dotfiles via a remote git repo, I'd think everything works as intended. If not, could you elaborate on your use case? More specifics would be better.

**Comment by ycardon** [comment]
> Could you clarify whether for _you_ the current behavior of z4h is what you want or not?

Fair enough :) 

To make things clearer, the behaviour I'd like to have is:
- detect that the remote config is more recent than the local one
- ask me wether I want to overwrite it or not (ie. do a "normal" ssh)

Let me elaborate. I work in a quite heterogeneous environment
- there are hosts that I `pet`:
  - my two workstations (Unbuntu and macOS) where dotfiles are partially synchronised (but not systematically nor automatically)
  - my servers (debian mostly and some archlinux and NixOS) that I'm not synchronising
- other hosts that I treat like `cattle`: VMs in the clouds or docker images I'm connecting to debug

The actual behaviour of z4h is perfect for `cattle`: I get my familiar environment without spending time in industrialisation.

My request is specifically to address the `pet` hosts: either because I didn't take the time / forgot to commit my dotfiles on the workstations or because I'm connecting from server to servers. Reading you, I realise I could spend more time on automation: I'd say that I'm using my dotfiles more for backup than synchronisation.

**Comment by ycardon** [comment]
I now synchronize `.zshrc` on my main workstation via git.
Copy via `z4h ssh` is only used on my `cattle` servers.

**Comment by romkatv** [comment]
> I now synchronize `.zshrc` on my main workstation via git.
> Copy via `z4h ssh` is only used on my `cattle` servers.

Good call.

By the way, I wasn't acting on this PR because it's non-trivial. Right now, when you connect to a remote host with `z4h ssh`, the code checks whether the remote site's cached version of zsh4humans is fresh enough to support all features on which your zshrc may be relying. You may have seen that sometimes when you `z4h ssh` it starts auto-updating. This happens whenever your local zsh4humans has a new feature that the remote host is lacking. Since you zsh startup files *might* be using this feature, zsh4humans needs to be updated.

This doesn't work if some dotfiles don't get copied. You can end up with incompatible zshrc and zshenv and it'll be unclear which version of zsh4humans is "fresh enough".

This can probably be solved but it's work. Given that this work would support a use case that has a better solution (the one you are using now), I didn't want to spend time on it.

**Comment by romkatv** [comment]
Forgot to mention that this issue was very valuable to me even if it didn't result in any zsh4humans changes. Please continue filing such issues in the future. They help shape zsh4humans as a product and give me an understanding of the users' needs in the real world.
