### ISSUE TITLE
[question] is there a way in z4h to determine the host OS kind ?

### ISSUE THREAD

**Issue by ycardon** [romkatv/zsh4humans#83]
As advised on z4h documentation, I guard some declarations or statements of my `.zshrc` with checks on whether a command exists or whether a path exists. There are some cases where I'd like to do checks on the host OS kind (for example, I don't want to `z4h install` some modules on a NAS).

What I do right now is adding the following section in my `.zshrc`

```sh
export HOST_OS_KIND=$(
  if (( $+commands[lsb_release] )) then; lsb_release -i | awk '{print $(NF)}'
  elif [[ $(uname) == 'Darwin' ]] then; echo 'macOS'
  elif [[ $(uname -a|grep synology) ]] then; echo 'Synology'
  else; echo 'unknown'
  fi
)
``` 
Is there a ready-to-use function / env variable in z4h to determine the kind of the host OS ? Alternatively, this function exists in p10k in order to show the `os_icon`, is there a way to reuse it in `.zshrc` ?

**Comment by romkatv** [comment]
Usually it's enough to switch on kernel, cpu, environment and availability of commands and files. Occasionally you might wan to switch on hostname, too.

```zsh
if [[ $OSTYPE == darwin* ]]; then
  # something specific to mac
elif [[ $OSTYPE == linux* ]]; then
  # something specific to linux
if

if [[ $CPUTYPE == x86_64 ]]; then
  # something specific to x86_64
fi

if [[ -v commands[git] ]]; then
  # something specific to git
fi

if [[ $TERM == (screen|tmux)* ]]; then
  # something specific to screen/tmux
fi

if [[ -d /proc ]]; then
  # something specific to procfs
fi

if [[ $HOST == nas ]]; then
  # something specific to NAS
fi
```

It's rarely a good idea to come up with a single `HOST_OS_KIND` on which you can dispatch. This is because the number of combinations is large, and it also makes code harder to understand because of indirections. Consider this:

```zsh
if [[ $HOST_OS_KIND == (macOS|Ubuntu) ]]; then
  # Only macOS and Ubuntu machines have git installed.
  alias gs='git status'
fi
```

versus this:

```zsh
if [[ -v commands[git] ]]; then
  alias gs='git status'
fi
```

The latter is clearer and more robust.

I might be able to offer more specific suggestions if you provide more specific data. What are the things that you don't want to `z4h install` on a NAS and why? Can you detect NAS by one of the means I mentioned above?

**Comment by ycardon** [comment]
I didn't know about `$OSTYPE`, thank you !

I completely agree: It's better to rely on a minimum requirement (is `git` installed ?) instead of a broader and less precise one (on this host because _I know_ that `git` is installed). On the contrary, when it comes to whether install something or not on a host, I would like to be as generic as possible.

I have a `z4h install lukechilds/zsh-nvm` statement (I know, you already told me that the implementation was quite slow, but it's really useful for me. On my defence, I did some test to `zsh-defer` it...). It autoloads node on the host if it's not installed, which is what I want on my servers except on my synology NAS.

I think I will just keep `[[ $(uname -a | grep synology) ]]` as a guard condition for this, no more `$HOST_OS_KIND` needed.

Last extra question: is there an advantage on guarding on `$path` declarations ?
```sh
[[ -e ~/.cargo/bin ]] && path=(~/.cargo/bin $path)
```

**Comment by romkatv** [comment]
> I think I will just keep `[[ $(uname -a | grep synology) ]]` as a guard condition for this, no more `$HOST_OS_KIND` needed.

More zsh-y and faster:

```zsh
[[ "$(uname -a)" == *synology* ]]
```

I would also recommend replacing `uname -a` with something more specific. If you are matching against the hostname, use `$HOST`. If not, check which field in the output of `uname -a` actually contains "synology". Perhaps `uname -v`, or maybe `uname -o`? If you end up invoking `uname`, guard it with `$OSTYPE` check to make it faster and to avoid errors from `uname` when invoking with unknown options.

```zsh
[[ $OSTYPE == linux* && "$(uname -v)" == *synology* ]]
```

> Last extra question: is there an advantage on guarding on `$path` declarations ?
> 
> ```shell
> [[ -e ~/.cargo/bin ]] && path=(~/.cargo/bin $path)
> ```

Command lookup will be faster. Also makes debugging easier.

**Comment by ycardon** [comment]
That's perfectly makes sense, thank you again ^^
