### ISSUE TITLE
purpose of tmux-start integrated?

### ISSUE THREAD

**Issue by vbauerster** [romkatv/zsh4humans#86]
Hi Roman!
I just gave v5 a try and have a question what is purpose of `zstyle ':z4h:' start-tmux 'integrated'` option? I'm asking because I've encountered a couple of issues with this option, which is default by the way. My out of the box experience wasn't smooth, because first issue I faced with default `.zshrc` is that my true color support inside tmux was broken. I started to investigate and found issue #78, which didn't help. Then I read [changelog](https://github.com/romkatv/zsh4humans/blob/v5/changelog.md) and discovered `tmux-start` option as it wasn't included in default `.zshrc`:

- It's now possible to automatically start `tmux` when zsh4humans is initializing.
  ```zsh
  zstyle :z4h: start-tmux [arg]...
  ```
  Where `[arg]...` is either `integrated` (the default), `no`, `command <cmd> [flag]...`, or
  `system`. The latter is equivalent to `command tmux -u`.

Interesting I thought, if default value is integrated then I suppose to have integrated tmux up and running, right? But there was no visual sign of tmux up and running in my terminal. I typed `echo $TERM` and the output was `tmux-256color`! Wow how come it's `tmux-256color` and I can't see tmux is running, is it expected?

Invoking system tmux with following config didn't apply `terminal-overrides` line, because outside `TERM` env var is not `xterm-256color` anymore, thus breaking true color support inside tmux.
```
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
```
I had to set `start-tmux` to `no` at the end of the day. So what is the purpose of `integrated`? It doesn't start integrated tmux automatically but sets `TERM` env var to `tmux-256color`, which is very confusing. BTW, setting `start-tmux` to `system` starts system tmux automatically without breaking true color support. Also I tested over ssh and there was same story, default `integrated` didn't start tmux or at least there was no visual sign of tmux and `TERM` was set to `tmux-256color`.

I tested in macOS with iTerm2 and ssh to debian linux.
PS: thanks for teleport over ssh, it works great!

**Comment by romkatv** [comment]
> My out of the box experience wasn't smooth

Sorry to hear that but I'm afraid this is expected when using v5. It's a bleeding edge development branch. It provides no backward compatibility guarantees and uses defaults that are best suited for testing new features.

> what is purpose of zstyle ':z4h:' start-tmux 'integrated' option?

It starts an integrated tmux. This enables new features such as prompt starting at the bottom and fzf opening above prompt.

If you are a tmux user, you need to set this option to `system`. Integrated tmux is for users who don't use tmux. It's by design that you cannot detect it when it's running because users who don't use tmux don't want tmux.

What issues have you run into when using integrated tmux?

**Comment by vbauerster** [comment]
> Sorry to hear that but I'm afraid this is expected when using v5. It's a bleeding edge development branch. It provides no backward compatibility guarantees and uses defaults that are best suited for testing new features.

That's ok, I was kind of prepared for that.

> If you are a tmux user, you need to set this option to `system`.

Yes I'm tmux user.

> What issues have you run into when using integrated tmux?

First of I wasn't aware of it, because it wasn't in default `.zshrc`. It is first time I tried Z4H and straight v5! As a tmux user I didn't expect there is integrated tmux is running without showing its interface, therefore I attempted to run my usual tmux session straight away and end up tmux inside tmux situation.

Possible solution is to include this option to default `.zshrc` with comment for tmux users, or set `TMUX` env var in integrated mode so invoking system tmux will give a warning message:
```
❯ echo $TMUX
/private/tmp/tmux-501/default,20371,0
❯ tmux new -s test
sessions should be nested with care, unset $TMUX to force
```

**Comment by vbauerster** [comment]
> This enables new features such as prompt starting at the bottom and fzf opening above prompt.

I liked this!

**Comment by romkatv** [comment]
> That's ok, I was kind of prepared for that.

Keep in mind that every time you update, you config may break. There is no backward compatibility in v5. Breaking changes are announced in #35.

> Possible solution...

v5 is too early in the development process for polishing. Everyone who's using it is expected to know all new features, settings, bugs and gotchas.

**Comment by vbauerster** [comment]
> If you are a tmux user, you need to set this option to `system`

For ssh cases, system tmux could be not installed or too old version. Appreciate the option that would make `integrated` to behave like `system` for such cases.

**Comment by romkatv** [comment]
> > If you are a tmux user, you need to set this option to `system`
> 
> For ssh cases, system tmux could be not installed or too old version. Appreciate the option that would make `integrated` to behave like `system` for such cases.

The integrated tmux isn't a normal tmux. It's a patched version that cannot be used as a regular tmux.

There is no point in launching the integrated tmux on a remote host if you are running any tmux on a local host. The new features (opening fzf above prompt, etc.) work as long as you have a local tmux (either system or integrated).

You can set parameters conditionally based on whether you are on a local host or connected over ssh.

```zsh
if [[ -n $Z4H_SSH ]]; then
  zstyle ...
else
  zstyle ...
fi
```

**Comment by romkatv** [comment]
FYI: I've added a question "do you use tmux?" to the installation wizard in v5. "Yes" sets `start-tmux` to `system`.
