### ISSUE TITLE
Use a whitelist rather than blacklist for automatic teleportation of z4h over ssh

### ISSUE THREAD

**Issue by JSamir** [romkatv/zsh4humans#87]
As per the title.

I do know that it is an advertised feature that the "teleporting" is done automatically, but I think teleporting to any server without asking is a bad default. Some day I will ssh into a server and forget to blacklist it prior to that. On the other hand, no harm is done if I connect before whitelisting a server.

And obviously, thanks for this great project :)

**Comment by romkatv** [comment]
This is supported. Example config:

```zsh
# Enable or disable automatic teleportation of z4h over
# ssh when connecting to these hosts.
zstyle ':z4h:ssh:example-hostname1'   passthrough 'yes'
zstyle ':z4h:ssh:*.example-hostname2' passthrough 'no'
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   passthrough 'no'
```

Note: In v5 this parameter has been renamed and the default value has been flipped. You can see it here: https://github.com/romkatv/zsh4humans/blob/90d35867bc2ca3774c767c23b46d0ecea1333ee5/.zshrc#L26-L31

**Comment by JSamir** [comment]
Thanks, will try it out later and close the issue afterwards.

**Comment by JSamir** [comment]
Did not work, am I doing something wrong?

This is the relevant part of my config:
```
#zstyle ':z4h:ssh:*'           send-extra-files '~/.iterm2_shell_integration.zsh'
# Disable automatic teleportation of z4h over ssh when connecting to some-host.
# This makes `ssh some-host` equivalent to `command ssh some-host`.
zstyle ':z4h:ssh:lindev'            passthrough      'yes'
zstyle ':z4h:ssh:lindev2'           passthrough      'yes'
#zstyle ':z4h:ssh:jenkins-slave01'   passthrough      'no'
# disable automatic teleportation of z4h for all other hosts
zstyle ':z4h:ssh:*'                 passthrough 'no'
# Move the cursor to the end when Up/Down fetches a command from history?
zstyle ':zle:up-line-or-beginning-search'   leave-cursor 'yes'
zstyle ':zle:down-line-or-beginning-search' leave-cursor 'yes'
```

At first I tried uninstalling z4h from one of my machines, but that did not work (will open separate issue). After that I tried connecting to a machine I never connected before (which is not one of the 2 whitelisted) and it still teleported z4h over.

**Comment by romkatv** [comment]
> Did not work, am I doing something wrong?
> 
> This is the relevant part of my config:
> 
> ```
> #zstyle ':z4h:ssh:*'           send-extra-files '~/.iterm2_shell_integration.zsh'
> # Disable automatic teleportation of z4h over ssh when connecting to some-host.
> # This makes `ssh some-host` equivalent to `command ssh some-host`.
> zstyle ':z4h:ssh:lindev'            passthrough      'yes'
> zstyle ':z4h:ssh:lindev2'           passthrough      'yes'
> #zstyle ':z4h:ssh:jenkins-slave01'   passthrough      'no'
> # disable automatic teleportation of z4h for all other hosts
> zstyle ':z4h:ssh:*'                 passthrough 'no'
> # Move the cursor to the end when Up/Down fetches a command from history?
> zstyle ':zle:up-line-or-beginning-search'   leave-cursor 'yes'
> zstyle ':zle:down-line-or-beginning-search' leave-cursor 'yes'
> ```
> 
> At first I tried uninstalling z4h from one of my machines, but that did not work (will open separate issue). After that I tried connecting to a machine I never connected before (which is not one of the 2 whitelisted) and it still teleported z4h over.

This is working as intended. Here's a snippet of the config I posted earlier:

```zsh
# The default value if none of the overrides above match the hostname.
zstyle ':z4h:ssh:*'                   passthrough 'no'
```

In your config you've replaced the comment (it now says the opposite of what the next line actually does) but kept the value.
