### ISSUE TITLE
darwin arm64 is unsupported

### ISSUE THREAD

**Issue by sirkon** [romkatv/zsh4humans#88]
Hi!

I can't install this on my MacBook Pro with M1, the installer exits with "unsupported platform" message. What is missing here? How can I help you to add a support for the platform?

**Comment by romkatv** [comment]
With some luck, arm64 support will land next week.

**Comment by sirkon** [comment]
Nice, thank you!

**Comment by romkatv** [comment]
I've added darwin-arm64 support to v5. If I don't uncover any issues with it, I'll backport it to v4 in a few days.

**Comment by sirkon** [comment]
It works. Yet, I don't know it is intentionally or not, I couldn't to extend $PATH with my own entities.

**Comment by romkatv** [comment]
> I couldn't to extend $PATH with my own entities.

Please elaborate. What do you do, what do you expect and what do you observe?

**Comment by sirkon** [comment]
put 


```bash
export PATH=$PATH:/my/path
```

in ~/.zshrc/  | ~/.env.zsh | whatever yet it will not appear in PATH (after restart, of course).

**Comment by romkatv** [comment]
Please do the following:

1. Run: `exec zsh`
2. Run: `typeset -p PATH`
3. Post a screenshot here.
4. Post the content of `~/.zshrc` and `~/.zshenv` here.

**Comment by sirkon** [comment]
No, it looks like there was some typing error of mine, everything works fine now.

**Comment by romkatv** [comment]
> No, it looks like there was some typing error of mine, everything works fine now. Sorry for misreport.

Thanks for the update.

> I've added darwin-arm64 support to v5. If I don't uncover any issues with it, I'll backport it to v4 in a few days.

The changes are too big for my comfort for backporting them to v4. Darwin arm64 support will be confined to v5 (unstable dev branch) for now.
