### ISSUE TITLE
Alternative place for .zlogin configuration for Sway start

### ISSUE THREAD

**Issue by AntonFriberg** [romkatv/zsh4humans#89]
I have previously utilized `~/.zlogin` to [auto-start sway](https://github.com/swaywm/sway/wiki#login-managers) window-manager on initial login. According to your documentation, this is not recommended with z4h. 

>Zsh supports several additional startup files with complex rules governing when each file is sourced. The additional startup files are `~/.zprofile`, `~/.zlogin` and `~/.zlogout`. **Do not create these files.**

This is what I have currently in my `~/.zlogin` 
```
# If running from tty1 start sway
if [ "$(tty)" = "/dev/tty1" ]; then
    exec sway
fi
```

How do you recommend that I set up the same behavior without this configuration in `~/.zlogin`?

**Comment by romkatv** [comment]
This will still work. You might want to replace `$(tty)` with `$TTY` there to avoid a fork.

If your OS has an init system, it's a good idea to use *that* instead of hijacking login shell via rc files. I know that sway documentation suggests doing it this way but it's still an awful hack.

**Comment by AntonFriberg** [comment]
Thanks for the clarification!
