### ISSUE TITLE
Backup or warn before overwriting the .zshrc on ssh target

### ISSUE THREAD

**Issue by AntonFriberg** [romkatv/zsh4humans#90]
I did not get the idea that zsh4humans would overwrite the .zshrc on the ssh target without warning or doing a backup with the default configuration. This is destructive behavior that I feel is very dangerous for users that do not backup their zsh configuration periodically.

**Comment by romkatv** [comment]
This is on my TODO list but there is no ETA.

FWIW, no one has complained about data loss yet. This doesn't mean that the potential damage caused by data loss is small but it's a sign that the likelihood of it happening is smaller than you might think.
