### ISSUE TITLE
Weird ssh completions

### ISSUE THREAD

**Issue by maximbaz** [romkatv/zsh4humans#91]
Hey 🙂 

I noticed a weird issue, when I do `ssh <Tab>`, I get hostname suggestions from `~/.ssh/known_hosts` but not from `~/.ssh/config` (you can see I'm not ssh'ing to new hosts often as it took me this long to notice this issue 😅).

What I did:

```sh
mv ~/.ssh/known_hosts{,.bak}
mv ~/.ssh/config{,.bak}
echo "Host abcd" > ~/.ssh/config
echo "z4h init || return" > ~/.zshrc
rm -rf ~/.cache/zsh4humans
```

In a new terminal, once z4h bootstraps, I think I should be back to a standard configuration.

Now I try `ssh <Tab>` and here's what I see:

![image](https://user-images.githubusercontent.com/1177900/104510632-b8bcf980-55eb-11eb-9522-874094bd29c7.png)

There is no `abcd` entry in the list, but a bunch of.... usernames? What are these even? I would expect to only see one entry at this point, `abcd`.

![image](https://user-images.githubusercontent.com/1177900/104510718-db4f1280-55eb-11eb-9ed3-d1d9d7b40653.png)

Now to the weird part, if I `Esc` and try instead `ssh a<Tab>` I get...

![image](https://user-images.githubusercontent.com/1177900/104510757-f28e0000-55eb-11eb-81e4-094b9cd48d9c.png)

`abcd` is present now?? And `avahi` which again I don't really want to see here.

I checked the code and I could really only find a match in `_fzf_complete_ssh()` in `v5/fzf/shell/completion.zsh`:

```zsh
_fzf_complete_ssh() {
  _fzf_complete +m -- "$@" < <(
    setopt localoptions nonomatch
    command cat <(command tail -n +1 ~/.ssh/config ~/.ssh/config.d/* /etc/ssh/ssh_config 2> /dev/null | command grep -i '^\s*host\(name\)\? ' | awk '{for (i = 2; i <= NF; i++) print $1 " " $i}' | command grep -v '[*?]') \
        <(command grep -oE '^[[a-z0-9.,:-]+' ~/.ssh/known_hosts | tr ',' '\n' | tr -d '[' | awk '{ print $1 " " $1 }') \
        <(command grep -v '^\s*\(#\|$\)' /etc/hosts | command grep -Fv '0.0.0.0') |
        awk '{if (length($2) > 0) {print $2}}' | sort -u
  )
}
```

Interestingly, executing this code manually in the new terminal window gives me _precisely_ what I would expect from ssh completions, it gives me just one line, `abcd`.

Do you have any idea what might be going on here? 🙂

**Comment by romkatv** [comment]
zsh4humans doesn't use `_fzf_complete_ssh`. Completions come from zsh proper. zsh4humans also doesn't set any `zstyle` options related to ssh completions. So the completions you see are the same as you would get here:

```zsh
zsh -f
autoload -Uz compinit
compinit
```

That said, I don't like the default completions for ssh, so I have this in my zshrc:

```zsh
zstyle ':completion:*:ssh:argument-1:'       tag-order hosts users
zstyle ':completion:*:scp:argument-rest:'    tag-order hosts files users
zstyle ':completion:*:(ssh|scp|rdp):*:hosts' hosts
```

With this setup `ssh <TAB>` will show all hosts from the ssh config and nothing else. If this isn't what you want, adjust `zstyle` as you like. Docs are here: http://zsh.sourceforge.net/Doc/Release/Completion-System.html. You might have to read the source code of the completers, too.

**Comment by maximbaz** [comment]
Oh wow, thanks! To be honest I didn't even assume that we are might be using standard ssh completions 😅 Maybe worth taking this in zsh4humans? Sounds like a much more "humane" default than whatever is the default ssh completion 😉 

In any case, thanks, closing, my issue is solved 👍

**Comment by romkatv** [comment]
> Maybe worth taking this in zsh4humans? Sounds like a much more "humane" default than whatever is the default ssh completion 😉

My `zstyle` options simply disable most of the functionality provided by the standard completions. All that stuff might be there for a reason, so disabling it can be surprising. It's likely that the average user doesn't list all their remote hosts in the ssh config, so these options wouldn't be a good choice.

I think this falls outside of the mandate of zsh4humans, at least for now. I've already a long list of must-haves (you may have noticed that I haven't been working on z4h for quite some time -- being busy with other stuff), so I'd rather not grow it further for a problem that can be solved with the stock zsh options.
