### ISSUE TITLE
z4h zle kill widgets should support saving to cutbuffer/kill-ring

### ISSUE THREAD

**Issue by NgoKimPhu** [romkatv/zsh4humans#92]
Current implementation using `fn/-z4h-move-and-kill` doesn't support pushing killed text to cutbuffer/kill-ring
I made my own [hack fix](/romkatv/zsh4humans/compare/v5...NgoKimPhu:kill-buffer_z4h-move-and-kill?expand=1#diff-80757271e4bbced29992f1059095359820f2b2ddfb5bf0ccadbfcdf313f929fa) but there might be a better way (I'm new to zsh), so I'm opening this issue instead.
Here's a [related discussion over at zsh-users/zsh-autosuggestions/issues/363](https://github.com/zsh-users/zsh-autosuggestions/issues/363#issuecomment-449554120)

**Comment by romkatv** [comment]
Thanks for the report. Fixed in v5 and backported to v4. Run `z4h update` to pick up the fix.

**Comment by NgoKimPhu** [comment]
thanks for the fix :D
