### ISSUE TITLE
_z4h_macos_opt_key isn't correct for all keyboards

### ISSUE THREAD

**Issue by ORBAT** [romkatv/zsh4humans#93]
Hi! First of all I'd like to say that I really like z4h and p10k, they make zsh customization downright fun.

I'm on macOS (10.14 but that shouldn't be relevant) and I use a Finnish keyboard layout, and I noticed that the `_z4h_macos_opt_key` mapping is wrong for me. As an example, `-z4h-init` has the mapping `q  'œ'`, but for me <kbd>Opt</kbd>-<kbd>q</kbd> produces `•`.

I did some short googling and couldn't find any sane way of getting the current keyboard layout's key code mappings on the command line. Dunno if there is one, haven't really had to deal with this before.

Would it be possible to allow overriding `_z4h_macos_opt_key` in zshrc, unless Someone™ can come up with a way of making the mappings portable? I'll just fiddle with `-z4h-init` directly in the meantime.

**Comment by romkatv** [comment]
Indeed, zsh4humans has these mappings only for the en-us layout. Note that this is a workaround for the misguided defaults in several macOS terminals. The proper solution is to configure your terminal to treat Option key as Alt. All terminals have this settings but unfortunately it's not the default. Terminals on all other operating systems behave like this by default and this is how virtually all terminal users want them on macOS, too. You can verify that your terminals is configured correctly by pressing <kbd>Ctrl+V</kbd> in zsh and then hitting <kbd>Opt+q</kbd>. You should see `^[q` (the first two symbols will normally be red). Now all <kbd>Opt</kbd> bindings will work.
