### ISSUE TITLE
Add option for non-interactive installation

### ISSUE THREAD

**Issue by anstadnik** [romkatv/zsh4humans#94]
Hi!
I want to install zsh4humans non-interactively. It is needed because I want to use it in the Dockerfile. I have all the config files needed and copy them myself to the appropriate destinations. I would like to run the installation script in a non-interactive way.
I tried that but seems that there is a check which does not allow me to do that in the installation script.
Then I tried to load z4h.zsh and .zshenv manually and after trigger the installation of other parts. My last attempt was `zsh -i ~/.zshenv`, which seemed to run somehow, but fail with the next message:
```
z4h: installing zsh4humans
-z4h-run-process-tree:setopt:8: can't change option: monitor
```
Is it possible to pre-download everything needed without doing that manually?

**Comment by romkatv** [comment]
The only job of the installer is to create 3 local files in the home directory: `.zshenv`, `.zshrc` and `.p10k.zsh`. You can copy these files across machines.

**Comment by romkatv** [comment]
If you copy the files I specified above, zsh4humans will install automatically the first time you start `zsh`. You can trigger this manually in non-interactive mode with the following command:

```zsh
script -qec 'zsh -c "zsh -is </dev/null"' /dev/null
```

**Comment by anstadnik** [comment]
Amazing, thank you!

**Comment by woss** [comment]
Hi, i've been trying to install the zsh4humans with good p10k.zsh in docker for the use of the devcontainer ( vscode ) using the above method but it doesn't work for some reason. 

You said that copying the files will automatically trigger the installation, it doesn't. also the install script is also trying to install the zsh with the interactive mode.

It would super awesome if you could show us the example how we can have this awesome project in our  fav development env. :)

**Comment by romkatv** [comment]
> You said that copying the files will automatically trigger the installation, it doesn't.

All you need to do is copy `~/.zshrc`, `~/.zshenv` and `~/.p10k.zsh` and then start `zsh`.

> also the install script is also trying to install the zsh with the interactive mode.

Don't run the install script.

**Comment by woss** [comment]
right, so it doesn't do anything on the dockerfile build. it triggers installation and interactive after i start the container which is quite painfull to do everytime i recreate it.
![image](https://user-images.githubusercontent.com/80440/117654692-673a0b00-b196-11eb-93a5-d3b7263ea281.png)

what i want to accomplish is that i have zsh4humans installed and preconfigured inside the image and people can add `.env.zsh` file to extend the original one (v5). any idea how to accomplish this?
Here is my attempt to do it https://gitlab.com/anagolay/node/-/blob/41-add-benchmarks-for-the-pallets/devcontainer.base.Dockerfile#L28

**Comment by romkatv** [comment]
Add zsh to yor docker file.

**Comment by woss** [comment]
base image url is this [here](https://github.com/microsoft/vscode-dev-containers/blob/v0.159.0/containers/rust/.devcontainer/base.Dockerfile) 
and the script that installs and configures this base box is this https://github.com/microsoft/vscode-dev-containers/blob/v0.159.0/containers/rust/.devcontainer/library-scripts/common-debian.sh#L319

**Comment by woss** [comment]
no 5.7

**Comment by romkatv** [comment]
zsh4humans needs zsh 5.8. Install zsh 5.8.

**Comment by woss** [comment]
right. so i install the 5.8 and after that is there any way to install this repo without actually running the image as a container. i'm talking about build process ( which is non interactive )

**Comment by romkatv** [comment]
> right. still the script part and Dockerfile are not good friends

I don't understand this. I'm not sure where you see a problem. From my POV, everything just works.

**Comment by woss** [comment]
well, i've spent a good deal of time yesterday trying to do exactly what you said in prev comments. including running the script without any success. i love this project and the powerlevel, and i really want to have my zsh looks the same in all dev envs. it's easy when i develop in terminal and debian but witht the devcontainers i am at a loss how to get this up and running. any snippet on the `script` and `Dockerfile` would be greately appreciated

**Comment by romkatv** [comment]
> well, i've spent a good deal of time yesterday trying to do exactly what you said in prev comments. including running the script without any success. i love this project and the powerlevel, and i really want to have my zsh looks the same in all dev envs. it's easy when i develop in terminal and debian but witht the devcontainers i am at a loss how to get this up and running. any snippet on the `script` and `Dockerfile` would be greately appreciated

I don't use the tools you've mentioned, so I don't have a `script` or `Dockerfile` that I can share. The information I've posted above is accurate though. It tells you what you need to do to install zsh4humans in non-interactive mode. If you don't know how to run these commands in your environment, you might have better luck asking for help in places that are dedicated to said environment (e.g., docker forums or vscode forums).

**Comment by pzheltov** [comment]
In case if this is of interest to anyone, the solution is to add `POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true` to `.zshrc`, thus suppressing all interactivity in the docker step.

**Comment by romkatv** [comment]
The solution is https://github.com/romkatv/zsh4humans/issues/94#issuecomment-836415473

**Comment by pzheltov** [comment]
@romkatv I have tried copying the files as above. But I also saw that the previous commenter gave up eventually: https://github.com/romkatv/zsh4humans/issues/94#issuecomment-836613351, and it wasn't quite working the way I wanted. The *initial setup* of z4h still happens on the first run of zsh, but in the docker environment this is not what we typically want: the first run of zsh will happen when the container is instantiated, and it's too late. We want all z4h downloads to happen at build time of the image, so we basically are bound to call the install script in the Dockerfile. Setting `POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true` suppresses the interactive portion of the install script and triggers the installation at build time, as desired.

**Comment by romkatv** [comment]
> We want all z4h downloads to happen at build time of the image

Thanks for putting in writing what you are trying to achieve. You can do that with the following command when building the container:

```zsh
script -qec zsh /dev/null <<<exit >/dev/null
```

This command needs to be run after the rc files are created. If you don't have `script` in the container, you'll need to install it first.
