### ISSUE TITLE
Support specifying branch name in `z4h install`

### ISSUE THREAD

**Issue by laurentlbm** [romkatv/zsh4humans#96]
`z4h install` downloads the master branch and there is no way of specifying another. It would be great to be able to specify a branch, e.g. `z4h install user/repo@main`

Also, if we could specify a URL for a repository, we could install plugins hosted on other platforms like Gitlab.

**Comment by romkatv** [comment]
> `z4h install` downloads the master branch and there is no way of specifying another. It would be great to be able to specify a branch, e.g. `z4h install user/repo@main`

Fixed in v5 and backported to v4.

> Also, if we could specify a URL for a repository, we could install plugins hosted on other platforms like Gitlab.

This will have to wait (perhaps indefinitely).

**Comment by laurentlbm** [comment]
Thank you, it works perfectly.

**Comment by romkatv** [comment]
Thanks for verifying.
